### ISSUE TITLE
Bombing hotkey

### ISSUE THREAD

**Issue by allenluce** [stumpwm/stumpwm#1033]
I'm using this `.stumpwmrc`:

    (in-package :stumpwm)
    (set-prefix-key (kbd "M-o"))
    (define-key *top-map* (kbd "C-M-k") "exec echo -n")

with this `.xinitrc`:

    export LC_ALL=en_US.UTF-8
    xsetroot -solid black &
    stumpwm

on a locally compiled version `22.05-149-g90cbcbd` on FreeBSD 13.1-RELEASE-p1 (GENERIC amd64), Xorg version 1.20.14.

Upon hitting `C-M-k`, I get this message:
```
The value
  NIL
is not of type
  NUMBER
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1005B10113}>
0: ((:METHOD IO-LOOP (STUMPWM::SBCL-IO-LOOP)) #<STUMPWM::SBCL-IO-LOOP {10048E5573}> :DESCRIPTION "StumpWM") [fast-method]
1: (STUMPWM::STUMPWM-INTERNAL-LOOP)
2: (STUMPWM::STUMPWM-INTERNAL ":0")
3: (STUMPWM ":0")
4: ((LAMBDA NIL :IN "/usr/home/allen/src/stumpwm/make-image.lisp"))
5: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
6: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
7: (SB-IMPL::%START-LISP)
```

The echo does execute, this error pops up after it completes. Anyone have any idea what's going on?

**Comment by jamesmccabe** [comment]
What is `"exec echo -n"` supposed to do?
It doesn't seem to do anything for me.

Try:
 `(define-key *top-map* (kbd "C-M-k") "echo test")`

**Comment by allenluce** [comment]
`exec echo -n` just a null op for demonstration purposes. Replacing it with `echo test` gives me the same error. The command does work and completes normally (i.e. `bash -c 'echo test > /tmp/test'` creates the file as expected). But that error pops up anyways.

I'm wondering what it actually means and how to avoid it.

**Comment by sdilts** [comment]
Looks like this might be another issue with the IO loop and FreeBSD. Are you running a version after https://github.com/stumpwm/stumpwm/pull/1020 was merged? I can't figure out which commit you are running.

It sounds like a similar problem, especially with that stack trace.

**Comment by dmb2** [comment]
@allenluce very well written bug report! Thank you! Did @sdilts solution work?
