### ISSUE TITLE
Does stumpwm work on Mezzano-os?

### ISSUE THREAD

**Issue by ghost** [stumpwm/stumpwm#1037]
Hi all! I would like to know if there is any version of stumpwm for Mezzano-os. So... I would be happy to use stumpwm which is written in lisp on an operating system which is also written in lisp.

**Comment by szos** [comment]
I'm not familiar with the display server/gui setup that mezzano uses, but I think its safe to say that no, StumpWM wont work on Mezzano. This is because Stump is an X11 window manager, and I dont think Mezzano uses X11 (I found no reference to either xlib, clx, or x11 in the mezzano codebase).

**Comment by szos** [comment]
No problem. 

> please close this issue

I'm not a maintainer and cant close this, only you and the maintainers can close this issue.
