### ISSUE TITLE
gselect takes 150ms

### ISSUE THREAD

**Issue by some-mthfka** [stumpwm/stumpwm#1039]
I have recently upgraded from the quicklisp version (the March one I think) to master (due to SBCL removing unix-select) and now I am seeing some very noticable lag when switching between groups. I used [tracer](https://github.com/TeMPOraL/tracer) and it reports that `gselect' takes 142ms! 
```
"traceEvents" :  [
{ "name" : "GSELECT", "cat" : "STUMPWM", "ph" : "X", "pid" : 1, "tid" : 68808239139, "ts" : 1663422258177898, "dur" : 142972,  "args" : { "in" : "skipped", "out" : "skipped" }},
{ "name" : "thread_name", "ph" : "M", "pid" : 1, "tid" : 68808239139, "args" : { "name" : "slynk-worker" }}
],
```
Unfortunately the profiler doesn't give more details (although it did show my hooks until I removed them).
A quick switch between 3-4 groups is perceptibly painful. A roll through a dozen groups is a slide show fwiw. Along with SBCL I have upgraded my whole Arch system except mesa and the linux kernel. 
So, ok, the performance was never particularly great on group switching for me in stumpwm, so maybe it wasn't just the recent half-year of updates that are solely responsible for this, but in any case 150ms is kind of sad, right?
PS i3 performance hasn't degraded.

**Comment by szos** [comment]
I'm not familiar with tracer, but from a quick glance it looks like its only tested against SBCL 1.5.0 - could it be misreporting or altering anything? Could similar profiling be done with `sb-profile`?

I'm not sure whats causing this issue, but some ideas/questions: 
- Whats your mode line format? `switch-to-group` calls `update-all-mode-lines` and if theres something that takes a long time in the mode line format perhaps its slowing things down? though if that were the case I'd suspect commands in general to also be unacceptably slow... 
- Similar question regarding `*focus-group-hook*`, are there any functions bound there?
- If you bump up your debug level (maybe to 5 or so), what does the log say when switching groups?
- You could try logging the time in between each form within the function `switch-to-group` and using that to find what portion of the function is taking so long.

**Comment by some-mthfka** [comment]
stumpwm.log and stumpwm.log.1 are both empty with `(declaim (optimize (speed 3) (debug 5) (safety 3) (space 0)))` at the top of .stumpwmrc.
I have 10 groups, each has a single window. If I kill 8 windows and switch between the two groups that have windows left, it's maybe 110ms average (ranging anywhere from 70ms to 200ms) vs ~170ms or so average with everything open. The number of calls to `XLIB:DISPLAY-FINISH-OUTPUT` seems to drop accordingly from 35 to ~26.
Now, I can't claim to understand the precise nature of this function, so I don't know if this can work, but would it perhaps be possible to call it just once after `sync-keys` and `io-channel-handle` are all done after a group switch? Or maybe schedule a countdown timer for it's execution every time it's called and reset that timer upon subsequent calls?

**Comment by szos** [comment]
By debug level i meant the stumpwm variable `*debug-level*`, which is used by dformat to determine if something should be formatted to the log. 

`XLIB:DISPLAY-FINISH-OUTPUT` just flushes the x11 event queue if i recall correctly.

**Comment by some-mthfka** [comment]
Oh, I see, debug level 5, here's output for a switch from one group to another (+ a few keypresses):
```
23:17:36  1 >>> :PROPERTY-NOTIFY
23:17:36  2 property notify #<XLIB:WINDOW :0 2200006> :_NET_WM_USER_TIME :NEW-VALUE
23:17:36  2 <<< :PROPERTY-NOTIFY
23:17:36  1 >>> :FOCUS-OUT
23:17:36  5 #<XLIB:WINDOW :0 2200006> :WHILE-GRABBED :NONLINEAR 
23:17:36  2 <<< :FOCUS-OUT
23:17:36  1 >>> :FOCUS-IN
23:17:36  2 <<< :FOCUS-IN
23:17:36  1 >>> :KEY-PRESS
23:17:36  5 vvv Grab keyboard: :SUCCESS
23:17:36  1 Awaiting key (*TOP-MAP* *TILE-GROUP-TOP-MAP* *GROUP-TOP-MAP*)
23:17:36  1 key-press: #S(STUMPWM::KEY
              :KEYSYM 91
              :SHIFT NIL
              :CONTROL NIL
              :META T
              :ALT NIL
              :HYPER NIL
              :SUPER NIL
              :ALTGR NIL) 8 "gselect ["
23:17:36  5 ^^^ Ungrab keyboard: 4427
23:17:36  3 focus-window: #<TILE-WINDOW "config_emacs_special" #x200013D>
23:17:36  4 Ignoring error: XLIB:MATCH-ERROR
23:17:36  5 show-frame-outline!
23:17:36  5 show-frame-outline!
23:17:36  2 <<< :KEY-PRESS
23:17:36  1 >>> :FOCUS-OUT
23:17:36  5 #<XLIB:WINDOW :0 2200006> :WHILE-GRABBED :NONLINEAR 
23:17:36  2 <<< :FOCUS-OUT
23:17:36  1 >>> :FOCUS-IN
23:17:36  2 <<< :FOCUS-IN
23:17:36  1 >>> :MAP-NOTIFY
23:17:36  2 <<< :MAP-NOTIFY
23:17:36  1 >>> :MAP-NOTIFY
23:17:36  2 <<< :MAP-NOTIFY
23:17:36  1 >>> :MAP-NOTIFY
23:17:36  2 <<< :MAP-NOTIFY
23:17:36  1 >>> :PROPERTY-NOTIFY
23:17:36  2 property notify #<XLIB:WINDOW :0 200013D> :WM_STATE :NEW-VALUE
23:17:36  2 <<< :PROPERTY-NOTIFY
23:17:36  1 >>> :PROPERTY-NOTIFY
23:17:36  2 property notify #<XLIB:WINDOW :0 2200006> :WM_STATE :NEW-VALUE
23:17:36  2 <<< :PROPERTY-NOTIFY
23:17:36  1 >>> :UNMAP-NOTIFY
23:17:36  2 UNMAP: NIL T NIL
23:17:36  2 <<< :UNMAP-NOTIFY
23:17:36  1 >>> :FOCUS-OUT
23:17:36  5 #<XLIB:WINDOW :0 2200006> :NORMAL :NONLINEAR 
23:17:36  2 <<< :FOCUS-OUT
23:17:36  1 >>> :FOCUS-IN
23:17:36  2 <<< :FOCUS-IN
23:17:36  1 >>> :ENTER-NOTIFY
23:17:36  2 <<< :ENTER-NOTIFY
23:17:36  1 >>> :UNMAP-NOTIFY
23:17:36  2 UNMAP: NIL NIL #<TILE-WINDOW "gselect takes 150ms ? Issue #1039 ? stumpwm/stumpwm - qutebrowser" #x2200006>
23:17:36  3 decrement ignores! 1
23:17:36  2 <<< :UNMAP-NOTIFY
23:17:36  1 >>> :UNMAP-NOTIFY
23:17:36  2 UNMAP: NIL T #<TILE-WINDOW "gselect takes 150ms ? Issue #1039 ? stumpwm/stumpwm - qutebrowser" #x2200006>
23:17:36  2 <<< :UNMAP-NOTIFY
23:17:36  1 >>> :FOCUS-OUT
23:17:36  5 #<XLIB:WINDOW :0 200013D> :NORMAL :POINTER 
23:17:36  2 <<< :FOCUS-OUT
23:17:36  1 >>> :FOCUS-IN
23:17:36  2 <<< :FOCUS-IN
23:17:36  1 >>> :PROPERTY-NOTIFY
23:17:36  2 property notify #<XLIB:WINDOW :0 8C> :_NET_ACTIVE_WINDOW :NEW-VALUE
23:17:36  2 <<< :PROPERTY-NOTIFY
23:17:36  1 >>> :PROPERTY-NOTIFY
23:17:36  2 property notify #<XLIB:WINDOW :0 8C> :_NET_CLIENT_LIST_STACKING :NEW-VALUE
23:17:36  2 <<< :PROPERTY-NOTIFY
23:17:36  1 >>> :PROPERTY-NOTIFY
23:17:36  2 property notify #<XLIB:WINDOW :0 8C> :_NET_CURRENT_DESKTOP :NEW-VALUE
23:17:36  2 <<< :PROPERTY-NOTIFY
23:17:36  1 >>> :SELECTION-NOTIFY
23:17:36  2 selection-notify: #<XLIB:WINDOW :0 600003> :STUMPWM-SELECTION :CLIPBOARD
23:17:36  2 <<< :SELECTION-NOTIFY
```

**Comment by dmb2** [comment]
Any follow up on this? Is it still an issue?

**Comment by equwal** [comment]
We need a better profile to be able to figure out what is worth refactoring. Just by looking at the code and guessing won't do it. Premature optimization is the root of all evil.

That being said, there is a ton of room for improvement in there. I just poked around and found a
```
(if (> (length list) 1)...
```
in a relevant function.

**Comment by equwal** [comment]
I remember doing a lot of profiling on stump when I was active. I think I mostly used the stuff in the standard like time + bespoke macros or whatever.

**Comment by equwal** [comment]
The above is nice but it isn't fine grained enough.

Another trick is to redefine different functions by passing them into a new higher level wrapper function with `time`. Then whenever they run you see them. And you can even put a notification in there too to get a popup.

**Comment by equwal** [comment]
The common lisp Xlib library is a giant codebase shit show from hell, but if you want to go putting your hands in there to make it more efficent the current maintainers will accept such pulls.

I like this graph but where is Number of time called? That is a trivial thing to track.
`  seconds  |     gc     |   consed  | calls |  sec/call  |  name `

**Comment by equwal** [comment]
All of these functions in groups are fundamentally going to be inefficient because they do things to all of the groups by stepping through the list in typical lisp style. There could be a big benefit in exploring more efficient datatypes for some of the slower functions. And not doing unnecessary work like that. The `(> (length list) 1)` example is really spot-on.

**Comment by equwal** [comment]
All of these functions in groups are fundamentally going to be inefficient because they do things to all of the groups by stepping through the list in typical lisp style. There could be a big benefit in exploring more efficient datatypes for some of the slower functions. And not doing unnecessary work like that. The `(> (length list) 1)` example is really spot-on.

**Comment by equwal** [comment]
Another spot to check is `format`, since StumpWM does a lot of unkosher format use. The compiler wants to optimize away your format directives, but you must give it a *static string*.

```
(list (format-expand *group-formatters* fmt g) g))
```

This thing is also called in there.

Need to do some profiling, again, but I bet some of these formatters are an actual issue, because they cause slowdowns specifically when the user is doing input. Some C-esque array antics could replace them instead.

**Comment by equwal** [comment]
Something I have wanted to do is just sit down and profile all kinds of things in StumpWM to get a kind of "security audit" thing going. There is so much low hanging fruit there. Stump is slow.

**Comment by equwal** [comment]
Another issue on profiling

https://github.com/stumpwm/stumpwm/issues/382#issuecomment-566817695
