### ISSUE TITLE
Commands executing out of order

### ISSUE THREAD

**Issue by oneirophon** [stumpwm/stumpwm#1047]
Hello! I have the following in my .stumpwmrc:

```
(defcommand rox () ()
  (run-commands "vsplit" "exec rox" "move-focus down" "exec rox")
)
```

The intended behavior is to split the current frame in half and place a rox filer window in each half. However, it seems to execute the "move-focus-down" command before the first instance of "exec rox", thus placing both rox filer windows in the bottom half. Any help would be appreciated; I'm totally new to the world of Lisp, so I apologize if I'm just doing something wrong here.

**Comment by sdilts** [comment]
What's probably happening is that rox doesn't start communicating with Stumpwm until after the other commands have been processed. The commands are running in order, but in order for it to work, everything after the `exec rox` command would need to be done after rox opens a window.

I don't think this is something we can really program for without messing with too much of the internals. 

You might be able to accomplish this by pre-arranging the frames, then using [rule based window placement](https://stumpwm.github.io/git/stumpwm-git_5.html#Rule-Based-Window-Placement) to get them in the correct spot.

**Comment by nicholasrupert** [comment]
That section on rule based window placement is now here: https://stumpwm.github.io/v1.0.0/stumpwm-v1.0.0_34.html#Rule-Based-Window-Placement
