### ISSUE TITLE
Dynamic Groups Do Not Work As In the Window Managers It Attempts to Replicate

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [stumpwm/stumpwm#1048]
Hello,

I am trying to move to stumpwm from dwm due to my furthering interest in Common Lisp. I have gotten a somewhat [basic setup](https://gitlab.com/FOSSilized_Daemon/dotfiles/-/tree/main/src/dotfiles/home/.library/generic/common-lisp/stumpwm), but found one annoying issue I cannot find a solution for. In most dynamic window managers a dynamic window stack can be moved through in an "up" and "down" way. In other words you can just bind like so and move through all windows.

```
(define-key *top-map*  (kbd "s-j") "prev")
(define-key *top-map*  (kbd "s-k") "next")
(define-key *top-map*  (kbd "s-J") "exchange-direction down")
(define-key *top-map*  (kbd "s-K") "exchange-direction up")
```

The issue in stumpwm is that the later two bindings will not always work because windows are still seen as next to each other sometimes. I was curious if this was intentional and if so how I can get around it? I do not know much about CL at the moment so I don't think I could implement this functionality, but was recommended to post here to see if this was an overlook.

Additionally, and somewhat unrelated, how does one reorder group numbers? I am deleting the Default group in order to have all my groups be [dynamic](https://gitlab.com/FOSSilized_Daemon/dotfiles/-/blob/main/src/dotfiles/home/.library/generic/common-lisp/stumpwm/common-lisp/workspace.lisp#L10), but I hit an issue where I want a specific group to be group 1 and so on but cannot find anyway to do [his in the documentation](https://stumpwm.github.io/).

**Comment by szos** [comment]
The command youre looking for is `rotate-windows`, i believe.

**Comment by FOSSilizedDaemon** [comment]
> The command youre looking for is `rotate-windows`, i believe. All the dynamic group related commands are in dynamic-group.lisp, at the bottom of the file.

Aha! That was correct! The only issue is that it does not keep focus when rotating the windows.

**Comment by szos** [comment]
Also, you linked to the online documentation, which is very old at this point. If you build stump from source you should have a local up to date version of the manual as in info file.
