### ISSUE TITLE
Frames misplaced when mode-line is on

### ISSUE THREAD

**Issue by Jehops** [stumpwm/stumpwm#1064]
When I start X, the screen is laid out so that a primary head/frame for a laptop is to the left of a head/frame for an external monitor and everything works as expected.

To arrange the screen so that the frame for the laptop monitor is below the frame for the external monitor, I run something like

xrandr --output DP-1 --auto --above LVDS-1 --output LVDS-1 --auto

or

xrandr --output LVDS-1 --primary --mode 1366x768 --pos 597x1440 --output DP-1 --mode 2560x1440 --pos 0x0

This all works fine if there is no mode-line on the laptop frame.  However, if the mode-line is on, then the frame for the laptop is positioned inside the frame for the external monitor.  If a window is displayed and focused on the external monitor and I run `move-window down`, the window, instead of moving to the laptop frame, is buried under the other windows on the external monitor.

I see this in two different environments with no configuration.

Environment 1:

% uname -sr
FreeBSD 14.0-CURRENT

% pkg query %n-%v sbcl stumpwm
sbcl-2.2.10,1
stumpwm-22.11.17 (updated locally from FreeBSD port, but I see this behavior in 22.10)

Heads: 2 (laptop and external monitor connected via DP).

Environment 2:

% uname -sr
Linux 6.0.12-arch1-1

% pacman -Q sbcl stumpwm
sbcl 2.2.11-1
stumpwm 22.11-2

Heads: 2 (laptop and external monitor connected via HDMI).

**Comment by triclops200** [comment]
I also have the same issue, attaching a link to a video for reference. Are there any logs that could be useful?

https://drive.google.com/file/d/1OgmkYEc98k68SvaXuCLQ65ir8jk38grn/view?usp=sharing

**Comment by hcarter1112** [comment]
Same issue here. Running Linux and 2 1440 monitors. I am using the xrandr call to configure them. Both over DP. One is rotated portrait right and they  are arranged with the  --pos flag... A lot like @Jehops .

**Comment by jorams** [comment]
This should be fixed in 7d3a67216114b69c42f49fc0613ac6d6d14e84ea. It turned out to be a much simpler bug than I expected.
