### ISSUE TITLE
error loading modules installed via archlinux

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [stumpwm/stumpwm#1067]
I am using archlinux. I have installed `sbcl`, `stumpwm` as well as [stumpwm-contrib](https://security.archlinux.org/package/stumpwm-contrib) using pacman.

```
pacman -S sbcl stumpwm stumpwm-contrib
```

However I am having problems with loading the modules from `stumpwm-contrib`.

The function `(list-modules)` correctly returns a list of modules present. So I know `stumpwm` can see them. However when I attempt to load one (using "winner-mode" as an example)  via `(load-module "winner-mode")` I get an error. That says `Can't create directory /buildBacktrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1004F90113}>`. Any ideas as to why this is and how to fix it?

I've looked at various links regarding `stumpwm` installation and module loading, the problem is many use an alternative means of installation--typically building from source and installing quicklisp. Noteworthy also is [this reddit article](https://old.reddit.com/r/stumpwm/comments/lb2sba/problems_loading_modules/) where someone seems to have run into the same problem as me. Unfortunately, he didn't solve the problem instead choosing to install `stumpwm` differently.

I'm am willing to go the route of a different means of installation if necessary, but I would prefer to load the modules as I have them installed so that I can have all my packages installed consistently (all from pacman).

**Comment by Luis-Henriquez-Perez** [comment]
I got loading modules work, but I had to use `stumpwm-git` from the AUR.

**Comment by adlai** [comment]
> I had to use `stumpwm-git` from the AUR

That is not, in my least humble opinion, grounds for closing the issue.

**Comment by Luis-Henriquez-Perez** [comment]
# Table of Contents

1.  [whether this is really an issue](#org0d74bec)
2.  [what happened](#orge6bfc2e)
3.  [why I think this happened](#orgb8ed361)


<a id="org0d74bec"></a>

# whether this is really an issue

As a new stumpwm user I thought I would install stumpwm as well as stumpwm-contrib via pacman. I know there are other ways to do it&#x2013;one is building stumpwm from the git repo and another is using quicklisp. My rationale was I don't want to use too many package managers. I was already using arch, so I wanted to use `pacman` for as much as I could.

What I want to know is, is this an accepted way of installing stumpwm? Moreover, is installing it and the modules from pacman and then loading those modules an accepted way
of loading the modules?

Perhaps I wasn't supposed to install it and use it in this way. In that case then maybe what happened is not suprising or unexpected.


<a id="orge6bfc2e"></a>

# what happened

What happened is I installed stumpwm and stumpwm contrib with `pacman -S stumpwm stumpwm-contrib`.

I confirmed that `(list-modules)` correctly returned the list of stumpwm modules.

![stumpwm-confirm-list-modules-works](https://github.com/stumpwm/stumpwm/assets/30783193/dd118cae-c970-4ead-ac5b-904675d62780)


However the second I tried to load any of the modules I would get one of two errors. Here I tried to
load it via `loadrc`, which I bound to `C-t R`.

![stumpwm-load-module-error](https://github.com/stumpwm/stumpwm/assets/30783193/8f469c8e-7737-467f-b8c8-d105f856b1a2)

I produced this from loading this minimal config file: [stumpwm-config.txt](https://github.com/stumpwm/stumpwm/files/12453827/stumpwm-config.txt).

Here I tried to do it specifically evaluating `(load-module "swm-gaps")` with `C-t :`.

![stumpwm-interactively-try-to-load-module](https://github.com/stumpwm/stumpwm/assets/30783193/a1598506-b23d-4c22-93d6-4b3d6743c650)


<a id="orgb8ed361"></a>

# why I think this happened

I suspect that for some reason the modules require creating a directory and when they try to create
that directory they don't have the proper permissions. Thus they fail in creating the directory and
the error arises. Somehow the stumpwm from the aur is installed in such a way that it does not need
these permissions.

**Comment by tychoish** [comment]
> That is not, in my least humble opinion, grounds for closing the issue.

I think if @Luis-Henriquez-Perez is correct (and it seems reasonable to think that they are?) then this is probably easy enough to track down. 

While I use arch I've been compiling stumpwm from my own local checkout (with quicklisp installed dependencies) for a few years now (though I did use the arch/aur packages for many years.) 

Just for reference:
- https://gitlab.archlinux.org/archlinux/packaging/packages/stumpwm/-/blob/main/PKGBUILD?ref_type=heads
- https://gitlab.archlinux.org/archlinux/packaging/packages/stumpwm-contrib/-/blob/main/PKGBUILD?ref_type=heads
- https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=stumpwm-git
- https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=stumpwm-contrib-git

It does look like the mainline packages do `cp -ra` and the AUR packages to `cp -r --no-preserve=ownership` which might be a hack, honestly: not super sure what the right answer is on this: contrib probably wants to be something you as a user write, but installing contrib from OS packages is probably a bit dicey in general? Not sure what the right answer is. 

- remove contrib from mainline arch: if people want to use contrib repos, they're better off using the AUR (or frankly installing with quicklisp from a checkout, and I don't think there's a lot of harm in that? The main thing we lose  is accessibility for people who want to use stumpwm but who aren't into common lisp. Such users might exist, but then you get to configuring stump...
- have the recomendation be that you copy the contrib packages into your home directory from `/usr/share` (wiki change for this?)
- arch packages should just package contrib directly. 
- changes to the way stumpwm uses contrib (or contrib itself) to remove the requirement to write (what would this be and can we  enforce it) 

I think the right course of action on this is to file a bug against the mainline arch packages?

**Comment by KonstantinDjairo** [comment]
installing stumpwm-contrib-git from the aur didnt solved anything here.
so i agree that this issue might stay open

**Comment by tychoish** [comment]
> installing stumpwm-contrib-git from the aur didnt solved anything here.
> so i agree that this issue might stay open

This is probably an issue with the Arch packages rather than stumpwm.

**Comment by dmb2** [comment]
Unless we are explicitly breaking something that is being exposed by the packaging process this issue should be filed downstream with Arch's package maintainer.

**Comment by adlai** [comment]
> > That is not, in my least humble opinion, grounds for closing the issue.
> 
> I think if @Luis-Henriquez-Perez is correct (and it seems reasonable to think that they are?) then this is probably easy enough to track down.
> 
> While I use arch I've been compiling stumpwm from my own local checkout (with quicklisp installed dependencies) for a few years now (though I did use the arch/aur packages for many years.)

That's the way I got StumpWM to work for the ~decade when I was using it as my primary environment.

> 
> [...] Not sure what the right answer is.
> 
> * remove contrib from mainline arch: if people want to use contrib repos, they're better off using the AUR (or frankly installing with quicklisp from a checkout, and I don't think there's a lot of harm in that? The main thing we lose  is accessibility for people who want to use stumpwm but who aren't into common lisp. Such users might exist, but then you get to configuring stump...

Ideologically, I think it's important to have StumpWM accessible as precisely this "slippery slope"; consider how the highest-level purpose of programming, is minimaxing of peripheral operations performed relative to the expressive power unlocked. While many detractors still discourage CL use in production projects, I doubt anyone actually discourages learning it. Most people are probably agnostic, having heard of "lisp" only in the context of speech impediments, thus the importance of simplifying the initial steps towards discovering the powerful side of CL.

> [...]
> 
> I think the right course of action on this is to file a bug against the mainline arch packages?

I'm actually in the opposite category right now; CL programmers who don't use StumpWM. However, I have an account on the Arch bugtracker, and might open an issue for this after investigating further.

**Comment by tychoish** [comment]
> While many detractors still discourage CL use in production projects, I doubt anyone actually discourages learning it. Most people are probably agnostic, having heard of "lisp" only in the context of speech impediments, thus the importance of simplifying the initial steps towards discovering the powerful side of CL.

For sure and I think you're right, the issue is less ideological on this point, and more about "people who use arch linux, but aren't already
