### ISSUE TITLE
Error building under debian from master

### ISSUE THREAD

**Issue by tvraman** [stumpwm/stumpwm#1068]
I'm a long-term stumpwm user. I was running stumpwm on Debian --
installed via the apt package manager and it was working fine until my
most recent reboot.

Then it stopped working with the system logging a compile error on
iloop  -- from the system log:

Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/package.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/package-tmpUTZ0UUTE.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/primitives.lisp" (written 14 APR 2018 01:55:59 AM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/primitives-tmpOOSRA8PZ.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/workarounds.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/workarounds-tmpDMIL0RVK.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/wrappers.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/wrappers-tmp8MR9IMIO.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/pathnames.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/pathnames-tmpJQDKAVAY.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/font-rendering.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/font-rendering-tmp3I8CEEQY.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/keysyms.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/keysyms-tmpA3RHFLWZ.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/keytrans.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/keytrans-tmpYZIB7VXO.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/kmap.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/kmap-tmpR8PK79V8.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/input.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/input-tmpN1ZVB1HZ.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/core.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/core-tmpZGRRPISB.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/command.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/command-tmpFNKDE5XP.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/menu.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; file: /usr/share/common-lisp/source/stumpwm/menu.lisp
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/menu-tmpRJTU435C.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]:    compiling #<cl-source-file "stumpwm" "menu">
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/screen.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/screen-tmpI9WG87JK.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/head.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/head-tmpYDE6I9E6.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/group.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/group-tmp319UV2V8.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/bindings.lisp" (written 14 APR 2018 01:55:59 AM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/bindings-tmpLYQINFYS.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/events.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/events-tmpGA31XWNO.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/window.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/window-tmp5HT23M6C.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/floating-group.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/floating-group-tmpA60KLDKY.fasl
Jan  9 06:43:25 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/tile-group.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/tile-group-tmpD801X3GJ.fasl
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/tile-window.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/tile-window-tmpGOW1GC70.fasl
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/window-placement.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/window-placement-tmpPQ1X28TL.fasl
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/message-window.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/message-window-tmpE92ECU7O.fasl
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/selection.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/selection-tmp8S0II570.fasl
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/module.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ; wrote /home/raman/.cache/common-lisp/sbcl-2.2.9.debian-linux-x64/usr/share/common-lisp/source/stumpwm/module-tmpJE88A12F.fasl
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ; compiling file "/usr/share/common-lisp/source/stumpwm/ioloop.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]: ;       Stream: #<sb-int:form-tracking-stream for "file /usr/share/common-lisp/source/stumpwm/ioloop.lisp" {10043A00A3}>
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]:   of #P"/usr/lib/stumpwm/load.lisp":
Jan  9 06:43:26 raman9 /usr/libexec/gdm-x-session[3218]:   COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "stumpwm" "ioloop">
Jan  9 06:47:26 raman9 /usr/libexec/gdm-x-session[3102]: ; compiling file "/usr/share/common-lisp/source/stumpwm/ioloop.lisp" (written 12 JAN 2017 03:58:23 PM):
Jan  9 06:47:26 raman9 /usr/libexec/gdm-x-session[3102]: ;       Stream: #<sb-int:form-tracking-stream for "file /usr/share/common-lisp/source/stumpwm/ioloop.lisp" {1003193173}>
Jan  9 06:47:26 raman9 /usr/libexec/gdm-x-session[3102]:   of #P"/usr/lib/stumpwm/load.lisp":
Jan  9 06:47:26 raman9 /usr/libexec/gdm-x-session[3102]:   COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "stumpwm" "ioloop">

Seeing that the files installed were from 2017, I hopefully updated
from git and attempted to compile, but get a set of different build
errors around xlib and randr:

On git master branch:

make clean followed by make gives this trace.

Is there a fix, ie do I need to install some missing libs?
My system is up-to-date re packages according to the system itself.

make
/usr/bin/sbcl --load ./make-image.lisp
This is SBCL 2.2.9.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
; compiling file "/home/raman/sourceforge/stumpwm/head.lisp" (written 09 JAN 2023 07:25:36 AM):
; 
; caught error:
;   read error during compile-file:
;   
;     Symbol "RR-GET-OUTPUT-INFO" not found in the XLIB package.
;   
;       Line: 44, Column: 30, File-Position: 1503
;   
;       Stream: #<sb-int:form-tracking-stream for "file /home/raman/sourceforge/stumpwm/head.lisp" {1003A6C8E3}>

; compilation aborted after 0:00:00.004
While evaluating the form starting at line 13, column 0
  of #P"/home/raman/sourceforge/stumpwm/load-stumpwm.lisp":
While evaluating the form starting at line 3, column 0
  of #P"/home/raman/sourceforge/stumpwm/./make-image.lisp":

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {10048E81B3}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "stumpwm" "head">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "stumpwm" "head">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "stumpwm" "head">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [RETRY                        ] Retry EVAL of current toplevel form.
  5: [CONTINUE                     ] Ignore error and continue loading file "/home/raman/sourceforge/stumpwm/load-stumpwm.lisp".
  6: [ABORT                        ] Abort loading file "/home/raman/sourceforge/stumpwm/load-stumpwm.lisp".
  7:                                 Retry EVAL of current toplevel form.
  8:                                 Ignore error and continue loading file "/home/raman/sourceforge/stumpwm/./make-image.lisp".
  9:                                 Abort loading file "/home/raman/sourceforge/stumpwm/./make-image.lisp".
 10:                                 Ignore runtime option --load "./make-image.lisp".
 11:                                 Skip rest of --eval and --load options.
 12:                                 Skip to toplevel READ/EVAL/PRINT loop.
 13: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "stumpwm" "head">)))
   source: (ERROR 'COMPILE-FILE-ERROR :CONTEXT-FORMAT CONTEXT-FORMAT
                  :CONTEXT-ARGUMENTS CONTEXT-ARGUMENTS)
0]

**Comment by sdilts** [comment]
You need to update your clx version. Uninstall the debian package if it's
installed on your system, and use the quicklisp version instead as per the
installation instructions. If you are already using quicklisp, check the
docs on how to update just one package, or update all of them with
`ql:update-all-dists`.

**Comment by tvraman** [comment]
I do have ql installed but can never remember if stumpwm is using it,
will check tomorrow morning when I'm more awake.

Aside: have been running exwm as an alternative all day and  it's look
good, but I'd love to get stumpwm back so I can go back to work:-)


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
built like a champ once I updated clx from ql.


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
