### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [stumpwm/stumpwm#1091]
Building with SBCL 2.3.1.122-1455d60f6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 6f1564a721e7021be803c4481ec548331afe2185

*stumpwm-tests* fails to build because of a failure in  _stumpwm_.

*stumpwm* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Symbol "REPLACE-CLASS" not found in the DYNAMIC-MIXINS package. Line: 613, Column: 44, File-Position: 19739 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/stumpwm/30f93a2b318192875563d063d96af51dfa8f5ccb/stumpwm-20230322-git/primitives.lisp" {10088B22F3}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001728003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "stumpwm" "primitives">

```

*stumpwm/build* fails to build because of a failure in  _stumpwm_.

[Full log here](http://report.quicklisp.org/2023-03-22/failure-report/stumpwm.html)

**Comment by szos** [comment]
I think weve had dynamic mixins vendored for a while now, and id imagine quicklisp has built stumpwm since we vendored it; is this at all related to commit 6fa1e1a038e7ffb9e5a2395936d37a4c90e42f91?

Perhaps it would be best to rename the dynamic mixins package that we have vendored to ensure it doesnt clash with the version in quicklisp?

**Comment by quicklisp** [comment]
I'm not sure about that commit, but if you have a vendored dynamic mixins
and rely on new features added to it, it won't work properly when I try to
build stumpwm, sorry. A different name would help.

**Comment by szos** [comment]
Ah i understand, ill whip up a pr this week to address this, changing the package name so everything will work together. Thanks for the info!

**Comment by xach** [comment]
Is this likely to be merged sometime soon?

**Comment by szos** [comment]
Im not sure, i dont have such privilidges. @dmb2 could you take a look at the associated PR and merge if it looks good?

**Comment by szos** [comment]
No problem! If i remember correctly, after discussing with dmb2 we opted for vendoring to avoid adding more dependencies users must obtain on their own. We also stripped out the closer to mop functions and replaced them with sbcl specific mop functions.
