### ISSUE TITLE
Cannot drag to resize table column in firefox under stumpwm

### ISSUE THREAD

**Issue by etclub** [stumpwm/stumpwm#1094]
Please refer to https://github.com/webcompat/web-bugs/issues/120868
But not sure if it is an issue related to stumpwm or firefox.

**Comment by szos** [comment]
I am unsure this is an issue with StumpWM; I'm unable to reproduce using Firefox 111.0.1 and StumpWM built from git. Mousing over the column separators highlights them blue and click&drag-ing them resizes the column.

**Comment by etclub** [comment]
You are right. 
After updating stumpwm from v20 to the latest version, it works.
