### ISSUE TITLE
Research/Implement inputting cyrillic characters into stumpwm prompts

### ISSUE THREAD

**Issue by dbjergaard** [stumpwm/stumpwm#111]
Other complaints from Debian users concern non-ASCII or Dvorak input in
Stumpwm, e.g.:

  It is not possible to input cyrillic characters into stumpwm prompts,
  so it is not possible to exec programs with cyrillic arguments.

What can be done about it?  It's probably more problem of CLX than of
Stumpwm, is there any way to get working support for XKB input in SBCL
and CLISP?

**Comment by dbjergaard** [comment]
This can't be fixed until clx handles utf8 input upstream from us.  There is a PR in the works that will allow us to do this, but it will take time to get merged and for us to implement the change.  I am removing this as a requirement for stumpwm 1.0.0 but will keep this open

**Comment by dbjergaard** [comment]
@PuercoPop I know you contribute to sharplispers/clx.  Was there a PR in the works that would allow us to revisit rendering/handling multibyte strings? Basically, we want to move towards everything being utf8.

**Comment by PuercoPop** [comment]
@dbjergaard Not as far as I can tell

**Comment by dbjergaard** [comment]
I'm closing this for now as the problem is upstream from us (clx needs to support utf8 characters).
