### ISSUE TITLE
A reference to SB-MOP means it cannot work on other implementations

### ISSUE THREAD

**Issue by Yehouda** [stumpwm/stumpwm#1126]
https://github.com/stumpwm/stumpwm/blob/9072f22e1b0fa6a9ce0e7658713fb61a9ddb1469/dynamic-mixins/src/dynamic-mixins.lisp#L8C14-L8C14

The reference to a symbol in SB-MOP means it cannot work in other implementations. 

The version in https://github.com/rpav/dynamic-mixins/blob/7cc09bee7d68527f37406671fabe910e8235b746/src/dynamic-mixins.lisp#L8 seem not to have the SB-MOP.

**Comment by PuercoPop** [comment]
The fact that we use `sb-ext:string-to-octets`, `sb-ext:run-program`, [etc](https://github.com/search?q=repo%3Astumpwm%2Fstumpwm%20sb-ext&type=code) are other reasons. We could use use babel for string-to-octets and closer-mop for sb-mop, etc. But as stated in the [README.md](https://github.com/stumpwm/stumpwm#prerequisites) sbcl is a dependency.
