### ISSUE TITLE
jitsi-meet

### ISSUE THREAD

**Issue by OrionRandD** [stumpwm/stumpwm#1144]
What is the best way to use jitsi-meet inside stumpWM?
Specially for sharing application or the whole screen?
Thx

**Comment by dmb2** [comment]
Hi, I'm not sure what this product is, but as long as it supports X11, sharing the screen should work within the app as expected.  If you have a bug or more information about how stumpwm is the problem, please feel free to re-open.

**Comment by OrionRandD** [comment]
> Hi, I'm not sure what this product is, but as long as it supports X11, sharing the screen should work within the app as expected. If you have a bug or more information about how stumpwm is the problem, please feel free to re-open.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

StumpWM

Official website
https://stumpwm.github.io/

The stumpwm experience  
https://www.youtube.com/watch?v=tKt_rVO960Q

The stumpwm experience - modern version
https://www.youtube.com/watch?v=TdA6t6sLWQY

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

**Comment by OrionRandD** [comment]
> Hi, I'm not sure what this product is, but as long as it supports X11, sharing the screen should work within the app as expected. If you have a bug or more information about how stumpwm is the problem, please feel free to re-open.

https://jitsi.org/jitsi-meet/
