### ISSUE TITLE
Executing certain commands in the background means I can no longer start any program

### ISSUE THREAD

**Issue by K1D77A** [stumpwm/stumpwm#1158]
When I execute `gentoo-pipewire-launcher` using C-t ! (exec) often I am then unable to launch any program.. emacs (C-t e), terminal, anything using `exec` :( 
I dont know why this hap. I have tried executing this on startup using #'uiop:run-program and Stumps #'run-shell-command and I get the same behaviour. I have tried executing it with & as well. 
gentoo-pipewire-launcher
```sh
removed because not relevant
```
Obviously I did not write that, it is packaged as part of Gentoo's pipewire package.
FWIW: executing this script does successfully launch Pipewire.. I just can't launch anything else after.

**Comment by dmb2** [comment]
We try to be XDG compliant, but we are not 100% of the time. Do you have dbus running? Can you launch this before stumpwm in an xinit script? Does it need to run interactively in a terminal?

**Comment by K1D77A** [comment]
I have not had any problems after launching stumpwm with the dbus launcher. For more info: https://wiki.gentoo.org/wiki/D-Bus I'll close the issue soon assuming I have no more problems.

**Comment by K1D77A** [comment]
Booted my laptop. Couldn't open any programs using exec :(

**Comment by K1D77A** [comment]
I have nothing starting on launch and it has happened again. Closing this.
