### ISSUE TITLE
Stump's documentation is lacking and outdated

### ISSUE THREAD

**Issue by Dorovich** [stumpwm/stumpwm#1160]
This may have been pointed out aready, but as for recent versions of StumpWM, both documentation available on the [webpage](https://stumpwm.github.io/documentation.html) and `info` entry are outdated (many functions and ways of configuring features are done differently in newer versions) and a lot of features are missing (some functions don't even show up). This is a problem almost every StumpWM user would benefit from if it were fixed.

In my experience i have had to look up how some variables and funcions are named in the source code, and also things like how to make custom keymaps for my configuration. But after all, this is a great window manager and i'd love seeing it improve!

**Comment by szos** [comment]
This is similar to issue #944. 

Regarding updating the info manual that is generated when building from source, if theres specific things not in the manual you can enumerate them here and Ill try to put together a pr adding them in, or you can add them to stumpwm.texi.in yourself. 

Regarding updating the webpage, thats something the maintainers will need to address.

**Comment by dmb2** [comment]
It is issues like this that really make me want to quit maintaining open source.  

There is zero domain knowledge (no Common Lisp, no X11, no FreeDesktop window manager specs) required for you @Dorovich to actually make the improvements you are implicitly tasking the rest of the community to fix.  

@szos gave you the correct advice, edit stumpwm.texi.in yourself and open a PR.

Want to change the stumpwm.github.io website? [Open a PR](https://github.com/stumpwm/stumpwm.github.io/pulls). Its written in Emacs's org-mode. Clone repo (`git clone git@github.com:stumpwm/stumpwm.github.io.git`) edit the .org files (no need to know org as long as you're changes are to body text), type `make website` view the results in your browser, if you like them, open a PR. The Makefile is written to ease my development burden, so it assumes you can push to the repo (which you won't be able to). Therefore you must use `make website` to see local changes.  You'll need the dependencies to build stumpwm, to build the texi file, to build the info file, texi2html, texi2pdf, and emacs installed.  If that's too much just hand-edit (with butterflies if that's your style) the .org file and submit a PR for just those files.  I'll gladly handle the rest.

For the record, (and for better or worse) the following is a ranking (logarithmic order from high to low)  of how often I check repository issues:
1. stumpwm/stumpwm
2. stumpwm/stumpwm-contrib
3. stumpwm/mahogany
4. stumpwm/stumpwm.github.io

If you've opened an issue in a non stumpwm/stumpwm repo, and I haven't responded in a month, open second issue in stumpwm/stumpwm with a link to your original issue.  The shorter the second issue, the more ashamed I'll be I didn't respond to the original issue (I promise).

> In my experience i have had to look up how some variables and funcions are named in the source code, and also things like how to make custom keymaps for my configuration. But after all, this is a great window manager and i'd love seeing it improve!
I mean this in the most supportive way possible, but reading the source code, hacking in your changes, and being proud of what you've accomplished is *exactly how* stumpwm should be experienced.  Its OK if this isn't for you.
