### ISSUE TITLE
check for "trailing garbage" doesn't work?

### ISSUE THREAD

**Issue by greg-minshall** [stumpwm/stumpwm#1162]
thanks for stumpwm.

if i have some command
````
(defcommand f-int-one (x) ((:number "s: ")) (message (format nil "~S" x)))
````

and then do `[C-t ; f-int-one 3 4]` (notice the extra argument), i see the message `3`, but no error.  it seems like it should throw an error.

below is a manipulated (i'd never seen `labels` before, so [over-] used it) from command.lisp (`call-interactively`, `eval-command`), and the output of the diagnostic messages i stuck in.

i don't understand the `position-if` code; naively, it is stopping the results of  `argument-line-end-p` from throwing an error.

````
(defun al ()
  (in-package :stumpwm)
  (defcommand f-but-one (x)
    ((:number "s: "))
    (message (format nil "~S" x)))
  (labels ((al-if (arg-line)
             (let*
                 ((al-end-p (argument-line-end-p arg-line))
                  (al-string (argument-line-string arg-line))
                  (al-start (argument-line-start arg-line))
                  (pos-if (if al-end-p
                              "<<EOF>>"
                              (position-if
                               'alphanumericp
                               (argument-line-string arg-line)
                               :start (argument-line-start arg-line)))))
               (format nil "al-end-p ~S; al-string ~S; al-start ~S; pos-if ~S"
                       al-end-p al-string al-start pos-if)))
           (check (arg-line)
             (unless (or (argument-line-end-p arg-line)
                         (position-if 'alphanumericp
                                      (argument-line-string arg-line)
                                      :start (argument-line-start arg-line)))
               (throw 'error (format nil "Trailing garbage: ~{~A~^ ~}"
                                     (subseq (argument-line-string arg-line)
                                             (argument-line-start arg-line)))))))
    (let* ((arg-line (make-argument-line :string "f-but-one 3 4" :start 0))
           (cmd (argument-pop arg-line))
           (three (argument-pop arg-line)))
      (message "cmd ~S; three ~S" cmd three)
      (message "~S" (al-if arg-line))
      (check arg-line)
      (message "pop (four) ~S" (argument-pop arg-line))
      (check arg-line)
      (message "~S" (al-if arg-line)))))
````

the output (and version)
````
> eeval (al)
cmd "f-but-one"; three "3"
"al-end-p NIL; al-string \"f-but-one 3 4\"; al-start 12; pos-if 12"
pop (four) "4"
"al-end-p T; al-string \"f-but-one 3 4\"; al-start 14; pos-if \"<<EOF>>\""
NIL
> vversion
22.11 Compiled On Sun Nov 19 2023  5:35:46
````

(those duplicated 'e', 'v'...)

**Comment by greg-minshall** [comment]
i do notice this oddity, making me worry i don't understand what is intended.

````
> ff-int-one 3
3
> ff-int-one 3 4
3
> ff-int-one 3 .
Error In Command 'f-int-one 3 .': The value
                                               "."
                                             is not of type
                                               LIST
````
(the period being non-alphanumeric.)

apologies if this is all noise.

**Comment by dmb2** [comment]
Hi! You have a bit of overhead in your example code... I'm not sure why you have defcommand inside a defun.  

Can you explain what your goals are? 

Which part of the StumpWM api is confusing?

Its hard for me to separate what is a common lisp question and what's a StumpWM question/issue.

**Comment by greg-minshall** [comment]
hi, thanks for looking.  sorry for the confusion!  the defun is in there just to have it defined in the example.

the question, or "bug report" (maybe) is, why does stumpwm not throw an error when a command is invoked (in stumpish or via [C-t ;] with too many (alphanumeric) arguments?

i should have used an example where the lambda list included an `&optional` argument (since otherwise the SBCL lisp code would have thrown an error).  something like this say:

````
(defcommand f-w-opt (x &optional y) ((:number "s: ")) (message (format nil "~S" x)))
````

or, even this (to show that the lisp interpreter sees `y` in the lambda list, but is called with it unset:
````
(defcommand f-w-opt-y (x &optional y) ((:number "s: ")) (message (format nil "~S" y)))
````

(one would call it [`C-t ; f-w-opt-y 3 4`].)

i hope that is clearer.

**Comment by greg-minshall** [comment]
@dmb2 also, my writeup was also confusing in the sense that i didn't really show the complaint/error, i just alluded to it.  the issue is that an extra argument is specified on the command line, but stumpwm does not throw an error, *nor* pass that argument to the command.  (ditto using [`C-t ; ...`].)

the longer piece of code was not trying to show the error.  rather, just me trying to understand/debug what might be going on inside stumpwm's command.lisp code.

in the following, `args` allows `x` and an optional `y`, but `interactive-args` describes only one argument (this is a programmer bug!).  two arguments are specified on the command line.  stumpwm doesn't throw an error, but, at the same time, passes only one argument to the function.

````
> eval (defcommand f-w-opt-x-y (x &optional y) ((:number "s: ")) (message (format nil "~S; ~S" x y)))
#S(COMMAND :NAME F-W-OPT-X-Y :CLASS T :ARGS ((:NUMBER "s: ")))
> ff-w-opt-x-y 3 4
3; NIL
````

**Comment by dmb2** [comment]
I understand that the code isn't behaving the way you expect.  Specifically, if you call the code with the arguments '3 4' the code just produces 3 without signalling an error.  Alternately, if you use "3 ." the interpreter signals an error.

I don't understand what the expected behavior is.  I don't understand what your goal is.

I suspect that there isn't really a bug here, and that the code is working as intended, but not as you expect.  It is hard  to read your example code without understanding what your goals are.

**Comment by greg-minshall** [comment]
hi, David.  you're right, it isn't clear if the behavior is "as intended".  but, i would suggest an error message ("wrong number of arguments").  just to help the programmer or user.

**Comment by dmb2** [comment]
I think the issue is Common Lisp's weird behavior and language for indicating an error/unexpected input.  That is (unfortunately) outside the scope of something I can improve.

**Comment by greg-minshall** [comment]
hi, David,

i was thinking that maybe if this bit in command.lisp was removed, stumpwm would throw an error?
````
                         (position-if 'alphanumericp
                                      (argument-line-string arg-line)
                                      :start (argument-line-start arg-line)))
````
