### ISSUE TITLE
Can't use hover menus on websites in Firefox

### ISSUE THREAD

**Issue by tsmacdonald** [stumpwm/stumpwm#1172]
# Steps to reproduce:

1. In Firefox, go to any website that displays links when you hover over something (e.g. a dropdown menu). [Here's a random example](https://sessionsandsail.com/). I've also noticed it with non-Youtube video player controls, such as Twitter's.

2. Hover over a menu item, observe the submenu that expands.

3. Note that if you hover over a submenu item, Firefox will show the correct URL at the bottom.

4. Click the menu item. Firefox will treat this as a click on the element _beneath_ the submenu, and will not take you to the right page.

# Other info:

* I have Vimium installed; if I use its keyboard shortcut to open the link instead things work fine—this seems to be tied to mouse behavior.

* I can reproduce this in a private window (without Vimium and ad blockers active)

* I can _not_ reproduce this using whatever Ubuntu's default window manager is, which is why I think it's a Stump problem more than a Firefox problem.

* I can _not_ reproduce this on Chrome.

# Versions:

```
$ uname -a
Linux $HOSTNAME 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
$ sbcl --version
SBCL 2.1.9
;; asking Stump for its version:
1.01 Compiled on Wed Jan 25 2023
```

# Related issues

Potentially

https://github.com/stumpwm/stumpwm/issues/330

and

https://github.com/stumpwm/stumpwm/issues/398

**Comment by szos** [comment]
Im on StumpWM version 22 and cant reproduce; does this issue persist on more recent releases of Stump?

**Comment by tsmacdonald** [comment]
Apologies, I was on an old version due to https://github.com/stumpwm/stumpwm/issues/994. Since that's resolved I was able to upgrade to I-think-it's-22 and the problem is indeed gone. Sorry for the false alarm!
