### ISSUE TITLE
Custom map wont accept move-focus right

### ISSUE THREAD

**Issue by chomwitt** [stumpwm/stumpwm#1174]
My Devuan apt shows :Installed: 2:22.11-3
 C-t v show 1.0.1 

Trying to create a custom map to support keys : prefix + f + right  etc
althought left is recognized . right is not:

```
(defvar *my-frame-map*
  (let ((m (stumpwm:make-sparse-keymap)))
    (stumpwm:define-key m (stumpwm:kbd "f") "curframe")
    (stumpwm:define-key m (stumpwm:kbd "Left") "move-focus left")
 (stumpwm:define-key m (stumpwm:kbd "Right") "move-focus right")
     (stumpwm:define-key m (stumpwm:kbd "p") "prev-in-frame")
    m ; NOTE: this is important
  ))

(stumpwm:define-key stumpwm:*root-map* (stumpwm:kbd "f") '*my-frame-map*)
```

**Comment by chomwitt** [comment]
I have managed to solve a lot of issues, including that i reported, by compiling it following the instructions on this site.

**Comment by dmb2** [comment]
Cool! 1.0.1 is kind of ancient.  Where did you get it?
