### ISSUE TITLE
quoted-insert?

### ISSUE THREAD

**Issue by Hexstream** [stumpwm/stumpwm#1175]
Hello,

So I finally got around to [adding some very convenient top-level shortcuts on `F4` and `F6`](https://github.com/Hexstream/status-quo.hexstream.expert/commit/86bf52493bf30540e655eba6729f1290cd8fcddd),
which is extremely convenient when using [my layout](https://status-quo.hexstream.expert/hardware/planck-ez/#raise).

That's great, but my immediate next thought was that I might occasionally want to send `F4` or `F6` to an application.

I can think of various stupid workarounds to do this (such as using `meta`), but the holy grail would be to bind a `quoted-insert` command on `C-t q` which would simply read (_as a key press, not a key name_) the next key and send it directly to the application, as if there were no StumpWM top-level bindings at all. (`quoted-insert` is of course inspired by the emacs command of the same name.)

So for instance, `C-t q C-t` would be exactly equivalent to `C-t t` (`send-escape`), but this would generalize the notion to send any character whatsoever.

(**edit:** I actually already obsoleted my new `F4` thing, and have plans to also obsolete `F6`, but `quoted-insert` would still be a nice feature...)

**Comment by szos** [comment]
You could probably write that command trivially using the send-fake-key and print-key functions? Ie some variation on

`(send-fake-key (current-window) (print-key key-read-in-from-command))`

(Im writing that from memory, the function signature is likely different, so go check out the code/documentation if you use it)

**Comment by tobyWorland** [comment]
Will `send-raw-key` do? 
https://stumpwm.github.io/git/stumpwm-git_25.html

**Comment by Hexstream** [comment]
Actually, I think it will, _thank you!_

Unfortunately, [this seems to be a new feature in StumpWM 23.11](https://github.com/stumpwm/stumpwm/commit/f68f058a5e053509b2eed4a094bc679b11fa01fd#diff-0deabce278b548a31abf7bbddfe9592966fa34ff06603173b0e3565b6a47e302R102). I'm still on StumpWM 1.0.0 on Debian 11, I think I'll just skip Debian 12 and upgrade to Debian 13 when that comes out, and then I think I can use that feature then.

This feature seems [pretty well-buried in the manual](https://stumpwm.github.io/git/stumpwm-git_25.html), because if I go [here](https://stumpwm.github.io/git/stumpwm-git.html) then click on `2 Key Bindings` and then `2.5 Remapped Keys`, there's just no indication that there is a "secret" 2.5.1 section...

Anyway, I guess I'll close this for now, as it seems `send-raw-key` will eventually solve my problem.

_Cheers!_
