### ISSUE TITLE
<prefix> F10 does not work, stumpwm doesn't create group 10.

### ISSUE THREAD

**Issue by rdap** [stumpwm/stumpwm#1180]
I have been trying to configure stumpwm to create 12 groups at startup; but the tenth is inaccessible via <prefix> F10 because stumpwm never creates group 10. (F11 and F12 work fine after remapping those keys to "gselect 11" and "gselect 12", however.)  Instead, stumpwm creates groups in the following pattern:

1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 11, 12

stumpwm's bindings.lisp seems to indicate that <prefix> F10 should switch to the tenth group, however this does not work, so I'm reporting this as a bug.

**Comment by szos** [comment]
This issue should be fixed with PR 1181 (now merged).
