### ISSUE TITLE
stumpwm fails to compile with SBCL 2.4.2

### ISSUE THREAD

**Issue by ckonstanski-olo** [stumpwm/stumpwm#1182]
SBCL 2.4.2 was released in the gentoo portage tree yesterday. After upgrading stumpwm failed to compile. Reverting to 2.4.1 fixed it. Using the latest stumpwm from git.

**Comment by catap** [comment]
Without error it is quite difficult to guess the reason, but https://github.com/stumpwm/stumpwm/pull/1179 may help you.

**Comment by dmb2** [comment]
Please reopen with more details/reproducibility instructions.
