### ISSUE TITLE
StumpWM remappings fail for Firefox on Gentoo Linux

### ISSUE THREAD

**Issue by nameiwillforget** [stumpwm/stumpwm#1190]
I've relently switched my system from Arch to Gentoo. On Arch I had lots of remappings for Firefox:
```
(define-remapped-keys
    `(…
         (,(lambda (win)
              (and (member (window-class win)
                       '("Firefox")
                       :test #'string-equal)
               (not binwarp:*binwarp-mode-p*)))
        ("C-a"   . "Left"))))
        …
```
On Arch, this worked perfectly, but now that I'm on Gentoo, it doesn't. The difference has to be in the Firefox files in some way, because if I copy `/usr/bin/firefox` and `/usr/lib/firefox/` and start in Gentoo, it works. I've tried switching from the self-compiled FF to the pre-compiled version and from the current version (126.0) to the oldest ebuild (115.9), but that didn't change anything. I've also tried putting
```
 export GDK_CORE_DEVICE_EVENTS=1  
```
into my `.xinitrc`, as suggested [here](https://github.com/stumpwm/stumpwm/issues/589), but it also didn't help. The USE-flags I've used to compile FF were 
```
USE="X clang dbus eme-free gmp-autoupdate hardened lto pgo pulseaudio system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-webp wifi -debug -geckodriver -hwaccel -jack -libproxy -openh264 -screencast (-selinux) -sndio -system-png (-system-python-libs) -wayland"
```
Any ideas what could be the problem or how I could find out?

**Comment by nameiwillforget** [comment]
I think I found the problem: on my previous (Arch) system I had noticed that StumpWM's keyboard translations didn't work on GTK programs and didn't know I had to set `GDK_CORE_DEVICE_EVENTS`, so I put `-gtk` into my USE-flags to have as many programs as possible be compiled without it. This didn't change the Firefox compilation but did change some others and exclude some packages that would otherwise have been added as dependencies. I changed the flag to `gtk` and re-compiled the programs in `@world`, which pulled in some gdk-programs as dependencies, and now it seems that gtk-programs in general are sensitive to Stump's key translations. I've only tried this on the pre-compiled version of Firefox, but on that version it's working now. I'll also try a manually compiled version later, but I think it should work now, so I'm closing this issue for now.

**Comment by nameiwillforget** [comment]
I have to re-open this, because when I compile Firefox, the remappings don't work. I've now also tried this out on my newly-gentooed desktop, where the same thing happens: the pre-compiled version works, the locally compiled one ignores remappings.

**Comment by dmb2** [comment]
This appears to be a problem with how firefox is compiled.  It sounds like somewhere firefox is getting compiled in a way that works, but when you run the compilation a required flag is causing it to avoid listening to events being sent to it.  

If you can demonstrate that stumpwm is doing something wrong, we can fix that, however in this case it is an X11 client application that is misbehaving (gtk+firefox in this case).
