### ISSUE TITLE
Notifications from newer Firefox versions treated as tiled windows

### ISSUE THREAD

**Issue by svenssonaxel** [stumpwm/stumpwm#1196]
Filed as Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1903540

However, it could be a bug in stumpwm or clx/xlib.

**Comment by svenssonaxel** [comment]
`xwininfo` shows lots of differences between the good and bad notificatons.

good:
```
_NET_WM_OPAQUE_REGION(CARDINAL) =
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_UTILITY
```

bad:
```
_NET_WM_STATE(ATOM) =
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: <field not available>
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CLOSE
_GTK_THEME_VARIANT(UTF8_STRING) =
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NOTIFICATION
```

**Comment by svenssonaxel** [comment]
Firefox bug confirmed and fixed, it is not a stumpwm bug.

**Comment by Izder456** [comment]
I'm on Firefox 128.6.0esr running 24.11 and I still get this issue, Any chance this will be fixed on ESR?.

**Comment by svenssonaxel** [comment]
@lzder456 You can always ask in https://bugzilla.mozilla.org/show_bug.cgi?id=1903540 but I wouldn't hope for too much. Another option is to run the latest Firefox on your current system, for example by
* Installing nix: `curl -fsSL https://install.determinate.systems/nix | sh -s -- install --determinate`
* Running firefox via nix: `nix run github:nixos/nixpkgs/master#firefox -- --version`
