### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by cdegroot** [stumpwm/stumpwm#1204]
After updating (a lot of stuff: sbcl, hyperlisp, stumpwm..., I think the latter from 23.11 to master) the WM started using a lot of CPU time, around 80% of a single core. Sniffing around made me conclude it was most likely the io-loop, and while I don't know why yet, something causes selects to be called with no timeout (directly visible in strace). On a whim, I replaced `(values null null)` for when no timeouts are listed with `(values 0 100)` and got a much better behaved version, but it smells off (hence no PR) - if I add some printing to that part of the code, there's always an entry on the timeouts list. 

Mostly posting this, therefore, to help track things and to think out loud, maybe someone else has seen this behaviour and/or maybe I'm reading the code all wrong. 

```
$ git diff
diff --git a/ioloop.lisp b/ioloop.lisp
index 207df86..b553629 100644
--- a/ioloop.lisp
+++ b/ioloop.lisp
@@ -287,7 +287,7 @@
                                                                   s-to-ms))
                                                         0)))
                                     (floor remaining-ms 1000000))
-                                  (values nil nil))))
+                                  (values 0 100))))
                        ;; Actually block for events
                        (multiple-value-bind (rval errno)
                            (multiple-value-call #'sb-unix:unix-fast-select

```

**Comment by Junker** [comment]
I have the same behaviour after update to master.
Also I updated CLX because of #1201.

Additional info:
SBCL: 2.4.7
StumpWM: bfa43b7
CLX (https://github.com/sharplispers/clx): 69f2ebb

**Comment by Junker** [comment]
In my case, downgrading SBCL to version 2.4.6 fixed the problem.

**Comment by MIvanchev** [comment]
Downgrading to 2.4.6 fixed it for me as well

**Comment by MIvanchev** [comment]
I believe we need to get all hands on this and try to understand and fix the IO loop because this keeps happening and we can't stay with 2.4.6 forever.

**Comment by Izder456** [comment]
what ended up fixing it for me was changing how I bound keys. I had previously looped through lists of binds using `sb-thread`. and even with `join-thread` or whatever, they didn't properly clean up after themselves and stayed in the stack/memory or something. that led to unnecessary cpu time holding onto these threads as variables. I moved to an asynchronous method of doing this instead of multithreading and my issue went away. I infer that limiting how much you have the cpu handle via symbols or macros can help ameliorate this problem.

another thing that helped lessen my cpu usage was to minimize how much the modeline does on each refresh, cos my stumpwm cpu usage would spike each time it refreshed. making it do less made it also spike less on each refresh. 

I also wanna point out i'm on the latest stable of stumpwm and sbcl from the openbsd/amd64 and openbsd/macppc on -current ports tree, so its clearly not an issue of being on the wrong sbcl or stumpwm version, at least in my case it wasn't.

if anyone reading this thread wants an example config, I have my whole stumpwm config documented in org-mode on [my codeberg](https://codeberg.org/izder456/StumpWM-Config)

**Comment by MIvanchev** [comment]
@Izder456 thanks for sharing that nice config =) I think the remedy however is symptomatic, the real problem is likely that StumpWM's loop is busy waiting for events instead of blocking with a timeout as intended.

**Comment by Izder456** [comment]
@MIvanchev I'm unsure what you mean by "I think the remedy however is symptomatic". Are you saying my experiences with this issue are symptoms of this looping issue? I just don't think I understand properly. Any clarification would be helpful. Thanks

**Comment by MIvanchev** [comment]
@Izder456 I think the tweaks to your config that made the issue disappear / less prominent are not addressing the real cause. The real cause IMO are miscalculated waiting timeouts in the IO loops or even SBCL bugs. I'm working on simplifying and debugging the loop now so we'll know soon enough.

**Comment by MIvanchev** [comment]
Hi, I have reworked the IO loop by simplifying the code, removing all the restarts (why were they there?) and removing the API of *current-io-channel* which was there only to server restarts. The high CPU usage is gone and I'm using latest SBCL. I appreciate your feedback, please give it a try and a look!

**Comment by kflak** [comment]
I am experiencing intermittent high cpu usage (around 55-65%) of stumpwm on commit a774bfe with sbcl 2.5.3. It ramps up at random moments and goes back down after a couple of minutes, so it's hard to say exactly what triggers it. Any pointers on how to debug this?

**Comment by MIvanchev** [comment]
@kflak Can you check with `top` that it's indeed StumpWM's process taking up the CPU? After that we might do some profiling...

**Comment by kflak** [comment]
htop gives me this:

![Image](https://github.com/user-attachments/assets/fb8b9533-823d-484a-8fbe-063ffb09c121)

**Comment by MIvanchev** [comment]
OK, so if you have time and patience you can try to debug it. You'll need to run a Swank server, then call

```
(sb-sprof:start-profiling :max-samples 200000)
```

let StumpWM run a bit

then

```
(progn 
  (sb-sprof:stop-profiling)
  (with-open-file (os "/home/<your-home-dir>/profile-results.txt" :direction :output :if-exists :supersede :if-does-not-exist :create)
    (sb-sprof:report :stream os :type :graph))))
```

**Comment by kflak** [comment]
Cool, will try it when I have a bit more time. Today might be tricky, but if things calm down I'll do it. Hopefully I'll be able to catch one of the high-cpu episodes...

**Comment by kflak** [comment]
OK, getting a bit further here. The increase in cpu usage is happening when I run Reaper, a Digital Audio Workstation. Attaching the profile-results.

[profile-results.txt](https://github.com/user-attachments/files/19929270/profile-results.txt)

**Comment by kflak** [comment]
I tried opening the same Reaper session in i3, and I am not getting any additional CPU usage there. So it's pretty clear that this is, indeed, something on the stumpwm side. The only things in my stump config regarding Reaper is:

```common-lisp
(define-frame-preference "sound"
  (nil T T :class "REAPER")
  (nil T T :class "Snd")
  (nil T T :class "ocenaudio"))
```
and 

```common-lisp
(define-key *root-map* (kbd "C-r") "exec reaper")
```

**Comment by MIvanchev** [comment]
Great results! Let me study the profile log, from what I think the program floods Stump with X11 events and the loop cant sleep. Maybe you could also check the Stump log at debug level.

27. April 2025 13:39, "Kenneth Flak" ***@***.*** ***@***.******@***.***>)> schrieb:
  kflak left a comment (stumpwm/stumpwm#1204) (https://github.com/stumpwm/stumpwm/issues/1204#issuecomment-2833413116)  

	I tried opening the same Reaper session in i3, and I am not getting any additional CPU usage there. So it's pretty clear that this is, indeed, something on the stumpwm side. The only things in my stump config regarding Reaper is: 

	(define-frame-preference "sound" (nil T T :class "REAPER") (nil T T :class "Snd") (nil T T :class "ocenaudio")) 

	and 

	(define-key *root-map* (kbd "C-r") "exec reaper")

**Comment by kflak** [comment]
Cool :-) How do I set the debug level?

**Comment by MIvanchev** [comment]
`(setf *debug-level* 9001)`

:)

**Comment by kflak** [comment]
Couldn't upload the log file to github. Less tha n2 minutes worth of playing around produced a file of 81 mb...! Put it up on wetransfer instead: https://we.tl/t-J2CmgZaBX7. Expires in three days, though, so better download before that time :-)

**Comment by MIvanchev** [comment]
So @kflak, this is very useful, from what I see there's indeed an event flood from Reaper about maximizing the "Choose Project" window and maybe the program's main window. Is the app behaving OK?

**Comment by MIvanchev** [comment]
@kflak I could allowing Reaper as much "space" as possible when managing these two Windows with titles `REAPER v7.36 - Registered ...` and `REAPER Choose Project`. Someone [here](https://old.reddit.com/r/linuxaudio/comments/10lbmdp/reaper_and_tiling_wm_madness_hopelessness_despair/) talks about how Reaper behaves differently on every tiling WM and in general doesn't like to be bossed around regarding positioning and sizing of sub-windows.

**Comment by kflak** [comment]
Great, we're getting to the point now :-) If I make sure that Reaper opens up in a float group the problem seems to go away, apart from a whole bunch of flickering between the main window and the "Open file..." dialog when launching the application. The flickering goes away after clicking anywhere. So yeah, it seems that it's all connected to the unfortunate interaction between Reaper's disregard for tiling wms and how stumpwm deals with it. I'd be curious to figure out why I don't have any problems on i3 with it, though, but I am happy to keep reaper floating instead of tiling, and consider this to be a good enough solution. Thanks a lot for the help!!!

**Comment by MIvanchev** [comment]
Thanks for taking the time to analyze the issue. This is very useful to StumpWM. I guess i3 has a mechanism to deal with these finite exchanges by breaking them up if nothing new happens.

**Comment by kflak** [comment]
My pleasure to help out, I'm really enjoying stumpwm so far. Really nice to have a wm programmed in common-lisp, as I'm increasingly moving my creative coding needs over to that programming language.
