### ISSUE TITLE
Can't compile stumpwm with sbcl 2.4.7

### ISSUE THREAD

**Issue by Minda1975** [stumpwm/stumpwm#1205]
Hello.

First of all I would like to thank you for this amazing window manager. Amazing in its genius.
I decided to compile this window manager using Debian 12. So, I downloaded sbcl from the official website (2.4.7), installed it as written in the instructions. After restarting the computer, sbcl works normally. Then I downloaded stumpwm (git version), compiled it as per the instructions. Compilation went without any problems.
Then I  rebooted the computer again and typed startx ( i am using .xinitrc with command exec stumpwm) . When trying to start a graphical session with the startx command, stumpwm crashed and the graphical session did not start.
Here is what was written in the log (.xsession-errors)

```
Unhandled XLIB::UNIMPLEMENTED-EVENT in thread #<SB-THREAD:THREAD tid=9116 "main thread" RUNNING
                                                 {1001340003}>:
  Event code 0 not implemented for display #<XLIB:DISPLAY :0 (The X.Org Foundation R12101007)>

Backtrace for: #<SB-THREAD:THREAD tid=9116 "main thread" RUNNING {1001340003}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<XLIB::UNIMPLEMENTED-EVENT {10015EB7F3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<XLIB::UNIMPLEMENTED-EVENT {10015EB7F3}>)
2: (INVOKE-DEBUGGER #<XLIB::UNIMPLEMENTED-EVENT {10015EB7F3}>)
3: (CERROR "Ignore the event" XLIB::UNIMPLEMENTED-EVENT :EVENT-CODE 0 :DISPLAY #<XLIB:DISPLAY :0 (The X.Org Foundation R12101007)>)
4: (XLIB::GET-INTERNAL-EVENT-CODE #<XLIB:DISPLAY :0 (The X.Org Foundation R12101007)> 50)
5: (XLIB::READ-EVENT-INPUT #<XLIB:DISPLAY :0 (The X.Org Foundation R12101007)> 50 #S(XLIB::REPLY-BUFFER :SIZE 32 :IBUF8 #(50 62 0 0 66 0 0 0 37 105 0 0 ...) :>
6: (XLIB::READ-INPUT #<XLIB:DISPLAY :0 (The X.Org Foundation R12101007)> NIL NIL #<FUNCTION (LAMBDA (XLIB::PENDING-COMMAND) :IN XLIB::READ-REPLY) {B8001836BB}>
7: (XLIB::READ-REPLY #<XLIB:DISPLAY :0 (The X.Org Foundation R12101007)> #S(XLIB::PENDING-COMMAND :SEQUENCE 17 :REPLY-BUFFER NIL :PROCESS #<SB-THREAD:THREAD t>
8: (XLIB:KEYBOARD-MAPPING #<XLIB:DISPLAY :0 (The X.Org Foundation R12101007)> :FIRST-KEYCODE NIL :START NIL :END NIL :DATA NIL)
9: (XLIB::DISPLAY-KEYBOARD-MAPPING #<XLIB:DISPLAY :0 (The X.Org Foundation R12101007)>)
10: (XLIB:KEYSYM->KEYCODES #<XLIB:DISPLAY :0 (The X.Org Foundation R12101007)> 65511)
11: ((LABELS STUMPWM::FIND-MOD :IN STUMPWM::GET-MODIFIER-MAP) "Meta_L" NIL)
12: (STUMPWM::GET-MODIFIER-MAP)
13: (STUMPWM::UPDATE-MODIFIER-MAP)
14: (STUMPWM::STUMPWM-INTERNAL ":0")
15: (STUMPWM:STUMPWM ":0")
16: ((LAMBDA NIL :IN "/home/user/git/stumpwm/make-image.lisp"))
17: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
18: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
19: (SB-IMPL::%START-LISP)

unhandled condition in --disable-debugger mode, quitting

```
I then uninstalled sbcl (version 2.4.7) and installed the version from the Debian 12 package repository (version SBCL 2.2.9). I was able to compile stumpwm from git with this version of sbcl. 

So I think there is a bug in your code or it is not updated to the latest version of sbcl. This can cause unnecessary trouble for new users.

**Comment by Minda1975** [comment]
This is quick update to this issue.

I was able to install stumpwm using the latest version of sbcl. I would like to describe a mini tutorial for those who will encounter this problem and for those who are not lisp experts.

First, install sbcl, as described [here](https://github.com/stumpwm/stumpwm/wiki/Compiling-SBCL). I installed it in` ${HOME}/.local/bin`
Then i installed **quicklisp** as described [here](https://github.com/stumpwm/stumpwm/blob/master/README.md)

Then, according [#1201](https://github.com/stumpwm/stumpwm/issues/1201#issuecomment-2270205206) i installed **clx** into `local-projects`

Then, in a repl i installed **cl-ppcre** and **alexandria**:
```
(ql:quickload "cl-ppcre")
 (ql:quickload "alexandria")
```
And finally I compiled stumpwm. This method works just fine.
P.S.
I don't think it's appropriate to close this bug report, since this solution is not covered in the stumpwm wiki. And if you install stumpwm using the instructions given in the stumpwm wiki, you will not get a positive result.

**Comment by dmb2** [comment]
This is a problem upstream from us.  When the upstream CLX hits quicklisp, our procedures should continue to work.  Apart from installing clx to local-projects and compiling your sbcl from source, I do not see how your steps are different from the standard procedure.
