### ISSUE TITLE
FreeBSD Build failure after PR 1194

### ISSUE THREAD

**Issue by Jehops** [stumpwm/stumpwm#1211]
Hello,

[Here](https://cgit.freebsd.org/ports/tree/x11-wm/stumpwm/Makefile#n43) is how the FreeBSD port/package builds StumpWM.  As the subject says, the build fails after f2691951b3340852638eac1ff87a034557535bfe.

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD tid=957333 "main thread" RUNNING
                                                              {1103F70273}>:
  Component #:ALEXANDRIA not found, required by #<SYSTEM "stumpwm">
```
I tried adding `--eval "(require:asdf)"` in there or simply use the target in StumpWM's Makefile, but the same error is reported about Alexandria not being found.

CC: @MIvanchev

**Comment by MIvanchev** [comment]
@Jehops can we get the build log? I suspect you are trying to run the tests for which you'll need alexandria because it's a requirement of StumpWM.

**Comment by Jehops** [comment]
@MIvanchev, here is the full build log.  https://pkg.ftfl.ca/data/15amd64-default/2024-09-20_07h45m32s/logs/errors/stumpwm-23.11.28.log

AFAICT, I am (or was) providing Alexandria, but it's no longer being found.

**Comment by MIvanchev** [comment]
@Jehops so let's make sure Alexandria is indeed provided and SBCL is able to find it in the well known locations, one of which was `/usr/share/common-lisp/source/` IIRC. Maybe do a `sbcl --non-interactive --eval "(require :asdf)"  --eval "(asdf:load-system \"alexandria\")"  --eval "(asdf:load-system \"alexandria
\")"` before building StumpWM.

**Comment by Jehops** [comment]
@MIvanchev, this conversation has helped me understand why things no longer work for us. For $reasons, we don't want to install the dependencies (into the well-known locations), so we simply extract the tarballs for Alexandria and the other dependencies next to StumpWM's build directory [0].
```
nobody@15amd64-default:/wrkdirs/usr/ports/x11-wm/stumpwm/work $ ls -lh
total 34
drwxr-xr-x  6 nobody wheel   13B Oct 18  2023 alexandria-20231021-git
drwxr-xr-x  5 nobody wheel   27B Jun  9  2023 cl-ppcre-20230618-git
drwxr-xr-x  7 nobody wheel   52B Mar 31  2023 clx-20230618-git
drwxr-xr-x  6 nobody wheel   87B Sep 20 15:06 stumpwm-23.11-30-g9d67454

```
We then create symlinks to their `.asd` files [1].

```
nobody@15amd64-default:/wrkdirs/usr/ports/x11-wm/stumpwm/work $ find ./stumpwm-23.11-30-g9d67454 -type l -name "*.asd" -exec sh -c 'echo "{} -> $(readlink -n "{}")"' \;
./stumpwm-23.11-30-g9d67454/cl-ppcre-unicode.asd -> /wrkdirs/usr/ports/x11-wm/stumpwm/work/cl-ppcre-20230618-git/cl-ppcre-unicode.asd
./stumpwm-23.11-30-g9d67454/clx.asd -> /wrkdirs/usr/ports/x11-wm/stumpwm/work/clx-20230618-git/clx.asd
./stumpwm-23.11-30-g9d67454/alexandria.asd -> /wrkdirs/usr/ports/x11-wm/stumpwm/work/alexandria-20231021-git/alexandria.asd
./stumpwm-23.11-30-g9d67454/cl-ppcre.asd -> /wrkdirs/usr/ports/x11-wm/stumpwm/work/cl-ppcre-20230618-git/cl-ppcre.asd
```
Would it cause others problems if we could make this work again?

[0] https://github.com/freebsd/freebsd-ports/blob/main/x11-wm/stumpwm/Makefile#L5-L10
[1] https://github.com/freebsd/freebsd-ports/blob/main/x11-wm/stumpwm/Makefile#L39-L41

**Comment by MIvanchev** [comment]
Hey @Jehops you can do this, it's **not** the proper way with SBCL and it has runtime implications because the dependencies still need to be present. The build fails because of this change 

```
-  (asdf:initialize-source-registry
-   '(:source-registry
-    (:directory "@STUMPWM_ASDF_DIR@")
-    :inherit-configuration))

+  (asdf:oos 'asdf:load-op 'stumpwm)
+  (asdf:load-asd #p"@STUMPWM_ASDF_DIR@/stumpwm.asd")
+  (asdf:load-system "stumpwm")
```

This used to register the StumpWM dir as a source repository for ASDF systems which is highly discouraged. Instead, StumpWM's ASD is loaded with the absolute path and all other dependencies are expected at well-known locations. You can fix your build by running `initialize-source-registry` somewhere but it's a bit hard for me to understand the $reasons because the Common Lisp dependencies of StumpWM are not statically linked.

**Comment by Jehops** [comment]
Here is the short version for $reasons.

1. When we depended on the ports below, it required more maintenance and made things fragile.  Whenever any of the dependencies changed in any way, StumpWM would fail to run until it was rebuilt.

2. Our SBCL port depends on and loads an external asdf (even though SBCL includes its own), which does interesting things to make different CL systems play nice together.   You can read about it [here](https://cgit.freebsd.org/ports/tree/devel/cl-asdf/files/asdf-init.lisp).  Given StumpWM only works with SBCL, it was easier to avoid all this and use the technique I described earlier.  Using StumpWM as my only window manager didn't give any problems, and I haven't received any reports from users.

I'm travelling, but when I get home, I will dig into this deeper.

```
devel/cl-alexandria
devel/cl-alexandria-sbcl
x11/cl-clx
x11/cl-clx-sbcl
textproc/cl-ppcre
textproc/cl-ppcre-sbcl
```

**Comment by MIvanchev** [comment]
@Jehops Regarding 1. This happens also when SBCL itself changes because compiled CL is compatible only to the same SBCL version it was produced with. Anyhow you can use `asdf:initialize-source-registry` on Stump's root dir or load each of the depencies' ASDs through `asdf:load-asd`.

**Comment by Jehops** [comment]
I have [a local version of the FreeBSD port](https://github.com/Jehops/freebsd-ports/blob/stumpwm_update/x11-wm/stumpwm/Makefile) that successfully builds using the default make target. There are some other issues, but they don't seem related, so let's close this issue. Thank you.
