### ISSUE TITLE
The "SDL fullscreen game patch" breaks some Java windows

### ISSUE THREAD

**Issue by dolda2000** [stumpwm/stumpwm#138]
I recently pulled the latest changes to StumpWM and got, among them, the "SDL fullscreen game patch" from commit af8d8e6506. This appears to break Java windows that are locked in size, the failure mode being that, having switched away from them, they don't display when switching back to them.

Specifically, it seems to be the elision of `(setf (xlib:window-priority (window-parent win)) :top-if)` for size-locked windows that causes this failure mode. Reverting that part of the commit makes the Java windows work again.

I can't really say I'm familiar enough with X11 to truly understand what this means, however, and neither does the SDL patch commit document how SDL windows benefit from this change, so I'm pretty much stuck at this point.

**Comment by talchas** [comment]
This is a bit of a necro, but I just ran into this yesterday and figured out what was going on (and a less heuristic-based fix if you want it).

SDL-1.2 (and I believe SDL2 in the "legacy" choice if it can't find xrandr/etc) does "fullscreening" by making a new override-redirect window and sticking it over the entire screen, and then drawing to that (or rather a child window of it we don't see). However, if the game does this immediately after creating its normal window at launch this can race with stumpwm doing the group-raise-request on the original application window (which doesn't get unmapped or anything, but also doesn't get drawn to), which winds up with it displayed over the "fullscreen window" somehow. You can sometimes see this race condition by stracing or ltracing the misbehaving app to slow it down on startup and let stumpwm win the race (and then you can make stumpwm lose it again by doing things like bumping up `*debug-level*`).

The original patch worked around this by guessing what windows were the original application windows, and not raising them, but this leads to the problems here. What I instead did that worked was move the `with-server-grabbed` block from around `reparent-window` to be around the whole case in `process-mapped-request` (and around the call to `process-mapped-window` in `process-existing-windows` that I /think/ is what the original grab is for):

```
(xlib:with-server-grabbed (*display*)
  (let ((window (process-mapped-window screen window)))
    (group-raise-request (window-group window) window :map)))
```

A test case for the sdl app: https://gist.github.com/talchas/22aacac5a410df975b7f (note that 640x480 can't instead be your native resolution, and you can build at least on my system with `gcc -O2 $(pkg-config --cflags --libs sdl) foo.c`

**Comment by dbjergaard** [comment]
Hi,

Thanks for the thorough investigation.  You mentioned that you have a workaround
that correctly addresses this? I'm very happy to roll back the patch that fixes
#138 in favor of your patch in order to have the correct behavior.

Cheers,

    David
