### ISSUE TITLE
Support all NETWM window types

### ISSUE THREAD

**Issue by dmb2** [stumpwm/stumpwm#139]
See `primitives.lisp:377`, 
Specifically:
- `_NET_WM_WINDOW_TYPE_DESKTOP`
- `_NET_WM_WINDOW_TYPE_TOOLBAR`
- `_NET_WM_WINDOW_TYPE_MENU`
- `_NET_WM_WINDOW_TYPE_UTILITY`
- `_NET_WM_WINDOW_TYPE_SPLASH`

cf http://standards.freedesktop.org/wm-spec/wm-spec-1.5.html#idm140200472629520

**Comment by fstamour** [comment]
why not? ~~I might still do it~~ xD
