### ISSUE TITLE
Crashes when using slime/swank

### ISSUE THREAD

**Issue by Jehops** [stumpwm/stumpwm#183]
If I put 

    (require 'swank)
    (swank:create-server :dont-close t)

in `~/.stumpwm.rc`

and

    (load (expand-file-name "~/quicklisp/slime-helper.el"))
    (setq inferior-lisp-program "~/local/bin/sbcl")

in `~/.emacs.d/init.el`, then StumpWM becomes unstable.  Here is output from a recent crash

    Unhandled memory fault at #x2.
    [Condition of type SB-SYS:MEMORY-FAULT-ERROR]

    Restarts:
    0: [REMOVE-FD-HANDLER] Remove #<SB-IMPL::HANDLER INPUT on descriptor 4: <RESTART     <<error printing restart>> {1006278903}>

    Backtrace:
    0: (SB-SYS:MEMORY-FAULT-ERROR)
    1: ("foreign function: call_into_lisp")
    2: ("foreign function: post_signal_tramp")

This is on FreeBSD 10.1 AMD64 running SBCL 1.2.7, StumpWM code from git (pulled a few days ago, but this has been a problem for a long time), and installing StumpWM's dependencies with quicklisp.

**Comment by dbjergaard** [comment]
In my invocation I don't have the `:dont-close t` portion:
```lisp
(require 'swank)
(swank:create-server)
```
Otherwise it appears that we are doing very similar things and I've
never noticed any instability.  Does this happen with a specific action?
Does it happen only after you connect via slime?

    Dave

**Comment by Jehops** [comment]
I've changed the line in `~/.stumpwmrc` to `(swank:create-server)` and I'll test a little to clarify your other questions.

**Comment by Jehops** [comment]
Simply uncommenting `(swank:create-server)` in `~/.stumpwmrc` causes instability.  There is no specific action I've noticed and it happens without connecting with slime.

**Comment by jorams** [comment]
I've never seen anything like this. What version of SLIME do you use? From the latest Quicklisp?

If you run `(swank:create-server)` from an SBCL REPL without StumpWM, do you have the same kind of instability?

**Comment by Jehops** [comment]
Yes, I'm running SLIME from the latest Quicklisp.  I'll try to answer your last question, but because the crashes only happen after hours, it might take me a few days.

**Comment by dbjergaard** [comment]
I see that you're running a local version of sbcl, a couple things to try:
1. Run sbcl from your distro's package manager. Re-install quicklisp after removing your local sbcl. 
2. Uninstall the package manager's sbcl and re-install your local version, then uninstall/reinstall quicklisp.

I suspect that there is some version mismatch that may be causing the mysterious instabilities.  I'm willing to bet that isolating which sbcl is getting run where will fix your issue.  Since your running locally, you can have situations where the system uses sbcl for one thing (say stumpwm's compilation) but quicklisp picks up your local install, or quicklisp and sbcl get built with the system sbcl and slime is running the local version.  Any of these combinations could lead to bad behavior.

**Comment by Jehops** [comment]
The reason I'm running a local version of SBCL is that the FreeBSD port/package is stuck at version 1.1.12.

1. I had this problem when I only had the SBCL package installed (no local SBCL compiled manually), but to be certain, I uninstalled SBCL and Quicklips, unset any environment variables related to the local SBCL, removed all configuration files and started again.  I installed the FreeBSD SBCL package, then installed Quicklisp and recompiled StumpWM.  It took a few hours, but StumpWM crashed again.  This time the prefix key just stopped working and I couldn't switch between windows.  So, in short, no change from when I was using the local, more recent SBCL.  I can say with near certainty that when I remove `(swank:create-server)` from `~/.stumpwmrc` everything is stable.

2. No change.

**Comment by Jehops** [comment]
Here's a new backtrace from the latest crash running swank from StumpWM.

    Unhandled breakpoint/trap at #x821DFF0C2.
       [Condition of type SB-SYS:BREAKPOINT-ERROR]
    
    Restarts:
     0: [REMOVE-FD-HANDLER] Remove #<SB-IMPL::HANDLER INPUT on descriptor 4: #<RESTART <<error printing restart>> {1007130043}>
    
    Backtrace:
      0: (SB-KERNEL::UNHANDLED-TRAP-ERROR #.(SB-SYS:INT-SAP #X821DFEE40))
      1: ("foreign function: call_into_lisp")
      2: ("foreign function: funcall1")
      3: ("foreign function: handle_trap")
      4: ("foreign function: undoably_install_low_level_interrupt_handler")
      5: ("bogus stack frame")
      6: (SB-IMPL::SUB-SUB-SERVE-EVENT NIL NIL)
      7: (SB-IMPL::SUB-SERVE-EVENT NIL NIL NIL)
      8: (SB-SYS:WAIT-UNTIL-FD-USABLE 4 :INPUT NIL T)
      9: (XLIB::BUFFER-INPUT-WAIT-DEFAULT #<XLIB:DISPLAY :0 (The X.Org Foundation R11407000)> NIL)
     10: (XLIB::BUFFER-INPUT-WAIT #<XLIB:DISPLAY :0 (The X.Org Foundation R11407000)> NIL)
     11: (XLIB::READ-INPUT #<XLIB:DISPLAY :0 (The X.Org Foundation R11407000)> NIL NIL #<FUNCTION (LAMBDA (XLIB::PENDING-COMMAND) :IN XLIB::READ-REPLY) {1002F019DB}> #S(XLIB::PENDING-COMMAND :SEQUENCE 1 :REPLY..
     12: (XLIB::READ-REPLY #<unavailable argument> #<unavailable argument>)
     13: (XLIB:QUERY-EXTENSION #<XLIB:DISPLAY :0 (The X.Org Foundation R11407000)> :XINERAMA)
     14: (XLIB::INITIALIZE-EXTENSIONS #<XLIB:DISPLAY :0 (The X.Org Foundation R11407000)>)
     15: (XLIB:OPEN-DISPLAY "" :DISPLAY 0 :PROTOCOL :LOCAL :AUTHORIZATION-NAME NIL :AUTHORIZATION-DATA NIL)
     16: (STUMPWM::STUMPWM-INTERNAL ":0")
     17: (STUMPWM:STUMPWM ":0")
     18: ((LAMBDA NIL :IN "/usr/home/jrm/scm/stumpwm.git/make-image.lisp"))
     19: ((FLET #:WITHOUT-INTERRUPTS-BODY-87 :IN SAVE-LISP-AND-DIE))
     20: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

**Comment by dbjergaard** [comment]
is there a way we could eliminate stumpwm by connecting to a lisp with swank that is running something minimal.  The stack trace doesn't really show anything suspicious from stumpwm's end, its all xlib related things, so this may even be an issue in clx on FreeBSD.

**Comment by Jehops** [comment]
Yeah, the backtrace isn't helpful, but it's the best I can get.  I spent a ridiculous amount of time with nyef on #sbcl on Freenode trying to get a trace before sbcl wipes it out and starts again.

I'm not sure about your suggestion above, but if I find some time I'll look into it.  It will probably take me some time.  Work is very busy.

**Comment by dbjergaard** [comment]
To be a little more clear, maybe trying to get sbcl to crash with a simple "hello world" clx application.  There's sort of an example here:
http://www.cawtech.demon.co.uk/clx/simple/hello-world.txt

So get the hello world window up, connect with swank and try to draw another string like "Hi back!" or something from swank.  That would replicate whats going on with stumpwm.

If you can't figure out how to dump hello world into a standalone binary there are examples in stumpwm's makefile (which calles make-image.lisp iirc)

**Comment by dbjergaard** [comment]
Can you make sure you're using the right core file? I just had a situation on my desktop where stumpwm was picking up the system lisp, but that lisp was using a local core file causing all kinds of fun.

**Comment by Jehops** [comment]
I can confirm the correct core file was being used.

**Comment by dbjergaard** [comment]
Did you have any luck getting a hello world to crash? This really looks like a clx issue.

**Comment by Jehops** [comment]
I gave it a shot, but ran into problems.  Are you ever in #stumpwm on Freenode?

**Comment by dbjergaard** [comment]
I can be in about an hour as dbjergaard or ocmsRzr, just a forewarning:
I'm not a lisp expert by any means, stumpwm is a learning process for me
more than anyone.

Cheers,

    Dave

**Comment by Jehops** [comment]
OK, it will be the blind leading the blind.  I'm in and out of meetings, but will be around part of the time.

**Comment by dbjergaard** [comment]
sorry I missed you, I got stuck in some other things.

**Comment by dbjergaard** [comment]
Please reopen this if there is any new developments.  IIRC we debugged this over irc, but didn't find anythign that eliminated stumpwm or clx.  Its a really weird and irreproducible bug. If my suspicions are right, it has more to do with your environment than stumpwm proper.
