### ISSUE TITLE
Update manual to describe init file options

### ISSUE THREAD

**Issue by etrumbo** [stumpwm/stumpwm#185]
Recently I patched the code base to allow StumpWM to look for ~/.stumpwm.d/init.lisp as an init.file. I started that after stumbling onto stumpwm.lisp's 'load-rc-file' routine, which provides for the Unix-traditional ~/.stumpwmrc, an XDG-style ~/.config/stumpwm/config, or a system-wide /etc/stumpwmrc. All except ~/.stumpwmrc have been undocumented outside of the source.

I propose that we add some mention of these different init file options to StumpWM's Info manual. I believe it merits its own page, perhaps named "Init File". I'm inexperienced in Texinfo composition, but I would be willing to begin work in my fork and I look forward to input on this.

**Comment by dbjergaard** [comment]
Hack away! If you get stuck let me know.  The stumpwm.info file is generated from stumpwm.texi which is compiled from stumpwm.texi.in, so in order to have your changes show up in a PR, you'll need to make your edits in stumpwm.texi.in.

**Comment by etrumbo** [comment]
I'll see what I can do. Do you agree that StumpWM's init file merits a separate (if brief) section in the manual?

-- 
Edward Trumbo

"In Emacs Veritas."

**Comment by dbjergaard** [comment]
Yes, the more documentation the better, especially when they're
currently undocumented features.

    Dave

**Comment by etrumbo** [comment]
OK, I've updated the wiki's "Customize" page, and I'll start the Info
manual ASAP.

-- 
Edward Trumbo

"In Emacs Veritas."

**Comment by scottjad** [comment]
@dbjergaard I'm seeing the "Init File" section in the html output at https://stumpwm.github.io/git/stumpwm-git_1.html#Introduction but not in the pdf output at https://stumpwm.github.io/git/stumpwm-git.pdf. Any ideas why that might be?

Also I think it would be nice to mention in this section how to reload the init file as the user make edits; not delve into slime but mention whatever the basic version is. Is loadrc the command for that?

After the "...edit it to suit your preferences." paragraph I think we should add one like this
```
As you make edits to the file, you can reload it with @kbd{C-t ;
loadrc}.
```
Is that the correct format? 

I don't know how well loadrc works on basic configs, it doesn't handle my config.

**Comment by dbjergaard** [comment]
That looks correct, mostly I just do the build incantation and make sure the output looks right.

RE: pdf vs html, it is likely that one is out of date since I don't have an automated way of regenerating the manual in html and pdf when an update is made.
