### ISSUE TITLE
CCL builds incomplete stumpwm.info manual

### ISSUE THREAD

**Issue by etrumbo** [stumpwm/stumpwm#188]
At various times, I've built and run StumpWM using SBCL, CLISP, and Clozure CL (CCL), all in current 64-bit Linux versions. I've noticed a strange problem with stumpwm.info when built with CCL -- every function listing fails to list the parameters, replacing them with "(Check the code for args list)" throughout. SBCL and CLISP both pull the relevant information into the Info doc correctly.

Versions:
CCL for 64-bit Linux, Subversion revision 16352.
Texinfo 4.13 (Not current, but I've heard there are performance regressions with 5.x)
Slackware Linux, 64-bit -current

**Comment by jorams** [comment]
That's because [this][here] doesn't have a clause for CCL. If you know how to get the lambda list of a function in CCL you can open a pull request. (or just reply here)

[here]: https://github.com/stumpwm/stumpwm/blob/master/manual.lisp#L46

**Comment by etrumbo** [comment]
Thanks. Pull request waiting.
