### ISSUE TITLE
StumpWM dies since commit 2f0231b

### ISSUE THREAD

**Issue by ghferrari** [stumpwm/stumpwm#193]
Since commit 2f0231b67e23d677612eb4c5f29649bd4eb07059 stumpwm dies on startup with the following error messags:

Feb 25 16:48:41 lindy /etc/gdm3/Xsession[1338]: debugger invoked on a SIMPLE-ERROR in thread
Feb 25 16:48:41 lindy /etc/gdm3/Xsession[1338]: #<THREAD "main thread" RUNNING {1005286CD3}>:
Feb 25 16:48:41 lindy /etc/gdm3/Xsession[1338]: unknown type specifier: STUMPWM::FLOAT-GROUP
Feb 25 16:48:41 lindy /etc/gdm3/Xsession[1338]: Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
Feb 25 16:48:41 lindy /etc/gdm3/Xsession[1338]: restarts (invokable by number or by possibly-abbreviated name):
Feb 25 16:48:41 lindy /etc/gdm3/Xsession[1338]: 0: [QUIT-STUMPWM] Quit Stumpwm
Feb 25 16:48:41 lindy /etc/gdm3/Xsession[1338]: (SB-KERNEL::%%TYPEP #<STUMPWM::TILE-GROUP {1005AAF4D3}> #<SB-KERNEL:UNKNOWN-TYPE STUMPWM::FLOAT-GROUP> T)
Feb 25 16:48:41 lindy /etc/gdm3/Xsession[1338]: 0]
Feb 25 16:48:41 lindy /etc/gdm3/Xsession[1338]: debugger invoked on a TYPE-ERROR in thread
Feb 25 16:48:41 lindy /etc/gdm3/Xsession[1338]: #<THREAD "main thread" RUNNING {1005286CD3}>:
Feb 25 16:48:41 lindy /etc/gdm3/Xsession[1338]: The value NIL is not of type (OR (AND SYMBOL (NOT NULL)) RESTART).

**Comment by dbjergaard** [comment]
Do you initialize any float groups in your stumpwmrc?

**Comment by hamo** [comment]
I met the same problem. You can find my stumpwmrc at  https://github.com/hamo/Dotfiles/blob/Arch/.stumpwmrc

**Comment by ghferrari** [comment]
Hi David, no, I don't initialise any float groups at all.

On 27 February 2015 at 04:31, Bai, Yang <notifications@github.com> wrote:

> I met the same problem. You can find my stumpwmrc at
> https://github.com/hamo/Dotfiles/blob/Arch/.stumpwmrc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stumpwm/stumpwm/issues/193#issuecomment-76329048>.
>



-- 
Dr Geoffrey Ferrari
Lecturer in Philosophy
Jesus College

Mobile: 07989 851364
Work Email: geoffrey.ferrari@jesus.ox.ac.uk
Personal Email: geoffrey.ferrari@oriel.oxon.org
Web: geoffreyferrari.com

**Comment by a13** [comment]
+1
https://github.com/a13/dotfiles/blob/master/.stumpwmrc

**Comment by jorams** [comment]
We're probably missing an import somewhere.

**Comment by a13** [comment]
yes, because float-group is defined in package

 (in-package :stumpwm.floating-group)

**Comment by dbjergaard** [comment]
@jorams can you look into this? I don't really have a clue about it.  The best I could do is roll back to before the commit, but I think this may be symptomatic of merging your float-group package PR.

**Comment by jorams** [comment]
I believe it's fixed now, :+1:

**Comment by a13** [comment]
works for me, thanks!
