### ISSUE TITLE
Ability to swap/shuffle window applications in one command

### ISSUE THREAD

**Issue by shakthimaan** [stumpwm/stumpwm#197]
I am interested to see a shortcut to shuffle the windows repeatedly, similar to http://xmonad.org/tour.html#shuffling.

This way, one doesn't need to remember what is hidden and to pull the hidden application into an empty window.

**Comment by dbjergaard** [comment]
Does C-t M-arrow do what you want?  StumpWM is conceptually different from xmonad in that it is not a dynamic window manager. StumpWM relies on the user to define frames.  If you want to cycle through the windows in a frame there's C-t n or C-t p.

**Comment by dbjergaard** [comment]
Also, an online version of the info manual is here:
https://stumpwm.github.io/documentation.html

**Comment by shakthimaan** [comment]
Yes, C-t M-arrow works. I am trying to move away from arrow keys, so this short-cut can be re-mapped? I shall go through the manual.

Thanks for your prompt replies.

**Comment by dbjergaard** [comment]
You'll want to check:
https://stumpwm.github.io/0.9.8/stumpwm-0.9.8_2.html#Binding-Keys

Feel free to close this if you feel that I've addressed the issue.

**Comment by shakthimaan** [comment]
I have tried C-t n and C-t p and that works too. I use C-t w to see a list of windows to pull from. Thanks again for your prompt replies.

Closing the issue.
