### ISSUE TITLE
undefine key "k" from *root-map* is not working

### ISSUE THREAD

**Issue by spiderbit** [stumpwm/stumpwm#202]
neither:

```lisp
(define-key *root-map* (kbd "k") NIL)
```

nor 

```lisp
(undefine-key *root-map* (kbd "k"))
```

it deletes windows I did not want to be deleted because its a similar shortcut than what I uso for paste or yank (letter v position on dvorak).

**Comment by dbjergaard** [comment]
can you explain when and where you are using this? I checked and the code should be working. Also, could you try with another key in the *root-map*?

**Comment by dbjergaard** [comment]
Please reopen this if the issue still affects you.  Make sure that you aren't removing the keybinding before it gets repopulated by something else.
