### ISSUE TITLE
StumpWM/X server crash when running Renoise

### ISSUE THREAD

**Issue by defaultxr** [stumpwm/stumpwm#205]
I'm running StumpWM 0.9.9-68-g8d93923 under SBCL 1.2.10 and xorg-server 1.17.1. I'm using Arch Linux. StumpWM and/or the X server consistently crash when I try to run Renoise. This still happens even if I rename my .stumpwmrc so it isn't loaded. It also happens even if I run Renoise in a float group.

To reproduce, download the demo version of Renoise and run it. After the splash screen, StumpWM and the X server will crash.

Here are the last lines of the stderr of the X session when StumpWM's *debug-level* is set to 20:

---

18:39:01 timeout: NIL
18:39:01 >>> :FOCUS-IN
18:39:01 <<< :FOCUS-IN
18:39:01 timeout: NIL
18:39:01 >>> :PROPERTY-NOTIFY
18:39:01 property notify #<XLIB:WINDOW :0 265> :_NET_ACTIVE_WINDOW :NEW-VALUE
18:39:01 <<< :PROPERTY-NOTIFY
18:39:01 timeout: NIL
18:39:01 >>> :PROPERTY-NOTIFY
18:39:01 property notify #<XLIB:WINDOW :0 265> :_NET_CLIENT_LIST_STACKING :NEW-VALUE
18:39:01 <<< :PROPERTY-NOTIFY
18:39:12 timeout: NIL
18:39:12 >>> :CREATE-NOTIFY
18:39:12 <<< :CREATE-NOTIFY
18:39:13 timeout: NIL
18:39:13 >>> :CONFIGURE-REQUEST
18:39:13 CONFIGURE REQUEST :ABOVE #<XLIB:WINDOW :0 1800148> 0 0 1596 971 0 15
18:39:13 <<< :CONFIGURE-REQUEST
18:39:13 timeout: NIL
18:39:13 >>> :CONFIGURE-NOTIFY
18:39:13 CONFIGURE NOTIFY NIL #<XLIB:WINDOW :0 1800148> 0 0 1596 971 0 NIL
18:39:13 <<< :CONFIGURE-NOTIFY
18:39:13 timeout: NIL
18:39:13 >>> :CONFIGURE-REQUEST
18:39:13 CONFIGURE REQUEST :ABOVE #<XLIB:WINDOW :0 1800148> 42 26 1596 971 0 15
18:39:13 <<< :CONFIGURE-REQUEST
18:39:13 timeout: NIL
18:39:13 >>> :CONFIGURE-REQUEST
18:39:13 CONFIGURE REQUEST :ABOVE #<XLIB:WINDOW :0 1800148> 0 0 1596 971 0 64
18:39:13 <<< :CONFIGURE-REQUEST
18:39:13 timeout: NIL
18:39:13 >>> :MAP-REQUEST
18:39:13 map request: #<WINDOW :0 1800148> #<WINDOW :0 265> NIL
18:39:13 role: NIL
18:39:13 Free number: (0 1 2 3)
18:39:13 maximizing #S(TILE-WINDOW "" #x1800001)
18:39:13 maximize window #S(TILE-WINDOW "" #x1800001) x: 2202 y: 346 width: 556 height: 208 border: 0 stick: T
18:39:13 maximizing #S(TILE-WINDOW "renoise  /home/modula" #x140000A)
18:39:13 maximize window #S(TILE-WINDOW "renoise  /home/modula" #x140000A) x: 1680 y: 0 width: 1596 height: 900 border: 0 stick: NIL
18:39:13 maximizing #S(TILE-WINDOW "dpaste: 2HWRJ3A: err2.txt, by modula - NetSurf" #x1600024)
18:39:13 maximize window #S(TILE-WINDOW "dpaste: 2HWRJ3A: err2.txt, by modula - NetSurf" #x1600024) x: 1680 y: 0 width: 1600 height:
900 border: 0 stick: NIL
18:39:13 maximizing #S(TILE-WINDOW "Warning from NetSurf" #x1600003)
18:39:13 maximize window #S(TILE-WINDOW "Warning from NetSurf" #x1600003) x: 2266 y: 400 width: 425 height: 97 border: 1 stick: T
18:39:13 maximizing #S(TILE-WINDOW "Renoise (x86_64)" #x1800148)
18:39:13 maximize window #S(TILE-WINDOW "Renoise (x86_64)" #x1800148) x: 1680 y: 0 width: 1600 height: 900 border: 0 stick: NIL
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0.0"
      after 1528 requests (1528 known processed) with 0 events remaining.
/usr/lib/python2.7/site-packages/batti/BatteryMonitor.py:141: GtkWarning: GdkWindow 0xc00003 unexpectedly destroyed
  gtk.main()
batti: Fatal IO error 104 (Connection reset by peer) on X server :0.0.
urxvt: X connection to ':0.0' broken, unable to recover, exiting.

-----

batti and urxvt are part of the stderr because they were casualties of the X server crash. They don't affect this issue at all.

This doesn't happen in other window managers like Fluxbox. I can run Renoise in it without any issue.

I can provide any more information that is necessary but I think this issue should be reproducable. I don't think it's an issue with my graphics card or anything like that.

**Comment by dbjergaard** [comment]
Is there a lisp stack trace with this?  What is the behavior like? Does it hang for a while and then crash? Finally, are there any options for renoise to be start maximized, or to request a geometry when starting renoise?

**Comment by defaultxr** [comment]
No stack trace was printed to stdout or stderr. What I pasted is the last lines of stderr from the session before I was dropped back to the console.

Renoise's splash screen runs fine, but as soon as the main window is about to display, the X server crashes. This doesn't happen in any other window manager.

This should be reproducable with the demo version of Renoise from http://renoise.com/download . I'm using the 64 bit version, but I think it should work with either one.

I don't believe Renoise has any command line options to change the main window's geometry, but it's normally resizable once started.

**Comment by futuro** [comment]
I had this issue as well, and I believe I solved it by de-selecting the "Override window manager shortcuts" preference. It's in Preferences->Keys->Global keyboard options. Also, I think if you open ~/.renoise/<version>/Config.xml and change 
```
    <OverrideSystemShortcuts>true</OverrideSystemShortcuts>
```
to
```
    <OverrideSystemShortcuts>false</OverrideSystemShortcuts>
```
That will probably do the same as well, but I haven't double checked it.

**Comment by defaultxr** [comment]
Works for me as well, thanks for the workaround.

**Comment by senkowo** [comment]
I recently installed Renoise and I'm having the same issue. Toggling the preference "Override window manager shortcuts" did not fix it. 

There are several recent (<1yr old) posts over on the Renoise forums with others having the same issue:
- https://forum.renoise.com/t/linux-x11-crash-with-stumpwm-window-manager-and-renoise/43330
- https://forum.renoise.com/t/x11-crash-on-stumwm-linux/69746

In debugging this, I ran stumpwm with basically default settings, inside of a Xephyr server (nested X server), and found some interesting results. When Renoise starts up, only stumpwm crashes—the Xephyr X server does not.

Here's a snippet of the stumpwm debug output from running Renoise (*debug-log* set to 20):
```
20:46:25  2 property notify #<XLIB:WINDOW :1 51E> :_NET_CLIENT_LIST_STACKING :NEW-VALUE
20:46:25  2 <<< :PROPERTY-NOTIFY
20:46:26  1 >>> :CREATE-NOTIFY
20:46:26  2 <<< :CREATE-NOTIFY
20:46:26  1 >>> :CREATE-NOTIFY
20:46:26  2 <<< :CREATE-NOTIFY
20:46:26  1 >>> :CONFIGURE-REQUEST
20:46:26  3 CONFIGURE REQUEST :ABOVE #<XLIB:WINDOW :1 600034> 0 0 742 231 0 15 
20:46:26  2 <<< :CONFIGURE-REQUEST
20:46:26  1 >>> :CONFIGURE-NOTIFY
20:46:26  4 CONFIGURE NOTIFY NIL #<XLIB:WINDOW :1 600034> 0 0 742 231 0 NIL 
20:46:26  2 <<< :CONFIGURE-NOTIFY
20:46:26  1 >>> :CONFIGURE-REQUEST
20:46:26  3 CONFIGURE REQUEST :ABOVE #<XLIB:WINDOW :1 600034> 109 266 742 231 0 15 
20:46:26  2 <<< :CONFIGURE-REQUEST
20:46:26  1 >>> :CONFIGURE-REQUEST
20:46:26  3 CONFIGURE REQUEST :ABOVE #<XLIB:WINDOW :1 600034> 0 0 742 231 0 64 
20:46:26  2 <<< :CONFIGURE-REQUEST
20:46:26  1 >>> :MAP-REQUEST
20:46:26  3 map request: #<WINDOW :1 600034> #<WINDOW :1 51E> NIL
20:46:26 10 role: NIL
```

An interesting thing with Xephyr servers is that when a window manager running inside it crashes, the X windows (and programs) are not killed, and can still be interacted with. And upon restarting stumpwm, it should grab all the existing windows. 

If I try to start stumpwm while Renoise is still up and running inside the Xephyr X server, stumpwm loads up, then immediately crashes. 
Here's the output from that (note: at this point, Renoise is yet to fully load. There is a floating error message saying "Failed to create a RealTime priority thread for ALSA. Will create a non RT thread instead..." (Also note that on the previous error log, stumpwm crashes on that same state, with that floating error message (although, this shouldn't matter whether stumpwm crashes or not—it seems like stumpwm crashes on any Renoise X window))):
```
20:48:47  5 Outputting a message:
        ^2*Welcome to The ^BStump^b ^BW^bindow ^BM^banager!
        Press ^5*C-t ?^2* for help.
20:48:47  3 Using window stacking: 600001 
20:48:47  1 Processing "" #<XLIB:WINDOW :1 600001>
20:48:47 10 role: NIL
20:48:47  3 Free number: NIL
20:48:47  3 maximizing #<TILE-WINDOW "" #x600001>
20:48:47  4 maximize window #<TILE-WINDOW "" #x600001> x: 202 y: 410 width: 556 height: 208 border: 0 stick: T
20:48:47  1 Processing "Renoise" #<XLIB:WINDOW :1 600034>
20:48:47 10 role: NIL
```  

I did the same here but running stumpwm after Renoise fully starts up, and where I'm on the main Renoise interface.
```
20:50:47  5 Outputting a message:
        ^2*Welcome to The ^BStump^b ^BW^bindow ^BM^banager!
        Press ^5*C-t ?^2* for help.
20:50:47  3 Using window stacking: 600001 
20:50:47  1 Processing "Renoise (x86_64)" #<XLIB:WINDOW :1 600031>
20:50:47 10 role: NIL
```

And finally, here's the stdout log from Renoise, right up to the moment stumpwm crashes:
```
Renoise LOG> ScriptingTools: Initializing Scripting Tool: '/usr/local/share/renoise-3.4.3/Scripts/Tools/com.renoise.UpdateChecker.xrnx/'...
Renoise LOG> DspDevices: Registering native DSP effects...
Renoise LOG> LADSPA: LADSPA_PATH environment variable not set. Using '/usr/lib[64]/ladspa:/usr/local/lib[64]/ladspa:~/.ladspa'...
Renoise LOG> Audio Plugins: Skipping LADSPA plugin path '/usr/lib/ladspa/' (Directory does not exist)...
Renoise LOG> Audio Plugins: Skipping LADSPA plugin path '/usr/lib64/ladspa/' (Directory does not exist)...
Renoise LOG> Audio Plugins: Skipping LADSPA plugin path '/usr/local/lib/ladspa/' (Directory does not exist)...
Renoise LOG> Audio Plugins: Skipping LADSPA plugin path '/usr/local/lib64/ladspa/' (Directory does not exist)...
Renoise LOG> Audio Plugins: Skipping LADSPA plugin path '/home/yui/.ladspa/' (Directory does not exist)...
Renoise LOG> DSSI: DSSI_PATH environment variable not set. Using '/usr/lib[64]/dssi:/usr/local/lib[64]/dssi:~/.dssi'...
Renoise LOG> Audio Plugins: Skipping DSSI plugin path '/usr/lib/dssi/' (Directory does not
```

Also, when stumpwm crashes, in the tty/terminal from which stumpwm is run in, it prints "Another window manager is running". This might be related to the fact that I'm running it inside of a nested X server inside a different window manager, but that message only appears when stumpwm crashes in this situation, so it's at least worth noting. 

I might try getting useful logs from using the Stumpwm Debugger (https://github.com/szos/SDB), but I'm not sure how effective that will be. 

I've heard that stumpwm can crash with very specific X applications when focusing or managing them, so it might be a similar case to that. I also know that Renoise is a rather old program, so perhaps it's a case of the program using a weird and legacy way of windowing, perhaps. 

If I ultimately cant get Renoise working, I might resort to running Renoise in a nested X server, but using a different window manager. 

Any advice would be appreciated!
