### ISSUE TITLE
*mode-line-position* ignored

### ISSUE THREAD

**Issue by spaceotter** [stumpwm/stumpwm#215]
I'm trying to get this to cooperate with xfce4 panel, but setting *mode-line-position* doesn't change the mode line position.
In ~/.stumpwmrc:
```(setf *mode-line-position* :bottom)```
This appears to work with the default mode line, but not with xfce-panel or lxpanel.

**Comment by zarkone** [comment]
You have to enable-disable modeline in this case, eval stumpvm command
`mode-line` twice.

Eric Eaton writes:

**Comment by zarkone** [comment]
You might find useful the `Mode-line` section of StumpWM manual and
`mode-line.lisp` source file.
Eric Eaton writes:

**Comment by spaceotter** [comment]
That doesn't work. re-enabling the mode-line just puts it back at the top.

**Comment by alezost** [comment]
I have the following code in [my config](https://github.com/alezost/stumpwmrc/blob/master/utils.lisp#L307-L325):
```lisp
(defun utl-mode-line-pos (pos)
  "Put the mode line at a position POS (can be :TOP or :BOTTOM)."
  (let ((screen (current-screen))
        (head (current-head)))
    (enable-mode-line screen head nil)
    (setf *mode-line-position* pos)
    (enable-mode-line screen head t)))

(defcommand utl-mode-line-on () ()
  "Turn the mode line on unconditionally."
  (enable-mode-line (current-screen) (current-head) t))

(defcommand utl-mode-line-bottom () ()
  "Put the mode line on the bottom of the screen."
  (utl-mode-line-pos :bottom))

(defcommand utl-mode-line-top () ()
  "Put the mode line on the top of the screen."
  (utl-mode-line-pos :top))
```

So I can call `utl-mode-line-top`/`utl-mode-line-bottom` commands to
change position of the modeline.

**Comment by zarkone** [comment]
```   
Alternatively, external panel applications such as the GNOME panel
and KDE's kicker may be used. Simply starting one of these programs is
enough to set it as the mode line of the head it would like to be on
(if the panel is XRandR aware) or whichever head is available. In order
to avoid problems displaying menus, configure your panel application for
positioning at the top or bottom of the head rather than relying on
*MODE-LINE-POSITION*
```
So, in case of `lxpanel` you should configure position in it's own preferences dialog (i've just tried to install it, right-click on the panel and select "preferences"). I guess it would work with `xfce-panel` too.

**Comment by spaceotter** [comment]
So it does work if the panel is set to be at the top. However no combination of settings or @alezost's code seems to make stump put it at the bottom. I find this rather strange. I guess I'll just have to live with the panel at the top.
