### ISSUE TITLE
Enhancement: pull-from-windowlist

### ISSUE THREAD

**Issue by ralt** [stumpwm/stumpwm#216]
It makes sense to have a behavior similar to emacs' `switch-to-buffer`. Here is an implementation:

```lisp
(defcommand pull-from-windowlist () ()
  "pulls a single window from a window list"
  (pull-window
   (second (select-from-menu
            (current-screen)
            (mapcar #'(lambda (w)
                        (list (format-expand *window-formatters*
                                             *window-format*
                                             w)
                              w))
                    (group-windows (current-group)))))))
```

Not sure how to actually do this feature request, or even if it's wanted.

**Comment by dbjergaard** [comment]
we can just add this tile-window.lisp (unless its behavior makes sense for float groups, then window.lisp).  Can you please expand the doc string? Then I'll add the appropriate bits so that it can be included in the manual.

**Comment by ralt** [comment]
Since this seems to be a good idea, I just opened a PR (see #219), where I've expanded the docstring. Is it good enough? We should continue the discussion over there.
