### ISSUE TITLE
ccl build fails at stumpwm::generate-manual step

### ISSUE THREAD

**Issue by futuro** [stumpwm/stumpwm#217]
The command 
```
ccl --eval "(load \"load-stumpwm.lisp\")" --load manual.lisp --eval "(progn (stumpwm::generate-manual)(quit))"
```
Fails with the following error
```
> Error: The value #<simple-vector 2> is not of the expected type symbol.
> While executing: macro-function, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip evaluation of (progn (stumpwm::generate-manual) (quit))
> Type :? for other options.
1 > 
```
After digging around a bit, it seems this is caused by calling stumpwm::generate-command-doc (part of generate-manual) with the string "!!! act-on-matching-windows". Specifically, it's choking on the call to ccl:arglist on line 104 in manual.lisp. Expanded out a little, it looks something like this:
```lisp
(ccl:arglist (symbol-function (find-symbol (string-upcase "act-on-matching-windows") :stumpwm)))
```
I'm opening this issue so others know what's going on with the ccl build. Revision 7e2e21a is good, and master is bad. So I ran a bisect with the following script
```sh
#!/bin/sh
make clean
./autogen.sh
./configure --with-lisp=ccl
make
```
And the results are
```git
398c4b03929ed003b39ee26050c9928a475d732f is the first bad commit
commit 398c4b03929ed003b39ee26050c9928a475d732f
Author: David Bjergaard <dbjergaard@gmail.com>
Date:   Thu Jun 11 09:44:21 2015 -0400

    travis tweaks

:100644 100644 2efd7183365d3f99ca1614d5742ab86fd51e0a6b 7e4e1f4698397b7b9b6a67d2dfd9e72c3769ba72 M      .travis.yml
:100644 100644 c878c54fc81e08aba6637009d328355522ecb761 177bab26fa2e06a61e37252e5c8f98f58c94f650 M      stumpwm.texi.in
```
Digging a little deeper, it seems that line 1527 in stumpwm.texi.in, which contains the text "!!! act-on-matching-windows", is solely responsible for the build failure. I tested building without that line and it succeeded.

Here's what I think the problem is: act-on-matching-windows is a macro, but it's been marked as a command in the texi file, so ccl:arglist is being passed something like
```lisp
#(7100233775316992 #<Compiled-function STUMPWM:ACT-ON-MATCHING-WINDOWS Macroexpander #x302001871CAF>)
```
instead of something like
```lisp
#<Compiled-function STUMPWM:MOVE-WINDOWS-TO-GROUP #x30200187445F>
```

I changed line 1527 from '!!! act-on-matching-windows' to '%%% act-on-matching-windows', so generate-macro-doc is called on it instead of generate-command-doc, and the compilation succeeded. The documentation looks good, so I'm going to generate a pull request shortly.

**Comment by futuro** [comment]
I have created pr #218 to address this issue.

**Comment by dbjergaard** [comment]
I am humbled by your debugging skills :+1:
