### ISSUE TITLE
stumpwm stayes black after update to fedora 22

### ISSUE THREAD

**Issue by spiderbit** [stumpwm/stumpwm#222]
I updated form FC21 to FC22 last evening. after that it would not start properly again. it just stays black screen and does not react to any keys.

I can switch to TTYs thats the only thing that works.

I tried to start without config, I renamed the .stumpwm.d folder.

I deactivated wayland gdm.

I start it over gdm (desktop file) the last thing I thought was that it has maybe something to do that fedora dont starts X as root any more. The errors sound similar:

 Liveusb-creator displays just a blank window on Fedora 22 
 hp-plugin shows a blank gray window 

* https://fedoraproject.org/wiki/Common_F22_bugs#Upgrade_issues

I think also that it has to do with X somehow everything else stayed pretty much the same.

I recompiled the stumpwm binary, I basicly reinstalled it the compilation did go through make install as root worked.

I use the following xsession (gdm) file:

[Desktop Entry]
Name=StumpWM
Encoding=UTF-8
Comment=Launch the Stump window manager
Exec=stumpwm
TryExec=stumpwm
Type=XSession

**Comment by dbjergaard** [comment]
I have foggy recollections of running into this in Ubuntu and its GDM a while ago.  Could you try with an .xinitrc/.xsession that contains "exec /path/to/stumpwm" only?  Then, in the gdm, choose "local session" or make the equivalent change to gdm to boot Xsession (Exec=/etc/X11/Xsession)?

If the issue is that your running xwayland, then there's not much I can do to help, stumpwm is just broken.  This has to do with the fact that clx on which stumpwm is based, is independent of xlib. clx implements the X11 protocol, but I don't know how well it will work in wayland's emulation of X11.

**Comment by spiderbit** [comment]
I dont really get why I would run Xwayland, fedora did only switch to wayland for gdm in version 22, and I even deaktivated that.

When native X runs it makes no sense to use xwayland ot top of that or am I wrong here?

could it have something to do that it starts a second X screen, I think fc21 did start stumpwm or other window managers in the same X window/server? here it creates a new one.

gdm        955  0.0  0.2 236408 22984 tty1     Sl+  08:02   0:01 /usr/libexec/Xorg vt1 -displayfd 3 -auth /run/user/42/gdm/Xauthority -nolisten tcp -background none -norese
black     2837  0.1  0.5 521588 41772 tty2     Rl+  08:04   0:57 /usr/libexec/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -nolisten tcp -background none -nore

[root@jupiter notes]# ls -l /usr/local/bin/stumpwm 
-rwxr-xr-x 1 root root 68845616 16. Sep 06:38 /usr/local/bin/stumpwm

I just wonder am I really the only person that tried stumpwm in fedora 22, I cant belive that its out nearly half a year.

I will later try your suggestion still to see if it changes something.

**Comment by dbjergaard** [comment]
sorry, I was speculating.  If you know that your running pure X11 from end to end, then it should just be a matter of getting stumpwm to launch the way it expects.  In my experience, the recent versions GDM don't do this and its better if GDM launches Xsession which launches stumpwm.  Its less convoluted than it sounds.  Its how I've been launching stumpwm on ubuntu and debian for the last 3 years.

**Comment by spiderbit** [comment]
interesting yes I will try that, I also search a way to start exwm (because I am a emacs maniac, and my hacks to make stumpwm more like emacs as example I like the ido buffer menu better than the stumpwm one) over gdm, maybe that would work there too.

**Comment by spiderbit** [comment]
so thanks to your help I have a working stumpwm back but not over gdm cant get it work there.

its the .xinitrc where I had to put that exec command. and in theory it should be /etc/X11/xinit/Xsession

but over startx it works now. Is that fixed I dont know :) maybe for now?

would be nice to have the solution when u want to use gdm to have a complete fix, I dont care to much I guess but maybe we can reopen it when I/someone else finds for that a solution.

Maybe some time fedora adds stumpwm as package then this would be less problematic.

**Comment by dbjergaard** [comment]
you can still use gdm as long as you have gdm launch Xsession which in turn launches stumpwm.

**Comment by spiderbit** [comment]
I understand that in theory, but I am to dumb to do that it seems :)

Exec=stumpwm
TryExec=/etc/X11/xinit/Xsession

hmm did I change the wrong line maybe, I test that later :) and report if that fixes that too. Thx so far :)

**Comment by dbjergaard** [comment]
sorry I didn't mean to be vague, I assumed that if you had to make the stumpwm file, you had the Xsession file just as easily (for some reason my gdm has one built in so I never needed to make it by hand)

Here's what I would try in /usr/share/xsessions/:
```
[Desktop Entry]
Encoding=UTF-8
Name=Xsession
Comment=Launch a per user Xsession
Exec=/etc/X11/Xsession
TryExec=/etc/X11/Xsession
Icon=
Type=XSession
```

**Comment by spiderbit** [comment]
there is no file Xsession in /etc/X11, but there is one in the xinit subfolder, so I guessed that would it be, I assigned it also to Exec but still no success.

**Comment by dbjergaard** [comment]
strange on my system I have:
> $ file /etc/X11/Xsession
> /etc/X11/Xsession: POSIX shell script, ASCII text executable

**Comment by spiderbit** [comment]
I use fedora 22
