### ISSUE TITLE
Does StumpWM support key sequence?

### ISSUE THREAD

**Issue by qizhihere** [stumpwm/stumpwm#223]
hi, i would like to use key sequence just like in emacs: `(kbd "s-z c c")`, but then it reports that it cannot parse key. Is this feature currently not available? Or i didn't get the right method to achieve this?

**Comment by jorams** [comment]
StumpWM binds a single key combination in a `keymap`. That key combination can then be bound to either a command or another keymap (or a symbol bound to a keymap). You could achieve what you want roughly like this (not tested):

```lisp
(let ((keymap1 (make-sparse-keymap))
      (keymap2 (make-sparse-keymap)))
  (define-key *top-map* (kbd "s-z") keymap1)
  (define-key keymap1 (kbd "c") keymap2)
  (define-key keymap2 (kbd "c") "some-command"))
```

**Comment by qizhihere** [comment]
yes, i see. thanks for your help :)
