### ISSUE TITLE
keep floating window on top

### ISSUE THREAD

**Issue by qizhihere** [stumpwm/stumpwm#224]
How can i keep floating window on top?

**Comment by dbjergaard** [comment]
on top of what? in the tiled group you cannot.  In a float group, I'm not sure. I don't use it very much and when I have it has proven more trouble than its worth.

**Comment by qizhihere** [comment]
eh...maybe you're right. I personally use it rarely, but sometimes the always-on-top feature is required, such as drag and drop?

**Comment by dbjergaard** [comment]
Ah, I think I see: you want to be able to re-focus floating windows?

**Comment by qizhihere** [comment]
Yes, i want a floating window which always keeps on top of other windows and won't lose its focus.

**Comment by noctuid** [comment]
@dbjergaard I don't know how high of a priority you consider "float splits" and floating dialogs to be, but I think they can be very useful. I don't often use floating groups, but I like having floating dropdowns (terminals or a scratchpad for some other program) appear above tiled windows.

**Comment by dbjergaard** [comment]
Its more on the list for StumpWM 2.0.  StumpWM's features are frozen in 0.9.9
and onwards. But this is a feature that I want to have for sure.
