### ISSUE TITLE
Two, or many full-screen frames in one group

### ISSUE THREAD

**Issue by zarkone** [stumpwm/stumpwm#229]
Hi! 

Didn't find in docs, is it possible to create many full-screen frames in one group? For example, one would contain full-screen application and second will be split in two frames, vertically. 

Thanks!

**Comment by dbjergaard** [comment]
If I understand what you're saying, you want something akin to nested groups? To be more specific, you want to cycle through multiple frames in a group, some of which are full screen and some of which have been split and contain sub-frames.  If thats the case, no it doesn't exist in stumpwm.

**Comment by zarkone** [comment]
Yes, exactly. Try to use groups more efficient, if so. Thanks!
David Bjergaard writes:

**Comment by dbjergaard** [comment]
Sorry, that feature doesn't exist.  Is there a reason that you can't just use multiple groups and cycle through them? Also, you might want to check out https://github.com/stumpwm/stumpwm-contrib/tree/master/util/windowtags, and email/talk to @38a938c2 who has some interesting ideas about managing windows.

**Comment by zarkone** [comment]
Oh, thanks, will defenetly follow your advice!
David Bjergaard writes:

**Comment by 38a938c2** [comment]
For the record:

1) I still use StumpWM as my main WM now

2) I do use window tagging and frame tagging

3) http://mtn-host.prjek.net/viewmtn/stumpwm-tagging/ (you can get 
a tarball from there, if you don't have monotone DVCS installed)
