### ISSUE TITLE
Gimp confuses input devices

### ISSUE THREAD

**Issue by brianqq** [stumpwm/stumpwm#232]
# Versions

CPU: x86_64
Linux: Arch Linux
          Kernel version 4.2.2-1
XOrg server: version 1.17.2-4
xsetwacom: version 0.31.0

Lisp: SBCL 1.2.12 (installed with arch linux)
StumpWM: built from git source today
Gimp: GNU Image Manipulation Program version 2.8.14 (installed from archlinux)
I'm using two monitors. I haven't yet tested this with only one monitor.
# Bug

The gimp periodically stops receiving input from the wacom tablet. This happens frequently enough to render the gimp useless. Switching to xfce4 fixes the problem.
# Steps to reproduce

Connect wacom tablet.
Run stumpwm.
Open the GIMP
Create a new file.
Open the device status window
Pick the pencil tool
Draw a few disconnected squiggles (pick up the stylus and put it back down)
When it freezes, take the stylus away from the tablet
Wait a few seconds. After some lag, the gimp will change its mind about the current input device. This will be shown in the device status window.

**Comment by brianqq** [comment]
I just tested this on ccl64. The same error occurs.

**Comment by dbjergaard** [comment]
I can confirm this, I saw it yesterday

**Comment by brianqq** [comment]
When I get home, I'm happy to try debugging this. But I'm not familiar with the code base. Any advice would be appreciated!

**Comment by brianqq** [comment]
When I get home, I'm happy to try debugging this. But I'm not familiar with the code base. Any advice would be appreciated!

**Comment by dbjergaard** [comment]
To clarify: I saw similar behavior just using a mouse, and it seems to happen if you say use the brush and draw a while holding down the left mouse button.  

What I think is happening (and if it is true there isn't much we can do) is that the tablet is generating a lot of events that stumpwm can't keep up with and so it apparently freezes while the events get processes in order.  I'm not sure the best way to debug this is.  The first most passive way is to set up the debug log and set debugging to 10.

**Comment by brianqq** [comment]
This also happens in Krita, so this seems like a problem on the StumpWM end. I will check the documentation for setting up the debug log.

**Comment by dbjergaard** [comment]
If someone has the know-how a good first step to debugging this is to see how the input events are being handled. Specifically this may be a manifestation of StumpWM's lack of xinput support.

**Comment by dbjergaard** [comment]
Can you confirm if the latest merge with the new mode-line update code fixes this issue? I expect we slayed a few of these weird performance bugs.
