### ISSUE TITLE
Stumpwm lags when playing full screen video

### ISSUE THREAD

**Issue by therabidmachine** [stumpwm/stumpwm#236]
When using Chrome in Stumpwm I have an issue with playing videos in fullscreen mode. After a few seconds the audio will begin to stutter and the video will freeze. This affects many sites and playing videos non fullscreened is fine. I haven't noticed this problem in any other WMs/DEs.

**Comment by dbjergaard** [comment]
Hmm, not sure how to proceed,  use videos in full screen from various apps and haven't seen this issue.  Can you tell me which OS + stumpwm version you're using and verify that it is in stumpwm by moving your stumpwmrc  out of the way and making sure that .xinitrc just contains "exec /path/to/stumpwm"

**Comment by dbjergaard** [comment]
Can you give more information about your system? How is stumpwm set up? Video card info? OS?

**Comment by dbjergaard** [comment]
I will re-open this if you can provide more info on what is going on.
