### ISSUE TITLE
Move windows when a monitor is unplugged

### ISSUE THREAD

**Issue by ralt** [stumpwm/stumpwm#237]
How to reproduce:

- Plug in another monitor, configure it with xrandr, put some windows on it.
- Unplug the monitor, disable it with xrandr, and your windows are lost with no way (that I've found) to restore them.

Somehow, if stumpwm finds out that some windows are on a non-existent screen, it should move them to the next screen?

I'm not sure of the technical feasibility there. Maybe managing the monitor layouts is necessary to do that. (I've started [something](https://github.com/ralt/remon/) to manage layouts with xrandr, maybe some code could be stolen.)

**Comment by jorams** [comment]
To deal with this, I generally use a command called `pull-window-from-list`, but I apparently have that defined in my [`stumpwmrc`](https://github.com/jorams/dotfiles/blob/03c4d0f01699e8ca4bf3cf9495f29f866b1c66b0/stumpwmrc/util.lisp#L59).

The `pull-hidden-*` commands can also help.

A more general solution could be nice though.

**Comment by dbjergaard** [comment]
This is weird, because I unplug monitors with xrandr all the time and I never
lose my windows... here's my commands:
```lisp
(defcommand unplug-monitors () ()
	    "Removes monitors and re-activates the laptop screen"
	    (run-shell-command "xrandr --output HDMI1 --mode 1920x1080 --pos 0x0 --rotate normal --output LVDS1 --off --output DP1 --off --output VGA1 --off")
	    (refresh-heads)
	    (run-shell-command "xrandr --output HDMI1 --off --output LVDS1 --mode 1366x768 --pos 0x0 --rotate normal --output DP1 --off --output VGA1 --off")
	    (refresh-heads)
	    (set-wallpaper *wallpaper*)
	    (refresh-heads))

(defcommand setup-phy () ()
  "Setup display and keyboard for my office at work"
  (run-shell-command "xrandr --output HDMI1 --mode 1920x1080 --pos 0x0 --rotate normal --output LVDS1 --off --output DP1 --off --output VGA1 --off")
  (refresh-heads)
  (run-shell-command "xrandr --output HDMI1 --mode 1920x1080 --pos 1920x0 --rotate normal --output LVDS1 --off --output DP1 --off --output VGA1 --mode 1920x1200 --pos 0x0 --rotate normal")
  (refresh-heads)
  (refresh-heads)
  (run-shell-command "xset b off")
  (run-shell-command "xmodmap ~/.xmodmap")
  (set-wallpaper *wallpaper*))
```

Can you clarify what you mean by "lost"?

**Comment by NicolasPetton** [comment]
@dbjergaard out of curiosity, why do you run `(refresh-heads)` twice?

**Comment by dbjergaard** [comment]
I'm not sure... I still end up needing to run refresh-heads every once and a while.  I think an appropriate solution would be to sleep for a second and then run refresh-heads. All that function does is scan for available screens and set them up for stumpwm to use.  Calling it multiple times just forces the scan to happen again.  If it takes time for the xrandr command to finish, the first refresh-heads command won't pick up the new monitors.

**Comment by dbjergaard** [comment]
@jorams would it be possible to adapt your solution as an interactive command "pull-all-to-screen" or something? That way if users are affected by lost windows they have some recourse.

Also, @ralt does refresh-heads move the windows? I've noticed that if I unplug monitors (even with xrandr) stumpwm won't remap the windows until I run refresh-heads.

**Comment by jorams** [comment]
@dbjergaard That command basically just calls `stumpwm::pull-window`, so it just pulls things into the current frame. What exactly do you propose `pull-all-to-screen` to do?

**Comment by dbjergaard** [comment]
Something like:
(mapcar 'pull-window (screen-windows (current-screen)))

If that makes sense.

**Comment by ralt** [comment]
`refresh-heads` does the trick. Shouldn't it be called in stumpwm's internal loop? I'm not sure how much overhead this adds, and if it can be optimized (e.g. only run when the state is inconsistent).

**Comment by dbjergaard** [comment]
I'll look into it, for now, I'm closing this one.

**Comment by jorams** [comment]
@dbjergaard Sure, that would work as a last resort. Should probably be called `pull-all-to-frame` though.

**Comment by dbjergaard** [comment]
I think we can leave it since refresh-heads remaps the windows already.  It would be better if we could detect when refresh-heads needs to be called from the internal loop and then everything would work as expected.

**Comment by jorams** [comment]
We currently use `xdpyinfo` to find out what heads exist, and we don't want to run that in any sort of loop. Sadly I *think* detecting such changes automatically requires support for RandR, which isn't (yet) supported by CLX. There's a [PR](sharplispers/clx#15) for it, but merging it caused some trouble.

Perhaps in the near future we can detect if there's RandR support and do something nicer if there is. Or maybe there's another way to detect screen changes, not requiring RandR.
