### ISSUE TITLE
Stumpwm fails on startup

### ISSUE THREAD

**Issue by ghferrari** [stumpwm/stumpwm#239]
Hi, stumpwm fails for me on the latest debian jessie with sbcl. The output of journalctl -b -r reports the following lines:
Dec 27 13:13:14 lindy /usr/lib/gdm3/gdm-x-session[1468]: Argument X is not a NUMBER: NIL
Dec 27 13:13:14 lindy /usr/lib/gdm3/gdm-x-session[1468]: #<THREAD "main thread" RUNNING {100505C453}>:
Dec 27 13:13:14 lindy /usr/lib/gdm3/gdm-x-session[1468]: debugger invoked on a SIMPLE-TYPE-ERROR in thread

Can anyone help me diagnose the problem? Some system info is given below:
sbcl --version  = SBCL 1.3.0.debian
quicklisp version = 2015-09-24
systemd --version = systemd 228

Thanks,

Geoff

**Comment by dbjergaard** [comment]
You're pulling from a different log source, can you get the lisp backtrace? When does this happen? Can you do 'copy-unhandled-error' from the eval prompt?

**Comment by ghferrari** [comment]
Hi David,

Thanks for getting back to me. Basically stumpwm fails for me on login i.e. I type in my username and password to login, and then I simply get an empty X window with no stumpwm showing. That's why included the output of the systemd log.

Once the Xwindow login has stalled, I can do a text login on another tty, but I don't what what more I can do from there to give you the information you ask for. Any suggestions?

**Comment by dbjergaard** [comment]
Hi,

Once you're in the tty, check that stump is still running (ps aux | grep
stumpwm) then you can try to connect via slime/emacs:

> emacs -nw
> M-x slime-connect

If you have this in your .stumpwmrc:
> (require 'swank)
> (swank:create-server)

From there, you want to look at/dump the variable stumpwm:*last-unhandled-error*
check user.lisp:336 for an example of how that is used in context.

Hope this helps.

    David

**Comment by ghferrari** [comment]
Hi David,

I wasn't able to follow your instructions directly - I suspect that stumpwm hits the debugger before it processes my .stumpwmrc, so that I'm unable to access the process through emacs+slime.

I played around with the build process to start swank earlier and then managed to come up with the following backtrace. Is this helpful information??

Kind regards,

Geoff

Argument X is not a NUMBER: NIL
   [Condition of type SIMPLE-TYPE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1006670033}>)

Backtrace:
  0: (SB-KERNEL:TWO-ARG-= NIL 0)
  1: (SB-VM::GENERIC-=)
  2: (XLIB::GET-BEST-AUTHORIZATION "" 0 :LOCAL)
  3: (XLIB:OPEN-DISPLAY "" :DISPLAY 0 :PROTOCOL :LOCAL :AUTHORIZATION-NAME NIL :AUTHORIZATION-DATA NIL)
  4: (STUMPWM-INTERNAL ":0")
  5: (STUMPWM ":0")
  6: (SB-INT:SIMPLE-EVAL-IN-LEXENV (STUMPWM) #<NULL-LEXENV>)
  7: (EVAL (STUMPWM))
  8: (SWANK::EVAL-REGION "(stumpwm:stumpwm) ..)
  9: ((LAMBDA NIL :IN SWANK-REPL::REPL-EVAL))
 10: (SWANK-REPL::TRACK-PACKAGE #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {10078A4EFB}>)
 11: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {10078A4E5B}>)
 12: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {10078A4E3B}>)
 13: (SWANK-REPL::REPL-EVAL "(stumpwm:stumpwm) ..)
 14: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK-REPL:LISTENER-EVAL "(stumpwm:stumpwm) ..)
 15: (EVAL (SWANK-REPL:LISTENER-EVAL "(stumpwm:stumpwm) ..)
 16: (SWANK:EVAL-FOR-EMACS (SWANK-REPL:LISTENER-EVAL "(stumpwm:stumpwm) ..)
 17: (SWANK::PROCESS-REQUESTS NIL)
 18: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
 19: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
 20: (SWANK/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {100667800B}>)
 21: ((FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/data/quicklisp/dists/quicklisp/software/slime-2.14/swank/sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-RE..
 22: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-OUTPUT* . #1=#<SWANK/GRAY::SLIME-OUTPUT-STREAM {1006657A43}>) (*STANDARD-INPUT* . #2=#<SWANK/GRAY::SLIME-INPUT-STREAM {1006566F73}>) (*TRACE-OUTPUT* . #1#) (*ERR..
 23: (SWANK::HANDLE-REQUESTS #<SWANK::MULTITHREADED-CONNECTION {1005A6CEF3}> NIL)
 24: ((FLET #:WITHOUT-INTERRUPTS-BODY-1016 :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 25: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 26: ((FLET #:WITHOUT-INTERRUPTS-BODY-335 :IN SB-THREAD::CALL-WITH-MUTEX))
 27: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFF0A96D5B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
 28: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "repl-thread" RUNNING {1006670033}> NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::SPAWN-REPL-THREAD) {100666FF9B}> (#<SB-THREAD:THREAD "re..
 29: ("foreign function: call_into_lisp")
 30: ("foreign function: new_thread_trampoline")

**Comment by jorams** [comment]
A very quick look at the source of `XLIB::GET-BEST-AUTHORIZATION` suggests there's a problem with your `~/.Xauthority`.

**Comment by ghferrari** [comment]
Thanks, jorams. I don't have a ~/.Xauthority file - with the latest version of debian, it's kept instead at /var/run/<uid>/gdm/Xauthority.

I've tried symlinking this file to ~/.Xauthority but that doesn't solve the problem. Any other suggestions?

**Comment by jorams** [comment]
It tries reading either the file named in the environment variable `XAUTHORITY` or, if the environment variable doesn't exist, `~/.Xauthority`. It is very much possible that the error is instead in `/var/run/uid/gdm/Xauthority`. The data in that file does not correspond to the format read by CLX, in that the third field is empty.

The main suggestion I see everywhere regarding a corrupt Xauthority is to just delete it, causing it to be regenerated the next time you log in.

**Comment by ghferrari** [comment]
Thanks for the hint jorams.

I tried deleting my /var/run/users/uid/gdm/Xauthority file so that it would be recreated, but it didn't solve the problem.

As you said, XLIB (through READ-XAUTH-ENTRY) is parsing my XAuthority file and returning the third field (number) as nil. This causes an error when XLIB::GET-BEST-AUTHORISATION tests the result with
(= number display).

I don't know what to do at this stage because I don't know whether it my Xauthority file that's corrupt of whether there's a but with XLIB. But as a temporary fix, I've replaced the test above with (= (or number 0) display) and now stumpwm starts properly.

If you have any further suggestions on where and how to report a bug, please let me know. Thanks, Geoff

**Comment by jorams** [comment]
I *think* this is something that could need a fix in [CLX](https://github.com/sharplispers/clx), but I'm not sure what the correct approach would be. 

What libXau does is pretty different from what CLX does. I'd probably go with `(or (null number) (= number display))`, but perhaps that function should be changed entirely to match [what libXau does] (http://cgit.freedesktop.org/xorg/lib/libXau/tree/AuGetBest.c).

**Comment by dbjergaard** [comment]
@jorams can we hot-wire this into stumpwm? I'm opening an issue on clx. If there's nothing we can do, then lets close this one and hopefully clx can do something to address the issue.

**Comment by dbjergaard** [comment]
@ghferrari can you roll back your sbcl version? I'm running 1.2.4.debian in Jessie and I don't have this issue.

**Comment by jorams** [comment]
@dbjergaard We could probably just overwrite the function with the fixed version, in `workarounds.lisp`.

Also, this has nothing to do with SBCL versions. It's whatever creates the `Xauthority` file that's exhibiting different behaviour, and it's CLX that can't handle the new behaviour.

**Comment by ghferrari** [comment]
Hi David,

Thanks for raising the bug on CLX. In the meantime, my hacked workaround
above is working fine for me.

Thanks again,

Geoff

**Comment by dbjergaard** [comment]
Hi Geoff,

Could you post the workaround and I'll add it to workarounds.lisp for you to
test?

    David

**Comment by ghferrari** [comment]
Hi David,

I'm using jorams' workaround above - which is the same bugfix that has been accepted into clx here https://github.com/sharplispers/clx/pull/23

Basically, it's a small change to XLIB:GET-BEST-AUTHORISATION

**Comment by dbjergaard** [comment]
If that was merged, then I see no reason to include it in workarounds.lisp. I'm closing this for now, and if we get more bug reports about it, we can refer people to this thread.
