### ISSUE TITLE
Separate input history for exec command

### ISSUE THREAD

**Issue by afrepues** [stumpwm/stumpwm#24]
Having one history for all commands diminishes the usefulness of the history quite easily, as finding the previous input can be a long process of navigating back the history (the only way, no search is possible).

**Comment by KeiferMiller** [comment]
It isn't really an ideal solution, but I have a kludge in my `.stumpwmrc` that addresses this:

```
(defvar *shell-input-history* nil
  "History for the shell input line.")

(defmacro separate-input-history (history-var &rest body)
  "Store Input Bar history for @var{body} in @var{history-var}."
  `(let ((*input-history* ,history-var))
     ,@body
     (setf ,history-var *input-history*)))

(defcommand exec-with-history () ()
      "Run the specified shell command with a discrete input history."
      ;; Steal the global input history before calling exec
      (separate-input-history *shell-input-history*
			      (run-commands "exec")))
(define-key *root-map* (kbd "d") "exec-with-history")
```

**Comment by dbjergaard** [comment]
While it may not be possible to completely disentangle the two sources, I hadn't considered just adding a separate history for the exec command.  I'll think about how this could be better integrated.  Thanks for posting!

**Comment by ralt** [comment]
@dbjergaard is this still a thing? Would you accept a patch separating the 2 histories in the way @KeiferMiller offered?

**Comment by dbjergaard** [comment]
absolutely!
