### ISSUE TITLE
Emacs doesn't display right font

### ISSUE THREAD

**Issue by JoshRagem** [stumpwm/stumpwm#247]
When I start emacs `^t^e` it does not launch with the same font settings as xterm. It also does not respect the font configuration I set with spacemacs. If I force spacemacs to change themes it switches to the correct font but not the correct font size. I know that emacs can draw the font bigger because I can manually increase the font size within a buffer. I don't have this problem running emacs/spacemacs on OS X.

More info:
Emacs 24.5.1
Spacemacs 0.105.16
Ubuntu 15.10
Stumpwm built from master this morning

**Comment by jorams** [comment]
I don't think this has anything to do with StumpWM. `C-t C-e` just runs `emacs` as if you had typed that into a terminal.
