### ISSUE TITLE
xft fonts not rendered correctly in some contexts

### ISSUE THREAD

**Issue by NicolasPetton** [stumpwm/stumpwm#250]
Using the `ttf-fonts` contrib package, some fonts are not rendered correctly (for instance using `windowlist`), a green-ish border is displayed around text:

![2](https://cloud.githubusercontent.com/assets/123539/14998521/92bf969e-1184-11e6-94b7-0cc39d75570c.png)

Which is weird as in modeline all fonts are rendered correctly as shown below.

![1](https://cloud.githubusercontent.com/assets/123539/14998557/c46f6836-1184-11e6-9d3d-5a7b898a0fcf.png)

This happens with all the fonts I tried (Fira Mono, DejaVu Sans Mono, Liberation Mono) using `xft:font`.

**Comment by dbjergaard** [comment]
Hi Nicolas, unfortunately this is a contrib module and the author has moved on.  This has been reported  before in stumpwm-contrib/#21.  I have reopened it since I have some experience with font-rendering now and I may be able to do something about it.  This is a very low priority issue at the moment though.

**Comment by NicolasPetton** [comment]
David Bjergaard <notifications@github.com> writes:

> Hi Nicolas, unfortunately this is a contrib module and the author has
> moved on.  This has been reported  before in stumpwm-contrib/#21.  I
> have reopened it since I have some experience with font-rendering now
> and I may be able to do something about it.  This is a very low
> priority issue at the moment though.

If you can give me pointers, I will see if I can find a fix for it.

**Comment by dbjergaard** [comment]
Hi check master.  Someone addressed this with a PR today.

**Comment by NicolasPetton** [comment]
awesome, thanks!
