### ISSUE TITLE
mode-lines are updated on each mousewheel event

### ISSUE THREAD

**Issue by NicolasPetton** [stumpwm/stumpwm#252]
When scrolling with the mouse wheel, all mode-lines are updated (many, many times, since many events are triggered when scrolling).

This makes scrolling really slow with some applications like chromium, and consumes a lot of cpu, depending on how many elements are drawn in the mode-line.

It looks like an event `:BUTTON-PRESS` is triggered on mouse wheel, which results in calling `UPDATE-ALL-MODE-LINES` for each one of them.

**Comment by dbjergaard** [comment]
I'll look into this.  I can see that this would be very frustrating.  The modeline should definitely not refresh itself when the mouse wheel triggers the event.  Unfortunately :BUTTON-PRESS is a generic event for any button, so it can make sense to have the modeline update itself when it gets one of these events in case you destroy a window or trigger some other change to the modeline.

Without delving too deep into the code, I assume this choice was made to make the modeline responsive to user changes without having complex code paths signaling when the modeline should re-draw.

**Comment by NicolasPetton** [comment]
@dbjergaard any news about this issue?  Can I help in some way?

**Comment by dbjergaard** [comment]
Sorry, no news. I took a brief look at the `:button-press` event handler and it looks like it doesn't directly call update-all-mode-lines.  That event handler should only fire when you mouse over the mode-line.  Can you let me know how you determined which event is triggered by the mousewheel?

**Comment by NicolasPetton** [comment]
> Sorry, no news.

Can you reproduce the issue?

**Comment by dbjergaard** [comment]
No I can't I opened google-chrome and scrolled a long webpage but stumpwm didn't become unresponsive.  Can you give me a breakdown of:
- how you start stumpwm/post your stumpwmrc
- you computer specs
- a bullet proof procedure for reproducing

**Comment by jorams** [comment]
I did some quick testing. The `group-button-press` method for tiling groups calls `update-all-mode-lines`. Because of that you can trigger a ton of updates by scrolling in an empty frame. I can't, however, get it to trigger when scrolling in a window.

**Comment by NicolasPetton** [comment]
Joram Schrijver <notifications@github.com> writes:

> I did some quick testing. The `group-button-press` method for tiling
> groups calls `update-all-mode-lines`. Because of that you can trigger
> a ton of updates by scrolling in an empty frame. I can't, however, get
> it to trigger when scrolling in a window.

I was using NixOS back when I reported this issue, and I'm now using
Fedora, but I will try to reproduce it and give you a recipe.

**Comment by scottjad** [comment]
This bug will only manifest if *mouse-focus-policy* is :click.

**Comment by dbjergaard** [comment]
I can confirm this bug. We'll have to handle the click focus policy better.

**Comment by dbjergaard** [comment]
Hi, I just pushed a commit to address this.  My limited testing shows there's a difference but the mice I have on hand don't send enough events fast enough to cause a visible lag.  This is the less aggressive approach than not updating the mode-line at all if the focus policy is set to click.  I think it was being updated twice previously.

**Comment by scottjad** [comment]
@dbjergaard That fix has this issue: Clicking a window (to focus it) will no longer update the mode-line (if mouse-focus-policy is click), and so if someone has something in their mode-line like a window list with an indicator of the current window, it will show incorrect information.

**Comment by dbjergaard** [comment]
Are you sure? I'm running the fix, and when I click (with mouse-focus-plolicy :click) it updates the window list properly.  I'm pretty sure the mode-line is only updated once and it was updated twice before the fix.

**Comment by scottjad** [comment]
@dbjergaard Ignore my comment, I forgot to restart stumpwm.

**Comment by NicolasPetton** [comment]
@dbjergaard It only partially fixes the issue, on Firefox when the mode-line is on, scrolling still lags.

Since scrolling is not an actual click event, could we just not update the mode-line when scrolling at all?

**Comment by dbjergaard** [comment]
I'm not sure how to key on the event since the mouse wheel event is a button-press event (as is left and right clicking)

**Comment by jethrokuan** [comment]
I can confirm this issue, for some reason *mouse-focus-policy* defaulted to `:click` for me, setting it to `:ignore` (my preference) removes the lag caused by mouse scrolling. Also on NixOS.

**Comment by PuercoPop** [comment]
One alternative would be to move the drawing of the mode-line to be timer-based and for `update-modelines` to enqueue a redraw-modeline operation (say in 300ms) if one is not already queued. This way calling update-modelines multipletimes in a short period of time would not result in multiple draw operations. This is the approach taken by the taskbar found in Unity.

Another alternative would be to always redraw the mode-line every 2/300ms. This would result in unnecessary work but would simplify the mode-line API a lot, we wouldn't need to note that a change has occurred in the mode-line such as `group-button-press`.

We could avoid unnecessary redraws in the latter approach if we kept a dirty flag for the mode-line slots. This can be done in a way that is transparent to the users of the mode-line if we use a class instead of a structure of the mode-line and hooking to `(setf slot-value-using-class) :after`.

@dbjergaard What do you think about this approach?

**Comment by TeMPOraL** [comment]
This is a workaround, but it might also be worth it to put more focus in examples/documentation on using timers in configuration to avoid heavy computations on modeline redraws. I referenced this on #382, it basically solved my performance problems.

[Here's part of my .stumpwmrc](https://gist.github.com/TeMPOraL/6290b5be47cb6f37bb1b18c6fd0f6b61) that refreshes Dropbox status asynchronously via timers, and status of org-mode clock via fsnotify (I have hooks in Emacs that populate this file, thus forming a crude IPC between the two).

**Comment by TeMPOraL** [comment]
@piotrklibert please do, I for one would be very interested in this.

**Comment by dbjergaard** [comment]
@piotrklibert You have correctly identified the weak point of the gui elements in StumpWM.  Unfortunately, there are no good gui toolkits for common lisp. 

From a stump internals perspective, the mode line is just an x-window that we blast strings to, and all the logic goes into parsing and generating the string to display from the user's format specifiers.

I would love to see a modeline that is interactive and clickable and lispy.  I don't know how it would be done though.  The most true-to-lisp route would be to figure out how to do something with McClim.  I would start it as a module and aim for a system tray. 

One of the things the community likes about stumpwm is its lack of dependencies.  I'm not opposed to adding more now that quicklisp is easy to use, but with modules, your free do do whatever you want!

**Comment by sdilts** [comment]
It is possible to get the button that was pressed (i.e. left button, right button, etc) using the `code` variable passed to the event handler for `:button press`. I found some useful information at  an archive.org snapshot of [commonlisp.net](https://web.archive.org/web/20050426204313/http://common-lisp.net/project/cmucl/doc/clx/12_12_1_Keyboard_and_Pointer_Events.html#:button-press), and at [Xah Lee's website](http://xahlee.info/linux/linux_x11_mouse_button_number.html). I'm working on a simple fix to not update the modeline when scroll events are received.

**Comment by sdilts** [comment]
You can check the button type using the `code` variable passed into the `:button-press` event. Here is some relevant documentation from an archive.org snapshot of [commonlisp.net](https://web.archive.org/web/20050426204313/http://common-lisp.net/project/cmucl/doc/clx/12_12_1_Keyboard_and_Pointer_Events.html#:button-press) and [Xah Lee's website](http://xahlee.info/linux/linux_x11_mouse_button_number.html). I'm working on a pull request now to ignore modeline updates from events generated by the mouse wheel.

**Comment by ralt** [comment]
For the people in this thread: there has been a bunch of improvements/fixes recently merged in master that should fix the issues mentioned here.
