### ISSUE TITLE
Handle Alt+Shift keys release

### ISSUE THREAD

**Issue by kostafey** [stumpwm/stumpwm#254]
Is there any way to handle Alt+Shift (only) release keys from stumpwm?

Prehistory.

I'm using xxkb. In Ubuntu it works on Alt+Shift keys **release**. In Arch I can't find any way to do that, it always works on keys **press**. Configs are the same, xxkb versions are the same, the difference in magic :). So, I've started to search different solutions.

**Comment by jorams** [comment]
This might be because of a difference in X versions.

But no, not currently. StumpWM usually ignores keypresses of only modifiers.

**Comment by kostafey** [comment]
> because of a difference in X versions.

Thank you for this idea. In Arch you have to use last program versions. Ok, it seems, I should dig into other direction ).
