### ISSUE TITLE
Invisible letters in TrueType fonts

### ISSUE THREAD

**Issue by kostafey** [stumpwm/stumpwm#256]
I can't see any letters in TrueType fonts at all (they looks like whitespaces instead of letters).
System: Archlinux with infinality. Consolas font is present. Stumpwm from git.

Run in console:

```lisp
> sbcl

* (ql:quickload :clx-truetype)
* (xft:cache-fonts)
```

Part of `~/.stumpwmrc`:
```lisp
(load-module "ttf-fonts")
(set-font (make-instance 'xft:font :family "Consolas" :subfamily "Regular" :size 12))
```

There is no any errors, just invisible letters. How can I debug it?

**Comment by dbjergaard** [comment]
Hi,
there could be a few possible issues, If its a problem with ttf-fonts, then this will get bumped up to clx-truetype.  Since this is lisp, clx-truetype is a native font library, it renders the fonts itself.  That means (afaik) that infinality hints will be ignored since clx-truetype is parsing the ttf fonts and extracting the glyphs itself.

I need a screenshot, or a website to visit that will show the issue in the title.  I justed loaded up the ttf-fonts package to see if I could see the issue, and I can't. 

My educated guess is that stumpwm is stripping out the non-ascii characters and rendering them as empty boxes rather than passing them to the ttf-font to be rendered properly.  A screenshot would be very helpful.

**Comment by dbjergaard** [comment]
Can you confirm if the issue looks like this:
![selection_014](https://cloud.githubusercontent.com/assets/171410/15359554/d60e4f68-1cd7-11e6-950d-80b2322ec336.png)

**Comment by kostafey** [comment]
> Can you confirm if the issue looks like this

No, I see completely clean modeline, empty background without any other marks at all. Tha same story with windowlist. Clean empty items in the list.

I'll be at my computer some hours later, but in your screenshot it wll looks like this:
![empty](https://cloud.githubusercontent.com/assets/1282079/15362830/42db2a16-1d1f-11e6-841a-19f8c481c7c8.png)

**Comment by dbjergaard** [comment]
can you try:
`(ql:update-all-dists)
`
then:
`rm -rf .cache/common-lisp/*
`
(this step aggressively cleans out all common lisp assembly objects so that when you rebuild stumpwm, you rebuild everything directly from its source, if you have other common lisp projects they will have to be recompiled the next time you load them)

and finally in stumpwm's main dir:
```
git pull
make clean; make; make install
```
You may also have to:
```
(ql:quickload :clx-truetype)
(xft:cache-fonts)
```
Finally, make sure that there isn't anything overriding `*window-format*` or `*screen-mode-line-format*` variables in your .stumpwmrc.

**Comment by dbjergaard** [comment]
Also: when I did `(ql:quickload :clx-truetype)` it didn't complete with an error about the package being locked.  I chose the restart that unlocked the package and everything completed and I was able to properly load the ttf-fonts on my system

**Comment by kostafey** [comment]
@dbjergaard, I've done this reinstallation&recaching steps twice with the same result.
Command `(ql:quickload :clx-truetype)` completes well for me.

But I think, there is some other problem in my case. Invisible letters is only for Consolas font. When I attempt to use another font, there is an error that font isn't found.

In `.stumpwmrc` - error can't find font.
```lisp
(set-font (make-instance 'xft:font :family "FiraMono" :subfamily "Regular" :size 12))
```

But it's ok for `.emacs`:
```lisp
(set-face-font 'default "FiraMono-12.0:antialias=subpixel")
```

and ok for `rxvt-unicote` in `.Xresources`:
```
URxvt*font: xft:FiraMono:size=12:antialias=true:hinting=true
```

Is there some specific way to search xft fonts in stumpwm?

**Comment by dbjergaard** [comment]
You should be able to do something like this from a REPL:
```lisp
(ql:quickload :clx-truetype)
(clx-truetype:get-font-families) ;; lists all the fonts in the cache
(clx-truetype:get-font-subfamilies "Family Name") ;; list valid subfamilies for a given family
```
If you want to print out the valid families and subfamilies for the available fonts:
```lisp
(mapc (lambda (x) (format t "Family: ~a  Subfamilies: ~{~a, ~}~%" x (clx-truetype:get-font-subfamilies x)) ) (clx-truetype:get-font-families))
```
Remember: clx-truetype only works with ttf fonts,  otf or FreeType fonts won't show up or work.

**Comment by kostafey** [comment]
> (clx-truetype:get-font-families)

ok, it's my mistake, there is no "FiraMono" font, only "Fira Mono", thank you. But subfamily are ok.

So, I have some attempts with different known (installed) fonts with the same result. Only invisible letters, without any errors.

Only bitmap fonts are visible like `(set-font "-*-terminus-*-*-*-*-18-*-*-*-*-*-iso10646-*")`.

There is ttf files for Consolas and both ttf + otf files for Fira Mono in my `~/.local/share/fonts/`.

**Comment by dbjergaard** [comment]
I forget the documentation, but you have to make sure the clx-truetype scans
~/.local/share/fonts.  If Consolas isn't returned by
clx-truetype:get-font-families its not in the database.  I have run ttf-fonts
with consolas as a test, and I don't have any problems.

**Comment by kostafey** [comment]
Consolas **is** in the list returned by `(clx-truetype:get-font-families)` in my case. I've attempted to set fonts directly **from** this list. Anytime I get the same result - invisible letters.

**Comment by kostafey** [comment]
> clx-truetype scans ~/.local/share/fonts

Furthermore I have `~/.fonts` folder with the same content as `~/.local/share/fonts`.

**Comment by dbjergaard** [comment]
can you send your ttf copy of consolas. For the md5sum of mine are:
```
d7226c559e7d0ffeacb300984c2d9be8  .fonts/CONSOLAB.TTF
44799a64a98468667480348bcab0de9a  .fonts/CONSOLAI.TTF
dd67cc82c437fd23ab38a8efead69e47  .fonts/CONSOLA.TTF
2e0e3d14b8348938e002be83bff12228  .fonts/CONSOLAZ.TTF
```

**Comment by kostafey** [comment]
It looks like the same.
```
d7226c559e7d0ffeacb300984c2d9be8  /home/kostafey/.fonts/CONSOLAB.TTF
44799a64a98468667480348bcab0de9a  /home/kostafey/.fonts/CONSOLAI.TTF
dd67cc82c437fd23ab38a8efead69e47  /home/kostafey/.fonts/CONSOLA.TTF
2e0e3d14b8348938e002be83bff12228  /home/kostafey/.fonts/CONSOLAZ.TTF
```
Here is a copy.
[consolas.zip](https://github.com/stumpwm/stumpwm/files/285392/consolas.zip)

**Comment by kostafey** [comment]
ok, I've done the following. Since Arch Linux prefers to keep fonts in `~/.local/share/fonts/` I've removed the `~/.fonts` folder.

Then in `~/.stumpwmrc`:
```lisp
(setq clx-truetype::*font-dirs*
      (append (list (namestring
                     (merge-pathnames ".local/share/fonts/" (user-homedir-pathname))))
              clx-truetype::*font-dirs*))

(clx-truetype:cache-fonts)

(set-font
 (make-instance 'xft:font :family "Consolas" :subfamily "Regular" :size 18))
```

Consolas font is found, e.g. the test
`(clx-truetype:get-font-subfamilies "Consolas")` returns `("Regular" "Bold" "Italic" "Bold Italic")`

But stumpwm failed with the following error: 
```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION STUMPWM::FONT-EXISTS-P (1)>
when called with arguments
  (#<'CLX-TRUETYPE:FONT :FAMILY "Consolas" :SUBFAMILY "Regular" :UNDERLINE NIL :STRIKETHROUGH NIL :OVERLINE NIL :BACKGROUND NIL :FOREGROUND NIL :OVERWRITE-GCONTEXT NIL :ANTIALIAS T>).
```

It can be tested with (failes with the same error):
```lisp
(stumpwm::font-exists-p
 (make-instance 'xft:font :family "Consolas" :subfamily "Regular" :size 18))
```

**Comment by ereslibre** [comment]
I could reproduce this using X.org's modesetting driver, while using Intel driver it works as expected (fonts are rendered normally). Using modesetting driver I get no font rendering on StumpWM itself (but normally on the rest of applications). Might suggest some kind of incompatibility on clx-truetype with the modesetting driver?

**Comment by ereslibre** [comment]
BTW, it might be interesting to check if this issue on clx-truetype (https://github.com/filonenko-mikhail/clx-truetype/issues/5) has anything to do with this problem

**Comment by ereslibre** [comment]
Hello,

I can confirm this now. I am using clx-truetype exclusively and its test case (https://github.com/filonenko-mikhail/clx-truetype/blob/master/test/hello-world.lisp). I modified it a bit:

```
(ql:quickload :clx-truetype)

(defpackage #:clx-truetype-test
  (:nicknames :xft-test)
  (:use #:cl #:xft)
  (:export show-window))

(in-package :clx-truetype-test)

(defparameter *display* nil)

(defparameter *screen* nil)
(defparameter *root* nil)

(defun show-window ()
  (let* ((*display* #-windows (xlib:open-default-display)
                    #+windows (xlib:open-display "127.0.0.1" :protocol :tcp))
         (*screen* (xlib:display-default-screen *display*))
         (*root* (xlib:screen-root *screen*))
         (black (xlib:screen-black-pixel *screen*))
         (white (xlib:screen-white-pixel *screen*))
         (window
           (xlib:create-window :parent *root* :x 0 :y 0 :width 640 :height 480
                          :class :input-output
                          :background white
                          :event-mask '(:key-press :key-release :exposure :button-press
                                        :structure-notify)))
         (grackon (xlib:create-gcontext
                   :drawable window
		   :foreground black
		   :background white))
         (font (make-instance 'font :family "Atari ST 8x16 System Font" :subfamily "Medium"
                              :size 36 :antialias t)))
    (unwind-protect
         (progn
           (xlib:map-window window)
           (setf (xlib:gcontext-foreground grackon) black)
           (xlib:event-case (*display* :force-output-p t
                                  :discard-p t)
             (:exposure ()
                        (xlib:clear-area window :width (xlib:drawable-width window)
                                         :height (xlib:drawable-height window))
                        (draw-text window grackon font "The quick brown fox jumps over the lazy dog." 100 100 :draw-background-p t)
                        (when (= 0 (random 2))
                          (rotatef (xlib:gcontext-foreground grackon) (xlib:gcontext-background grackon)))
                        (draw-text-line window grackon font "Hello, world." 100 (+ 100 (baseline-to-baseline window font)) :draw-background-p t)
                        (setf (font-antialias font) (= 0 (random 2)))
                        (if (= 0 (random 2))
                            (setf (font-subfamily font) "Medium")
                            (setf (font-subfamily font) "Medium"))
                        (draw-text window grackon font "Hello, world." 100 (+ 100 (* 2 (baseline-to-baseline window font))) :draw-background-p t)
                        (draw-text window grackon font "Press space to exit. Нажмите пробел для выхода." 100 (+ 100 (* 3 (baseline-to-baseline window font))) :draw-background-p t)
                        nil)
             (:button-press () t)
             (:key-press (code state) (char= #\Space (xlib:keycode->character *display* code state)))))
      (progn
        (xlib:free-gcontext grackon)
        (xlib:destroy-window window)
        (xlib:close-display *display*)))))

(show-window)
```
Now, here are two screenshots. One with X.org's modesetting driver loaded, and another one with X.org's intel driver loaded.

- Intel driver
![stumpwm-intel-driver](https://cloud.githubusercontent.com/assets/8706/16902432/8301f9b2-4c5e-11e6-877b-69b03f31b770.jpg)

- Modesetting driver
![stumpwm-modesetting-driver](https://cloud.githubusercontent.com/assets/8706/16902438/90dbb26c-4c5e-11e6-9142-82d367dcd80b.jpg)

So yeah, the problem exists on clx-truetype as its issue 5 suggests (filonenko-mikhail/clx-truetype#5) or even beyond.

**Comment by ereslibre** [comment]
Maybe recently added double buffering to modesetting driver has something to do with this (https://cgit.freedesktop.org/xorg/xserver/commit/?id=b83dede9cb930cf55249ad8e935f3c4d4328e2d9). CLX has no support for double buffering in sharplispers version, but it has on InvalidCo fork (https://github.com/InvalidCo/clx).

**Comment by dbjergaard** [comment]
can you try swapping out the clx versions? I can help if you don't know how.

**Comment by ereslibre** [comment]
The CLX library from sharplispers has already double buffering support, but clx-truetype or StumpWM should call to the right buffer swapping. I am pretty clueless on where the error is at the stack actually. I simplified a lot the previous example and I even tried to set ttf-surface and ttf-pen properties on the window of the example on the configure-notify event (as https://github.com/filonenko-mikhail/clx-truetype/issues/5 suggested), but no luck.

I can try to swap CLX versions anyway later when getting back home. What's the recommended way of doing so? (I have been editing my own ~/quicklisp code while trying many things, for example, I removed all caches from clx-truetype and still didn't render properly, blank fonts with modesetting driver).

I checked that the glyphs were being rendered correctly internally by clx-truetype and passed to X11 correctly too.

![cnrx1kexgaagp93](https://cloud.githubusercontent.com/assets/8706/16950180/242a3d02-4dbf-11e6-8e87-e663b8e43211.jpg)

If you have access to a relatively new intel card, you will be able to set the modesetting driver and check the issue. Thing is, the stack is missing tests everywhere so it boils down to a trial-error investigation.

**Comment by dbjergaard** [comment]
I dug pretty deep into font rendering in the past because I wanted to be able to load freetype fonts as well as truetype.  I have a half-baked version that almost works, but it needs to be gone over and the bugs fixed.  

That being said, the issue here is definitely with clx and not stumpwm.  To swap them out, you'll want to:
1. delete the cached files 
```rm -rf .cache/common-lisp/sbcl-*```
If that is heavy handed for you, then go in and find the specific package from quicklisp and rm it.  
2. Then, remove the clx from quicklisp:
```rm quicklisp/dists/quicklisp/software/clx-*-git/```
3. Checkout clx from the other repo:
```git clone https://github.com/InvalidCo/clx.git ~/quicklisp/local-projects/clx-invalidco```
4. Load it up:
```sbcl --eval '(ql:quickload :clx)'```
Assuming you're using sbcl... If you can get it going, then maybe try to submit an upstream PR to get this into the sharplispers distribution.  (Unless InvalidCo is going to...)

**Comment by PuercoPop** [comment]
@dbjergaard apropos one can also uninstall a system from the CL REPL using `ql:uninstall`, ej. `(ql:uninstall :clx)`

**Comment by ereslibre** [comment]
OK, with InvalidCo fork I cannot even run the example nor StumpWM. I will try other ways and report back if find anything...

Thanks for the detailed instructions! It was really easy to swap them.

From what I have been able to check I'd say font rendering works perfectly. The bug is not in StumpWM, but rather on clx-truetype and beyond. Since the rest of software renders correctly I tend to think the problem isn't either on the driver nor X.org. So I guess my first suspects are clx-truetype and clx itself.

**Comment by ereslibre** [comment]
By the way, I simplified the example I use to check if it is being rendered or not.

```
(ql:quickload :clx-truetype)

(defpackage #:clx-truetype-test
  (:nicknames :xft-test)
  (:use #:cl #:xft)
  (:export show-window))

(in-package :clx-truetype-test)

(defparameter *display* nil)

(defparameter *screen* nil)
(defparameter *root* nil)

(defun show-window ()
  (let* ((*display* #-windows (xlib:open-default-display)
                    #+windows (xlib:open-display "127.0.0.1" :protocol :tcp))
         (*screen* (xlib:display-default-screen *display*))
         (*root* (xlib:screen-root *screen*))
         (black (xlib:screen-black-pixel *screen*))
         (white (xlib:screen-white-pixel *screen*))
         (window
           (xlib:create-window :parent *root* :x 0 :y 0 :width 640 :height 480
                               :class :input-output
                               :background black
                               :event-mask '(:key-press :key-release :exposure :button-press :structure-notify)))
         (grackon (xlib:create-gcontext
                   :drawable window
                   :foreground black
                   :background white))
         (font (make-instance 'font :family "DejaVu Sans" :subfamily "Book" :size 12 :antialias t)))
    (unwind-protect
        (progn
          (xlib:map-window window)
          (setf (xlib:gcontext-foreground grackon) black)
          (xlib:event-case (*display* :force-output-p t
                                      :discard-p t)
                           (:exposure ()
                                      (xlib:clear-area window :width (xlib:drawable-width window)
                                                              :height (xlib:drawable-height window))
                                      (draw-text window grackon font "Oh, hi." 100 100 :draw-background-p t)
                                      nil)
                           (:button-press () t)
                           (:key-press (code state) (char= #\Space (xlib:keycode->character *display* code state)))))
      (progn
        (xlib:free-gcontext grackon)
        (xlib:destroy-window window)
        (xlib:close-display *display*)))))

(show-window)
```

**Comment by dbjergaard** [comment]
if you are feeling adventurous: 
https://github.com/dbjergaard/clx-ft2-renderer

That renderer works, but I don't quite have a module that lets you run it in stumpwm. And its about as slow as the clx-truetype renderer. If your interested I can post my clx-ft2 module and you can try to run it.

**Comment by dbjergaard** [comment]
I dumped the contrib module here:
https://github.com/dbjergaard/stumpwm-freetype-fonts
You'll have to check it out under `.stumpwm.d/modules/util/ft2-fonts` for it to get picked up when stumpwm starts

**Comment by ereslibre** [comment]
It just got fixed. From my pacman.log file....

[2016-07-21 16:03] [ALPM] upgraded xorg-server-common (1.18.3-3 -> 1.18.4-1)
[2016-07-21 16:03] [ALPM] upgraded xorg-server (1.18.3-3 -> 1.18.4-1)
[2016-07-21 16:03] [ALPM] upgraded xorg-server-xwayland (1.18.3-3 -> 1.18.4-1)

I will check out of curiousity what the changes were between versions...

@kostafey if you upgrade, can you please confirm that you now fonts are rendered?

**Comment by ereslibre** [comment]
Okay, *sorry for spamming the thread*, but it got interesting. It seems that [this commit](https://cgit.freedesktop.org/xorg/xserver/commit/?id=b64108fa305e956e4edaae9d53071ff0abee268e) detected if a composite operation was equivalent to a copy operation. clx-truetype does that, [actually](https://github.com/filonenko-mikhail/clx-truetype/blob/master/clx-truetype.lisp#L601).

So, thing is, that X.org patch was missing was to translate those coordinates from relative to absolute, [being fixed later](https://cgit.freedesktop.org/xorg/xserver/commit/?id=f5b224a0e20f1d44d4ab1aeeddbb4e2d40dec998).

What intrigues me relative to this bug report is that in any case @kostafey reports using modesetting, and the date of the issue is even before b64108fa305 made it into X.org (not to mention being released). So maybe there is another problem after all...

**Comment by dbjergaard** [comment]
Whats the conclusion of this? Is it fixed enough to close the issue?

**Comment by ereslibre** [comment]
From my point of view, yes. The issue wasn't on StumpWM, clx-truetype or clx. At least what I could reproduce, that could had nothing to do with what @kostafey reported... It would be great to hear back from @kostafey, but from my point of view it got fixed.

**Comment by kostafey** [comment]
@ereslibre, Unfortunately I've missed the conversation. Anyway, I've updated xorg-* and stumpwm. At this moment fonts rendering is ok. Thank you!
