### ISSUE TITLE
How do you recover from crash ?

### ISSUE THREAD

**Issue by jtbm37** [stumpwm/stumpwm#259]
Sometimes I mess around with my config and stumpwm crashes. Fair enough. But how do I recover from it ? I can open a different tty, update the config then kill the existing instance but I am not sure how to start a new one.

It would be ideal not to lose the existing session (windows).

Thanks.

**Comment by jtbm37** [comment]
Note that I also use XFCE.

**Comment by dbjergaard** [comment]
It depends on how hard the crash is.  Usually stumpwm will give you options to continue as if the procedure happened.  Other times it will signal the error and recover gracefully.  In both these cases its possible to continue to use stumpwm.  In these cases I usually launch xterm (C-t c by default) and edit the stumpwmrc to comment out or fix the error.

If the error is so bad that stumpwm hangs and doesn't respond to C-t g or any of the prefix commands, then I usually have to switch to a tty and kill the xserver.   If you require debug info, it is possible to switch to a tty, launch emacs in terminal mode and connect  to stumpwm from slime (assuming swank started early enough in the stumpwmrc).  Again here you may be able to tell the lisp process to continue as if nothing happened and recover from the error.  

The ideal situation would be that you prototype your changes from emacs and slime, and you work out showstopping bugs before you restart stumpwm.  This can be done from slime, developing the code and then testing it before you start stumpwm.  When you know the code works the way you want, then add it to you rc file and restart.  One of the killer features of stumpwm is that you can rewire anything "hot" without having to restart.  Just connect to the running instance with slime and eval whatever code your working on until it works the way you want, and then put the changes in the .stumpwmrc file for good.  

If your additional functionality is useful (and general enough) consider putting it in a separate file and making it into a contrib module that you can post for the community to use!

**Comment by jtbm37** [comment]
That's great. Thank you so much.
