### ISSUE TITLE
Unable to start stumpwm after upgrade to Ubuntu 15.10

### ISSUE THREAD

**Issue by jtbm37** [stumpwm/stumpwm#262]
When I run from the terminal I get this:

```
debugger invoked on a SB-INT:SIMPLE-PARSE-ERROR in thread
#<THREAD "main thread" RUNNING {1005386463}>:
  no non-whitespace characters in string "".

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

(no restarts: If you didn't do this on purpose, please report it as a bug.)

(PARSE-INTEGER "" :START 0 :END NIL :RADIX 10 :JUNK-ALLOWED NIL)
0] 		
```

This is both with latest version on git and from official repo.
I tried with no stumpwmrc.

**Comment by jtbm37** [comment]
I upgraded from ubuntu 15.04 to 15.10

**Comment by kostafey** [comment]
Have you tried to recompile stumpwm?

**Comment by jtbm37** [comment]
Yes I have. No error. I then went to upgrade from 15.10 to 16.04. Same result.

**Comment by kostafey** [comment]
SBCL version?

**Comment by PuercoPop** [comment]
@jtbm37 could you paste the whole backtrace (so we can see from where is parse-integer being called)? Also, just in case, what is the value of the DISPLAY variable (the result of running `echo $DISPLAY` on your shell)

**Comment by jtbm37** [comment]
@kostafey `SBCL 1.3.1.debian`

**Comment by jtbm37** [comment]
@PuercoPop 
`$ echo $DISPLAY`
`:1.0`

#### Backtrace
```
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1005134443}>
0: (PARSE-INTEGER "" :START 0 :END NIL :RADIX 10 :JUNK-ALLOWED NIL)
1: (XLIB::READ-XAUTH-ENTRY #<SB-SYS:FD-STREAM for "file /run/user/1000/gdm/Xauthority" {10052577B3}>)
2: (XLIB::GET-BEST-AUTHORIZATION "" 1 :LOCAL)
3: (XLIB:OPEN-DISPLAY "" :DISPLAY 1 :PROTOCOL :LOCAL :AUTHORIZATION-NAME NIL :AUTHORIZATION-DATA NIL)
4: (STUMPWM::STUMPWM-INTERNAL ":1.0")
5: (STUMPWM:STUMPWM ":1.0")
6: ((LAMBDA NIL :IN "/home/matrix/Documents/Github/stumpwm/make-image.lisp"))
7: ((FLET #:WITHOUT-INTERRUPTS-BODY-82 :IN SAVE-LISP-AND-DIE))
8: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
```

**Comment by PuercoPop** [comment]
Ok the issue seems to be with stumpwm::parse-display-string, iirc clx has an internal function to do that that doesn't use regexps. I'll look into it later today

**Comment by PuercoPop** [comment]
@jtbm37 can you post the contents of your Xauthority file?

**Comment by jtbm37** [comment]
@PuercoPop 
it's kind of garbage so I can't post straight it here. here is the file
[xauth.txt](https://github.com/stumpwm/stumpwm/files/353190/xauth.txt)

**Comment by PuercoPop** [comment]
@jtbm37 This is weird, I can't reproduce, your .Xauthority parses fine on my end.

```lisp
XLIB> (with-open-file (in #P"/home/puercopop/Downloads/xauth.txt" :element-type '(unsigned-byte 8)) (read-xauth-entry in))
(:LOCAL "mlnx" NIL "MIT-MAGIC-COOKIE-1"
 #(144 18 78 113 29 143 193 26 33 191 237 60 16 26 126 60))
```

Have you uploaded the file located at `/run/user/1000/gdm/Xauthority`?

Could you try running the following code in a SBCL repl? (or slime if you are more comfortable wth CL)
It should raise an error on parse-integer

```lisp
(ql:quickload :clx) ;; Or (asdf:make :clx) if you don't have quicklisp installed

(with-open-file (in #P"/run/user/1000/gdm/Xauthority" 
                    :element-type '(unsigned-byte 8))
  (xlib::read-xauth-entry in))
```

**Comment by jtbm37** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/536407/16673535/df018f9e-44a6-11e6-8a8c-552b2035be81.png)
@PuercoPop no problem at all. thank you for your help. stumpwm is part of my toolbox so I'll do what I can to help fixing it.

> Have you uploaded the file located at /run/user/1000/gdm/Xauthority?

Yes 

> Could you try running the following code in a SBCL repl? (or slime if you are more comfortable wth CL)
It should raise an error on parse-integer

See screenshot above.

**Comment by jtbm37** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/536407/16673656/fa8ad79c-44a7-11e6-80a0-4aab05d8f960.png)

**Comment by PuercoPop** [comment]
@jtbm37 Is your quicklisp up to date? read-xauth-entry only calls parse-integer in one place, before [explicitly checking against the `""` string](https://github.com/sharplispers/clx/blob/master/display.lisp#L65) since commit [313ce95c5](https://github.com/sharplispers/clx/commit/313ce95c52edc3b05c58144a02027ab37a4f8b0d#diff-449296ca00a93d386ffa4f077cfbfdfc) which was merged [3 years ago](https://github.com/sharplispers/clx/pull/10).

Could run `(ql:update-all-dists)` and run the snippet again? What is the result of  `(ql:where-is-system :clx)`? It should be something like `#P"/home/puercopop/quicklisp/dists/quicklisp/software/clx-20160421-git/"`.

**Comment by jtbm37** [comment]
@PuercoPop I did update. Same result after update.

> What is the result of (ql:where-is-system :clx)?

`#P"/usr/share/common-lisp/source/clx/"`

**Comment by PuercoPop** [comment]
Ok, as I suspected. The problem is that you aren't using the CLX from quicklisp but one installed through apt-get, which as usual is woefully out of date for ubuntu (or most distros for that matter). You have to uninstall that version.

**Comment by jtbm37** [comment]
@PuercoPop That did it ! I guess the upgrade installed stumpwm from the official repo.

Thank you very much for your help.
