### ISSUE TITLE
stumpwm doesn't recognise Compose key

### ISSUE THREAD

**Issue by eadmund** [stumpwm/stumpwm#264]
stumwpm doesn't recognise Compose key sequences: `Compose t h` just yields 'th.'

Maybe this is something which has to be handled in CLX? It looks like xlib normally provides this in C programs?

**Comment by dbjergaard** [comment]
This would be in CLX, and you'll have to either hack clx from stumpwm, or submit a patch to clx.  I'm not sure whats going on with sharplisper's clx distribution in quicklisp.  They seem less active than stumpwm.

**Comment by eadmund** [comment]
I'm digging into CLX. It doesn't look like it anticipated XIM or similar, so this will probably be open for awhile. The good news is maybe if I'm able to figure it out StumpWM can support non-Latin characters. We'll see though — I make no guarantees:-)

**Comment by dbjergaard** [comment]
Since this is upstream (in clx) I'm closing it.  Please take it up with sharplispers/clx if there is anyway to fix it.
