### ISSUE TITLE
restart-hard doesn't execute *quit-hook*

### ISSUE THREAD

**Issue by eadmund** [stumpwm/stumpwm#265]
`restart-hard` leaves open file descriptors open; this means that if a StumpWM instance is e.g. running swank then the new StumpWM won't be able to open the swank port again.

I think that it'd be good to run the `*quit-hook*`, even on a hard restart, in order to cleanly shut down anything which is running — or maybe there should be a `*restart-hook*` instead?

**Comment by dbjergaard** [comment]
Was this fixed by your PR? If not, feel free to open a new one, or let me know what I need to do to make restart-hard close the open file descriptors.  I'm not sure how to handle those.

**Comment by eadmund** [comment]
Yup, this can be closed.

I figure that if there's a restart hook then anyone who opens a file descriptor can close it himself. There's probably a way for StumpWM itself to take advantage of this too, but that can be a PR for a different day.
