### ISSUE TITLE
How to use StumpWM with SLIME?

### ISSUE THREAD

**Issue by kahrkunne** [stumpwm/stumpwm#268]
So I put something like
`(ql:quickload :swank)
(swank:create-server)` in my .stumpwmrc, then did `M-x slime-connect` in Emacs, then `M-x slime`, then `M-x slime-next-connection` once I noticed it was also starting it's own swank and connecting to that, then after making sure I was connected to the right one (127.0.0.1:4005), I tried doing some stumpwm things (redefining variables did nothing, typing `(in-package :stumpwm)` gave me errors).

I couldn't find much online either (only outdated things, it seems), so quite frankly, I'm stumped (pun intended). How do I do the live coding thing?

**Comment by jtbm37** [comment]
[This](http://www.kaashif.co.uk/2015/06/28/hacking-stumpwm-with-common-lisp/index.html) got me started the first time I tried to debug stumpwm.

**Comment by kahrkunne** [comment]
That worked perfectly, thanks! A shame this tutorial was so hard to find, sadly. This is definitely one of the cooler things that I've seen!

**Comment by PuercoPop** [comment]
It may be a good idea to add it to the FAQ in the wiki

**Comment by jtbm37** [comment]
@PuercoPop Done. See last question in [FAQ](https://github.com/stumpwm/stumpwm/wiki/FAQ)

**Comment by dbjergaard** [comment]
My only concern with this tutorial is that it makes it seem like you have to setup stumpwm in a non-standard way in order to get swank to work.  You should have to do `(ql:quickload :swank)` once, and then all you should need to add to stumpwm is:
```lisp
(require 'swank)
(swank:create-server)
```
That being said they may end up being morally equivalent in the end.
