### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by kahrkunne** [stumpwm/stumpwm#269]
So this is a weird one... When in StumpWM, I have no sound. Youtube videos won't play, and if I start mpd and pick a song, it starts playing but I hear nothing (however if I tab back to the TTY from which I started StumpWM, sound will play there. "Pavucontrol" shows no playback streams. Issue does not occur in other window managers (such as dwm, which I was using up to this point). Running Gentoo Linux, in case that's relevant.

EDIT: This should be obvious, but everything relevant is unmuted, including alsamixer

**Comment by kahrkunne** [comment]
I fixed it by running the commands specified in https://trisquel.info/en/forum/i-have-no-sound
Specifically, sudo usermod -aG `cat /etc/group | grep -e '^pulse:' -e '^audio:' -e '^pulse-access:' -e '^pulse-rt:' -e '^video:' | awk -F: '{print $1}' | tr '\n' ',' | sed 's:,$::g'` `whoami` seems to fix it. I have no clue what that does exactly, though, and so I have no idea what makes my audio setup broken on stumpwm but not elsewhere.

**Comment by dbjergaard** [comment]
I'm not sure either, other than to say that stumpwm is very minimal in what it registers/integrates with the rest of the desktop. That coupled with the fact that pulseaudio came along after the majority of stumpwm was written makes it seem like there's something missing. 

That being said, I'm running pulseaudio and I don't have this issue (though I use gnome-settings-daemon to handle stuff like this)
