### ISSUE TITLE
stumpwm should not depend on ppcre

### ISSUE THREAD

**Issue by tychoish** [stumpwm/stumpwm#274]
I've been installing it for years, and it's not given me trouble, but it strikes me (particularly after looking at the code) that PPCRE is a huge overhead in support of questionable idioms, particularly for a couple of very small and very limited cases we use it in. As a fun project, let's see if we can get the same functionality some other way.

**Comment by dbjergaard** [comment]
can you float this on devel? At first glance I agree, but other users may use ppcre for things outside the base stumpwm (matching window regexes etc).  It would be worth having a discussion about.

**Comment by dbjergaard** [comment]
Given the level of dependency on ppcre in the contrib modules, I'm going to keep this as a dependency.  Its not the only place where stumpwm does this (there's wrapper code for contrib modules in stumpwm proper).

**Comment by tychoish** [comment]
it is possible for contrib modules to have additional dependencies above and beyond what -core depends on, right? That doesn't strike me as a huge problem.
