### ISSUE TITLE
*mode-line-timeout* is ignored

### ISSUE THREAD

**Issue by Jehops** [stumpwm/stumpwm#276]
The  mode-line no longer updates after commit 56303adf44876ef71571e4745521bbccacae477a.  After reverting back to 9d854fda0b11815930468a27da280ebbf2073971, the mode-line updates again.

**Comment by dbjergaard** [comment]
This is related to #270 and #272, if you can see how to get the timers to execute properly please let me know/open a PR.

**Comment by jorams** [comment]
Fixed by 13ff02bf6a02daf6f81b9f311371a1e64e657621
