### ISSUE TITLE
"x not bound"

### ISSUE THREAD

**Issue by erjoalgo** [stumpwm/stumpwm#296]
I have been running into a very frustrating problem for some time. When I plug in an external keyboard and start typing,

I get an "x not bound" message for every key press x for which there exists a H-x binding (H is hyper)  

This doesn't seem to happen with the laptop's built-in keyboard

I've run xev, and pressed "x" on both keyboards. Both show the same keysym, but only on the 2nd keyboard I get the "x not bound" message.

I've checked the code, it seems that "x not found" should only happen on describe-key:

```lisp
(defcommand describe-key (keys) ((:key-seq "Describe Key: "))
"Either interactively type the key sequence or supply it as text. This
command prints the command bound to the specified key sequence."
  (let ((cmd (loop for map in (top-maps)
                   for cmd = (lookup-key-sequence map keys)
                   when cmd return cmd)))
    (if cmd
        (message "~{~a~^ ~} is bound to \"~a\"." (mapcar 'print-key keys)  cmd)
        (message "~{~a~^ ~} is not bound." (mapcar 'print-key keys)))))
```

I also sometimes notice "x not found" even on the laptop keyboard, especially when the cpu is so busy that it lags behind the X input (keypresses, etc).

Could this be a threading issue?

**Comment by erjoalgo** [comment]
This was reported using:

```
commit 7d78c80558247508077cd56ee2ba62dcc614b087
Merge: 92d2d56 a66b851
Author: Joram Schrijver <i@joram.io>
Date:   Thu Mar 3 12:39:51 2016 +0100

    Merge pull request #243 from xsteve/fix-select-from-menu
    
    menu.lisp: select-from-menu: Honour the initial-selection parameter
```
Which was significantly behind. It has been fixed in
```
commit 7ad1c929d1ff8174b5e4f3873d4b320b2f57fd32
Merge: 2c1dfcc 2265734
Author: David Bjergaard <dbjergaard@users.noreply.github.com>
Date:   Mon Dec 19 12:09:34 2016 -0500

    Merge pull request #294 from dmh43/DH-which-key
    
    Add which-key-mode
```
I'd be curious to identify which commit fixed the issue, via `git bisect`. Closing for now.

**Comment by erjoalgo** [comment]
Error shown below with external keyboard:
![a-not-bound](https://cloud.githubusercontent.com/assets/5349288/21599338/ec8daa5c-d11f-11e6-97b3-a79201a1fcf5.jpg)

**Comment by jorams** [comment]
This error does not actually come from `describe-key`, but from the `:key-press` event handler in `events.lisp`.

**Comment by erjoalgo** [comment]
I edited :key-press to make it more verbose as in below:

```lisp
(define-stump-event-handler :key-press (code state #|window|#)                                       
  (write-line (prin1-to-string (list "code" code "state" state                                       
                                     "window" #|window|#)))                                          
   (write-line (prin1-to-string (list "top maps" (top-maps))))                                       
  (labels ((get-cmd (code state)                                                                     
             (with-focus (screen-key-window (current-screen))                                        
               (handle-keymap (top-maps) code state nil t nil))))                                    
                                                                                                     
    (unwind-protect                                                                                  
         ;; modifiers can sneak in with a race condition. so avoid that.                             
         (unless (is-modifier code)                                                                  
           (multiple-value-bind (cmd key-seq) (get-cmd code state)                                   
             (write-line (prin1-to-string                                                            
                          (list "before unwind protect. cmd: " cmd                                   
                                "key seq" key-seq)))                                                 
             (cond                                                                                   
               ((eq cmd t))                                                                          
               (cmd                                                                                  
                (unmap-message-window (current-screen))                                              
                (eval-command cmd t) t)                                                              
               (t (message "~{~a ~}not bound." (mapcar 'print-key (nreverse key-seq))))))))))
```

I was able to reproduce the issue, I see the following when pressing "a" from the external keyboard:

```
$ tail -f /tmp/stumpwm-out 
("code" 38 "state" 0 "window")
("top maps" (*TOP-MAP* STUMPWM::*TILE-GROUP-TOP-MAP* STUMPWM::*GROUP-TOP-MAP*))
("before unwind protect. cmd: " NIL "key seq"
 (#S(STUMPWM::KEY
     :KEYSYM 97
     :SHIFT NIL
     :CONTROL NIL
     :META NIL
     :ALT NIL
     :HYPER NIL
     :SUPER NIL)))
```

I don't see anything wrong, I see the code is correct ("a" keypress") and the state is correct (no modifiers). 

Why is :key-press being called only sometimes (only on presses from the external keyboard)? 

Is "code" for a supposed to be 97 instead of 38?

**Comment by erjoalgo** [comment]
I noticed when the "a" and other keys work correctly, the `:key-press` handler is not invoked, and every time the "a not bound" happens, `:key-press` is invoked. Is there another handler that is supposed to be handling a key press event that is not bound to anything on the top map?

**Comment by dbjergaard** [comment]
Without digging too deep: 
"a" not bound  will get displayed if stumpwm is trying to interpret the keypress as a keybinding. It looks it up in the top keymap and when it can't find it, it issues the message.  Normally stumpwm will just pass the keypress event to the client.  

Somehow adding the keyboard is causing stumpwm to do the former instead of just passing the event to client windows.

It would be useful to have a backtrace from the point that the message shows up to see how it arrived at that context.  If not, there is not much we will be able to do since I've never had issues with external keyboards.  Is it a standard us 105 key keyboard?

**Comment by erjoalgo** [comment]
I see the stack trace is unreadable, even after I've added `(proclaim '(optimize (debug 3)))` and restarted things. Any hints on how to make the stack trace more readable?

**Comment by jorams** [comment]
This turns out to be incredibly easy to reproduce:

```lisp
(define-key *top-map* (kbd "H-a") "echo definitely")
```

Now every time I press the `a` key, I get "a not bound".

**Comment by erjoalgo** [comment]
@dbjergaard 
Do you know where is the code that decides whether to "Normally stumpwm will just pass the keypress event to the client" vs "looks it up in the top keymap "?

**Comment by jorams** [comment]
I *think* I know what's happening. @erjoalgo said on IRC that they bind the right super key to hyper. When an external keyboard is plugged in, in my experience, the X keybindings are reset. StumpWM  will receive a `:mapping-notify` event, causing it to call `update-modifier-map`. However, because the X bindings are not properly set up, there is no actual hyper key.

The subsequent call to `sync-keys` causes all bindings on all windows to be set up again. It uses the function `x11-mods` in the process, which will add the relevant modifier for "hyper" to the *state mask*. In this case, however, there is no such modifier. Thus no actual modifiers will be added to the mask, causing the original key without any modifiers to be grabbed on each window.

It's also why my reproduction above works for me: I don't have a hyper key.

**Comment by erjoalgo** [comment]
To summarize from the IRC discussion. 

- I'm using xmodmap to map the control-r keycode to Hyper_L: `keycode 105 = Hyper_L`
- After unplugging/re-plugging the external keyboard, the 105 =>  Hyper_L keysym mapping gets lost on the external keyboard, and I instead get the original Control_R keysym for keycode 105 (via xev) 
- I can probably work around the issue by using udev rules to run specific xmodmap scripts
- I think this is a bug: "a" shouldn't be grabbed by stumpwm because a "H-a" binding exists, regardless of whether Hyper exists or not

**Comment by jorams** [comment]
I've opened #299 to fix this. @erjoalgo could you test if it fixes the problem?

I haven't noticed it breaking anything, but I might have missed a consequence of the change. Any other testing would also be appreciated.

**Comment by erjoalgo** [comment]
Like I commented in #299, that fix didn't work for me. 

What did work (although it is specific to Hyper modifier which is the only one I care about) is the commit [here](
https://github.com/erjoalgo/stumpwm/commit/b0e9ea00d30802fa73d8c4afdc29cc1949f48141):


Basically skipping the key grab when the key contains a Hyper modifier when Hyper is not bound:
```lisp
-               (when code
+               (when (and code
+                             ;;temporary hack to make sure H-a
+                             ;;doesn't cause "a" to be grabbed
+                             ;;when there is no H
+                             (or (not (key-hyper key))
+                                 (modifiers-hyper *modifiers*)))
```

**Comment by dbjergaard** [comment]
I know this is hackish, but if it works, can you open a PR and we'll merge it in?
