### ISSUE TITLE
`*screen-mode-line-format*` not working according to documentation

### ISSUE THREAD

**Issue by dhamidi** [stumpwm/stumpwm#308]
Given the following in ~/.stumpwmrc:

```
(setf *screen-mode-line-format*
      (list "[%w] " '(:eval (stumpwm:run-shell-command "bash -c \"~/local/bin/mode-line\"" t))))
```

Everything works as expected: `[%w] ` is respected and the shell command is run.

However, the following does not work:

```
(setf *screen-mode-line-format*
      (list  '(:eval (stumpwm:run-shell-command "bash -c \"~/local/bin/mode-line\"" t)) "[%w] "))
```

Only the result of `run-shell-command` is visible in the modeline.

I'm running stumpwm at commit 37a0ae9 (tagged `v1.0.0`).

Reading the documentation for `*screen-mode-line-format* gives the impression that the latter is supposed to render the output of the given shell command followed by whatever %w expands to.

**Comment by PuercoPop** [comment]
I can't reproduce.  Both mode line formats work. Even tested the case where the program exits with a failure code.
