### ISSUE TITLE
"C-t !" displays /bin/sh even when *shell-program* is non-nil

### ISSUE THREAD

**Issue by sydii** [stumpwm/stumpwm#325]
Currently /bin/sh is hardcoded into the definition of `run-shell-command` which causes it to be displayed instead of the user's preferred shell when `*shell-program*` is non-nil. What should occur is upon setting `*shell-program*`, the user-set shell should be displayed on screen when `C-t !` is typed.

The code currently in user.lisp, line 157 to 164:
```
(defcommand run-shell-command (cmd &optional collect-output-p) ((:shell "/bin/sh -c "))
  "Run the specified shell command. If @var{collect-output-p} is @code{T}
then run the command synchonously and collect the output. Be
careful. If the shell command doesn't return, it will hang StumpWM. In
such a case, kill the shell command to resume StumpWM."
  (if collect-output-p
      (run-prog-collect-output *shell-program* "-c" cmd)
      (run-prog *shell-program* :args (list "-c" cmd) :wait nil)))
```

**Comment by dbjergaard** [comment]
Fixed with #336
