### ISSUE TITLE
stumpwm fails to compile on recent versions of sbcl

### ISSUE THREAD

**Issue by bon** [stumpwm/stumpwm#326]
Using `git bisect` on the mirror of the sbcl code at https://github.com/sbcl/sbcl shows that the change introduced in sbcl/sbcl@60fa88b leads to 

```
While evaluating the form starting at line 3, column 0
  of #P"./make-image.lisp":

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1002176823}>:
  #<SB-C:TN t1> is not valid as the second argument to VOP:
  SB-VM::ANCESTOR-FRAME-SET/SYSTEM-AREA-POINTER
Primitive type: T
SC restrictions:
  (SB-VM::SAP-REG)
The primitive type disallows these loadable SCs:
  (SB-VM::SAP-REG)
```

The last sbcl commit which compiles stumpwm was sbcl/sbcl@74c07be10

**Comment by dbjergaard** [comment]
Can you kick this upstream? If sbcl broke the build between versions and we aren't doing something explicitly deprecated then its their problem not ours. 

None of what you've posted there looks like anything that we're touching explicitly.  Can you get a full stack trace?

**Comment by PuercoPop** [comment]
This has been fixed in head

**Comment by bon** [comment]
Identify issue, post issue, cook dinner, eat dinner, check on issue, issue identified and fixed.

Hats off to you guys. Gotta love open-source software.

**Comment by dbjergaard** [comment]
@PuercoPop I don't mind either way. I'm not so serious about having a auditable history of everything that has gone wrong and been fixed.  I suppose someday that will bite me, but for now it doesn't seem worth the effort.
