### ISSUE TITLE
configure with --with-lisp=clisp, error when "make", error msg:A function has been called that is not implemented yet

### ISSUE THREAD

**Issue by mashomee** [stumpwm/stumpwm#327]
i use clisp configure and make stumpwm, 
source code is acquired through "git clone",
then the error occured compainling about "sb-ext" package.

**Comment by PuercoPop** [comment]
Hi @mashomee,

[1.0](https://github.com/stumpwm/stumpwm/releases/tag/1.0.0) was the last release to support lisp implementations other than SBCL.

**Comment by mashomee** [comment]
Then I use version 1.0, It's complaining about package "uiop"
READ from #<INPUT BUFFERED FILE-STREAM CHARACTER #P"/dev/fd/0" @7>:
      there is no package with name "UIOP"

**Comment by PuercoPop** [comment]
That is because clisp is unmantained and has a very old ASDF version. You'll have to update your ASDF

**Comment by mashomee** [comment]
@PuercoPop Thanks!
