### ISSUE TITLE
Strange keyboard layout behaviour

### ISSUE THREAD

**Issue by ghferrari** [stumpwm/stumpwm#337]
I've been experiencing some strange behaviour with stumpwm over the last week.

First, my stumpwm started behaving strangely in that it couldn't find quicklisp or any of its libraries on startup. I traced this to lack of a SBCL_HOME environment variable, so this has now been fixed in my stumpwmrc. I'm using Debian testing and I solved this issue by adding this line to the start of my .stumpwmrc
`(sb-posix:putenv "SBCL_HOME=/usr/lib/sbcl")`

I also have another issue which I haven't been able to solve, so I'd appreciate any suggestions. Basically, the keyboard layout recognised as the top map in stumpwm is now different to the keymap recognised by any other x program. Among other problems, this means that my prefix key, which is bound to "C-#" has moved because "#" used to be near the Enter key but for some reason stumpwm now thinks it's on Shift-3. (Other keys like | have also moved).

So now, if I query my usual prefix key with C-h k, stumpwm reports that "\ is unbound". But when i press this key in emacs or any other application, I get "#" not "\\".

Does anyone have an idea what's going on and how to fix it?

Thanks,

Geoff

**Comment by dbjergaard** [comment]
I've just made a PR to revert the PR that got rid of SBCL_HOME.  Lets get that going (correctly since SBCL_HOME should be set before stumpwm starts) and see if that doesn't help your other issue.  

Otherwise I'll have to go through the recently merged PRs and see if there are any that could be affecting your keyboard layout. That is very strange.

**Comment by ghferrari** [comment]
Thanks, David. I just re-build stumpwm after your revert, but it doesn't solve my keyboard issue.

I honestly don't know if this issue was caused by a debian update or by a stumpwm update. My post above is just to try to get some extra information to help tracking down the problem.

Is there any useful info from my installation I can provide to help?

**Comment by jorams** [comment]
This should now be fixed by a71fda5a2eed9f314c73e763a8f1c32f87e52891, along with #339.

See https://github.com/stumpwm/stumpwm/issues/339#issuecomment-289271885 for the explanation. Basically, keyboard mapping events were ignored by StumpWM.

**Comment by ghferrari** [comment]
Thanks, Joram - that seems to have fixed it for me.
