### ISSUE TITLE
SBCL_HOME = "NIL"

### ISSUE THREAD

**Issue by defaultxr** [stumpwm/stumpwm#341]
My `SBCL_HOME` environment variable is normally unset, which causes sbcl to default to using /usr/local/lib/sbcl for that value. When I build stumpwm, [this line](https://github.com/stumpwm/stumpwm/blob/2368dc89a849ac5a0a2ab116404724e42329fbf6/make-image.lisp.in#L17) seems to cause the build process to use `(sb-ext:posix-getenv "SBCL_HOME")` which, since `SBCL_HOME` is empty, returns `NIL`. `format` then coerces `NIL` to a string, so when the newly-built stumpwm is run, `SBCL_HOME`'s value is `NIL`. This causes problems when trying to run sbcl from within stumpwm because sbcl will look for sbcl.core at `NIL/sbcl.core`, which doesn't exist.

Outside StumpWM:

```
$ sbcl
This is SBCL 1.3.15, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (format nil "SBCL_HOME=~A" #.(sb-ext:posix-getenv "SBCL_HOME"))

"SBCL_HOME=NIL"
* 
$ echo $SBCL_HOME

$
```

Inside StumpWM:

```
$ sbcl
fatal error encountered in SBCL pid 9948(tid 0x7ffff7fa7b80):
can't find core file at NIL/sbcl.core


$ echo $SBCL_HOME
NIL
$
```

SBCL 1.3.15, StumpWM 1.0.0-88-g7d63123 (built today). Still somewhat new to lisp so if you need any more information from me please let me know how to find that information.

**Comment by treere** [comment]
Hi @defaultxr I changed _make-image.lisp_ in this way but I-m not sure that it is the right way.

`(sb-ext:save-lisp-and-die "stumpwm" :toplevel (lambda ()
                                                ;; asdf requires sbcl_home to be set, so set it to the value when the image was built
                                                (sb-posix:putenv (format nil "SBCL_HOME=~A" #.(or (sb-ext:posix-getenv "SBCL_HOME") "")))
                                                (stumpwm:stumpwm)
                                                0)
                                    :executable t
                                    :purify t)`

**Comment by defaultxr** [comment]
That looks like it should work. I will test it later on my own machine and will report back.

**Comment by defaultxr** [comment]
Looks like it works - $SBCL_HOME is showing the correct value from shells launched from stumpwm if that change is made to make-image.lisp.in. So that change should resolve the issue.

**Comment by ahmed-shariff** [comment]
I also ran into the same problem, couldn't launch sbcl from stumpwm. For now I am unseting the variable from the terminal, and launching sbcl from there. I've installed stump using arch AUR. Where do I perform the fix @treere proposes?

**Comment by defaultxr** [comment]
@ahmed-shariff I don't have stumpwm installed through the AUR, I just have a local clone of this repository and make the change in that copy before compiling/installing normally as described in the README. The fix proposed by treere is the sexp starting on [line 15 of make-image.lisp.in](https://github.com/stumpwm/stumpwm/blob/master/make-image.lisp.in#L15) in the repo's root directory. One of the steps listed in the README will copy make-image.lisp.in to make-image.lisp which is the actual file that gets compiled, so if you're still having trouble make sure that make-image.lisp has the modification as well, not just make-image.lisp.in.

**Comment by ahmed-shariff** [comment]
I am new to Arch, will find a way to edit the AUR packages and let you know how it goes.
Meanwhile, as a workaround, I included `unset SBCL_HOME` in bashrc. To have the changes reflect in emacs when launched using the default `C-t e` key-binding, I redefine the key-binding to `sh -c emacs`

**Comment by jorams** [comment]
b740b04f8400e5aa42cff0086b659e8ea56d3420 should have just fixed the problem. #333 removed the entire call to `putenv` because it was no longer necessary. Then people complained because in some environments it *is* still necessary, so the change was reverted in #338. b740b04f8400e5aa42cff0086b659e8ea56d3420 just makes it conditional, so that SBCL_HOME will only be set if it was set at build time.
