### ISSUE TITLE
Move Xinerama to CL side and Add XRandr Support

### ISSUE THREAD

**Issue by PuercoPop** [stumpwm/stumpwm#346]
In order to avoid using a regexp to parse xpdyinfo we can insteald use clx's implementation. The two functions we care about are

- `xlib/xinerama:xinerama-is-active`
- `xlib/xinerama:xinerama-query-screens`

Unfortunately CLX doesn't implement the [Randr protocol](https://cgit.freedesktop.org/xorg/proto/randrproto/tree/randrproto.txt) so we'll have to continue using the regexp method shown in #328 

We should use Xephyr to simulate multiple monitor setups for testing

**Comment by letharin** [comment]
Sharplispers clx has an xrandr extension, isn't that the implementation that SBCL uses? Can it be used for SBCL and the fallback to the old method for clisp?

**Comment by dbjergaard** [comment]
no need to fall back for clisp since we don't support it anymore.  I assumed sharplisper's clx is the one distributed with quicklisp? if it is, then we can use their xrandr solution. Otherwise we'll have to do as @PuercoPop says.

**Comment by PuercoPop** [comment]
@letharin You are right. I had [missed it](https://github.com/sharplispers/clx/blob/master/extensions/randr.lisp). I'll use it as well. Hopefully during this easter holiday

**Comment by PuercoPop** [comment]
I've started to work on this issue on [the following branch](https://github.com/PuercoPop/stumpwm/tree/clx-xinerama-xrandr). I still have to test it using Xephyr, add xrandr support and if possible ask through the mailing list if anyone wants to give the branch a spin before merging

**Comment by PuercoPop** [comment]
@letharin The randr.lisp is not in ASDF file of CLX, which means it is not loaded by default. It also appears to throw errors when added to the ASDF system definition. However there is a [partial](https://github.com/sharplispers/clx/pull/15#issuecomment-124023883) xrandr implementation that does what we need. I'll try to get it merged

**Comment by dbjergaard** [comment]
Did I see the xrandr code get merged earlier? if so, please close this.
