### ISSUE TITLE
arch AUR makepkg validation failed

### ISSUE THREAD

**Issue by ahmed-shariff** [stumpwm/stumpwm#349]
cloned the AUR repository (https://aur.archlinux.org/stumpwm.git)
and ran `makepkg`.
Had the following output:
```
==> Making package: stumpwm 1.0.0-4 (Wed May  3 17:58:12 +0530 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading stumpwm-1.0.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   123    0   123    0     0     81      0 --:--:--  0:00:01 --:--:--    82
100  196k    0  196k    0     0  44717      0 --:--:--  0:00:04 --:--:-- 75368
  -> Downloading stumpwm-contrib.git...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    134      0  0:00:01  0:00:01 --:--:--   134
100 57804    0 57804    0     0  23563      0 --:--:--  0:00:02 --:--:-- 11.6M
==> Validating source files with md5sums...
    stumpwm-1.0.0.tar.gz ... Passed
    stumpwm-contrib.git ... FAILED
==> ERROR: One or more files did not pass the validity check!
```

**Comment by ahmed-shariff** [comment]
when i set the md5sums of ttps://github.com/stumpwm/stumpwm-contrib.git to 'SKIP' it works without a problem

**Comment by defaultxr** [comment]
This isn't a stumpwm issue, it's an issue that the maintainer of the stumpwm AUR package would need to fix. You may want to leave a comment or "Flag package out of date" on the [AUR page](https://aur.archlinux.org/packages/stumpwm-git/).

**Comment by PuercoPop** [comment]
It to some extend an issue with stumpwm-contrib. We should make a release of the contrib which goes in hand with the 1.0.0 release as well, especially because we have dropped support for implementations afterwards

**Comment by ahmed-shariff** [comment]
I will leave a comment in AUR as well

**Comment by dbjergaard** [comment]
I disagree, the whole reason stumpwm-contrib is outside of stumpwm is to decouple them.  I don't want to release contrib packages alongside stumpwm.  If package maintainers want to pull snapshots of contrib with stumpwm, thats their business.

The only counter argument I can see is if contrib modules use an old/broken API.  There are no CI tests for contrib modules, so this is something to think about.

**Comment by tpine** [comment]
While it does make sense to see them as different projects it seems to make sense from the stumpwm-contribs point of view to tag the release where they gain api compatibility with a major stumwm release over all the modules.

**Comment by dbjergaard** [comment]
Unfortunately I don't have the time or resources to make sure that the contrib modules remain compatable with stumpwm as released. I know this sounds dismissive, but everything the active developers are doing is a labor of love in our free time. 

A lot of the modules have significant bit rot, and some of them are evergreen. Unless someone is willing to step up and either write a CI framework, or actively maintain and cull bitrotted modules, I will keep things as they are.
