### ISSUE TITLE
error when trying to use ttf font

### ISSUE THREAD

**Issue by alexdreptu** [stumpwm/stumpwm#350]
```lisp
(ql:quickload :clx-truetype)                                                                               
(load-module "ttf-fonts")                                                       
(set-font (make-instance 'xft:font :family "InputMono" :subfamily "Regular" :size 11))
```
Using the above gives an error ```there is no applicable method for the generic function```

**Comment by jorams** [comment]
Could you get a stacktrace of that? `set-font` itself is not a generic function.

**Comment by alexdreptu** [comment]
I'm not sure how I would go about getting the stack trace, it was my first time trying stumpwm. I used the (loadrc) function and the console at the top of the screen popped up with the error and the usual options to re-evaluate, continue loading init.lisp etc.

**Comment by dbjergaard** [comment]
Two things:
- You have to cache the fonts before you use them (I forget the syntax ATM, but its done once interactively the same way you run fc-cache to pick up new fonts)
- You can only use *.ttf fonts.  

I have some code that does opentype fonts (ttf and otf), but it never quite got mature enough to make it into contrib. And it had the same performance issues as the clx-truetype module.

**Comment by ValTimchenko** [comment]
Hmm, try something like that (my working configuration):
(load-module "ttf-fonts")
(xft:cache-fonts)
(set-font `("-xos4-terminus-medium-r-normal--14-140-72-72-c-80-iso10646-1"
	    ,(make-instance 'xft:font :family "fontello"
			    :subfamily "Regular"
			    :size 10)))

**Comment by jakecoble** [comment]
This is the error and stacktrace I'm getting. 
```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION STUMPWM::FONT-EXISTS-P (1)>
when called with arguments
  (#<'CLX-TRUETYPE:FONT :FAMILY "Iosevka Term" :SUBFAMILY "Regular" :UNDERLINE NIL :STRIKETHROUGH NIL :OVERLINE NIL :BACKGROUND NIL :FOREGROUND NIL :OVERWRITE-GCONTEXT NIL :ANTIALIAS T>).
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [RETRY] Retry SLIME interactive evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT] abort thread (#<THREAD "worker" RUNNING {100351CEF3}>)

Backtrace:
  0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION STUMPWM::FONT-EXISTS-P (1)> #<'CLX-TRUETYPE:FONT :FAMILY "Iosevka Term" :SUBFAMILY "Regular" :UNDERLINE NIL :STRIKETHROUGH NIL :OVERLINE..
  1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION STUMPWM::FONT-EXISTS-P (1)> (#<'CLX-TRUETYPE:FONT :FAMILY "Iosevka Term" :SUBFAMILY "Regular" :UNDERLINE NIL :STRIKETHROUGH NIL :OVERLINE..
  2: (SET-FONT #<'CLX-TRUETYPE:FONT :FAMILY "Iosevka Term" :SUBFAMILY "Regular" :UNDERLINE NIL :STRIKETHROUGH NIL :OVERLINE NIL :BACKGROUND NIL :FOREGROUND NIL :OVERWRITE-GCONTEXT NIL :ANTIALIAS T>)
  3: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SET-FONT (MAKE-INSTANCE (QUOTE CLX-TRUETYPE:FONT) :FAMILY "Iosevka Term" :SUBFAMILY "Regular" ...)) #<NULL-LEXENV>)
  4: (EVAL (SET-FONT (MAKE-INSTANCE (QUOTE CLX-TRUETYPE:FONT) :FAMILY "Iosevka Term" :SUBFAMILY "Regular" ...)))
  5: ((LAMBDA NIL :IN SWANK:INTERACTIVE-EVAL))
```
This config was working before the last update.
```
(load-module "ttf-fonts")
(set-font (make-instance 'xft:font :family "Iosevka Term" :subfamily "Regular" :size 11))
```

**Comment by jakecoble** [comment]
I found out what I was doing wrong. Try calling `(list-modules)`. If that returns `NIL`, your modules aren't being loaded at all because stumpwm's module directory is pointing in the wrong place. Run `make install-modules` and it should download the modules to where stumpwm looks for them by default.

**Comment by jorams** [comment]
Hmm, I'm not a fan of the way `load-module` just doesn't do anything when the module doesn't exist.

**Comment by dbjergaard** [comment]
@jorams I agree. I'm going to close this and open another issue to handle this.
