### ISSUE TITLE
Crash on reading window hints, XLIB::DECODE-WM-SIZE-HINTS

### ISSUE THREAD

**Issue by ecraven** [stumpwm/stumpwm#357]
This mainly happens when trying some unity games on linux (for example https://samuraipunk.itch.io/fruits-of-a-feather).
````
> sbcl --version                                                                                                                          11:53:37
SBCL 1.3.17
````
stumpwm-20170516-git from quicklisp, StumpWM 1.0.0 Compiled on Mon May 22 2017
````
The value
4149330171
is not of type
(MOD 11)
when binding #:G1620

Backtrace for #<SB-THREAD:THREAD "main thread" RUNNING {1002CF6873}>
0: (XLIB::DECODE-WM-SIZE-HINTS #(944 0 0 0 0 1920 1200 1920 1200 0 0 189672832 ...))
1: (STUMPWM::GET-NORMALIZED-NORMAL-HINTS #<XLIB:WINDOW :0 1C00002>)
...

````

![stumpwm](https://cloud.githubusercontent.com/assets/215510/26545525/3b957760-4466-11e7-96ba-89511a941dc6.jpg)

**Comment by PuercoPop** [comment]
Hi, this is an issue with CLX (or fruits of a feather). One or two months ago [another user reported a similar issue with a different game](https://github.com/sharplispers/clx/issues/67). The work around we got at was wrapping the value in question with a call to (mod <foo> <index-of-the-huge-value).

I think the index was 17 but I may be misremembering. For example if 17 is the index of the problematic value

```lisp
;; In decode-wm-size-hints, replace
(decode-type (member-vector +win-gravity-vector+) (aref vector 17))
;; with
(decode-type (member-vector +win-gravity-vector+) (mod (aref vector 17)
                                                                       11))
```

Let me know if you need any further assistance.

**Comment by ecraven** [comment]
I understand that this is an issue with CLX, but isn't there a way that stumpwm could handle this more gracefully than by just totally crashing?

**Comment by ecraven** [comment]
https://github.com/sharplispers/clx/issues/67 is the clx issue for this problem.

**Comment by ecraven** [comment]
I hope https://github.com/sharplispers/clx/issues/74 closes this..
