### ISSUE TITLE
Inconsistent typesetting in manual

### ISSUE THREAD

**Issue by impaktor** [stumpwm/stumpwm#371]
Some main points that remain unresolved in the current documentation of stumpwm. These are things I didn't feel comfortable changing myself, from the texi->pdf file I've been reading:

- In Modules section, there are two "asdf" and three "ASDF". Which is preferred?

- Throughout the manual there's mixing of "stumpwm" and "StumpWM" (even a "Stumpwm").

- Is it `NIL` or `nil`? `non-NIL` or `non-nil`?

- Is it `t` or `T`?

- Manual says: _"Remember: StumpWM is designed to run on many lisp systems."_
But is this still true?

**Comment by tpine** [comment]
StumpWM (I use the version in the readme for how to type it personally) only now runs on SBCL. There is also a issue in the readme which still says it runs on multiple lisp systems as well which should also be changed.

**Comment by dbjergaard** [comment]
The answer to most of these is "it depends" 

- ASDF the package system is appropriate when referring to the software, in code lower case is appropriate:  `(require 'asdf)` is appropriate in code.

- StumpWM is the right way to refer to software, however in more casual settings stumpwm can be appropriate.  I perfer StumpWM consistently used in the manual, in other documents I don't care.

- `NIL` vs `nil` and `t` vs `T`: keep it consistent with the CLHS (http://www.lispworks.com/documentation/HyperSpec/Body/v_t.htm#t).  If used to show the result of a computation or as a reference to the symbol, upper case, else use lower case. 

The manual needs to be updated to remove reference to other lisp systems.

**Comment by impaktor** [comment]
Just letting you guys know, that I'm not planning any pull request to fix these things, I just wanted to point them out, so feel free to close this issue or do what you want with it.
