### ISSUE TITLE
Mouse scroll not working in GTK+ applications

### ISSUE THREAD

**Issue by ahmed-shariff** [stumpwm/stumpwm#372]
The mouse scroll doesn't seem to be working on gtk+ applications. I first noticed this with Tilix, assumed it was a problem [there](https://github.com/gnunn1/tilix/issues/999#issuecomment-312863056). The problem also seems to be there on several other application that use GTK+. When I login into xfce, there is no problem with the mouse scroll. Any advice?

**Comment by xsteve** [comment]
Hi Ahmed!

I had a similar issue with evince.

I could solve it by putting the following in ~/.xsession:
export GDK_CORE_DEVICE_EVENTS=1

Hope this helps,
  Stefan.

> The mouse scroll doesn't seem to be working on gtk+ applications. I
> first noticed this with Tilix, assumed it was a problem
> [there](https://github.com/gnunn1/tilix/issues/999#issuecomment-312863056).
> The problem also seems to be there on several other application that
> use GTK+. When I login into xfce, there is no problem with the mouse
> scroll. Any advice?

**Comment by dbjergaard** [comment]
This is covered in our FAQ.  Basically, clx doesn't support the XInput extension, so someone would have to put this upstream for us to avoid this workaround.  I set this variable in my .xinitrc, however I noticed too many adverse problems to make it a permanent change.  
See http://lists.libreplanet.org/archive/html/stumpwm-devel/2013-12/msg00008.html for details on adding this to clx
