### ISSUE TITLE
Add a supported way to define window gaps

### ISSUE THREAD

**Issue by dertuxmalwieder** [stumpwm/stumpwm#373]
One of the (very few) things I would love to see being added to StumpWM is a way to define gaps between windows. The [oldish patch](http://dpaste.com/2V30GJA) to add this feature has the notable disadvantage of being unmaintained. I, personally, would prefer not to have a number of unmaintained third-party patches in my window manager as there might be an incompatible update one day (cf. `dwm`).

Thank you for considering it (if you do). :-)

**Comment by vyp** [comment]
https://github.com/lepisma/swm-gaps third-party but maintained

**Comment by dbjergaard** [comment]
I'm not opposed to integrating this, but since there's already a module filling the need I'm torn.  I'll reach out to the module owner and see what they think of having the code integrated.

**Comment by vyp** [comment]
:tada: https://github.com/stumpwm/stumpwm-contrib/commit/78509c5ec09f311b3bd4270839cff6ae548abd85

**Comment by dertuxmalwieder** [comment]
Awesome!
