### ISSUE TITLE
Undefined behaviour in ADD-FLOAT-WINDOW (floating-group.lisp)

### ISSUE THREAD

**Issue by PuercoPop** [stumpwm/stumpwm#379]
Currently the [code in](https://github.com/stumpwm/stumpwm/blob/master/floating-group.lisp#L132) accesses the slots of the instance it changed the class of through `float-window-align`.The results of doing so are defined. Although the code seems to work (for now).

>  This implies that a programmer must not use change-class inside a method if any methods for that generic function access any slots, or the results are undefined.

From The CLHS entry on [Change Class]( http://www.lispworks.com/documentation/HyperSpec/Body/f_chg_cl.htm)

**Comment by equwal** [comment]
This issue is six years old. For what it's worth, I don't think SBCL will ever change this behaviour. I would like to imagine the idea of ANSI CL StumpWM though.

**Comment by dmb2** [comment]
@PuercoPop If you'd like to close this go ahead... 

I'm not going to deal with CLHS undefined behavior issues.  If this changes meaningfully in SBCL we'll have to revisit, but right now if UB in CLHS works in SBCL for us, and that's all we support, then I'm happy.  We're getting away with the good hack.
