### ISSUE TITLE
When spawning a new xterm, the mode-line is showing incorrect focus information

### ISSUE THREAD

**Issue by Armael** [stumpwm/stumpwm#383]
### Steps to reproduce:
With the default configuration:
- enable the mode-line `C-t : mode-line`
- spawn a first xterm `C-t c`
- spawn a second xterm `C-t c`

At this stage, the mode-line information regarding which window is focused is incorrect: it highlights window 0 as the one focused, while it should be window 1. Focusing the next window (`C-t n`) focuses the other xterm, and refreshes the mode-line: it still highlights window 0 — which is correct this time.

**Comment by dbjergaard** [comment]
I can't reproduce this. I see a slight pause when the new term is made, and then the mode line is correctly updated.

**Comment by dbjergaard** [comment]
I reproduced this on a different system.  Can you provide your sbcl version?

**Comment by Armael** [comment]
Thank you for investigating this! I'm running SBCL 1.3.19.

**Comment by dbjergaard** [comment]
Fixed!

**Comment by Armael** [comment]
Awesome!
