### ISSUE TITLE
Stumpwm broken for me since 49fdf94f8db0cf154a2cb8b78504bb711f93ec5b

### ISSUE THREAD

**Issue by ghferrari** [stumpwm/stumpwm#390]
Hi David,

I've reverted back to commit 49fdf94f8db0cf154a2cb8b78504bb711f93ec5b this morning. Something in your 4 commits since then up to eb04f6913835979acdc5b95ff7743b675e8a2ba9 is preventing stumpwm from working properly. Using eb04f6913835979acdc5b95ff7743b675e8a2ba9, stumpwm loads but then fails to recognise any keyboard input.

All the best,

Geoff

**Comment by VanLaser** [comment]
I also use the latest StumpWM, in Arch Linux (64bit), through the AUR package 'stumpwm-git'. After the latest update, StumpWM just hangs, right at the end of its loading (maybe a conflict with one of the contrib modules?). In any case, by editing the PKGBUILD and specifying the above commit - that worked:

```
source = ('stumpwm::git+https://github.com/stumpwm/stumpwm#commit=49fdf94'
         ('stumpwm-contrib-git::git+https://github.com/stumpwm/stumpwm-contrib')
```

**Comment by dbjergaard** [comment]
I reverted master to 49fdf94, but I did it with reset --hard, so I think I blew away some commits.  The timer-refactor stuff I can fix, but I'm afraid I may have broken/reverted a recent PR.  I will do some digging. In the mean time, StumpWM should build and run from master now.

**Comment by stefanhusmann** [comment]
I confirm, that there were broken commits (similar behaviour than ghferrari described). Thanks for reverting.

**Comment by dbjergaard** [comment]
I blew away my commits for refactoring timers, but everything else looks good.  I'm gonna close this since master is working again.
