### ISSUE TITLE
System date doesnt change running SBCL date

### ISSUE THREAD

**Issue by dmh43** [stumpwm/stumpwm#393]
Since setting the date with `sudo date +%T -s "9:07:00"` does not update the current time of the running SBCL process, the `format` macro will keep returning the old system date. Accordingly, the `stumpwm:time` will continue to return the old time and date.

I've worked around this by swapping `C-a` for another command which queries `/usr/bin/timedatectl` instead of the running SBCL process.

**Comment by PuercoPop** [comment]
We could use `sb-posix` get the updated system time?

**Comment by dmh43** [comment]
Ah good call, looks like it does change. I'll see if I can find some free time this week to implement a fix

**Comment by dbjergaard** [comment]
can we write a wrapper for get-universal-time in wrappers.lisp that uses sb-posix:time?

**Comment by dmh43** [comment]
Looks like I didnt find the time that week :sweat_smile: Thanks for bringing this back to my attention. Hopefully I'll find some time in the next few weeks :)
