### ISSUE TITLE
First window of blank group does not show urgency

### ISSUE THREAD

**Issue by agarick** [stumpwm/stumpwm#395]
**problem:**

The urgent windows formatter (`%u` in the modeline) does not behave when the first window of a group is urgent.

**steps to reproduce:**

1. configure:
    - enable modeline at start
    - include `%u` (fmt-urgent-window-list) in modeline
    - have at least 2 groups
1. start stumpwm.
1. select another group using `gselect`.
1. start a terminal that supports urgency hints.
1. artificially provoke urgency (eg: `sleep 2 && echo boo`).
1. before the sleep finishes, quickly switch to the default/first group.
1. the modeline does not show the urgent window (ie. the terminal that is echoing "boo" in the other group).

**notes:**

- A second window (created in the same frame) is also unable to register urgency.
- If you create another frame, windows in that new frame will successfully register urgency.
    - Windows in the old frame are still unable to register urgency.
    - Deleting the new (or old) frame will render the window(s) of the remaining frame unable to register urgency.
- ~~Possibly related? https://github.com/stumpwm/stumpwm/issues/383~~ (edit: issue persists after 383)

I'd like to help more with debugging, but I'm still pretty new to common lisp and stumpwm.

Also, I hope this actually is a bug and that I'm not overlooking a design decision. In a multi-monitor setting, it could make sense for the other screen to not produce urgency.

**Comment by dbjergaard** [comment]
I will need some time to look into this, but I wanted to say this is perfect example of how to write a bug report! I will do my best to reproduce and fix the bug.

**Comment by agarick** [comment]
Whoops, finger must have slipped.

(@dbjergaard Thank you for the compliment and, of course, for maintaining this fantastic project.)

**Comment by agarick** [comment]
Hm, I'm also having trouble reproducing this right now. In contrast to what I wrote above, the terminal is not signaling urgency no matter where it is (in a single frame, in a second frame, focused, unfocused, etc.)

I copied the seturgent script from the above site, and tried `sleep 5 && ./seturgent`, using several terminals, including [st](https://st.suckless.org/), urxvt, and xterm.

`sleep 5 && echo boo` is behaving/failing likewise.

I'm pretty stumped... The config I used for testing is as follows:

```lisp
(grename "a")
(mapcar #'gnewbg '("b"))
(mapcar (lambda (x) (define-key *top-map* (kbd (car x)) (cdr x)))
        '(("s-u"           . "next-urgent")
          ("s-BackSpace"   . "vsplit")
          ("M-s-BackSpace" . "hsplit")
          ("s-Delete"      . "remove-split")
          ("s-,"           . "prev-in-frame")
          ("s-."           . "next-in-frame")
          ("s-1"   . "gselect a")
          ("s-2"   . "gselect b")
          ("M-s-1" . "gmove a")
          ("M-s-2" . "gmove b")
          ("s-h"   . "move-focus left")
          ("s-j"   . "move-focus down")
          ("s-k"   . "move-focus up")
          ("s-l"   . "move-focus right")
          ("M-s-h" . "move-window left")
          ("M-s-j" . "move-window down")
          ("M-s-k" . "move-window up")
          ("M-s-l" . "move-window right")
          ("s-t"   . "exec alacritty -e tmux")
          ("s-w"   . "exec google-chrome-beta")))
(setf *screen-mode-line-format* (list " %n : %v ^>(%u)"))
(toggle-mode-line (current-screen) (current-head))
```

**Comment by agarick** [comment]
Well, since neither of us can reproduce the behavior at the top, I'll close this issue. If anyone thinks otherwise, please repoen. Cheers.

(I also recently switched to GuixSD and stumpwm isn't working for me there, so further testing is not feasible on my side.)
