### ISSUE TITLE
Compiler chokes on FAST-COPY-PIXARRAY

### ISSUE THREAD

**Issue by kaiser-dg** [stumpwm/stumpwm#397]
Relevant logs:
`; compiling (DEFUN FAST-COPY-PIXARRAY ...)

; /home/kdg/.cache/common-lisp/sbcl-1.3.20-linux-x64/usr/share/common-lisp/source/clx/dependent-TMP.fasl written
; compilation finished in 0:00:00.210
While evaluating the form starting at line 33, column 0
  of #P"/home/kdg/stumpwm/stumpwm-1.0.0/load-stumpwm.lisp":
While evaluating the form starting at line 3, column 0
  of #P"/home/kdg/stumpwm/stumpwm-1.0.0/./make-image.lisp":

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1001996893}>:
  COMPILE-FILE-ERROR while compiling #<CLX-SOURCE-FILE "clx" "dependent">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CLX-SOURCE-FILE "clx" "dependent">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CLX-SOURCE-FILE "clx" "dependent">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [RETRY                        ] Retry EVAL of current toplevel form.
  5: [CONTINUE                     ] Ignore error and continue loading file "/home/kdg/stumpwm/stumpwm-1.0.0/load-stumpwm.lisp".
  6: [ABORT                        ] Abort loading file "/home/kdg/stumpwm/stumpwm-1.0.0/load-stumpwm.lisp".
  7:                                 Retry EVAL of current toplevel form.
  8:                                 Ignore error and continue loading file "/home/kdg/stumpwm/stumpwm-1.0.0/./make-image.lisp".
  9:                                 Abort loading file "/home/kdg/stumpwm/stumpwm-1.0.0/./make-image.lisp".
 10:                                 Ignore runtime option --load "./make-image.lisp".
 11:                                 Skip rest of --eval and --load options.
 12:                                 Skip to toplevel READ/EVAL/PRINT loop.
 13: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T NIL "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<CLX-SYSTEM::CLX-SOURCE-FILE "clx" "dependent">)))
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL
0] 
`
I am using SBCL 1.3.20 on Gentoo Linux AMD64. I am also using the latest (I believe) version of Quicklisp.
Sorry if I didn't give you much to go off but I'm not sure what you need.

**Comment by Harleqin** [comment]
Which version of CLX do you get there?  The one from Quicklisp or the one from Gentoo?  Do you have the Lisp overlay for Gentoo?

For me (SBCL 1.3.20 on Arch x86-64, Quicklisp 2017-08-30), it compiles without a hitch.  When I look at the source for FAST-COPY-PIXARRAY, it seems to be a no-op for SBCL (the generic COPY-PIXARRAY implementation from image.lisp is then used).

**Comment by kaiser-dg** [comment]
I do have the Lisp overlay enabled however I was trying to compile manually, in my home folder.
I am using the Gentoo CLX version 0.7.4-r1

**Comment by kaiser-dg** [comment]
OK, thanks. Uninstalling CLX and using the QL version instead seems to have worked.
