### ISSUE TITLE
Multiple heads shown on one monitor.

### ISSUE THREAD

**Issue by duikboot** [stumpwm/stumpwm#401]
Thanks for stumpwm, I really love it.

If I only want to use my external monitor, two heads appear on that monitor.
`xrandr --output HDMI-1 --mode 2560x1080 --pos 0x0 --rotate normal --output eDP-1 --off`

Also if I choose to use my laptop monitor on a position other than on the left side of the external monitor, the external monitor shows two heads.

Only if the external monitor is positioned on the right side, only one head is shown on that monitor.
`xrandr --output HDMI-1 --mode 2560x1080 --pos 1920x0 --rotate normal --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal`

Am I missing something obvious, or is this a bug in stumpwm.

SBCL 1.3.20
Stumpwm: v1.0.1-rc-6-gfeb2505 Compiled On Tue Oct 24 2017  9:11:07

![screenshot](https://user-images.githubusercontent.com/240139/32134344-e6f72890-bbeb-11e7-876c-83b6a273d451.png)

**Comment by Harleqin** [comment]
I don't know (not too well versed in these mechanisms either). I am not sure whether it is necessarily stumpwm that is to blame. Can you show the output of `xrandr -q`? Why do you need to specify `--rotate`?

Aside: I usually use `--left-of`, `--right-of` etc. to position the screens.

**Comment by duikboot** [comment]
Actually, I now think it's a bug in arandr, which I used to position my monitors.
I'm sorry I wasted your time.
