### ISSUE TITLE
There is no class named STUMPWM::STUMPWM-IDLE-TIMER-CHANNEL on startup

### ISSUE THREAD

**Issue by rvm521443** [stumpwm/stumpwm#410]
Stumpwm fails to load with SB-PCL:CLASS-NOT-FOUND-ERROR (see title).

SBCL version 1.4.2
Stumpwm version: current master.

Seems like #408 fixes it.

**Comment by PuercoPop** [comment]
@rvm521443 Yeah, #408 should have fixed this
