### ISSUE TITLE
visual-pull-from-windowlist issues

### ISSUE THREAD

**Issue by ralt** [stumpwm/stumpwm#411]
Hi,

visual-pull-from-windowlist has 2 issues I'm aware of:

- It uses an external hook, which is the only command doing that.
- It locks up if another command is started when the menu is showing up.

I already have some ideas to take care of these, and plan on taking care of them ASAP.

Unfortunately, being a father of young kids, "ASAP" is very variable for me, so I can't give any commitment as to when I'll be able to do it.

**Comment by Kyo91** [comment]
visual-pull-from-windowlist also appears to lock up the screen if the windowlist becomes empty after filtering. Call the command then type random characters until none of our windows match and the screen should lock up.

**Comment by ralt** [comment]
Fun... I would suggest reverting this feature until it is properly fixed. (Speaking as the author of it.)

**Comment by dbjergaard** [comment]
@ralt can you help me either fix or revert this?

**Comment by ralt** [comment]
@dbjergaard sure, you can revert this commit https://github.com/stumpwm/stumpwm/commit/8441235056fc29e6cbfadf1d9c2865197bf70496
