### ISSUE TITLE
export find-wm-state, add-wm-state, and remove-wm-state

### ISSUE THREAD

**Issue by jakecoble** [stumpwm/stumpwm#412]
I'm writing a module that adds additional window states so stumpwm can play nice with compton. Windows behind the top window show through when transparency is enabled, and it applies shadows to all windows in the stack. They can be hidden with a compton rule, but the compton rule needs to identify which windows are to be hidden.

Here is an example of the solution I'm trying to allow: https://wiki.archlinux.org/index.php/Compton#Tabbed_windows

**Comment by dbjergaard** [comment]
These are basically wrappers around xlib functions so there is little chance of the interfaces changing.  I've exported them in the latest commit.
