### ISSUE TITLE
How can I check the name is bonded to stumpwm command

### ISSUE THREAD

**Issue by kostafey** [stumpwm/stumpwm#415]
```lisp
(defcommand firefox () ()
  "run firefox"
  (run-or-raise "firefox" '(:class "Firefox"))) ;=> #S(COMMAND :NAME FIREFOX :CLASS T :ARGS NIL)

;; Ok, defined. But how can I find out it?
(command-p 'firefox) ;=> NIL
(command-p `firefox) ;=> NIL
(command-p "firefox") ;=> NIL
```

**Comment by PuercoPop** [comment]
Commands are just functions, if you want to find out where it is defined, you can use sbcl's introspection capabilities, ie. `(sb-introspect:find-definition-sources-by-name 'firefox :function)`. If you to find out what commands are defined, you can look into the `*command-hash*` variable

```lisp
(loop
  :for command-name :being :the :hash-keys :of stumpwm::*command-hash*
  :collect command-name)
```

Is that what you wanted to know?

**Comment by kostafey** [comment]
Thank you for the answer. If any command is a function why I can't check it via `(functionp 'firefox)`?
It is also possible to check it via `(all-commands)`. Is there some more straightforward solution?

**Comment by kostafey** [comment]
```lisp
(in-package stumpwm) ;=> #<PACKAGE "STUMPWM">
(functionp 'stumpwm::firefox) ;=> NIL
```

**Comment by PuercoPop** [comment]
Sorry I was mistaken, [`functionp`](http://www.lispworks.com/documentation/HyperSpec/Body/f_fnp.htm) if the *object* passed to it is a function object, not of is the *symbol* passed to be is bound in the function namespace. `fboundp` does the latter.

```lisp
CL-USER> (functionp 'stumpwm:dump-screen-to-file)
NIL
CL-USER> (functionp #'stumpwm:dump-screen-to-file)
T
CL-USER> (fboundp 'stumpwm:dump-screen-to-file)
T
```

If you don't want to worry about what package is a command defined in you can compare the symbol-names

```lisp
(defun commandp (command-name)
  (loop
    :for command :being :the :hash-keys :of stumpwm::*command-hash*
    :when (string= (symbol-name command-name)
                   (symbol-name command ))
      :return command))

(commandp 'dump-screen-to-file) ; => STUMPWM:DUMP-SCREEN-TO-FILE
```

**Comment by kostafey** [comment]
@PuercoPop, thank you very much! Why not add this `commandp` function to the Stumpwm API?

**Comment by PuercoPop** [comment]
@kostafey Glad I could help.

> Why not add this commandp function to the Stumpwm API?

For starters, it would be confusing with structure predicate function `command-p` that checks if the object is an instance of the command structure. Also the code above works under the assumption that no command names have the same symbol-name, which is not true for all cases.

Maybe it would be a good idea to mimick a command namespace using a package or [lisp-namespace](https://github.com/guicho271828/lisp-namespace) :thinking: ?

I'm curious, what were you trying to do that needed you to check if a command exists?
