### ISSUE TITLE
mapping notify on CLX

### ISSUE THREAD

**Issue by dkochmanski** [stumpwm/stumpwm#439]
If this is already handled in StumpWM then I'm sorry for the noise.

Please see problem reported here:

https://github.com/sharplispers/clx/issues/12

To invalidate cache handle `:mapping-notify` event like:

```
(when (eql event-key :mapping-notify)
    (return-from event-handler (xlib:mapping-notify display request 0 0)))
```

**Comment by dbjergaard** [comment]
Hi, here's the relevant lisp code for our project:
```lisp
(define-stump-event-handler :mapping-notify (request start count)
  ;; We could be a bit more intelligent about when to update the
  ;; modifier map, but I don't think it really matters.
  (xlib:mapping-notify *display* request start count)
  (update-modifier-map)
  (sync-keys))
```
The second two functions make sure that everything is synced up with the current keyboard map.

**Comment by TeMPOraL** [comment]
Is the current implementation confirmed to be valid, or is there still work to do on this issue?

**Comment by dkochmanski** [comment]
Alright, thank you.

@TeMPOraL yes, all works as expected.
