### ISSUE TITLE
Small command

### ISSUE THREAD

**Issue by ralt** [stumpwm/stumpwm#440]
Hi,

I have this small command in my stumpwmrc:

```lisp
(defcommand shell-output (command) ((:shell "/bin/sh -c "))
  (message "~a" (run-shell-command command t)))
```

It runs a shell command and displays the output.

Which I use all the time. It's just super useful.

Should I document it somewhere (e.g. wiki?) or make a PR or..nothing? Just thought it might be useful to other people.

Cheers,
Florian

**Comment by dbjergaard** [comment]
@ralt Thanks for the contribution! Its a nifty little function, but I don't think it rises to a PR.  I suggest documenting it on our community wiki here: https://github.com/stumpwm/stumpwm/wiki/TipsAndTricks

If you don't think the wiki is visible enough we can find a way to make that link more prominent.

**Comment by dbjergaard** [comment]
@ralt I'm going to close this, but feel free to follow up here if you document it on the wiki so we know where to find your trick!
