### ISSUE TITLE
Stumpwm fails to start when initially loaded by lightdm

### ISSUE THREAD

**Issue by sdilts** [stumpwm/stumpwm#443]
Upon restart, Stumpwm fails to start when the `lightdm` display manager is used. However, when it is manually started by logging into a tty, starting the X server with `xinit`, and then started in the subsequent Xterm window, it loads with no errors. If I then try to login using the display manager, stumpwm behaves perfectly across multiple login sessions (same user) until the computer is restarted.

This occurs even with an empty init file on the latest version.

**Comment by dbjergaard** [comment]
You'll have to post all details of how to reproduce your lightdm setup (including configuration files, etc).  Without it, I cannot even begin to diagnose or solve this issue.

**Comment by OrionRandD** [comment]
I recently had this problem.
I just reinstalled lightdm.
sudo apt install --reinstall lightdm* 
In case you use debian or any derivative
