### ISSUE TITLE
"balance-frames" should emulate balance-frames behavior in Emacs

### ISSUE THREAD

**Issue by gotwf** [stumpwm/stumpwm#459]
"balance-frames" should emulate balance-frames behavior in Emacs.

Stumpwm-1.0.0 does so.  Head does not. 

I submit this is a bug.

Peace-- o/

**Comment by Harleqin** [comment]
Please describe the behaviour that you see and the one that you expect.

**Comment by gotwf** [comment]
I did.  Please describe what is unclear.  PuercoPop delved into this a bit (see recent commit), but that still falls short.

Sigh... Oh, not every stumper uses Emacs these  days...  My bad... ;(

Well, I shall still presume stump devs have the ability to install and launch a basic emacs session.  From there:

1) C-x 3 <- splits frame vertically.  You should now have two frames, splitting half of the original space per each.

2) C-x 3 <- splits vertically yet again, only this time you have the left half divided into halves again, i.e. quarters of the original space.

3) Now... drumroll please... C-x + to "balance frames".  You should now see three, each equally occupying one third of the original space.

4) Now repeat same sequence as above with each of v1.0.0 and then head.  And ye shall be enlightened.  "balance-frames" does no longer balance frames.  But it used to.  Bisect code 'twixt v1.0.0 and head, eh?

**Comment by dbjergaard** [comment]
no need for emacs, this clearly doesn't work as expected.  Either that or I'm so used to emacs's behavior that its obvious to me what is expected...either way bug confirmed and I'll look into it.

**Comment by dbjergaard** [comment]
Fixed in latest commit!

**Comment by PuercoPop** [comment]
@dbjergaard If we just revert the commit the behaviour describe in 447 returns. We can introduce an extra call to balance frames to address 447 w/o introducing this regression. I admit it seems kinda of a hacky approach but serves as a stop gap. What do you think?

https://github.com/stumpwm/stumpwm/commit/9d41f09c09cc5130e72c5378241aef0affbca87a#diff-4576d6a1869074a91fd1368f290a9279R1014

**Comment by gotwf** [comment]
Mayhaps this should be reopened, as the behavior described in Issue #447 still plagues head?

**Comment by dbjergaard** [comment]
For now, the balance-frames issue is more important from a behavior standpoint.  The splice issue is more a behavioral problem, whereas the balance-frame command was explicitly broken.  For now I'll leave things as is, and if we can get balance-frames and #447 addressed I'll take it.

**Comment by jorams** [comment]
Just to add a little update to this: #481 implements a combination of Emacs-like `balance-frames` and a proper binary tree. So it fixes both this issue and #447.
