### ISSUE TITLE
cannot start with startx on DISPLAY != 0

### ISSUE THREAD

**Issue by tgbugs** [stumpwm/stumpwm#462]
I am encountering strange behavior when running stump on a display other than 0.
OS Gentoo. SBCL 1.4.7. stumpwm at 0e826e8dc3ec344355a70b2070d6c36fa1a5ae05. My `.xinit-stumpwm` looks like this
```bash
defaultserverargs="-dpi 96"
xmodmap ~/.Xmodmap
stumpwm
```
When I run `startx ~/.xinit-stumpwm` everything works normally, low cpu usage on all cores.
When I run `startx ~/.xinit-stumpwm -- :2.0` or any other number not equal to zero (with or without the decimal) the new x instance starts, but stump cannot find the server and hangs indefinitely.

To get around this I can run `xinit ~/.xinit-stumpwm -- :2.0` but then the x server process for display 0 runs at 50% cpu usage on a single core. This also occurs when I launch using `sbcl --load ~/opt/stump-debug.lisp` instead of `stumpwm` where the contents of `stump-debug.lisp` are
```lisp
;; -*-lisp-*-
(require :stumpwm)
(stumpwm:stumpwm ":2.0")  ; displays match
```

**Comment by PuercoPop** [comment]
@tgbugs Hi, thanks for submitting the bug report. I start StumpWM in `:1` when debugging so I was thinking it is related to not passing the display port as an argument to the  StumpWM executable. However both, `startx` and `xinit`, set the DISPLAY environment variable and you are testing that is the case in the last test case so it seems unlikely. Just in case could you try

```
DISPLAY=":2.0" startx ~/.xinit-stumpwm -- :2.0
```

Did previous versions of StumpWM worked fine? If so could you run git bisect to track down the offending commit?

**Comment by tgbugs** [comment]
You are correct about `startx` and `xinit` setting DISPLAY, I ran an echo check in my xinit, but also tested setting it explicitly like you suggest, and get the same behavior.

I just started using stump so don't have any known good versions. I will hunt through the tagged commits to see if I can find one that is working. One additional piece of information that I forgot to include (which may ultimately not be relevant) is the xorg-server version is 1.19.5-r2.

**Comment by tgbugs** [comment]
Ok, closing this as a non stumpwm bug. Tested against all other versions, same behavior, then tested by starting another fluxbox session not on 0 as well, same behavior. Looks like there is probably something up with some other part of X on my system. Thanks for your time!
