### ISSUE TITLE
*focus-group-hook* not called for move-window-to-group

### ISSUE THREAD

**Issue by toshism** [stumpwm/stumpwm#464]
I noticed when moving a window to a group the *focus-group-hook* does not seem to be called. I wonder if it would be possible to add this? I'm not a lisp programmer but perhaps something like this?

```
(defun move-window-to-group (window to-group)
  (let ((old-group (window-group window)))
    (labels ((really-move-window (window to-group)
               (unless (eq (window-group window) to-group)
                 (hide-window window)
                 ;; house keeping
                 (setf (group-windows (window-group window))
                       (remove window (group-windows (window-group window))))
                 (group-delete-window (window-group window) window)
                 (setf (window-group window) to-group
                       (window-number window) (find-free-window-number to-group))
                 (push window (group-windows to-group))
                 (xlib:change-property (window-xwin window) :_NET_WM_DESKTOP
                                       (list (netwm-group-id to-group))
                                       :cardinal 32)
                 (group-add-window to-group window))))
      ;; When a modal window is moved, all the windows it shadows must be moved
      ;; as well. When a shadowed window is moved, the modal shadowing it must
      ;; be moved.
      (cond
        ((window-modal-p window)
         (mapc (lambda (w)
                 (really-move-window w to-group))
               (append (list window) (shadows-of window))))
        ((modals-of window)
         (mapc (lambda (w)
                 (move-window-to-group w to-group))
               (modals-of window)))
        (t
         (really-move-window window to-group))))
    (run-hook-with-args *focus-group-hook* to-group old-group)))
```
If I'm not missing something and that is actually acceptable I can create a pull request or whatever.

Thanks!

*edit:* oh and also related, I noticed that defgeneric defined for group-suspend that does not seem to be used anymore?
in groups.lisp
```
(defgeneric group-suspend (group)
  (:documentation "When the group is no longer the current group, this
function is called."))
```

**Comment by TeMPOraL** [comment]
RE `*focus-group-hook`, I'm not sure it belongs here.

From the documentation:

>  -- Hook: *focus-group-hook*
>     A hook called whenever stumpwm switches groups.  It is called with
>     2 arguments: the current group and the last group.

This hook fires correctly when you're switching your view between groups. I suppose, if you need a hook for the process of moving windows between groups, you could add a new one (a hook is just a `defvar`).

**Comment by Harleqin** [comment]
@toshism How do you invoke the switch/move?

**Comment by toshism** [comment]
Ok, I see where I was mistaken now and this doesn't make sense. I had assumed `move-window-to-group` was also switching to the group, but I see now that is not true. 

It's actually `add-group` that was switching, but it has the `background` option which fixes my issue. (I'm basically just recreating i3wm style groups, creating a new group and moving a window to it)

Sorry for the noise and thanks.
