### ISSUE TITLE
Hooks for keyrelease/keyup/keydown

### ISSUE THREAD

**Issue by sjl** [stumpwm/stumpwm#468]
I've been trying to get https://github.com/alols/xcape working with Stumpwm, and had a few problems. 
 Context, from IRC:

```
16:54:54 <sjl> is anyone here using https://github.com/alols/xcape with stumpwm?
   I'm seeing some weird behavior that I think might be caused by something in
   the guts of stumpwm, any maybe someone can guide me toward where in the
   stumpwm code to look
16:55:47 <sjl> When I run xcape and type some keys, sometimes (but not always)
   the key release events it sees seem to lag behind by half a second or so.
16:56:11 <sjl> If I run xev in a separate stumpwm frame and type into *that*,
   then xcape suddenly begins seeing all the key release events immediately.
16:56:48 <sjl> If I run xcape on its own under gnome, it also sees everything
   perfectly.  So it seems like stumpwm might be buffering the key release
   events somehow, but not when xev is running...
16:57:03 <sjl> er, when xev is *focused*, not just running.
0:57:04 <PuercoPop> sjl: It is possible that there is an underlying cause
  between this issue There is https://github.com/stumpwm/stumpwm/issues/450 and
  the one you are reporting. What are using xcape for?
0:58:49 <PuercoPop> In theory you could port xscape to StumpWM? Maybe we could
  add a key-release-hook?
16:14:10 <sjl> PuercoPop: sorry, didn't see your response (about xcape/key
   release events) til now.  I'm not sure I see how those that issue you linked
   would be related, but I don't know much about the internals of stumpwm (yet)
16:15:00 <sjl> I'm trying to use xcape to map my capslock key to be ctrl when
   held down, but escape when pressed and released quickly.  similarly for
   shifts -- I want it to be shift when held down and parens when pressed and
   released
16:15:41 <sjl> I'd definitely be up for porting that functionality to stumpwm.
   But like you said, I think I'd need a key release hook to be able to do that.
```

If a `*key-release-hook*` existed I might be able to implement this myself directly in StumpWM, which would be nice.  Although I'm not 100% sure it would work, because what I want is the following:

1. When `ctrl` is first pressed, don't send anything to the current window, just mark a bit of state in StumpWM.
2. If `ctrl` is released within the timeout, send an `escape` keydown and keyup immediately to the current window.  In this case the window never sees `ctrl` at all.
3. Otherwise, if some *other* key is pressed with `ctrl` still held, send the `ctrl` keydown and the other key's keydowm+keyup, so it can act like a normal `ctrl` key.
4. Otherwise, if the timeout expires, send the `ctrl` keydown as normal.
5. All this should also work as expected (I haven't fully thought my way through this yet) with StumpWM bindings that involve `ctrl` and `escape` too.

Because `*key-press-hook*` only fires when for keys in `*top-map*` I think part 3 would be a problem. I'd need to put *every* key into `*top-map*`, which is obviously not ideal.  Or maybe I'm reading the documentation wrong.

Maybe it would be worth adding `*key-down-hook*` and `*key-up-hook*` that could get called for every raw keyup/keydown seen by StumpWM?  That would enable lots of low-level keypress hackery for stuff like this.

I'm happy to implement this if it's something you think you want, if someone can point me in the right direction to get started.  I'm new to StumpWM but have some Common Lisp experience.

Note: `ctrl` and `escape` are just one example.  I also want to do something similar for the left and right `shift` keys and parentheses.  That one is even trickier, because sometimes when I type a `()` or `)(` really fast I don't release the first shift key before the second, so I have a hack in my MacOS setup to account for "right shift pressed while left shift held" and vice versa.  It's messy, but it works well.  A low-level interface to the keys would let me do all my crazy mapping in my own `.stumpwmrc` and no one else ever has to look at the eldritch horrors inside.

**Comment by dbjergaard** [comment]
To summarize your expected behavior (and I guess describe what xscape does):
1. If a modifier is rapidly struck, it should send escape to the client window instead of the modifier
2. If the modifier is held down, the escape isn't sent, but the overal key-chord is

I'm a little leary of running a hook on every key-down and key-up event.  This is a lot of events and there could be performance implications.  I'm not fully opposed to extra hooks as long as:
1. They are well documented.
2. They don't decrease performance.

**Comment by sjl** [comment]
Yep, that's the expected behavior for ctrl and escape.  For shift and parens ideally I'd have more control so I can remap the "pressing right shift while holding left shift" event to produce `()`, in case my fingers aren't fast enough to release the left shift before the right one goes down.

**Comment by dbjergaard** [comment]
Go ahead and add these hooks, we can discuss performance implications in the PRs.
