### ISSUE TITLE
How to keep a (notification) window on top?

### ISSUE THREAD

**Issue by sjl** [stumpwm/stumpwm#469]
I'm using [dunst](https://dunst-project.org) to get notification popups (for things like IRC mentions, calendar events, etc).  It mostly works with StumpWM, with one problem.

The notifications appear in the top right frame (good), but if I focus that frame while the notification window is up, then whatever window is in that frame will raise on top of the notification window.  If more notifications come in before the others have gone away, they get put into that same notification window, which is now below the other window and so I can't see them.  Once the notifications have timed out (or I clear them) any new ones coming in will create a new window, and the whole cycle will start again.

Is there a way I can tell StumpWM to keep the dunst notification window on top of everything else no matter what?  Or alternatively, is there some other workflow for popup notifications that StumpWM users tend to use

**Comment by tpine** [comment]
Hi sjl,

I don't have the same requirements as notificaions as you do but you can use https://github.com/stumpwm/stumpwm-contrib/tree/master/util/notify as a native notification tray which you can configure into stump properly.

**Comment by sjl** [comment]
I've seen that extension, but it doesn't really do what I need because it uses `stumpwm:message` to show the actual notifications.  This isn't ideal because:

* The notifications show up in the same place as all messages, so they don't stand out at all (I might be able to hack this into the notify plugin by binding the gravity var though).
* Only one notification can be shown at once.  If I get a calendar notification about a meeting and then someone pings me on IRC immediately after, the calendar notification is lost before I can read it.
* Notifications get cleared away by any StumpWM action, which isn't ideal.  I don't want to lose a notification just because I happen to be in the middle of changing frames when it arrives.
* Notifications don't stick around when I'm idle.  dunst lets you say "don't close notifications if you've been idle for a minute or more", which is nice when you need to step away for a bit.

I thought about implementing something like dunst in StumpWM itself, but haven't had the time to really look into it much.  I was hoping I could get away with just using dunst and somehow telling stump to always keep it shown.

**Comment by dbjergaard** [comment]
Does `message-no-timeout` not do what you need?

**Comment by dbjergaard** [comment]
Sorry you might need toggle-always-on-top.  

Stumpwm messages are pretty ephemeral. You may find some luck in hacking in some history based on the lastmsg and its related code.

**Comment by sjl** [comment]
`toggle-always-on-top` sounds promising.  If I can force the dunst notification window to stay on top of things, that'll work.  I tried this:

```
(defun raise-notifications (win)
  (debug-log "new window: ~A~%" (window-class win))
  (when (string= (window-class win) "dunst")
    (debug-log "Forcing ~A window to always be on top of ~A group.~%" win group)
    (pushnew win (group-on-top-windows (current-group)))))

(add-hook *new-window-hook* 'raise-notifications)
```

But it doesn't work.  The hook never fires for the dunst notification window.  I also can't find the dunst window in `(group-windows (current-group))` or in `*always-show-windows*`.  Where could it be hiding?

**Comment by dbjergaard** [comment]
Dunst may not be allowing stumpwm to map the window, so it may not show up in stumpwm's window list.  You could try enumerating the windows from clx, and then toggle window hints flag to make it always on top.  I'm being sketchy because I don't know if it'll work or if its possible.

**Comment by dbjergaard** [comment]
Dunst is not exposing its window in a way that can be directly manipulated by stumpwm.  I couldn't figure out how to find it from clx/xlib either.  Getting to the bottom of this would require a deep dive into how dunst makes and manages the window notifications.  

Unfortunately I can't see anything that stumpwm can do to help.  Feel free to reopen if you have more information I can use to figure out the problem.  Also consider opening this issue with them since they'll have a better idea of the internals of how dunst displays it's notifications.

**Comment by goose121** [comment]
It seems like dunst uses the `_NET_WM_STATE_ABOVE` hint to show itself above the rest of the windows, which isn't listed as a supported hint in [primitives.lisp](https://github.com/stumpwm/stumpwm/blob/master/primitives.lisp). Perhaps implementing that hint would allow it to work properly?

**Comment by goose121** [comment]
I found a temporary solution based on using that hint which does indeed keep dunst's windows on top (as well as any other windows that set that hint; I'd submit a PR but for the fact that this seems really hacky and not like the correct way to do it)
```lisp
(defmethod raise-window :after (win)
  (flet ((window-above-p (win) (find-wm-state win :_NET_WM_STATE_ABOVE)))
    (unless (window-above-p (window-xwin win))
     (mapc
      (lambda (w) (setf (xlib:window-priority w) :above))
      (remove-if-not
       #'window-above-p
       (xlib:query-tree (screen-root (current-screen))))))))
```
