### ISSUE TITLE
load-module "ttf-fonts" throws error

### ISSUE THREAD

**Issue by LeftyAce** [stumpwm/stumpwm#472]
Hi all,
I'm trying to enable nicer looking fonts using the following code in my .stumpwmrc:

`(load-module "ttf-fonts")`
`(set-font (make-instance 'xft:font :family "Anonymous Pro" :subfamily "Regular" :size 13))`

But when I do :loadrc, I get an error:

`Error: Component #:CLX-TRUETYPE not found, required by #<SYSTEM "ttf-fonts">`

I checked (list-modules) and it shows "ttf-fonts" in the list.
I installed the clx-truetype package through Arch linux's AUR...maybe there's a more direct way to install it or to verify the installation?

Any idea what's wrong?

**Comment by sdilts** [comment]
You can verify whether or not stumpwm can see `clx-truetype` by evaluating some code. Open up the eval prompt using `Ctrl-t :`, then type in `(require 'clx-truetype)` and hit enter. If that doesn't throw an error, then clx-truetype can be seen by stumpwm. If not, try restarting stumpwm and report back.

**Comment by LeftyAce** [comment]
Thanks for the suggestions. I tried `(require 'clx-truetype)` and got a long error message starting with `Don't know how to require CLX-TRUETYPE`
This is true before and after restarting stumpwm (and rebooting for good measure).

**Comment by sdilts** [comment]
Did you compile stumpwm from source, or did you install it through a package manager? (Re)Compiling from source may fix the problem. There are instructions in the Readme on how to do this. 

Before doing that, fire up `sbcl` in the terminal and run the `require` command again. If it works, then recompiling should fix the problem.

**Comment by dbjergaard** [comment]
I can give a longer answer later but:
Recompile and install everything from source using quicklisp. This is the least painful path. 

If you want to keep things managed separate from quicklisp/git then install quicklisp to have it resolve dependencies. Install clx-TrueType. Then modify stumpwm to be aware of quicklisp either by copying the quicklisp install from .sbclrc or by updating asdf:*central-registry* to point to the installed dependencies. 

Good luck!

**Comment by LeftyAce** [comment]
Ok, I'm attempting to install from scratch following the readme here: https://github.com/stumpwm/stumpwm

I added a step after quicklisp quickload "alexandria" I also quickloaded clx-truetype.

The rest of the compile goes well and I get a runnable stumpwm binary. Now when I run 
`eval: (require 'clx-truetype) `
I get no error, just a message saying "Nil"

If I try to add ttf-fonts in my stumpwmrc, it still errors out.

I tried loading clx-truetype in sbcl:

```
* (require 'clx-truetype)
WARNING: System definition file #P"/home/owen/quicklisp/dists/quicklisp/software/clx-truetype-20160825-git/clx-truetype.asd" contains definition for system "clx-truetype-test". Please only define "clx-truetype" and secondary systems with a name starting with "clx-truetype/" (e.g. "clx-truetype/test") in that file.
WARNING: System definition file #P"/home/owen/quicklisp/dists/quicklisp/software/cl-fad-20180430-git/cl-fad.asd" contains definition for system "cl-fad-test". Please only define "cl-fad" and secondary systems with a name starting with "cl-fad/" (e.g. "cl-fad/test") in that file.
WARNING: System definition file #P"/usr/share/common-lisp/source/cl-store/cl-store.asd" contains definition for system "cl-store-tests". Please only define "cl-store" and secondary systems with a name starting with "cl-store/" (e.g. "cl-store/test") in that file.

("CL-STORE")
```
You mentioned copying the quicklisp install from .sbclrc, but all that's in .sbclrc is

```
;;; The following lines added by ql:add-to-init-file:
#-quicklisp
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"
                                       (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))

```

I apologize for the basic questions, but how do I get everything visible to stumpwm? Or, if it's easier, all I really want to do is have nice looking fonts on the modeline. Maybe clx-truetype isn't the best way to do this.

**Comment by LeftyAce** [comment]
Ok, if I add these lines to my .stumpwmrc (note single quote, not double quote before clx-truetype):
```
(ql:quickload "clx-truetype) 
(load-module 'ttf-fonts")
```

and then loadrc, I get an error saying:

```
Error: Could not load or find module: "ttf-fonts"
[RETRY] Retry EVAL of current toplevel form.
[CONTINUE] Ignore error and continue loading file "~/.stumpwmrc".
[ABORT] Abort loading file "~/.stumpwmrc".
[EVAL-COMMAND-ERROR] STUMPWM::EVAL-COMMAND-ERROR
[EVAL-COMMAND-ERROR] STUMPWM::EVAL-COMMAND-ERROR
[TOP-LEVEL] Return to stumpwm's top level
```

The (ql:quickload "clx-truetype) by itself does not cause an error. 

Can you help me figure out where stumpwm is looking for "ttf-fonts"?
Or maybe ttf fonts aren't the best way to do this. All I want is for my modeline not to look super pixellated.

**Comment by LeftyAce** [comment]
ps, here's a screenshot of my modeline (with ugly fonts), with firefox tabs visible underneath (fonts look fine):


![ss](https://user-images.githubusercontent.com/11865910/42413804-da22822e-81dc-11e8-8e75-f69be4923c96.png)

**Comment by LeftyAce** [comment]
Well, I apologize this is getting a bit disorganized, but I've installed the "xorg-fonts-misc" and now have slightly nicer looking modeline:

![ss](https://user-images.githubusercontent.com/11865910/42413847-f8049b64-81dd-11e8-91d2-d67688569f9f.png)

I would like to know how to control the font (type, size, spacing, etc) in the modeline. Maybe truetype fonts aren't the way to go, but is there an example somewhere of how to choose and assign a font?

**Comment by jorams** [comment]
> is there an example somewhere of how to choose and assign a font?

You can use `xfontsel` to browse through installed X fonts. It's a bit of an unfriendly program, but it works. The string you get out of that can be passed to `set-font` as normal. Note that `set-font` can also take a list of fonts as an argument, and you can select fonts from that list using `^f0`, `^f1`, etc.

As for your problem loading ttf-fonts, the easiest way to make it work is probably to load it using `ql:quickload`. Create a symlink to the `ttf-fonts.asd` file in `~/quicklisp/local-projects` and then put `(ql:quickload :ttf-fonts)` at the top of your .stumpwmrc, in place of the above calls to `ql:quickload` and `load-module`.
