### ISSUE TITLE
Stumpwm spontaneously freezes/hangs after several hours of use

### ISSUE THREAD

**Issue by T-recks** [stumpwm/stumpwm#474]
I've been encountering an issue where stumpwm suddenly becomes unresponsive in the middle of use. There is no common factor that's apparent except that it typically (perhaps always? I'm not sure but I don't recall any exceptions) happens after many hours of running.

What happens:
- All stumpwm keybindings in \*top-map\* stop working.
- I can still use whatever window is currently selected (e.g. emacs, web browser).
- Trying to close the window typically does not work correctly (the window becomes a blank white slate instead of fully closing).
- I go to another tty, run terminal emacs, and attempt to slime-connect on localhost port 4004 (where my init.lisp starts a swank server). I get a message in the mini-buffer saying something like "Connecting to localhost on 4004.." but slime does not connect and gives no feedback. The only thing that happens is that a *slime-events* buffer opens in the background containing about 3 lines of lisp (as opposed to the many lines it contains whenever slime successfully connects/starts).
- If I try "sudo kill -9 PID" on any child processes of stumpwm (e.g. emacs, web browser), the process typically becomes defunct. At this point I "pkill x" and start over.

Any advice on how to troubleshoot this? So far I've tried running stumpwm with a minimal .xinitrc that loads a couple things I need related to xorg (e.g. .xmodmap and .xresources) and runs stumpwm. I've also tried using stumpwm without having it run a swank server. I'm hoping for something other than "use a minimal  init.lisp" since I presently have no way to reproduce the issue and simply running stumpwm all day as normal without any configuration waiting for the possibility that it might crash is not a very attractive option. I suppose if that's the only option then I may try it...

**Comment by jorams** [comment]
It sounds a bit like SBCL may have encountered some kind of corruption. It will try to continue, but if that's not possible it can cause weird issues. It can also end up in LDB, the low-level debugger. The process may still be alive, so no other process will know that it's really gone, but there is really no way to recover. You should, however, still see some output on StumpWM's TTY, but I also know that X may scramble the terminal settings and thereby make some output disappear.

I would suggest the following:

- Run StumpWM as  `stumpwm --disable-ldb --lose-on-corruption`. If the above scenario occurs then, it will just exit. Note that these flags should come before any other command line arguments.
- Pipe all output to a file so that, even if X screws up the TTY settings, you can still see what got printed: `startx |& tee x.log` (or some equivalent)

Combining the two should help to get some information to debug.

You could also add `(setf *debug-level* 10)` to the top of your `.stumpwmrc` to get all of StumpWM's debugging output, but that prints a lot of stuff and if you're running for hours it might not help very much. I would only suggest doing so if the above doesn't provide any clues. (Also note that it contains stuff like window titles and message text.)

**Comment by T-recks** [comment]
Thanks! I will try what you suggested and see how it goes. It may be a while before I have any update or additional information given the circumstances...

**Comment by T-recks** [comment]
It seems you were right about the problem originating in SBCL. In the most recent crash, everything looks pretty normal until immediately before crashing:

`Heap exhausted during garbage collection: 832 bytes available, 7984 requested.
Gen  Boxed Unboxed   LgBox LgUnbox  Pin       Alloc     Waste        Trig      WP GCs Mem-age
fatal error encountered in SBCL pid 8422(tid 0x7ff89b171080):
GC invariant lost, file "gencgc.c", line 451


xinit: connection to X server lost

waiting for X server to shut down `

Followed by the usual info when X dies during use (fatal IO errors in running programs, etc.) before the server terminates and the log ends. 

How do you recommend I proceed?

**Comment by jorams** [comment]
Sorry for the late response, the email somehow slipped through the cracks.

I've looked through your config (on GitHub, not sure how up-to-date that is) and I don't see anything that would cause this. I don't suppose it prints a stacktrace? Increasing the SBCL memory limit should not be necessary, unless the default is somehow very low for you.

What version of SBCL are you using? And what version of StumpWM?

**Comment by szos** [comment]
I have the same issue, running stumpwm from git and sbcl 1.4.10. I'll try recompiling sbcl and stumpwm to see if anything changes, and to make sure threads are disabled in sbcl. And I'll report back.

**Comment by MasterCsquare** [comment]
i also have the same issue. maybe the qt5 program lead to this. some issue have mentioned that qt5 program is not work well in stumpwm. VLC and Qtox both are qt5 program. i'm trying to not open qt5 program at all to see if this happen. report later.

**Comment by T-recks** [comment]
@jorams Well, it looks like you're not the only one late to respond. :)
I to am running version stumpwm 18.05 cloned form git (dependencies installed via quicklisp). SBCL version 1.4.10. My up to date config is available [here](https://gitlab.com/T-recks/stumpwm.d).

The window manager has not crashed recently because I keep an eye on the memory usage and restart the x server when it's getting high. I'm pretty sure there was no stack trace in the x.log but I'll check again next time it happens. I seem to observe it happening sometime after the dynamic space usage reported by `(room nil)` exceeds 800,000,000 bytes. Running `(sb-ext:dynamic-space-size)` reports a memory limit of 1,073,741,824 bytes.

@szos Thanks for the additional info. I use qutebrowser as my primary browser. As far as I know that's dependant on qt5 too. Perhaps I will also try avoiding qt5 for a while and see if it makes a difference.

**Comment by MasterCsquare** [comment]
i have been running stumpwm without qt5 program for 4x24 hours. everything works fine. very robust, no freeze/hang. the gc also works as normal.

**Comment by MasterCsquare** [comment]
another 8 days, i found that it still freeze without qt5 program. SBCL version 1.4.10. every time it freezed. the memory is out of (sb-ext:dynamic-space-size).

**Comment by T-recks** [comment]
I also tried running without any qt5 programs and the dynamic space usage still grew strangely high.

Also @szos

> Additionally see that the global variable GC-INHIBIT is true. Is this preventing SBCL from entering GC?

I checked sb-kernel:*gc-inhibit* and it's set to nil for me. Apparently that variable is not the cause of the issue, unless we are experiencing different problems. Did you try setting it to nil?

**Comment by dbjergaard** [comment]
Stumpwm maps already open windows. It won’t restore them unless you get fancy with fdump and friends. I hope we can figure out the underlying problem though. 

    David

**Comment by noogie13** [comment]
Anyone found anyway to get around this? I really like StumpWM but this happens every few days and is quite infuriating...

**Comment by mohe2015** [comment]
I don't use StumpWM but did anybody test with the latest version of sbcl (1.5.0)?

**Comment by voobscout** [comment]
> I don't use StumpWM but did anybody test with the latest version of sbcl (1.5.0)?

Yes, I did test it and it's still the same bug, I switched to awesomewm because of it, what a pitty....

**Comment by MasterCsquare** [comment]
i have switched to clfswm about 3 months, which also written in lisp. i compiled it with sbcl and it never freeze. so i think it's not the compiler's problem.

**Comment by voobscout** [comment]
I would've payed money for someone to fix it... my lisp foo is not up to the task

**Comment by TeMPOraL** [comment]
Check if you're not using a TrueType font (via `(set-font (make-instance 'xft:font ...))` in your .stumpwmrc). I hit this problem just last week; the problem would occur after some time, the faster the more intensively I used my computer. The problem disappeared when I switched back to standard bitmap fonts.

I suspect StumpWM, possibly through clx-truetype, leaks memory every time it renders a piece of text with a TTF font.

(SBCL 1.5.0, StumpWM from QuickLisp)

**Comment by T-recks** [comment]
@TeMPOraL 

This sounds very promising, thanks for the info. I have been using a TrueType font for the past several months but I've switched to a bitmap font now and will report back with my results after a few days.

**Comment by PuercoPop** [comment]
fwit I use TTFs w/o experiencing any hangup. Although I tend to turn of my PC at the end of the day

**Comment by T-recks** [comment]
I changed the line `(set-font (make-instance 'xft:font :family "DejaVu Sans Mono" :subfamily "Book" :size 11))` in my config to `(set-font "-windows-dina-medium-r-normal--13-100-96-96-c-80-iso8859-1")` (a bitmap font) and the issue has disappeared for me too. The dynamic space usage peaks at a fraction of what it previously used to and I no longer experience heap exhausting after running stumpwm for several hours.

**Comment by lepisma** [comment]
I have been facing similar issues. The crashes come after I wake up the machine from sleep though. Haven't trying logging anything but preemptively changed the font to a bitmap one around 4-5 days back but still am facing the issue.

Will try logging and see if my issue is also related to heap exhaustion.

**Comment by jorams** [comment]
I've looked into this a bit more, and indeed clx-truetype leaks memory. More specifically, it caches calculated bounding boxes as well as alpha maps for strings, and keeps growing the caches indefinitely. After enough distinct strings have been rendered (or just had their rendered size calculated) you can run out of memory.

One hacky workaround is to clear all those caches every 15 minutes or so:

```lisp
(run-with-timer
 900 900
 (lambda ()
   (loop for font in (stumpwm::screen-fonts (current-screen))
         when (typep font 'xft:font)
           do (clrhash (xft::font-string-line-bboxes font))
              (clrhash (xft::font-string-line-alpha-maps font))
              (clrhash (xft::font-string-bboxes font))
              (clrhash (xft::font-string-alpha-maps font)))))
```

This should prevent the issue, assuming these caches are actually the cause of the crash.

**Comment by MasterCsquare** [comment]
this workaround works for me. the memory keep in a low usage, about 140m, far away from `(sb-ext:dynamic-space-size)`.

**Comment by ebzzry** [comment]
I don’t use TrueType fonts, yet I also experience crashing. Like @T-recks, I also use Qutebrowser. Should I use another window manager, or there are well-known fixes?

**Comment by w96k** [comment]
I have the same problem. I have two pcs, one is thinkpad x200t (core2duo, intel gpu) and custom pc (i5, intel gpu). I have almost similiar guix configs for both machines. 
Freezes happen only when modeline enabled. Stumpwm works just fine on thinkpad (with enabled modeline) & freezes on custom pc. I use on both pc's bitmap font called "terminus".

Thinkpad config: https://github.com/w96k/dotfiles/blob/master/config.scm
Custom pc config: https://github.com/w96k/dotfiles/blob/master/work.scm

**Comment by ebzzry** [comment]
After putting the following in my `~/.xsession`

    exec sbcl --dynamic-space-size 2048 --eval '(asdf:make :stumpwm)' --eval '(stumpwm:stumpwm)'

StumpWM no longer crashes.

**Comment by goose121** [comment]
I'm not exactly sure why this issue was closed, as of the two solutions given, one of them was said by the author to be a hack, and the other just delays the issue by giving sbcl more heap size for `clx-truetype` to eat.

**Comment by noogie13** [comment]
It's a hack, but it works. The problem is with `clx-truetype` not with StumpWM itself, also `clx-truetype` isn't a dependency, so you can run without it if you don't want XFT fonts.

Maybe someone could fix `clx-truetype` but it's quite abandoned, and was (is?) off the quicklisp dists.

**Comment by T-recks** [comment]
If left open this issue will become a catchall for anyone experiencing any problem causing Stumpwm to freeze/hang. I'd suggest perhaps starting a new issue specifically about the clx-truetype memory leak. People experiencing freezes due to issues unrelated to this clx-truetype bug should create or comment upon other issues.
