### ISSUE TITLE
run-or-raise program stills focus with window rule to prevent focus still

### ISSUE THREAD

**Issue by wigust** [stumpwm/stumpwm#475]
Hello.

If I open an Xterm or other program with window rule RAISE set to NIL (second argument of `define-frame-preference` which documented as “When non-nil, raise and focus the window in its frame”), then the program stills the focus in case the frame was empty but doesn't still if the frame was not empty.  I've recorded the behavior to make it more clear [1].

StumpWM config `.stumpwm.d/init.lisp`:
``` common-lisp
(in-package :stumpwm)

(setf *message-window-gravity* :center)
(setf *input-window-gravity* :center)

(set-prefix-key (kbd "C-r"))
```

StumpWM window rules:
``` common-lisp
(("Default" 1 NIL NIL :CLASS "XTerm"))
```
Is the described behaviour is intended or not?

- [1] [Demo GIF on Imgur](https://i.imgur.com/Hl2Y4PK.gifv)

Thanks,
Oleg.

**Comment by dbjergaard** [comment]
Confirmed, we'll look into this.  For the record:
```
 (define-frame-preference "Default" (1 nil nil :class "XTerm"))
```
Is enough to reproduce.

**Comment by wigust** [comment]
Hello @dbjergaard

First of all thank you for taking a look on this issue.

I think that the bug is inside `group-add-window` procedure of `tile-group.lisp` file.

```lisp
        ;; maybe show the window in its new frame
        (when (null (frame-window (window-frame window)))
          (really-raise-window window))
```

After commenting the code block above I see that both following rules work as I expect.

```lisp
(define-frame-preference "Default" (1 nil nil :class "XTerm")) ;; [1] 
(define-frame-preference "Default" (1 t nil :class "XTerm")) ;; [2]
```

My expectatins:

- with [1] focus will stay on a current frame.
- with [2] focus will switch to new window in existing frame either it has window.

**Comment by dbjergaard** [comment]
I've commented these lines and tried to test that it didn't break anything.  It looks good, so I'm calling this issue fixed.
