### ISSUE TITLE
Stumpwm won't start / goes back to login in ubuntu 16.04

### ISSUE THREAD

**Issue by stephanpdx** [stumpwm/stumpwm#478]
I'm not sure whether this is a problem with Stumpwm, but I could not get it to start after installing it in Ubuntu 16.04.  I always get redirected back to the login screen.  Stumpwm worked fine when I had ubuntu 14 and other window managers work properly in ubuntu 16 (openbox, xfce, etc), so I am wondering whether this is a Stumpwm specific issue. 

I followed this advice and removed .Xauthority: 
https://askubuntu.com/questions/367260/i-am-logged-out-immediately-after-logging-in#367304

Thanks for your help!

Stephan

**Comment by xsteve** [comment]
Please take a look, if there is a file named ~/.xsession-errors

It often gives a hint about what is going wrong...

**Comment by stephanpdx** [comment]
Thanks -- that file shows no errors, but the file .xsession-errors.old might have some valuable information.  Here is its content:


; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFUN INT32->CARD32
;     (DEFUN XLIB::INT32->CARD32 (XLIB::X)
;       (DECLARE (TYPE XLIB:INT32 XLIB::X))
;       (DECLARE (XLIB::CLX-VALUES XLIB:CARD32))
;       (DECLARE (OPTIMIZE (SPEED 3) (SAFETY 0) (DEBUG 1)))
;       (THE XLIB:CARD32 (LDB (BYTE 32 0) XLIB::X)))
; --> PROGN SB-IMPL::%DEFUN SB-IMPL::%DEFUN SB-INT:NAMED-LAMBDA 
; ==>
;   #'(SB-INT:NAMED-LAMBDA XLIB::INT32->CARD32
;         (XLIB::X)
;       (DECLARE (TYPE XLIB:INT32 XLIB::X))
;       (DECLARE (XLIB::CLX-VALUES XLIB:CARD32))
;       (DECLARE (OPTIMIZE (SPEED 3) (SAFETY 0) (DEBUG 1)))
;       (BLOCK XLIB::INT32->CARD32 (THE XLIB:CARD32 (LDB (BYTE 32 0) XLIB::X))))
; 
; note: doing unsigned word to integer coercion (cost 20) to "<return value>"

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFUN AREF-CARD32
;     (DEFUN XLIB::AREF-CARD32 (XLIB::A XLIB::I)
;       (DECLARE (TYPE XLIB::BUFFER-BYTES XLIB::A)
;                (TYPE XLIB:ARRAY-INDEX XLIB::I))
;       (DECLARE (XLIB::CLX-VALUES XLIB:CARD32))
;       (DECLARE (OPTIMIZE (SPEED 3) (SAFETY 0) (DEBUG 1)))
;       (THE XLIB:CARD32
;            (LOGIOR (THE XLIB:CARD32 (ASH # 24)) (THE XLIB:CARD29 (ASH # 16))
;                    (THE XLIB:CARD16 (ASH # 8))
;                    (THE XLIB:CARD8 (AREF XLIB::A #)))))
; --> PROGN SB-IMPL::%DEFUN SB-IMPL::%DEFUN SB-INT:NAMED-LAMBDA 
; ==>
;   #'(SB-INT:NAMED-LAMBDA XLIB::AREF-CARD32
;         (XLIB::A XLIB::I)
;       (DECLARE (TYPE XLIB::BUFFER-BYTES XLIB::A)
;                (TYPE XLIB:ARRAY-INDEX XLIB::I))
;       (DECLARE (XLIB::CLX-VALUES XLIB:CARD32))
;       (DECLARE (OPTIMIZE (SPEED 3) (SAFETY 0) (DEBUG 1)))
;       (BLOCK XLIB::AREF-CARD32
;         (THE XLIB:CARD32
;              (LOGIOR (THE XLIB:CARD32 #) (THE XLIB:CARD29 #)
;                      (THE XLIB:CARD16 #) (THE XLIB:CARD8 #)))))
; 
; note: doing unsigned word to integer coercion (cost 20) to "<return value>"

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFUN AREF-INT32
;     (DEFUN XLIB::AREF-INT32 (XLIB::A XLIB::I)
;       (DECLARE (TYPE XLIB::BUFFER-BYTES XLIB::A)
;                (TYPE XLIB:ARRAY-INDEX XLIB::I))
;       (DECLARE (XLIB::CLX-VALUES XLIB:INT32))
;       (DECLARE (OPTIMIZE (SPEED 3) (SAFETY 0) (DEBUG 1)))
;       (THE XLIB:INT32
;            (LOGIOR (THE XLIB:INT32 (ASH # 24)) (THE XLIB:CARD29 (ASH # 16))
;                    (THE XLIB:CARD16 (ASH # 8))
;                    (THE XLIB:CARD8 (AREF XLIB::A #)))))
; --> PROGN SB-IMPL::%DEFUN SB-IMPL::%DEFUN SB-INT:NAMED-LAMBDA 
; ==>
;   #'(SB-INT:NAMED-LAMBDA XLIB::AREF-INT32
;         (XLIB::A XLIB::I)
;       (DECLARE (TYPE XLIB::BUFFER-BYTES XLIB::A)
;                (TYPE XLIB:ARRAY-INDEX XLIB::I))
;       (DECLARE (XLIB::CLX-VALUES XLIB:INT32))
;       (DECLARE (OPTIMIZE (SPEED 3) (SAFETY 0) (DEBUG 1)))
;       (BLOCK XLIB::AREF-INT32
;         (THE XLIB:INT32
;              (LOGIOR (THE XLIB:INT32 #) (THE XLIB:CARD29 #) (THE XLIB:CARD16 #)
;                      (THE XLIB:CARD8 #)))))
; 
; note: doing signed word to integer coercion (cost 20) to "<return value>"

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFUN CARD16->RGB-VAL
;     (DEFUN XLIB::CARD16->RGB-VAL (XLIB::VALUE)
;       (DECLARE (TYPE XLIB:CARD16 XLIB::VALUE))
;       (DECLARE (XLIB::CLX-VALUES SHORT-FLOAT))
;       (DECLARE (OPTIMIZE (SPEED 3) (SAFETY 0) (DEBUG 1)))
;       (THE SHORT-FLOAT (* (THE XLIB:CARD16 XLIB::VALUE) 1.5259022e-5)))
; --> PROGN SB-IMPL::%DEFUN SB-IMPL::%DEFUN SB-INT:NAMED-LAMBDA 
; ==>
;   #'(SB-INT:NAMED-LAMBDA XLIB::CARD16->RGB-VAL
;         (XLIB::VALUE)
;       (DECLARE (TYPE XLIB:CARD16 XLIB::VALUE))
;       (DECLARE (XLIB::CLX-VALUES SHORT-FLOAT))
;       (DECLARE (OPTIMIZE (SPEED 3) (SAFETY 0) (DEBUG 1)))
;       (BLOCK XLIB::CARD16->RGB-VAL
;         (THE SHORT-FLOAT (* (THE XLIB:CARD16 XLIB::VALUE) 1.5259022e-5))))
; 
; note: doing float to pointer coercion (cost 13) to "<return value>"

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFUN INT16->RADIANS
;     (DEFUN XLIB::INT16->RADIANS (XLIB::VALUE)
;       (DECLARE (TYPE XLIB:INT16 XLIB::VALUE))
;       (DECLARE (XLIB::CLX-VALUES SHORT-FLOAT))
;       (DECLARE (OPTIMIZE (SPEED 3) (SAFETY 0) (DEBUG 1)))
;       (THE SHORT-FLOAT (* (THE XLIB:INT16 XLIB::VALUE) 2.727077e-4)))
; --> PROGN SB-IMPL::%DEFUN SB-IMPL::%DEFUN SB-INT:NAMED-LAMBDA 
; ==>
;   #'(SB-INT:NAMED-LAMBDA XLIB::INT16->RADIANS
;         (XLIB::VALUE)
;       (DECLARE (TYPE XLIB:INT16 XLIB::VALUE))
;       (DECLARE (XLIB::CLX-VALUES SHORT-FLOAT))
;       (DECLARE (OPTIMIZE (SPEED 3) (SAFETY 0) (DEBUG 1)))
;       (BLOCK XLIB::INT16->RADIANS
;         (THE SHORT-FLOAT (* (THE XLIB:INT16 XLIB::VALUE) 2.727077e-4))))
; 
; note: doing float to pointer coercion (cost 13) to "<return value>"

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFMACRO HOLDING-LOCK
;     (DEFMACRO XLIB::HOLDING-LOCK
;               (
;                (XLIB::LOCK
;                 XLIB:DISPLAY
;                 &OPTIONAL
;                 (XLIB::WHOSTATE "CLX wait")
;                 &KEY
;                 XLIB::TIMEOUT)
;                &BODY XLIB::BODY)
;       (DECLARE (IGNORE XLIB:DISPLAY XLIB::WHOSTATE))
;       (IF XLIB::TIMEOUT
;           `(IF ,XLIB::TIMEOUT
;                (HANDLER-CASE
;                 (WITH-TIMEOUT ,XLIB::TIMEOUT
;                   #)
;                 (TIMEOUT NIL NIL))
;                (SB-THREAD:WITH-RECURSIVE-LOCK (,XLIB::LOCK)
;                  ,@XLIB::BODY))
;           `(SB-THREAD:WITH-RECURSIVE-LOCK (,XLIB::LOCK)
;              ,@XLIB::BODY)))
; 
; caught STYLE-WARNING:
;   &OPTIONAL and &KEY found in the same lambda list: (LOCK DISPLAY &OPTIONAL
;                                                      (WHOSTATE "CLX wait") &KEY
;                                                      TIMEOUT)

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFMACRO WITHOUT-INTERRUPTS
;     (DEFMACRO XLIB::WITHOUT-INTERRUPTS (&BODY XLIB::BODY)
;       `(SB-THREAD:WITH-RECURSIVE-LOCK (XLIB::*WITHOUT-INTERRUPTS-SIC-LOCK*)
;          ,@XLIB::BODY))
; --> PROGN 
; ==>
;   (EVAL-WHEN (:COMPILE-TOPLEVEL)
;     (SB-C::%COMPILER-DEFMACRO :MACRO-FUNCTION 'XLIB::WITHOUT-INTERRUPTS T))
; 
; caught STYLE-WARNING:
;   Duplicate definition for WITHOUT-INTERRUPTS found in  one file.

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFUN BUFFER-READ-DEFAULT
;     (SB-SYS:READ-N-BYTES (XLIB::DISPLAY-INPUT-STREAM XLIB:DISPLAY) VECTOR
;                          XLIB::START (- XLIB::END XLIB::START))
; --> BLOCK IF LET* SB-IMPL::EOF-OR-LOSE IF AND IF AND THE 
; ==>
;   (< SB-IMPL::READ-END SB-IMPL::END)
; 
; note: unable to
;   open-code FLOAT to RATIONAL comparison
; due to type uncertainty:
;   The first argument is a REAL, not a FLOAT.
; 
; note: forced to do GENERIC-< (cost 10)
;       unable to do inline fixnum comparison (cost 4) because:
;       The first argument is a REAL, not a FIXNUM.
;       The second argument is a (INTEGER -536870909 1073741818), not a FIXNUM.

; --> BLOCK IF LET* 
; ==>
;   (STREAM-READ-SEQUENCE STREAM SB-IMPL::BUFFER SB-IMPL::START SB-IMPL::END)
; 
; note: doing signed word to integer coercion (cost 20) from SB-IMPL::END

; --> BLOCK IF LET* SB-IMPL::EOF-OR-LOSE IF AND IF AND THE 
; ==>
;   (< SB-IMPL::READ-END SB-IMPL::END)
; 
; note: doing signed word to integer coercion (cost 20), for:
;       the second argument of GENERIC-<

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFMACRO READ-IMAGE-LOAD-BYTE
;     (- 7 POSITION)
; ==>
;   POSITION
; 
; note: deleting unreachable code

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFMACRO READ-IMAGE-ASSEMBLE-BYTES
;     (REVERSE XLIB::BYTES)
; ==>
;   XLIB::BYTES
; 
; note: deleting unreachable code

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFMACRO WRITE-IMAGE-LOAD-BYTE
;     (- XLIB::INTEGER-SIZE 8 POSITION)
; --> - - 
; ==>
;   XLIB::INTEGER-SIZE
; 
; note: deleting unreachable code

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFMACRO WRITE-IMAGE-ASSEMBLE-BYTES
;     (REVERSE XLIB::BYTES)
; ==>
;   XLIB::BYTES
; 
; note: deleting unreachable code

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFUN FAST-READ-PIXARRAY
;     (XLIB::READ-PIXARRAY-INTERNAL XLIB::BBUF XLIB::BOFFSET XLIB:PIXARRAY XLIB::X
;      XLIB::Y XLIB::WIDTH XLIB::HEIGHT XLIB::PADDED-BYTES-PER-LINE
;      XLIB::BITS-PER-PIXEL FUNCTION XLIB::UNIT ...)
; ==>
;   XLIB::BBUF
; 
; note: deleting unreachable code

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFUN FAST-WRITE-PIXARRAY-USING-BITBLT
;     (ARRAY-DIMENSION XLIB:PIXARRAY 1)
; 
; note: unable to
;   optimize
; because:
;   The array dimensions are unknown; must call ARRAY-DIMENSION at runtime.

; file: /usr/share/common-lisp/source/clx/dependent.lisp
; in: DEFUN FAST-WRITE-PIXARRAY
;     (XLIB::WRITE-PIXARRAY-INTERNAL XLIB::BBUF XLIB::BOFFSET XLIB:PIXARRAY XLIB::X
;      XLIB::Y XLIB::WIDTH XLIB::HEIGHT XLIB::PADDED-BYTES-PER-LINE
;      XLIB::BITS-PER-PIXEL FUNCTION XLIB::+IMAGE-UNIT+ ...)
; ==>
;   XLIB::BBUF
; 
; note: deleting unreachable code
While evaluating the form starting at line 28, column 0
  of #P"/usr/lib/stumpwm/load.lisp":

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {B3A37B1}>:
  COMPILE-FILE-ERROR while compiling #<CLX-SOURCE-FILE "clx" "dependent">
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 2 STYLE-WARNING conditions
;   printed 16 notes
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 20 requests (20 known processed) with 0 events remaining.


Does that give you an idea what's going on? 

Thank you so much,

Stephan

**Comment by PuercoPop** [comment]
@stephanpdx From the location of the CLX library in your system I'm guession you installed CLX from apt-get? If so don't do that, in general in debian based distros (including ubuntu) the versions of the shipped software are old and StumpWM doesn't work with them. You need to install the dependencies using quicklisp https://www.quicklisp.org/beta/.

**Comment by stephanpdx** [comment]
Thanks, Javier!

I de-installed stumpwm, then followed the README.md file to install stumpwm via github and the dependencies via
quicklist, and it works now.


It might be useful to add some disclaimer to the README file.  In the section "Build & Start Stumpwm", it reads:

Prerequisites

    - sbcl
    - quicklisp (for obtaining the following dependencies, not needed if you use your distribution's package manager.)
    - clx
    - cl-ppcre
    - alexandria


I read this and assumed that dependencies are taken care of by Ubuntu's distro manager, but that was apparently not the
case.  So, adding something like "In Ubuntu 16.04, the distribution's stumpwm package currently does not install the
correct dependencies." would be useful.


Thank you for making my day!  I cannot say enough about how much I like stumpwm.


Best,


      Stephan






Javier Olaechea writes:

> @stephanpdx From the location of the CLX library in your system I'm guession you installed CLX from apt-get? If so don't
> do that, in general in debian based distros (including ubuntu) the versions of the shipped software are old and StumpWM
> doesn't work with them. You need to install the dependencies using quicklisp https://www.quicklisp.org/beta/.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
Stephan Lindner, Ph.D.
Research Assistant Professor, OHSU Center for Health Systems Effectiveness (CHSE)
Research Assistant Professor, OHSU-PSU School of Public Health
3030 SW Moody, Portland OR 97201
Phone: (503) 418-2533 | Email: lindners@ohsu.edu<mailto:lindners@ohsu.edu>
