### ISSUE TITLE
How can I wipe out the root-map?

### ISSUE THREAD

**Issue by waisbrot** [stumpwm/stumpwm#480]
I'd like to make `*root-map*` from scratch (I want to remove a bunch of commands that I rarely/never use and I want to change some others to their more-verbose command names, like `remove-split` instead of `remove` so that the menu help is clearer).

However, I find that I can `undefine-key` some of the items but not all:

```
(undefine-key *root-map* (kbd "c"))
```

works as expected but

```
(undefine-key *root-map* (kbd "C-p"))
```

doesn't appear to change anything.

What's the correct way to remove this binding?

**Comment by PuercoPop** [comment]
You can acomplish that with `(setf stumpwm:*root-map* (stumpwm:make-sparse-keymap))`

**Comment by waisbrot** [comment]
Thanks for the reply, @PuercoPop, but I tried that. I can see that `stumpwm:*root-map*` has a value of `#S(STUMPWM::KMAP :BINDINGS NIL)`

Despite that, typing `<prefix> ?` shows a non-empty map and the bindings there are active. I can add a bunch of bindings myself, and they'll show up. Then, if I try to wipe the root map I see all of my bindings go away but the map shown by `<prefix> ?` still contains a bunch of entries.

![stumpwm](https://user-images.githubusercontent.com/1170218/43046478-6f9b4758-8d97-11e8-850f-dcf968a91650.png)

**Comment by jorams** [comment]
@waisbrot The reason for that is that `*root-map*` is not the only keymap active when you press the prefix key. It also activates `*group-root-map*` and, depending on the active group, `*tile-group-root-map*` or `*float-group-root-map*`. Clearing those as well leaves you without any prefix key bindings.

**Comment by waisbrot** [comment]
That's what I was missing. Thank you!
