### ISSUE TITLE
Removing frames does not behave like Emacs

### ISSUE THREAD

**Issue by scottjad** [stumpwm/stumpwm#489]
Emacs: C-x 2, C-x 2, C-x o, C-x o, C-x 0
Description: Open emacs. Create two splits, go to the bottom window (the largest), remove it.
Result: 1) the bottom window is selected 2) the bottom window has 75% of the space.

Stumpwm: C-t s, C-t s, C-t o, C-t o, C-t R
Result: This differs from Emacs in that 1) the top frame is selected instead of the bottom and 2) the two frames are of equal size.

This doesn't appear to be a recent change.

Ratpoison behaves like Emacs with regard to (2) but not (1).

**Comment by scottjad** [comment]
@dbjergaard I agree it's unclear whether matching emacs behavior is right, since screen is also an influence. Interestingly splitting behaves like emacs (and not screen), but unsplitting behaves like screen (and not emacs).

Perhaps the ideal would be to have an option where one can choose whether to have emacs or screen behavior, or choose separately for each action (splitting and unsplitting).

**Comment by thomasatkinson95** [comment]
I think in this case while we are inspired by both Screen and Emacs following Emacs at least as a default would be the least surprising for users since it follows the comparisons and integrations we have with Emacs.

**Comment by equwal** [comment]
I don't see how this is an issue at all. Stump provides a border so you can see which window gets focused, and there is nothing non-intuitive about it.

Without deliberately opening up emacs to check, how could you remember which way it goes?
