### ISSUE TITLE
Can't start StumpWM. SB-BSD-SOCKETS:SOCKET-ERROR

### ISSUE THREAD

**Issue by aricav96** [stumpwm/stumpwm#493]
I have followed the instructions in the README to install stumpwm (i.e. installed quicklisp and used it for the dependencies, and used make), but I can't get it to start. Here are some details:

I'm running Debian 9 and have SBCL 1.4.10. I start X via TDM (https://github.com/dopsi/console-tdm). When trying to run stumpwm via TDM, it just skips to i3. When trying from bash in a tty, sbcl shows the following error:

`debugger invoked on a SB-BSD-SOCKETS:SOCKET-ERROR in thread
 #<THREAD "main thread" RUNNING {10005A85B3}>:
    Socket error in "connect": 2 (No such file or directory)

...

(SB-BSD-SOCKETS:SOCKET-ERROR "connect" 2)
  error finding frame source: Bogus form-number: the source file has probably changed too much to cope with

  source: NIL` 

Could it be related to SBCL_HOME? I'm pretty new to Lisp, so I apologize if it's something obvious.

**Comment by dbjergaard** [comment]
Are you running swank?

Also, you say  "When trying from bash in a tty, sbcl shows the following error" Does this mean that if you type 'sbcl' at the command line you get this error? If so, this is not a stumpwm problem...

**Comment by aricav96** [comment]
Hello (sorry for taking so long to reply; I've been _really_ busy)

First off, sbcl is not the problem. What I meant by that is that I tried running the stumpwm binary from i3, failed (because i3 was running) and decided to try and run it from the tty (i.e. no X). Having said that, I think it makes sense that swank (or its absence anyways) is the culprit, due to the nature of the error (sockets and so on).

I assumed that installing SLIME would somehow do the trick. But it didn't change anything. If you'd excuse my ignorance, how exactly do I go about running swank outside of Emacs?

**Comment by aricav96** [comment]
First of all, thanks for your replies and your goodwill. I am very excited to use stumpwm and to be honest, I find these kinds of bumps on the road a given (so I'm not getting discouraged) c: 

Having said that, you hit the nail right on the head! Yesterday I thought about testing different ways to run stumpwm by skipping TDM altogether and it worked. It even works if I try startx on the tty. I just didn't have the time to report back here because it was pretty late. I even went as far as trying lightdm and surely enough it worked. I'm still not sure why it doesn't work (gotta check how TDM is starting X; after all, I can start i3 by using TDM), but I'm sure it's not a problem with stumpwm, so I'm closing the issue. Thanks again for your time.
