### ISSUE TITLE
Some windows (e.g. IntelliJ) do not unfocus properly

### ISSUE THREAD

**Issue by scottjad** [stumpwm/stumpwm#494]
When switching from IntelliJ to another window, the focus will remain with IntelliJ sometimes. I'm not sure what the pattern is, it's not 100% of the time, but it's maybe 80% of the time.

I'm guessing this applies to all Jetbrains IDEs, and potentially many Swing apps, and maybe other types of apps too.

@kriyative I believe this bug was introduced with this commit:
3224e57 Apply with-focus only for keys bound to keymaps

https://github.com/stumpwm/stumpwm/pull/467/commits/3224e5752ccf7201fa99b98e8b1104e2c407f49d

I do not experience the bug with the commit before it, 8f1ef80.

**Comment by kriyative** [comment]
@scottjad - thanks for letting me know. I'll try to reproduce the issue and debug further this weekend.

**Comment by kriyative** [comment]
@scottjad - I have been unable to reproduce the behavior you are experiencing. I'm not an IntelliJ  user, so I have only have a minimal setup - but I did try with `Windowed Mode` and `Floating Mode`, and focus changes worked as expected in both modes.

The only weirdness I saw was that when a menu-bar menu is open, IntelliJ refuses to relinquish focus (i.e., `C-t o` seems to do nothing).

I realize the issue is intermittent on your end, but if you can let me know the (more or less) exact sequence of actions which lead up to the focus issue, that might help me reproduce it locally.

**Comment by scottjad** [comment]
@kriyative Thanks for looking into this. Sorry for not giving better instructions before, I thought it would be easier to reproduce but I'm seeing now that it only manifests when using keybindings in `*top-map*` (which I use primarily in my config).

If I have IntelliJ in a normal tile group with a single frame, and the other window in that frame is an xterm, if I repeat `next` (`C-t n` by default) multiple times then everything works fine. If I bind it to `F1` with`(define-key *top-map* (kbd "F1") "next")` and repeat `F1` then after one or two times the xterm is will be on top but not have focus. For me I can tell that's the case because input will not appear in the window, the block cursor will just be an outline and `M-f` will bring up the File menu of IntelliJ.

I can reproduce this using `next`, `next-in-frame`, and `move-focus` from bindings in the `*top-map*`.

`F1` is not special, the same thing happens for `s-n`.

I am using IntelliJ 2018.2 and OpenJDK 1.8 (bundled with IntelliJ).

**Comment by kriyative** [comment]
@scottjad - perfect, I was able to reproduce the behavior with your instructions. I was also able to confirm that this only happens in IntelliJ (at least out of all the apps I seem to run) - and the behavior seems to be something like this:
- Assuming there are three frames on screen - IntelliJ, Emacs, and Chrome - and IntelliJ is currently selected
- press `F2` to switch from IntelliJ to Emacs - this works as expected
- press `F1` to switch back to IntelliJ - this also works as expected
- pressing `F2` again now, stumpwm reports Emacs as the current frame, however focus has not switched
- if I press `F3` (for Chrome) the frame is selected *and* focus changes as expected

I will try and narrow this down further today and try to push a PR

**Comment by kriyative** [comment]
@scottjad - sorry it took a while, but finally got the remap-keys issue with the focus change sorted out - have added a PR (https://github.com/stumpwm/stumpwm/pull/523). Please give it a try and let me know if it works out for you. Thanks.

**Comment by scottjad** [comment]
@kriyative - I've tried it and it appears to work great for me. Thank you for all your work resolving this, I really appreciate it.

**Comment by kriyative** [comment]
@scottjad - that's great. Thanks.
