### ISSUE TITLE
Undefined condition KBD-PARSE

### ISSUE THREAD

**Issue by szos** [stumpwm/stumpwm#497]
There seems to be an undefined condition called kbd-parse, which crashes StumpWM when sending an invalid string to the function kbd. My current work around is to define a condition in my stumpwmrc, but I'd imagine if something is signalling a condition its supposed to be handled by some function higher up the stack.

My current work around in use: 
```
(define-condition kbd-parse ()
  ((text :initarg :text :reader text)))

(defun kbd? (string)
  "takes a string and returns the result of calling {kbd} 
with string, or if it isnt valid return nil."
  (handler-case (kbd string)
	(kbd-parse-error () nil)
	(kbd-parse () nil)))```

**Comment by jorams** [comment]
This is a known issue, see #479. As a result of that #484 was opened, but not merging #479 does mean this error remains. Closing this in favor of #484.
