### ISSUE TITLE
retaining echoed messages 

### ISSUE THREAD

**Issue by erjoalgo** [stumpwm/stumpwm#499]
In my own setup, I made a small enhancement to `echo-string-list` to support providing a macro that retains all messages echoed within a form body:

```lisp
(with-retained-messages t
           (echo "this")
           (echo "message")
           (echo "is")
           (echo "retained"))
```

This allows me to compose commands that echo something to the screen without losing previous messages, and I also found it useful for debugging hooks and events that may fire from various places.

![demo](https://user-images.githubusercontent.com/5349288/44942304-e7abdb00-ad62-11e8-8c72-254a37f23c16.png)

Would it be worth adding this to the main branch? Below is a preview of the patch as I have it now. 

```diff
diff --git a/message-window.lisp b/message-window.lisp
index 1ea7311..60ce3a6 100644
--- a/message-window.lisp
+++ b/message-window.lisp
@@ -27,7 +27,8 @@
 (export '(echo-string
           err
           message
-          gravity-coords))
+          gravity-coords
+          with-retained-messages))
 
 (defun max-width (font l)
   "Return the width of the longest string in L using FONT."
@@ -212,10 +213,39 @@ function expects to be wrapped in a with-state for win."
   (let ((*record-last-msg-override* t))
     (apply 'echo-string-list screen (nth n (screen-last-msg screen)) (nth n (screen-last-msg-highlights screen)))))
 
+(defvar *retain-messages-p* nil
+  "When non-nil, retain old messages in addition to new ones.
+When the value is :log-order, new messages are added to the bottom as in a log file.")
+
+(defmacro with-retained-messages (log-order-p &body body)
+  "Retain all messages sent by (message ...), (echo ...) forms within body
+ without clearing the screen."
+  `(progn
+     ;; clear current messages if not retaining
+     (unless *retain-messages-p*
+       (setf (screen-current-msg (current-screen)) nil
+             (screen-current-msg-highlights (current-screen)) nil))
+     (let ((*retain-messages-p* ,(if log-order-p :log-order t)))
+       ,@body)))
+
 (defun echo-string-list (screen strings &rest highlights)
   "Draw each string in l in the screen's message window. HIGHLIGHT is
   the nth entry to highlight."
   (when strings
+    (when *retain-messages-p*
+      (let (top top-high bot bot-high)
+        (if (eq *retain-messages-p* :log-order)
+            ;; new messages added to the bottom, like a log file
+            (setf top (screen-current-msg screen) top-high (screen-current-msg-highlights screen)
+                  bot strings  bot-high highlights)
+            ;; new messages at the top
+            (setf top strings top-high highlights
+                  bot (screen-current-msg screen) bot-high (screen-current-msg-highlights screen)))
+        (setf strings (append top bot)
+              highlights (append top-high
+                                 (loop for idx in bot-high
+                                       with offset = (length top)
+                                       collect (+ idx offset))))))
     (unless *executing-stumpwm-command*
       (multiple-value-bind (width height)
           (rendered-size strings (screen-message-cc screen))
```

**Comment by dbjergaard** [comment]
we can merge this, especially since I think it will help with users who want more persistent notifications as in #469.

Please make sure that you add the documentation to this to the manual in your PR. 

Am I correct that the point of this is to toggle queuing the messages as they come in from various events rather than clobbering them? If not, does it make more sense to have a separate function called retain-echo-string-list which does the new behavior and echo-string-list keeps the old behavior?

**Comment by erjoalgo** [comment]
> Am I correct that the point of this is to toggle queuing the messages as they come in from various events rather than clobbering them? 

Yes. The goal is to temporarily suppress the clobbering behavior of messages echoed within a given form via calls to `echo-string, echo, message, echo-string-list` or anything that may build on top of those. Whether queuing is on/off can be controlled dynamically via a special variable, so a given function or form may either queue or clobber messages based on the special binding.

Since the goal is to change the behavior of existing `echo-string-list` invocations within a form, I don't know if this could be achieved by adding a new separate function since callers would still be using `echo-string-list`, unless `echo-string-list` could be temporarily redefined into `retain-echo-string-list`.

By default I expected `*retain-messages-p*` should be off, and I see it as a internal variable needed to implement the `with-retained-messages` macro rather than as a user option in itself. So maybe the special variable should not be documented, or have a caveat that points the user to the macro instead.
