### ISSUE TITLE
Reorganize miscellaneous portion of manual

### ISSUE THREAD

**Issue by dmb2** [stumpwm/stumpwm#501]
The miscellaneous section of the manual contains a dump of undocumented symbols.  They should be re-organized to the appropriate parts of the manual to make the information more easily accessible.

**Comment by soybarbanegra** [comment]
Hello, I would like to work on this. How do you think I should I organize them? Should I work directly on the texi file?

**Comment by dbjergaard** [comment]
Work on stumpwm.texi.in, you'll have to read a bit to figure out how stumpwm.texi and stumpwm.info are generated.  As far as organization: however you feel the ideas fit together is better than having the symbols dumped in the  bottom of the manual with no organization.

**Comment by equwal** [comment]
I'm currently working on this.

**Comment by equwal** [comment]
Fixed https://github.com/stumpwm/stumpwm/pull/672

**Comment by dmb2** [comment]
If this is fully addressed close the issue.

**Comment by equwal** [comment]
> If this is fully addressed close the issue.

I can't do that.
