### ISSUE TITLE
Clicking on a :hover element in browser hides it

### ISSUE THREAD

**Issue by ralt** [stumpwm/stumpwm#527]
So, I know stumpwm is not a browser, but this behavior is only seen when using stumpwm.

You can see it here: http://jsfiddle.net/396hLkgv/embedded/result/

Hover over "foo", and try clicking on "bar". It'll disappear, without any reason.

It looks like the mouse click sends... _something_ to Chrome, making Chrome think the mouse is no longer there. Almost as if there's a `banish`, or something like that (the cursor isn't moving, to be clear).

Any idea of where I can look at fixing this?

**Comment by PuercoPop** [comment]
Can't reproduce either in Chrome or Firefox. Maybe it is related to a contrib you are using?

**Comment by ralt** [comment]
Hm... I'll have to take a look, thanks. Closing until I have more information :)

**Comment by ralt** [comment]
I tried this again on a bare config, so the bug is still a thing.

I debugged a bit the events, and tried to comment out the relevant events that were being logged to no avail. It feels like maybe there's a missing `xlib:allow-events` somewhere? I'm not sure.

Either way, I'm reopening the issue, because it's not fixed.

**Comment by dmb2** [comment]
can you post the version of sbcl and clx you are using? I can't reproduce this.
