### ISSUE TITLE
stumpwm in sbcl won't quit

### ISSUE THREAD

**Issue by slsuse** [stumpwm/stumpwm#533]
System is a gentoo, stumpwm was installed via quicklisp in sbcl.
Compiling already hangs. Apparently the installation worked, but the process doesn't  return. I'm left with a sbcl hanging there and can C-c to the debugger.
Running stumpwm with sbcl --eval "(ql:quickload \"stumpwm\")" --eval "(stumpwm:stumpwm)" in my .xsession works until I want to log out.
As I couldn't find a keybinding to quit the WM, I used (quit) in the repl.
After that, stumpwm seems dead (no reaction to keybindings anymore) but the X11 session doesn't end. A ps x shows sbcl still running.

**Comment by M4rkD** [comment]
In case this is helpful to anyone else, I experienced the same behavior as in the OP when quitting StumpWM (but not the compilation error).

In my case, this was simply a stray character in my stump startup script which was throwing an error in SBCL after stumpwm had quit (i.e. after the call to `(stumpwm:stumpwm)` had returned).

To clarify further, my method of starting stumpwm was by running a startup script with SBCL which loads stumpwm and calls `(stumpwm:stumpwm)`.

**Comment by PuercoPop** [comment]
I use cl-launch to start StumpWM and haven't run into any issue either. Closing for now. @slsuse if this is still an issue for you please re-open
