### ISSUE TITLE
undo functionality

### ISSUE THREAD

**Issue by tterranigma** [stumpwm/stumpwm#535]
In ratpoison, there was this handy command, `undo` that would undo changes to the frame layout. It was useful for instance temporarily making a frame fullscreen and then going back to the previous layout. Is there sth similar in stumpwm?

**Comment by jbaber** [comment]
@dbjergaard I think it's winner-mode.

**Comment by agzam** [comment]
if someone has a config with an example, please share a link. I couldn't figure out how to get winner-mode to work. Thanks!
