### ISSUE TITLE
Generate manual on one page

### ISSUE THREAD

**Issue by swedebugia** [stumpwm/stumpwm#545]
Hi. I'm trying to convert the manual for reading on my e-reader. 
Could you publish a manual in one page in html?

**Comment by epanji** [comment]
I think what you need is texi2html for one page html:
```texi2html -css-include=your-style.css --no-menu --no-headers stumpwm.texi```

**Comment by PuercoPop** [comment]
`makeinfo --html --no-split stumpwm.texi` also work locally. I'll look into providing the one-page version.

**Comment by dbjergaard** [comment]
Sorry I struggle to update the online manual as it is. @puercopop proposed a good solution for you locally. I hope it works out.
