### ISSUE TITLE
command-menu, how to use it?

### ISSUE THREAD

**Issue by voobscout** [stumpwm/stumpwm#546]
# Either a typo or I'm not using it properly:
```lisp
(defun cmd-test (menu-entry-data)
  (print menu-entry-data))

(defun show-test-command-menu ()
  (stumpwm:command-menu (stumpwm:current-screen)
                        (stumpwm:entries-from-nested-list '(("CMD label" "CMD data")))
                        '((#\a 'cmd-test))))
;; Run it
(show-test-command-menu)
```
The above produces an error, because imho, this line:
https://github.com/stumpwm/stumpwm/blob/e68feeb1b8da327ccc5824cdfff09541dd1bb1b5/menu-definitions.lisp#L409
should instead be:
```lisp
(func (second (second command-entry)))
```

At least when I redefine `command-menu` with my 'fix', I am able to use it as intended (I think).

What am I missing?

**Comment by sdilts** [comment]
It's a typo. Since the list is already quoted, `cmd-test` shouldn't get quoted again. It works as expected when you use `(quote ((#/a cmd-test)))`. I'm not really sure why `(type-of (quote #'foo))` shows that `#'foo` is a list, but it is.

**Comment by sdilts** [comment]
As the author of this code, I'd be happy answer any questions, or even complaints, especially if the documentation needs to be improved.

**Comment by voobscout** [comment]
@sdilts, Thank you so much, good sir!

I'm afraid, you have grossly overestimated my Lisp acumen, this was no typo, but illiteracy with the language.

Awesome work on the command-menu, together with select-from-menu, it makes for a complete rofi/dmenu replacement and a bit more.

**Comment by PuercoPop** [comment]
>  I'm not really sure why (type-of (quote #'foo)) shows that #'foo is a list, but it is.

@sdilts It is because `#'` is a reader macro that expands to `(function ..)`. So the lisp reader transforms `#'foo` into `(function foo)`. For example:

```lisp
(car (read-from-string "#'identity"))
;; => FUNCTION

(cdr (read-from-string "#'identity"))
;; => (IDENTITY)
```
