### ISSUE TITLE
stumpwm starting with 12c9202df4ecb767c220619e0b20a1170bc6b6bc crashes when switching between aseprite and another window with *mouse-focus-policy* :sloppy

### ISSUE THREAD

**Issue by defaultxr** [stumpwm/stumpwm#561]
Hi,

With the following as `.stumpwmrc`:

```lisp
(in-package :stumpwm)
(setf *mouse-focus-policy* :sloppy
      *maxsize-border-width* 0
      *normal-border-width* 0)
```

and any stumpwm from git revision 12c9202df4ecb767c220619e0b20a1170bc6b6bc onward, opening [Aseprite](https://www.aseprite.org/) and then switching between it and another program (such as urxvt) causes it to crash with the error in [this screenshot](https://i.imgur.com/YAaeVMf.png).

I apologize for not running `copy-unhandled-error` for this, as stumpwm will crash repeatedly and I'm not able to gain back control at all, I have to switch to a virtual terminal with `C-M-F2` or the like and manually kill it with `pkill stumpwm`.

I can confirm the problem doesn't happen with any git revision prior to that commit (I reverted back to 84f093ebc4dcc571ef6d3ad3fa1afdda2a63fd7b and am not able to reproduce the crash with it).

I hope this is enough information. If you need more, please just tell me how to get it for you.

**Comment by epanji** [comment]
Is it still happen after this 47afa9a6e51fd28a1bdd501ec7bcd7c9485087a6 ?
I am not able to reproduce the crash by opening the link.

**Comment by epanji** [comment]
Quick hack is to add this code:
``` common-lisp
(defmethod xlib:wm-size-hints-x ((hints null)))
(defmethod xlib:wm-size-hints-y ((hints null)))
```
I don't know if it acceptable or not. Let's wait other opinion.

**Comment by PuercoPop** [comment]
Looking into things further, cause of the issue is that xlib:get-property returns nil when there is property by that name. Even when specifying the `:result-type` as vector. I'll report it on CLX to see if they agree with my interpretation. In the mean time we can work around this issue  by checkingthat the hints are not nil in `full-frame-p`.

```patch
@@ -42,7 +42,8 @@
 (defmethod window-visible-p ((window tile-window))
   (let* ((frame (window-frame window))
          (frame-windows (frame-windows (window-group window) frame)))
     (flet ((full-frame-p (win)
-             (not (and (xlib:wm-size-hints-x (window-normal-hints win))
+             (not (and (window-normal-hints win)
+                       (xlib:wm-size-hints-x (window-normal-hints win))
                        (xlib:wm-size-hints-y (window-normal-hints win))))))
       (or (eq window (or (frame-window frame)
                          (first frame-windows)))
```

@epanji I rather not add a method definition to an accessor.

**Comment by jorams** [comment]
Perhaps an easier testcase than Aseprite is feh.

1. Start StumpWM
2. Open a terminal
3. Open a random image file using `feh`

Checking whether or not the hints are nil is also done in other places, for example [`window-maxsize-p`](https://github.com/stumpwm/stumpwm/blob/4b7d8d8e14971d4542194d24cc211f2f26bebc4c/window.lisp#L517).

I will commit the above diff by @PuercoPop.
