### ISSUE TITLE
Frame unreachable

### ISSUE THREAD

**Issue by jcf** [stumpwm/stumpwm#572]
I use the following bindings to switch between my three monitors, and with the addition of https://github.com/stumpwm/stumpwm/pull/570 my primary middle monitor is on but StumpWM doesn't seem to recognise it at all.

``` lisp
(define-key *top-map* (kbd "s-1") "fselect 1")
(define-key *top-map* (kbd "s-2") "fselect 0")
(define-key *top-map* (kbd "s-3") "fselect 2")
```

I can see Polybar and my wallpaper, but trying to move windows to that monitor, or interact with that monitor in any way fails. It's like StumpWM doesn't know it's there.

Do I need to update my configuration to support this new feature?

**Comment by PuercoPop** [comment]
Could you place the output of running `xrandr` here? Have you tried running the command refresh-heads to see if that makes StumpWM pick it up? When you ran fselect the middle monitor gets no number assigned right?

**Comment by ralt** [comment]
Hi,

You need #573 to fix this exact bug. The monitors are all recognized as having the same frame number, which breaks a few things, as in your case.

**Comment by jcf** [comment]
With #573 applied I can interact with all my displays, but the order has changed which breaks my configuration; I'll have to work out the mapping of frame to and from display again.

Output from `xrandr` in case that's of use to anyone:

```
Screen 0: minimum 8 x 8, current 11520 x 2160, maximum 32767 x 32767
DVI-D-0 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 708mm x 399mm
   3840x2160     60.00*+  29.98    24.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected 3840x2160+7680+0 (normal left inverted right x axis y axis) 708mm x 399mm
   3840x2160     60.00*+  29.98    24.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 connected primary 3840x2160+3840+0 (normal left inverted right x axis y axis) 708mm x 399mm
   3840x2160     60.00*+  29.98    24.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
DP-5 disconnected (normal left inverted right x axis y axis)
```

**Comment by jcf** [comment]
Closing as #573 has resolved this issue. Thanks, everyone!

**Comment by ralt** [comment]
If that's any consolation, the new order should be consistent with xrandr given that it is now using the same API that xrandr is using.
