### ISSUE TITLE
Broken link in README.

### ISSUE THREAD

**Issue by tsandstr** [stumpwm/stumpwm#583]
The link for [Use lisp idioms](http://people.ace.ed.ac.uk/staff/medward2/class/moz/cm/doc/contrib/lispstyle.html) in the README file appears to be broken.

**Comment by szos** [comment]
While I never looked at the link in question before it was broken, id hazard a guess that its similar to the common lisp style guide found on lisp-lang.org.

**Comment by PuercoPop** [comment]
It is/was much shorter and less opinionated

http://web.archive.org/web/20160101153032/http://people.ace.ed.ac.uk/staff/medward2/class/moz/cm/doc/contrib/lispstyle.html
