### ISSUE TITLE
Stumpwm freezes when restarted with visible mode-line.

### ISSUE THREAD

**Issue by l0rdn1bbl3r** [stumpwm/stumpwm#584]
Hi,

since my stumpwm is also affected from  #474 I recently tried to restart stumpwm before this happens.
When I use the command `restart-hard` stumpwm restarts and then freezes. The keyboard is unresponsive w/ regard to stumpwm (can still type in the active window), the mode-line is empty and the default welcome message is somehow cut-off so that the last line isn't readable.

The issue was gone when I ran stumpwm with an empty `.stumpwmrc` (i.e. w/o mode-line).
I found that when disabling the mode-line by running command `mode-line` before `restart-hard` the restart succeeded (also if I enable the mode-line again in `.stumpwmrc` on restart).

I then tried to add `mode-line` as a hook to `*restart-hook*` but the hanging still occured. This seems strange enough since I'd expect the hook (after looking into the source) to result in the same outcome as doing it manually.
I then just wrote this little function instead of using the hook and this works just fine. Why this but not the hook?

```
(defcommand my-restart () ()
  (mode-line)
  (command-history::save-input-history)
  (restart-hard))
```

(the `(command-history::save-input-history)` is just there since I realized that this function is only hooked to `*quit-hook*` and not to `*restart-hook*` which might be worth knowing.

I'm fine w/ this solution for know but I still consider it a hack and would be interested in knowing if anyone experienced this issue and/or if someone with more knowledge of stumpwm could give some insights.

P.S. I start stumpwm in `~/.xinitrc` after starting X automatically at login. I run stumpwm-git from aur on manjaro (currently w/ sbcl 1.4.16).

Regards 

Chris

**Comment by duikboot** [comment]
I have the same issue, also with (restart-soft)

**Comment by mtlll** [comment]
I've been debugging this issue a bit, and it seems there's actually two separate bugs here.

The issue with restart-hard is related to #577 . Reverting the change in git solves the issue. Probably this is because we need to kill the modeline thread before restarting.

Even with #577 reverted, restart-soft still crashes when the modeline is enabled. So this bug works differently somehow.

**Comment by jorams** [comment]
In its current state, with the threaded mode-line reverted and all mode-lines being destroyed before restart, both restart-hard and restart-soft work correctly and I'm assuming this issue is fixed.

**Comment by MIvanchev** [comment]
I am currently experiencing this issue and i don't believe it's solved. stumpwm launches fine like this

```
(setf *screen-mode-line-format*
      (list "^> "
;             '(:eval (run-shell-command "setxkbmap -query | awk '/layout:/ {print $2}'"))
;             " | "
             '(:eval (run-shell-command "date \"+%H:%M\"" t))))
```

but freezes on start if I uncomment the layout code.
