### ISSUE TITLE
Stump keep crashing. (Seems like I'm running out of memory).

### ISSUE THREAD

**Issue by noogie13** [stumpwm/stumpwm#592]
I have tried to do the [suggested debugging](https://github.com/stumpwm/stumpwm/wiki/Freezes), but I don't get any real usable information other than that I have a memory error (eventually it tries to allocate some memory and there is non left). 

Would anyone mind perusing through [my configuration](https://github.com/noogie13/stumpwm-configs) and seeing if I have any silly things that are filling up my memory?
Thanks

**Comment by mtlll** [comment]
I've had a look, but I can't see anything obvious. It's hard for me to actually test your config since it depends on your specific software setup.

Your config is nicely modularized though. So I would suggest commenting out files one by one until the problem goes away, that way you find out where the problem is, if it's even in the config.

**Comment by TeMPOraL** [comment]
I'm betting TTF rendering has a memory leak. I recently updated StumpWM
and hit that very problem - if I switched the font to a truetype one,
Stump would exhaust SBCL heap and crash after some time. Didn't bother
to test it more thoroughly, but the time to crash seemed correlated with
Stump's mesaage & modeline activity.
(Possibly related: when using a TTF, Stump starts having a small but
noticeable lag when typing input in Stump's query textbox.)

On Fri, Mar 22, 2019, at 22:36, mtlll wrote:
> I've had a look, but I can't see anything obvious. It's hard for me
> to actually test your config since it depends on your specific
> software setup.> Your config is nicely modularized though. So I would suggest
> commenting out files one by one until the problem goes away, that way
> you find out where the problem is, if it's even in the config.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].

Links:

  1. https://github.com/stumpwm/stumpwm/issues/592#issuecomment-475791620

**Comment by noogie13** [comment]
Hi! I will totally try no CLX-truetype stuff. Will report back in a few weeks (hopefully).

**Comment by emacsomancer** [comment]
I also hit this - seemingly a TTF-related issue. I tried using  a ttf-font in the past couple of days and this morning, when I came back to my machine which had been running all night, the stump mode-line was empty and the machine unresponsive within stumpwm itself. switching to a tty, top revealed stumpwm taking up a significant chunk of memory.

**Comment by jorams** [comment]
If the problems seem TTF-related, it's probably https://github.com/stumpwm/stumpwm/issues/474#issuecomment-481885037

**Comment by noogie13** [comment]
Solved with advice in #474 to run a timer to clear the cache. Thanks.

(Late response, huh!)
