### ISSUE TITLE
mode-line  icon-fonts errors

### ISSUE THREAD

**Issue by sxgsgnh** [stumpwm/stumpwm#596]
I want to use some icon fonts to indicate certain states, such as: wifi, battery information, sound, but when mode-line uses icon-font or cjk-font, the characters he draws are confusing overall, not very good typography, in characters There is an error in the width.(clx-truetype)

**Comment by jamesmccabe** [comment]
You can use 2 fonts and use maybe FontAwesome for icons. I find if the text is bold it seems to render better with clx-truetype. FontAwesome works OK with regular for me.
```lisp
(set-font (list (make-instance 'xft:font
                               :family "DejaVu Sans Mono"
                               :subfamily "Bold"
                               :size 10)
                (make-instance 'xft:font
                               :family "FontAwesome"
                               :subfamily "Regular"
                               :size 10)
```
```lisp
"^f1<icon>^f0"
```
You can take a look at my stumpwm-config to see what I use.

**Comment by sxgsgnh** [comment]
thankyou
