### ISSUE TITLE
Text input focus does not follow mouse input

### ISSUE THREAD

**Issue by telramund** [stumpwm/stumpwm#597]
I have two frames side-by-side. Most of the time one frame has Emacs, the other has Firefox. When I work in Emacs, I can mouse-click the Firefox window at any time and work with it as normal - except that keyboard input still goes to Emacs. Often it is fine because I do many things in FF with mouse only. But it is very annoying to find that stuff I thought I am typing in FF is actually going to Emacs.

**Comment by notarock** [comment]
I had the same issues but I got used to it...
I get this too when using `(setf *mouse-focus-policy* :sloppy)` in my config. 
I just tried using `(setf *mouse-focus-policy* :click)` and it seems to fix this issue, but then I lose my "sloppy" focus policy :thinking: 
What is your mouse focus policy telramund? 
Also, is there a way to use 2 mouse policy at the same time? (let say I want to use :sloppy but still enable focusing with a mouse click like :click does)?

**Comment by telramund** [comment]
The problem went away after changing mouse policy to ":click". Many thanks, @notarock. I looked for this through the docs before posting, but to no avail.

Shouldn't ":click" be the default policy? I doubt many (any?) users would want mouse and text focus to  be on different windows.
