### ISSUE TITLE
Multiple Monitors Solution

### ISSUE THREAD

**Issue by falood** [stumpwm/stumpwm#609]
This is related to https://github.com/stumpwm/stumpwm/issues/104

We're talking about the solution to bind `group` to `physical monitor`, I'm not sure as a common lisp beginner whether I can take such a big story since 5 years ago, but I want to have a try.
I have some concern, I need the help from the project owner.

1. do you still think this feature is a good idea?
2. the current layout is screen -> group -> head -> window, maybe we want to change it to something like screen -> head -> group -> window, if so, should the name `head` still good for the use case? do you think `monitor` is better? or other suggestions?
3. should we provide the option for people to keep current layout?
4. is there any known issue may be a blocker?

Thanks a lot

**Comment by dbjergaard** [comment]
The status of all that discussion boiled down to: I don’t have the time or skills to implement the changes, but I welcome anyone who can to contribute. 

Someone suggested a fix to another feature request that I didn’t want to implement and we merged that as soon as the PR was code reviewed. 

I’m not opposed to changing vocabulary around heads and screens but it’s a bit of an undertaking. 

Any solution must keep the same behavior by default. 

The biggest issue is going to be figuring out how to get stump to recognize a group per physical screen. This could be trivial or it could be nearly impossible without a major rewrite. Even if you discover it’s not possible it will be a useful contribution for future users!

**Comment by dmb2** [comment]
I'm gonna close this for now, please open a PR with any WIP code you have so we can continue the discussion there!
