### ISSUE TITLE
Crash related to xrandr

### ISSUE THREAD

**Issue by jmbr** [stumpwm/stumpwm#610]
The latest stumpwm crashes whenever I try to disable a screen using the xrandr command:

    xrandr --output DP-0 --off

The crash is triggered by a condition signalled by the form (xlib:rr-get-crtc-info *display* crtc (get-universal-time)) in the function output->head within head.lisp. It turns out that the crtc value returned by one of the outputs coming from (xlib:rr-get-screen-resources root), called from make-screen-randr-heads is equal to zero and this triggers the error.

**Comment by PuercoPop** [comment]
Apparently writing the word issue between Close and the issue number prevents auto-closing from working :woman_shrugging:
