### ISSUE TITLE
Start numbering at 1 instead of 0?

### ISSUE THREAD

**Issue by jocap** [stumpwm/stumpwm#616]
Hi!

Love StumpWM, but I'm wondering whether there's a simple way to have window numbers start at 1 instead of 0, as 0 is positioned awkwardly on the keyboard, after 9 instead of before 1.

Best regards
John

**Comment by PuercoPop** [comment]
Yeah, there is [`*window-number-map*`](https://github.com/stumpwm/stumpwm/blob/5a289d5f0d893d968d65960eaf8067cafb5b2534/primitives.lisp#L612). Try adding `(setf  *window-number-map* "1234567890")` to your rc file

**Comment by jocap** [comment]
Thank you so much! (While I have you, is there any command like `fnext` but that goes backwards?)

**Comment by PuercoPop** [comment]
yeah, `fprev`

**Comment by jocap** [comment]
Thanks! It doesn't seem to be available in 1.0.0 -- I presume it's been added later?

**Comment by PuercoPop** [comment]
@jocap It would appear so https://github.com/stumpwm/stumpwm/commit/ed2e9b10c07fd076ec8ec9048b26d1d72ebb98a6 but 1.0.0 isn't our latest release. Consider updating your StumpWM.

**Comment by jocap** [comment]
Thanks, I'll do that!
