### ISSUE TITLE
QMK keyboard not triggering define-remapped-keys

### ISSUE THREAD

**Issue by szos** [stumpwm/stumpwm#620]
Hello,

I have found an odd quirk with the interaction between QMK and StumpWM; When using a QMK keyboard, StumpWM will recognize keys and key chords, but isn't passing them on to applications through `define-remapped-keys` properly. Sometimes I have gotten a single key stroke through, but 99% of the time they are sent directly to the application instead of the key defined in `define-remapped-keys`. Its as tho, ater pressing any key on the QMK keyboard, even if it isn't remapped to anything, `define-remapped-keys` disengages, and we have to switch to another window and back to get them to work again (on the laptops keyboard). 

This is, I believe, related to #589, as they both deal with `define-remapped-keys`. There is a fix provided in #589, and that enabled the occasional key chord to get through, before that no chords were going through. 

do note, when I say 'unable to get through' I mean that a given key chord elicits its original behaviore, instead of the behaviore defined in `define-remapped-keys`. f.eks. when `C-n` should send a down arrow, but instead gets sent itself (and if in firefox, opens a new window). 

My config is as follows:

````
(defparameter *default-remap-keys*
  '(("C-g" . "ESC")
    ("C-b" . "Left")
    ("C-f" . "Right")
    
    ("M-b" . "C-Left")
    ("M-f" . "C-Right")
    
    ("C-n" . "Down")
    ("C-p" . "Up")
    ("C-a" . "Home")
    ("C-e" . "End")
    ("M-v" . "SunPageUp")
    ("C-v" . "SunPageDown")
    ("C-d" . "Delete")
    ("C-k" . ("S-End" "C-c" "DEL"))
    ("C-w" . "C-x")
    ("M-w" . "C-c")
    ("C-y" . "C-v")
    ("C-s" . "C-f"))
  "The default keys for remapping. Remember, DEL is backspace, Delete is Delete")

(define-remapped-keys
    `(("Firefox"
       ,@*default-remap-keys*
       ("M-F" . "C-SunPageDown")
       ("M-B" . "C-SunPageUp")
       ("M-k" . "C-w")
       ("C-M-f" . "C-]")
       ("C-M-b" . "C-[")
       ("M-n" . "C-n")
       ("M-h" . "C-SunPageUp")
       ("M-j" . "C-SunPageDown")
       )
      ("calibre"
       ,@*default-remap-keys*))) 
````

**Comment by kriyative** [comment]
Hi @szos, I don't follow the connection between QMK and the remapped-keys feature you're referring to. I use a keyboard which runs  QMK as well, and the remapped-keys work as expected.

A couple of things to try:

- If you have access to a different (non QMK) keyboard, can you check if the remapped-keys work with that? Just to rule out QMK as a factor

- Could you temporarily try with a minimal set of remapped keys, to see if there's a specific keybinding which causes an issue. For example:
```lisp
(defparameter *default-remapped-keys*
  '(("C-n"   . "Down")
    ("C-p"   . "Up")))

(define-remapped-keys
    `(("Firefox"
       ,@*default-remap-keys*
       ("M-F" . "C-SunPageDown"))))
```
Cheers.

**Comment by szos** [comment]
Hello,

Given that you use a qmk keyboard, Im inclined to think this is likely an issue with my (QMK) setup. I am using a split board with both halves plugged into the computer. I will try wiring them together so theres only one connection to the computer. 

I have tried a minimal configuration and tried this on two laptops running StumpWM. Both exhibit this same behaviore; I press `C-p` on the laptop, and the webpage/calibre ebook scrolls up, I then press and hold `RCTL_T(KC_BSPC)` on the QMK keyboard and the print dialog comes up. However it is intermittent… Sometimes `C-p` will be 'caught', so to speak, by the remap-keys, and it will work, repeatedly. and then it will stop working. The most keys I've gotten 'caught' is two — additional keys such as `M-h` and `M-j` don't work. Any caught keys are 'set free', and stop working, when some other key is pressed. For example, when writing this, I press `C-p` and it brings up the print dialog, I cancel it, I press `C-p` again, and it moves the cursor up in the text box; I press `a` to insert a character and pressing `C-p` again brings up the print dialog. 

I will try a minimal QMK configuration with dedicated modifier keys, and once some parts get here Ill wire the two halves together. However, I'm hoping that the issue is with the QMK configuration, as `RCTL_T(KC_BSPC)` is on the same half as `KC_P`… 

On a related note, would you mind if I pick your brain on QMK? I've been having some quirks with it, and am unsure where to find information on them - no obligation.

**Comment by kriyative** [comment]
Hmm, if the behavior is correct for non-QMK keyboards you may be right about something in your QMK config being the source of the issue.

I have to admit, I don't know a great deal about the QMK firmware other than how to edit my config and reflash my Atreus62 keyboard - but, will help to the best of my understanding. Just for reference, my config is at:

https://github.com/kriyative/qmk_firmware/blob/master/keyboards/atreus62/keymaps/kriyative/keymap.c

I don't know if there's a way to direct message on GitHub - alternatively, you could open an issue on my qmk forked repo to continue the chat about QMK issues :) Cheers.

**Comment by szos** [comment]
After further investigation, it seems like stump is losing the remap keys bindings/focus randomly, with one exception: I can cause it to lose remap keys bindings/focus by pressing a key on the other side of the keyboard than the one used to press `C-p` and `C-n` and others. 

Given that this seems to be an issue with my QMK setup, I'm going to close this issue. Should it turn out that there is a genuine problem on StumpWM's end with QMK itself, I'll reopen this, but the probability of that is low, I think. @kriyative, Ill wire the two halves together and do some troubleshooting, but I may open an issue to ask for advice - thanks for ebing willing to hear this out.
