### ISSUE TITLE
keywait function

### ISSUE THREAD

**Issue by dingyi342** [stumpwm/stumpwm#622]
I want to realize a function called keywait, which can wait until the user press specified key.
e.g.
(keywait (kbd "RET"))
wait for user to press "Enter" key.

Background
-------------------------------------------------------------------------------
Because I don't installl any input method.
All input is done in emacs.
When I  press "s-i" in firefox input box, then I can input something in emacs minibuffer.
When I press Enter key in emacs minibuffer, it can turn back to firefox and paste my input string within emacs.

```
(defcommand input () ()
  (save-frame-excursion
   (emacs)
   (send-meta-key (current-screen) (kbd "M-:"))
   (window-send-string "(stumpwm/input)")
   (send-meta-key (current-screen) (kbd "RET"))
   ;;(keywait "RET") ;;what I need
   ))
 ```

emacs function:
```
(defun stumpwm/input ()
  (interactive)
  (let (
        (minibuffer-auto-raise t)
        (resize-mini-windows 'grow-only)
        )
    (kill-new (read-from-minibuffer "input: "))
    )
  )
```

**Comment by PuercoPop** [comment]
It seems you are looking for [`define-interactive-keymap`](https://stumpwm.github.io/git/stumpwm-git_13.html#index-define_002dinteractive_002dkeymap)

**Comment by dingyi342** [comment]
> It seems you are looking for [`define-interactive-keymap`](https://stumpwm.github.io/git/stumpwm-git_13.html#index-define_002dinteractive_002dkeymap)

Thanks.It works.
