### ISSUE TITLE
Remove references to Stumpwm Devel mailing list

### ISSUE THREAD

**Issue by tpine** [stumpwm/stumpwm#628]
The mailing list is basically dead should we remove references to it from the project so no one gets confused as to where the main development for stumpwm happens?

**Comment by xsteve** [comment]
No - please keep the mailing list and the references to it alive.
I don't think that the mailing list is dead.

**Comment by dbjergaard** [comment]
The mailing list is not dead! Do not remove references to it!

    David

**Comment by tpine** [comment]
My subscription must of mucked up then I only ever got a few emails from it.

Closing the issue then
