### ISSUE TITLE
Emacs crashes StumpWM

### ISSUE THREAD

**Issue by CodeTriangle** [stumpwm/stumpwm#637]
I am using sbcl 1.5.5 and roswell. StumpWM launches normally, but upon starting emacs either through `C-t e` or a terminal emulator, StumpWM crashes, sending me back to the login terminal. Piping the output of startx results in [this stacktrace](https://github.com/stumpwm/stumpwm/files/3538863/stumpwm-emacs-crash.txt) that I don't know nearly enough about the architecture of stumpwm to make heads or tails of.

Changing my emacs config has not helped so far, and none of the logs I have found clarify much about the situation.

Any assistance is appreciated.

**Comment by PuercoPop** [comment]
@CodeTriangle Can you make sure you are running the 'bleeding edge' version of StumpWM? The issue you are encountering was fixed recently by https://github.com/stumpwm/stumpwm/pull/636

**Comment by CodeTriangle** [comment]
I applied the changes, and it seems to have fixed the problem. Thank you for pointing me in the right direction.
