### ISSUE TITLE
Can't remap non-asciikeys for applications

### ISSUE THREAD

**Issue by yoeljacobsen** [stumpwm/stumpwm#638]
I fail to use define-remapped-keys with non-ascii characters.

Consider:
`
(define-remapped-keys
    '(("firefox"
       ("C-ב"   . "C-c")
       ("C-ה"   . "C-v")
       ("C-ז"   . "C-z"))))
`

The definition "works" but when I switch to firefox it can't parse the map.

This is not a duplicate of #111 or #194.

**Comment by dmb2** [comment]
Hi, 

While I understand it doesn't appear to be a duplicate, the underlying problem is in CLX and how it handles keyboard input for international keyboard.  You can read more here: http://dmb2.github.io/posts/clx_extensions.html

Let me know if you have any more questions.
