### ISSUE TITLE
Windows fully cover the screen, including mate-panel

### ISSUE THREAD

**Issue by Hexstream** [stumpwm/stumpwm#649]
Hello,

I finally upgraded from Debian 8 Mate to Debian 10 Mate.

I got StumpWM mostly working, but there is one very major issue: If there is any window in the current workspace, then it fully covers the screen, including mate-panel.

I do need to see mate-panel at all times (unless something is truly, *intentionally* full-screen), most notably because of the system monitor which I absolutely can't live without.

If there is a simple way to tell StumpWM to ignore the first 24 pixels at the top of the screen, that would solve my immediate problem.

**Comment by Hexstream** [comment]
After digging in the code a bit, I came up with the following trivial hack. I put this in my `.stumpwmrc`:

```
(resize-head 0 0 26 1600 (- 900 26))
```

**Comment by defaultxr** [comment]
I'm not familiar with mate-panel but stumpwm should work with windows that are set to be "dock"-type windows. It does this by replacing its mode-line with them, and then you can toggle the mode-line to hide or re-show the window operating as the dock.

For example, `stalonetray` supports running as a "dock":

`stalonetray --window-type dock`

Running this command puts stalonetray at the top of my screen and allows me to toggle it with the `toggle-mode-line` command.

I tried to find a similar command line option for mate-panel but nothing I found online turned up any results. Maybe it exposes such a setting via `dconf` or similar?

**Comment by dmb2** [comment]
I can't reproduce this and other panels work correctly.

**Comment by Hexstream** [comment]
I still have that problem, but [my dedicated *Toggle Fullscreen*](https://status-quo.hexstream.expert/hardware/planck-ez/#my-config) key makes it bearable.
