### ISSUE TITLE
Support HiDPI

### ISSUE THREAD

**Issue by lsp-ableton** [stumpwm/stumpwm#654]
On high resolution monitors, the stumpwm menus are extremely tiny. I managed to get the windows themselves to display correctly by making sure that the xserver is started with `-dpi 196`, but I don't know how to make the same setting apply to the stumpwm overlays.

**Comment by jorams** [comment]
I believe the (ancient) APIs StumpWM uses to render its overlays don't support this. I solve it by using a larger font size.

**Comment by nicholasrupert** [comment]
I just ran into this same problem. Is this still the case that you can't make everything bigger?
