### ISSUE TITLE
certain UTF-8 characters create issue when using clipboard module

### ISSUE THREAD

**Issue by emacsomancer** [stumpwm/stumpwm#656]
when I do `(clipboard-history:show-clipboard-history)`, using the [clipboard-history](https://github.com/stumpwm/stumpwm-contrib/tree/master/util/clipboard-history) module, when I try to browse, copied items with certain characters produce errors when selected from clipboard history, e.g.:

      0: (XLIB:CHAR->CARD8 #<unavailable argument>) [external]
      1: (XLIB::WRITE-VECTOR-CARD8-WITH-TRANSFORM #<XLIB:DISPLAY :0 (The X.Org Foundation R12005000)> 24 "\"For an entire century, the corporate class in America has dreamed of destroying organized labor, whic..
      2: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB:CHANGE-PROPERTY))
      3: ((FLET "WITHOUT-INTERRUPTS-BODY-29" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
      4: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB:CHANGE-PROPERTY) {7FE970A2DC0B}> #<SB-THREAD:MUTEX "CLX Buffer Lock" owner: #<SB-THREAD:THREAD "new-r..
      5: (XLIB:CHANGE-PROPERTY #<XLIB:WINDOW :0 115> :CUT-BUFFER0 "\"For an entire century, the corporate class in America has dreamed of destroying organized labor, which eats into their ability to amass endl..
      6: (CLIPBOARD-HISTORY:SHOW-CLIPBOARD-HISTORY)
      7: (SB-INT:SIMPLE-EVAL-IN-LEXENV (CLIPBOARD-HISTORY:SHOW-CLIPBOARD-HISTORY) #<NULL-LEXENV>)
      8: (EVAL (CLIPBOARD-HISTORY:SHOW-CLIPBOARD-HISTORY))
      9: (SWANK::EVAL-REGION "(clipboard-history:show-clipboard-history) ..)
     10: ((LAMBDA NIL :IN SWANK-REPL::REPL-EVAL))
     11: (SWANK-REPL::TRACK-PACKAGE #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {1003130ACB}>)
     12: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {1003130A6B}>)
     13: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {1003130A4B}>)
     14: (SWANK-REPL::REPL-EVAL "(clipboard-history:show-clipboard-history) ..)
     15: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK-REPL:LISTENER-EVAL "(clipboard-history:show-clipboard-history) ..)
     16: (EVAL (SWANK-REPL:LISTENER-EVAL "(clipboard-history:show-clipboard-history) ..)
     17: (SWANK:EVAL-FOR-EMACS (SWANK-REPL:LISTENER-EVAL "(clipboard-history:show-clipboard-history) ..)
     18: (SWANK::PROCESS-REQUESTS NIL)
     19: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
     20: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
     21: (SWANK/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {10031300CB}>)
     22: ((FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/slade/quicklisp/dists/quicklisp/software/slime-v2.24/swank/sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HA..
     23: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-INPUT* . #1=#<SWANK/GRAY::SLIME-INPUT-STREAM {100216C233}>) (*STANDARD-OUTPUT* . #2=#<SWANK/GRAY::SLIME-OUTPUT-STREAM {1008FA5303}>) (*TRACE-OUTPUT* . #2#) (*ERR..
     24: (SWANK::HANDLE-REQUESTS #<SWANK::MULTITHREADED-CONNECTION {1008521063}> NIL)
     25: ((FLET SB-UNIX::BODY :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
     26: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
     27: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
     28: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
     29: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE) {7FE970A2ED7B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "new..
     30: (SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE #<SB-THREAD:THREAD "new-repl-thread" RUNNING {10031285D3}> NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::SPAWN-REPL-THREAD) {100312857B}> NIL)
     31: ("foreign function: call_into_lisp")
     32: ("foreign function: new_thread_trampoline")

(@kriyative [suggests](https://www.reddit.com/r/stumpwm/comments/dv2ym5/clipboard_module_produces_errors_with_certain/f7bosoo/) that's it due to certain old UTF-8-unaware code.)

**Comment by kriyative** [comment]
A quick way to reproduce this issue from the REPL:
```common-lisp
(stumpwm:set-x-selection "’foo")
```

**Comment by dmb2** [comment]
Does the related pr fix this?

**Comment by kriyative** [comment]
@dmb2 - yes
