### ISSUE TITLE
Compilation error on Debian Jessie

### ISSUE THREAD

**Issue by Vorlonhomeworld** [stumpwm/stumpwm#660]
I'm attempting to compile Stumpwm 1.0.0 on Debian Jessie, using Sbcl lisp.
The make command exits with:

 "make: execvp: /usr/local/bin: Permission Denied".

On further testing:

The output for ls - l $(sbcl) is it starts a lisp shell(?), no errors though. 

The output for ls - ld /usr/local/bin is: drwxr-sr-x 2 root staff 20480 Nov 6 21:47 /usr/local/bin

Based on the output of the first command, I checked Makefile and Makefile.in. Both have the same permissions :

-rwxr-xr-x 1 root (size) (date) (time)

I've already switched to root and I get the same error.
I do have gcc and sbcl in the /usr/local/bin directory. I've also chown'ed the folder where stumpwm is currently, no change.

**Comment by PuercoPop** [comment]
Hey, sorry about the typo, the first command should have read `ls - l $(which sbcl)` but  I wanted to see if it had the executable flag on, which it does as the you report seeing the lisp repl.

Although it is unusual to have the StumpWM files owned by root if you execute the commands with sudo.

>  I've also chown'ed the folder where stumpwm is currently, no change.

What you report about the Makefile.in suggests otherwise, did you invoked `chown` with the recursive flag, `-R`, so that it applies to all the files inside the directory as well?

<hr />

what is the output if you invoke 

`$ sbcl --load ./make-image.lisp`

and

`$ sudo sbcl --load ./make-image.lisp`

**Comment by Vorlonhomeworld** [comment]
The output for sbcl - - load./make-image.lisp is:

Component : CL-PPCRE not found, required by #</SYSTEM “stumpsm">

The sudo version does the same.
I'll search for CL-PPCRE on my system

**Comment by Vorlonhomeworld** [comment]
> The output for sbcl - - load./make-image.lisp is:
> 
> Component : CL-PPCRE not found, required by #</SYSTEM “stumpsm">
> 
> The sudo version does the same.
> I'll search for CL-PPCRE on my system

Just finished the search and no,  sbcl doesn't include this. I can get this from Github, but before I do, I thought I should ask if you all think this is the problem and if I should attempt to get CL-PPCRE from Github.  Thanks!

**Comment by PuercoPop** [comment]
>  I can get this from Github, but before I do, I thought I should ask if you all think this is the problem and if I should attempt to get CL-PPCRE from Github

Instead of downloading it from GitHub directly get it through quicklisp. The instructions on how to do so can be found at https://github.com/stumpwm/stumpwm#prerequisites

**Comment by Vorlonhomeworld** [comment]
I appreciate the suggestion, however, my computer's not online, only my phone is (cell phone).
I'll check to see that I have the other needed packages, and if not, I'll get them!  Thanks

**Comment by Vorlonhomeworld** [comment]
Ok, so just to let you know Stumpwm IS running. I really was missing one lisp library. Once I added that back in, oddly enough, the make command threw the same error, but the "load image" command worked fine and assembled the file perfectly.
I just ran it, it looks good, but doesn't like St (suckless terminal), perhaps it's a passing thing)

Thanks for the assistance!!

**Comment by PuercoPop** [comment]
> I just ran it, it looks good, but doesn't like St (suckless terminal), perhaps it's a passing thing)

What is the issue you run into? I use St everyday w/o any issue.

**Comment by Vorlonhomeworld** [comment]
Stumpwm crashes (ran it from the command line "exec st"). I'll recheck and make sure nothing's wrong or missing (dependancy wise) with my stumpwm.

**Comment by Vorlonhomeworld** [comment]
Ok, all dependancies check out. I deleted stumpwm, ran autogen, configure, make (which did work this time) and make install. It runs and likes xterm, lxterm, L terminal,. but not st.     It seems to like all other programs as well.

**Comment by PuercoPop** [comment]
Do you get a stack trace when StumpWM crashes?

**Comment by Vorlonhomeworld** [comment]
No stack trace, st tries to load, then the screen changes to my login screen (xsession, not the terminal).
So far all of my other terminals work fine.)

**Comment by PuercoPop** [comment]
Could you try loading it either from the terminal (through startx) or inside of [Xephyr](https://github.com/stumpwm/stumpwm/wiki/Bugs#debugging-reproducible-crashing-bugs) so you can see the stack trace when it crashes?
