### ISSUE TITLE
`read-one-line` (and other input functions?) produce errors with Unicode characters

### ISSUE THREAD

**Issue by emacsomancer** [stumpwm/stumpwm#663]
Calling `read-one-line` and inserting a unicode character like é raises an error (which seems to freeze StumpWM):

```
The value
  #\LATIN_SMALL_LETTER_E_WITH_ACUTE
is not of type
  BASE-CHAR
```

This seems similar to the (fixed) issue https://github.com/stumpwm/stumpwm/issues/656 (though that issue didn't freeze StumpWM) .

**Comment by equwal** [comment]
I have been getting freezes also, and I think the clipboard system is the culprit.

Unfortunately I was not able to reproduce with
```common-lisp
(stumpwm:read-one-line (current-screen) "freeze with unicode: "
                                :initial-input "é")
```

**Comment by equwal** [comment]
Also possibly related:
https://github.com/stumpwm/stumpwm-contrib/issues/157

If anything is the coulprit, it is probably the use of `string-equal`, and the assumption that a string will be stored.

Have you tried upgrading your SBCL version? I am on 1.5.8 and cannot reproduce.

**Comment by emacsomancer** [comment]
Yes, I also do *not* get an error with `(read-one-line (current-screen) "freeze with unicode: " :initial-input "é")`, but try this:

```
(defcommand search-in-startpage () ()
  (let ((searchstring (read-one-line (current-screen) "Search for string in browser: ")))
    (when searchstring
      (run-shell-command (concat "firefox \"https://www.startpage.com/do/dsearch?query=" searchstring "\"")))))
```

This one doesn't actually crash stumpwm, but if you try pasting in something like "héllo", it immediately produces the error 

```
The value
  #\LATIN_SMALL_LETTER_E_WITH_ACUTE
is not of type
  BASE-CHAR
```

And this seems like it must be an issue with `readline`, since something like:

```
(let ((hello "héllo")) 
   (echo hello))
```

works without issue.

I'm on `sbcl-1.5.9`, but I had the same issue on `sbcl-1.5.8`

**Comment by equwal** [comment]
> Yes, I also do _not_ get an error with `(read-one-line (current-screen) "freeze with unicode: " :initial-input "é")`, but try this:
> 
> ```
> (defcommand search-in-startpage () ()
>   (let ((searchstring (read-one-line (current-screen) "Search for string in browser: ")))
>     (when searchstring
>       (run-shell-command (concat "firefox \"https://www.startpage.com/do/dsearch?query=" searchstring "\"")))))
> ```
> 
> This one doesn't actually crash stumpwm, but if you try pasting in something like "héllo", it immediately produces the error
> 
> ```
> The value
>   #\LATIN_SMALL_LETTER_E_WITH_ACUTE
> is not of type
>   BASE-CHAR
> ```
> 
> And this seems like it must be an issue with `readline`, since something like:
> 
> ```
> (let ((hello "héllo")) 
>    (echo hello))
> ```
> 
> works without issue.
> 
> I'm on `sbcl-1.5.9`, but I had the same issue on `sbcl-1.5.8`

I can't even get an extended character into the prompt. My compose key will not work, and changing to another keyboard layout does not work.

How are you "pasting" that in?

**Comment by emacsomancer** [comment]
@equwal get an extended character into your x-selection, i.e. just copy é or whatever and paste it into the `read-one-line` prompt.

**Comment by equwal** [comment]
> @equwal get an extended character into your x-selection, i.e. just copy é or whatever and paste it into the `read-one-line` prompt.

Okay, I was able to paste it in. Unfortunately I could not reproduce any freezing.

**Comment by emacsomancer** [comment]
@equwal for the simple function (given above) stumpwm doesn't freeze, but it does produce the error mentioned (and exit out of the function). did you not observe that behaviour? were you able to execute the websearch with something like "héllo"?

**Comment by equwal** [comment]
https://github.com/sharplispers/clx/issues/30 (CLX does not support Compose keys) is probably related.

**Comment by dmb2** [comment]
I think this is how we translate input into an internal representation.  It doesn't sound related to XKB or other sources of input errors.  I have to dig though.

**Comment by dmb2** [comment]
This is a bug in CLX.  I can take a stab at it but the fix isn't going to be in stumpwm. Please report to sharplispers/clx.
