### ISSUE TITLE
float certain windows by titles

### ISSUE THREAD

**Issue by linwaytin** [stumpwm/stumpwm#664]
Hi,

I would like to make certain windows floating by default.
For example, the calendar generated by a panel, which should be under the date widget, or a menu.
Is it possible to achieve this in Stumpwm?

Thank you.

**Comment by PuercoPop** [comment]
> Is it possible to achieve this in Stumpwm?

Yeah, you could use the `*new-window-hook*` + [Window Selection Expressions](https://stumpwm.github.io/git/stumpwm-git_5.html#Window-Selection-Expressions)

**Comment by linwaytin** [comment]
Thank you!
