### ISSUE TITLE
Cannot scroll in VTE based terminals

### ISSUE THREAD

**Issue by paulbdavis** [stumpwm/stumpwm#668]
For some reason I cannot seem to scroll with the mouse wheel in any VTE based terminal (I have tried termite, sakura, and gnome-terminal).

Non VTE teriminals I've tried work fine (xterm, urxvt, kitty).

**Comment by lxbarbosa** [comment]
not using stumpwm anymore, but I've seens that behavior in suckless st terminal and next browser too!

**Comment by xsteve** [comment]
Hi Paul,

you could try to put the following in ~/.xsession:
export GDK_CORE_DEVICE_EVENTS=1


> For some reason I cannot seem to scroll with the mouse wheel in any
> VTE based terminal (I have tried termite, sakura, and
> gnome-terminal).
>
> Non VTE teriminals I've tried work fine (xterm, urxvt, kitty).
>

**Comment by paulbdavis** [comment]
That worked for me (almost, I had to add it to `~/.xinitrc` since I am logging in from the TTY and not a display manager)
