### ISSUE TITLE
Terminal borders, empty frame indicator behave oddly with compositing

### ISSUE THREAD

**Issue by paulbdavis** [stumpwm/stumpwm#669]
I am using picom (compton) to add transparency to emacs and terminals, but for some reason the terminal compositing behaves differently than that of other windows. It presents on all terminals I've tried except xterm and urxvt

I'm not totally sure if this issue lies in stump or in compton/picom, but since the issue has not presented on i3 from my previous setup I think something is going on in stump that is causing them to be treated differently

If there is no rule in the compton conf for the terminal at all, it still causes the borders to go nearly transparent, just having the compositor enabled at all causes it.

I've also noticed that the dashed line indicating being in an empty frame also disappears when compositing is turned on 

Here you can see the border is given extra transparency 
![emacs](https://user-images.githubusercontent.com/2730634/70823911-3c2f6a00-1d9e-11ea-93af-0b1bd06ff1cb.jpg)
Versus the way the emacs border looks when inactive
![termite](https://user-images.githubusercontent.com/2730634/70823915-3cc80080-1d9e-11ea-97ee-16c26a0ffb02.jpg)
When it is not floating there is a "gap" caused by the overly transparent border (hard to see here, but the emacs window in the lower right has it's inactive color extending further than the terminal window above it)
![term-full](https://user-images.githubusercontent.com/2730634/70824684-fa072800-1d9f-11ea-939a-d5c0b7d34530.jpg)
Here are shots of the termial and emacs in i3 using the same `compton.conf` file
![i3-term](https://user-images.githubusercontent.com/2730634/70823912-3c2f6a00-1d9e-11ea-91ce-8de402945e54.jpg)
![i3-term-float](https://user-images.githubusercontent.com/2730634/70823913-3c2f6a00-1d9e-11ea-9cb1-ba1d0b04b57f.jpg)

**Comment by equwal** [comment]
This is related to https://github.com/stumpwm/stumpwm/issues/532. Adding support for CLX composite could fix a lot of rendering issues from forcing the use of the hardware device.

**Comment by paulbdavis** [comment]
Interesting, I'll have to hack on this when I have some "free time"...

**Comment by equwal** [comment]
[CLX composite](https://github.com/sharplispers/clx/blob/master/extensions/composite.lisp)
[Xorg documentation](https://www.x.org/releases/X11R7.7/doc/compositeproto/compositeproto.txt)

**Comment by dmb2** [comment]
We won't support extending clx, its best if you open the issue upstream with them.  Once clx has the extension implemented, stumpwm will benefit "for free"
