### ISSUE TITLE
Clipboard integration issues with xclip and vim.

### ISSUE THREAD

**Issue by equwal** [stumpwm/stumpwm#673]
Neither xclip nor vim seem to have access to my clipboard, which tends to be annoying.

`echo "Not in StumpWM clipboard :(" | xclip`
`xclip -o` => `Not in StumpWM clipboard`.
`vim` (try to paste something from the StumpWM clipboard with `p`.

So both these programs seem to be lacking the integration I'd like. I still have a clipboard in other programs. Emacs, for example, works fine. So I find myself doing things like this:
```bash
some command >~/.tmp # cannot use xclip
emacs ~/.tmp # yank it in emacs and kill
```

**Comment by kriyative** [comment]
@equwal - you might need to specify the X selection - xclip defaults to XA_PRIMARY, most apps seem to use XA_CLIPBOARD. See if the following works better:
```
echo "cut" | xclip -selection clipboard
```
and try pasting in vim.

**Comment by equwal** [comment]
> @equwal - you might need to specify the X selection - xclip defaults to XA_PRIMARY, most apps seem to use XA_CLIPBOARD. See if the following works better:
> 
> ```
> echo "cut" | xclip -selection clipboard
> ```
> 
> and try pasting in vim.

I see. This indeed works. The functions `getsel` and `putsel` also exist, but are pretty much useless.

**Comment by equwal** [comment]
The xclip suggestions works in general, but vim is still storing it's kill ring elsewhere.  I don't think this is a problem with StumpWM, so I am closing.

**Comment by kriyative** [comment]
BTW, `putsel` and `getsel` also default to the `primary` selection, and that could be changed. Also, the primary selection can be accessed using the middle mouse button paste in most apps. It's just that most paste keybindings refer to the `clipboard` selection

**Comment by equwal** [comment]
> BTW, `putsel` and `getsel` also default to the `primary` selection, and that could be changed. Also, the primary selection can be accessed using the middle mouse button paste in most apps. It's just that most paste keybindings refer to the `clipboard` selection

How could `getsel` and `putsel` be changed to just be generic copy/paste functions? I think if they were changed that way, and to use the `clipboard` selection, that using StumpWM's clipboard could be a lot more intuitive (eg. by putting them on `C-i y` and `C-i M-w`).

**Comment by equwal** [comment]
> BTW, `putsel` and `getsel` also default to the `primary` selection, and that could be changed.

Changing this breaks the `show-clipboard-history-contrib`, though that could be changed also. My view is that it is worth doing.

**Comment by kriyative** [comment]
Ah, I think I see what you mean. `putsel` and `getsel` are meant for the primary selection. Actually, `clipboard-history` probably is closer to what you are looking for, except that conflates tracking a history of clipboard values rather than just one. Not sure, how changing `putsel` breaks `clipboard-history` since that has an entirely independent mechanism for polling the current clipboard contents.

**Comment by kriyative** [comment]
`clipboard-history::poll-selection` likely does what you are looking for, of grabbing the current selection (it defaults to grabbing `:primary` selection, but the unfortunately named `poll-selections` function grabs the `clipboard` contents).

**Comment by equwal** [comment]
> Ah, I think I see what you mean. `putsel` and `getsel` are meant for the primary selection.
I don't see anywhere where they are *meant for* primary selection, there merely do it that way now. It is as easy as changing `:primary` to `:clipboard` in two places in `selection.lisp` to change the default.

> Not sure how changing `putsel` breaks `clipboard-history` since that has an entirely independent mechanism for polling the current clipboard contents.

Alas, I was mistaken about this. I think it will not break anything.

**Comment by equwal** [comment]
I have to wonder about the rationale by this code snippet:
```lisp
(defcommand getsel () ()
  "Echo the X selection."
  (message "~a" (get-x-selection)))
```

**Comment by equwal** [comment]
> `clipboard-history::poll-selection` likely does what you are looking for, of grabbing the current selection (it defaults to grabbing `:primary` selection, but the unfortunately named `poll-selections` function grabs the `clipboard` contents).

Hmmm. I think you meant `show-clipboard-history`. Indeed, there are some problems with the `clipboard-history` repo in the contrib. Why should adding an `s` to the name change it from the primary to clipboard selection, and that is the only difference? Strange. Also, that function is not exported, so I should be free to remove it.

**Comment by kriyative** [comment]
`poll-selections` is used here [1] - I know because I wrote that unfortunately named function. Ideally, it could be renamed something like `poll-clipboard-selection` or some such. Of course, it is local to the `clipboard-history` package, but since CL does allow referencing private symbols it could break code that use that symbol.

[1] https://github.com/stumpwm/stumpwm-contrib/blob/master/util/clipboard-history/clipboard-history.lisp#L75

**Comment by equwal** [comment]
Okay I
