### ISSUE TITLE
The PDF manual has blank pages after each chapter

### ISSUE THREAD

**Issue by equwal** [stumpwm/stumpwm#677]
Why?
https://stumpwm.github.io/git/stumpwm-git.pdf

It would be straightforward to kludge that thing using `pdfseparate` and `pdfunite`.

**Comment by dmb2** [comment]
Unfortunately some of our 'chapters' are less than a page of content, so it appears as a bunch of blank pages interspersed with content.  While it may not be aesthetically pleasing, or nice to trees if you print the manual single-sided, it does follow established conventions and I don't want to do anything to fix/change it.

**Comment by equwal** [comment]
Oh I see now; the blank page is the back side of the last page in a chapter, that way all chapters are on the front of a page.
