### ISSUE TITLE
More completion for more commands that take input?

### ISSUE THREAD

**Issue by equwal** [stumpwm/stumpwm#690]
Inputting things into StumpWM can be frustrating. There is straightforward completion available, but it is not consistent across commands.

The [`pass` contrib has a good example of completion done right](https://github.com/stumpwm/stumpwm-contrib/blob/master/util/pass/pass.lisp#L22).

For example, `C-t ;` could benefit from such a change. It uses a much weaker completion. Selecting groups by name with visual completion would also be helpful.

**Comment by jorams** [comment]
Could you provide some examples of commands with insufficient/bad/whatever completion?

I agree it's annoying that `colon` only completes the command name, and not any of its arguments.

> Selecting groups by name with visual completion would also be helpful.

What do you mean by this? `gselect` offers completion of groups by name.

**Comment by equwal** [comment]
> Could you provide some examples of commands with insufficient/bad/whatever completion?
> 
> I agree it's annoying that `colon` only completes the command name, and not any of its arguments.
> 
> > Selecting groups by name with visual completion would also be helpful.
> 
> What do you mean by this? `gselect` offers completion of groups by name.

I meant that completing-read with a set could be more helpful. With gselect it would be nice to see what named groups exist while completing the entry.

**Comment by jorams** [comment]
That seems like the kind of thing #519 was meant to help improve. To try it out:

```lisp
(setf *input-completion-style* (stumpwm::make-input-completion-style-unambiguous))
```

(apparently `make-input-completion-style-cyclic` and `make-input-completion-style-unambiguous` are not exported.)

I agree that none of this is quite ideal though.

**Comment by equwal** [comment]
> (setf *input-completion-style* (stumpwm::make-input-completion-style-unambiguous))

I'm currently using that version already. This is the kind of thing I mean:
```
;;; group selection example
(select-from-menu (current-screen)
                                  (mapcar #'group-name (sort-groups (current-screen)))
                                  "Group: "))
```
I'm glad to see this change has some support. While we're on the topic of redesigning this UI, I have two other suggestions:
- Do not capitalize `Default`, or instead use case-insensitive completion.
- Provide a set of predefined workspaces. These could be named 0-9 to avoid interfering with completion of user-defined groups (since you will not start typing numbers unless that is what you need), and be sorted to the end of the completion. I would rather not always have to name my workspace whenever I want to move some stuff out. For example, I often have a long-running program that I want to put somewhere off-screen, so I have to manually make the `trash` workspace. But I could just as easily put it in `workspace 0` every time.

**Comment by equwal** [comment]
`commands` now also has this: https://github.com/stumpwm/stumpwm/pull/709
