### ISSUE TITLE
Use asynchronous timers rather than synchronous ones

### ISSUE THREAD

**Issue by equwal** [stumpwm/stumpwm#699]
The mode line is the main place where these issues happen. Entering a key sequence blocks the mode line update https://github.com/stumpwm/stumpwm/issues/606. The mode line can prevent quitting StumpWM https://github.com/stumpwm/stumpwm/issues/675. And it can slow down StumpWM significantly if the mode line is too bloated.

StumpWM uses a custom timers mechanism that shadows the names of [SBCL's built-in ones that support threading](http://www.sbcl.org/manual/#Timers).

**Comment by dmb2** [comment]
Please submit this as a PR when it is complete, otherwise you're comments in the other issues sufficiently documents how to solve the problem for other people who may want to contribute.
