### ISSUE TITLE
system time update crashes stumpwm

### ISSUE THREAD

**Issue by ghost** [stumpwm/stumpwm#7]
StumpWM version: 202120107-git built from Quicklisp
Common Lisp environment: SBCL 1.0.57.0.debian (Debian Wheezy, i686)

If my system updates its time from ntp after StumpWM starts, the window manager crashes, taking the X server down with it.  I am using a clock in my mode line, which is configured with the following snippet from my .stumpwmrc:

(setq
 _time-modeline-string_ "%Y-%m-%d %H:%M"
 _screen-mode-line-format_ "(%g) (%d) (Batt: %B) (CPU: %f %t)"
 _shell-program_ "/bin/zsh")
(set-focus-color "gray50")
(set-unfocus-color "gray20")
(mode-line)

**Comment by ghferrari** [comment]
Does anyone know if this bug has been fixed upstream? I'm running StumpwWM on SBCL version 1.2.11 and on first boot StumpWM frequently hangs with this error reported in the log:

Jun 01 09:19:51 lindy /etc/gdm3/Xsession[1382]: debugger invoked on a TYPE-ERROR in thread
Jun 01 09:19:51 lindy /etc/gdm3/Xsession[1382]: #<THREAD "main thread" RUNNING {100531EC43}>:
Jun 01 09:19:51 lindy /etc/gdm3/Xsession[1382]: The value -3599448 is not of type UNSIGNED-BYTE.
Jun 01 09:19:51 lindy /etc/gdm3/Xsession[1382]: Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
Jun 01 09:19:51 lindy /etc/gdm3/Xsession[1382]: (no restarts: If you didn't do this on purpose, please report it as a bug.)
Jun 01 09:19:51 lindy /etc/gdm3/Xsession[1382]: (GET-INTERNAL-REAL-TIME)

As I say, this only ever seems to happen on first boot. If I force quit StumpWM and then re-login, StumpWM boots just fine.
