### ISSUE TITLE
`sibling` command is very weird

### ISSUE THREAD

**Issue by equwal** [stumpwm/stumpwm#705]
# Steps:
- Split window `C-t S`.
- Try it `C-t ; sibling RET`.
# Observed behaviour:
Arbitrarily go to the sibling, or do nothing if it already there.
# Expected behaviour:
If doing nothing, a message like `No other siblings.` would go far.

**Comment by dmb2** [comment]
Fail silently is kind of a unix thing.  Since the command does work correctly in the right context, this is a non-issue.  If you would like to submit a PR with more documentation of what sibling is and how it works, that is more than welcome!
