### ISSUE TITLE
^-t ; command box broken or changed behaviour

### ISSUE THREAD

**Issue by kaarejens** [stumpwm/stumpwm#713]
It seems that "ctrl-t - ;" has changed behaviour after recent commit. 

Both history (arrow up) and tab completion is now broken, while the new "list-commands-as-you-type" is the new behaviour. Also, ex. "run-shell-command urxvt" does not work, so now one must type "run-shell-command" hit enter, and then type the options. 

Not sure if this is on purpose, or if it is a bug, but at least for me, this is not what I expect.

This commit seems to be related: https://github.com/stumpwm/stumpwm/commit/41f0f70eaeec76e982d6dc5663ca73abcb44a267

**Comment by mtlll** [comment]
Perhaps it would be better to keep the old colon and add a new command colon-menu with the new behaviour. While this new behaviour is nice in theory, I personally never type a command into colon unless I already know how to type it, and often typing and tab completing is faster than selecting from the list.

For instance, now if I wanted to run 'next' using colon, even if I typed all of "next", I still have to press down 3 times to get past fnext, gnext, and gnext-with-window. The muscle memory reactiong of just typing next and pressing enter would run fnext. Additionally, pressing tab causes garbage characters to be input instead of completing. Perhaps SELECT-FROM-MENU should be changed to tab-complete on tab, because that's quite jarring for people who habitually hit tab to complete, like me.

**Comment by kaarejens** [comment]
My thoughts exactly. Though it would of course be nice to have a hybrid - best of both worlds, but until someone can produce such a code, it seems more convenient to put this on ex. ^-t  ,  or some other meaningful combo for now. 

I really like the idea of this, but if I would have to choose, I would say the old way, was quicker and more valuable. It also feels more aligned with the WM in general (remembering lots of key combos for efficiency and so on).

**Comment by PuercoPop** [comment]
> just realized the suggested ^-t , only makes sence with nordic keyboard layouts

Don't worry I think it was clear you meant <prefix>-t. 

I think it is reasonable to support the old functionality while still 'moving forward'. What do y'all think about restoring the old functionality and instead adding a new command _but_ updating the default binding for ^-t to the new command?

cc: @dmb2

**Comment by emacsomancer** [comment]
@PuercoPop I think restoring the old functionality and adding a new command is good. I don't have a firm opinion on the binding.

**Comment by equwal** [comment]
> Both history (arrow up) and tab completion is now broken, while the new "list-commands-as-you-type" is the new behaviour. Also, ex. "run-shell-command urxvt" does not work, so now one must type "run-shell-command" hit enter, and then type the options.

These can both be added back in, while keeping completion around. I would prefer this course of action.

**Comment by kaarejens** [comment]
I don't know the complexity of making something like this, but I think, if the list completion sorted by typed characters directly (ex. typing quit would land you the quit command instead of keyboard-quit etc.), one could use the tab-button to move down the completion list, and there would be no need for the old tab-completion function. That way, the arrow up could still be used as history. 

@equwal Would this be overly complex, or feasible to accomplish?

**Comment by equwal** [comment]
The referenced commit does a few of these things. Doing history right is more involved, as it involves modifying each command individually to have its own history variable. Doing it with just a single variable for all commands (like before) would be straightforward.

**Comment by dmb2** [comment]
@equwal Revert this with a PR ASAP.  This is why it is so important to make sure that the default behavior is maintained, and any new behavior is enabled with a user-configurable option whose default is to maintain the old behavior.

I don't like changing default bindings.  Is there any way to make this an opt-in option?

**Comment by emacsomancer** [comment]
@equwal Tangentially, is it possible to get Levenshtein Algorithm-style fuzzy matching in StumpWM? (E.g. "dlwn" can match "delete-window") I'm used to this behaviour from Emacs.

**Comment by equwal** [comment]
> @equwal Tangentially, is it possible to get Levenshtein Algorithm-style fuzzy matching in StumpWM? (E.g. "dlwn" can match "delete-window") I'm used to this behaviour from Emacs.

Sure it is. I was using the already built in `select-from-menu` function, which uses regexes by default. Just apply a different filter function and it should work.

**Comment by equwal** [comment]
> Though it would of course be nice to have a hybrid - best of both worlds, but until someone can produce such a code, it seems more convenient to put this on ex. ^-t , or some other meaningful combo for now.

It is possible to show completions in the input menu without using `select-from-menu`. This seems like the path forward.

**Comment by emacsomancer** [comment]
Is there a way of allowing the new behaviour to be optionally enabled, or otherwise accessed?

(Also, it seems that the reverting of the change affects `EXEC` (prefix+!).)
