### ISSUE TITLE
Border around frames with emacs

### ISSUE THREAD

**Issue by M4rkD** [stumpwm/stumpwm#719]
This is specific to emacs, but I was getting extra padding around emacs frames when tiled. In order to get get rid of this space, I had to include the following lines in my emacs config.

```
(add-to-list 'default-frame-alist '(undecorated . t))
(add-to-list 'default-frame-alist '(fullscreen . maximized))
(setq frame-resize-pixelwise t)
```
I believe stumpwm isn't the only window manager to do this. Is there anything that can be done about this?

If not, maybe we can pop this in the wiki (in the hope of saving time for others).

**Comment by jorams** [comment]
You can do this for all applications by setting `*ignore-wm-inc-hints*` to `t`:

```lisp
(setf *ignore-wm-inc-hints* t)
```

The reason it happens is that StumpWM honors size hints by default. Applications use these hints to tell the window manager things like the minimum and maximum size of the window, but also the amounts to increment the width and height by. Emacs, as well as various other applications, specify increments based on character sizes.

**Comment by M4rkD** [comment]
Thanks @jorams, I'm glad I raised this now - your solution is worth knowing. Much appreciated.

Hopefully, having it noted here might help others who stumble across this behavior.

I'll close the issue, as I can't see any actions to take.
