### ISSUE TITLE
Build error after commit 2f073d8

### ISSUE THREAD

**Issue by Jehops** [stumpwm/stumpwm#722]
Here is a full build log: http://pkg.awarnach.mathstat.dal.ca/data/12amd64-default/2020-01-10_11h22m35s/logs/errors/stumpwm-19.11.73_1.log

I believe the error started after upgrading SBCL.  If the issue is not obvious, over the weekend I can try testing different SBCL versions and/or dissecting StumpWM commits.

**Comment by PuercoPop** [comment]
Hey thanks again for. The error is not particularly obvious. It seems similar to the previous one, where there was a function that was only defined for Linux using the `#+linux` feature expression, but I checked the manual to see if readline-from-sysfs had crept into it once again but it doesn't appear to be the case.

It would be great if you could run a git bisect to find out the offending commit. This would be the 3rd time this year we have broken the build on OpenBSD so I think we should take proactive measures to avoid doing so in the future.

I've heard good things about the OpenBSD support of builds.sr.ht so we should setup the CI to build every PR on OpenBSD as well as Linux. I have a [build manifest for ubuntu](https://builds.sr.ht/~puercopop/job/135249) working. If you could provide me with the sequence of shell commands you use to build StumpWM I can write a build manifest for OpenBSD.

@dmb2 Are you ok with us using builds.sr.ht?

**Comment by Jehops** [comment]
I'll try to dig deeper this weekend.  I am using the _FreeBSD_ port to build it, but I can also try quicklisp and different SBCL versions to try and get to the bottom of the problem.

**Comment by PuercoPop** [comment]
Ok, lets do FreeBSD then. I run into some issues installing quicklisp on the sbcl from ports. Any tips? https://builds.sr.ht/~puercopop/job/135275

**Comment by Jehops** [comment]
It seems commit 7fc3def introduces the build failure.  The previous commit, 747b6c3 builds fine with SBCL 2.0.0.  I can also build the latest commit (currently bf0b06a) with `stumpwm.texi.in` reverted to 747b6c3: http://pkg.awarnach.mathstat.dal.ca/data/12amd64-default/2020-01-12_11h49m01s/logs/stumpwm-19.11.75.log

@PuercoPop, hooking CI in to one or both of the BSDs would be much appreciated.  I mention FreeBSD, because I think OpenBSD and FreeBSD could be sufficiently different.  I can really only offer information about FreeBSD, since I'm only a rare OpenBSD user.

An easy and helpful way to CI test StumpWM on FreeBSD would be to test via [the port](https://www.freshports.org/x11-wm/stumpwm/).  When a new commit is added, this is what could be done (using commit bf0b06a as an example)

- In the repository do `git describe --tags bf0b06a`
- In `usr/ports/x11-wm/stumpwm/Makefile` set `DISTVERSION` to `19.11-75` and `DISTVERSIONSUFFIX` to `-gbf0b06a`.
- In the same directory, run `make makesum` to regenerate the `distinfo` file.
- [Poudriere](https://www.freebsd.org/doc/handbook/ports-poudriere.html) is our port testing tool.  It is a bit involved to set up.  If you think it's useful, I can help with that.  To build directly, you can run `make install` in the same directory.

If you prefer to use quicklisp, I can take a closer look at the issues above.  It's hard to tell without the commands shown, but I guess the problem is described in the message when the SBCL package is installed.

```For Common Lisp ports requiring the asdf system definition library from
devel/cl-asdf, %%PREFIX%%/etc/asdf-init.lisp has been set to load in
%%PREFIX%%/etc/sbclrc.  If you plan to use Quicklisp, you must remove
this line from %%PREFIX%%/etc/sbclrc.```

**Comment by dmb2** [comment]
Lets set up a CI for any *BSD if its available and easy to implement.

**Comment by dmb2** [comment]
@Jehops This build failing on this commit is very odd, can you make sure that you have completely cleaned build artifacts each time you bisect?  On linux, the paths end up in ~/.cache/, I'm not sure if the same is true in *BSD.

**Comment by Jehops** [comment]
Sorry!  I somehow wrote the wrong hash.  Instead of 7fc3def I should have written 2f073d8.  I clearly meant 2f073d8, because I wrote, "The previous commit, 747b6c3 builds fine with SBCL 2.0.0.".

I am confident that no build artifacts are affecting things, because I test in a clean jail (OS-level virtualisation) each time.  Also, when I build on bf0b06a with `stumpwm.texi.in` reverted to 747b6c3 the build completes.

**Comment by Jehops** [comment]
I dug a little deeper.  It's [this line](https://github.com/stumpwm/stumpwm/commit/2f073d8ce7945771b3f0c38817ee7a79f306fd10#diff-8f2afcb3bd61a7e00271f0dd613fa3e9R2144) that adds `@@@ read-line-from-sysfs` to `stumpwm.texi.in` that is causing the build problem on FreeBSD.  That function is defined in `wrappers.lisp` and I'm guessing the line above is an indication that it's for Linux only.
