### ISSUE TITLE
Issue using fnext accross screens

### ISSUE THREAD

**Issue by triclops200** [stumpwm/stumpwm#723]
It just says "No other frames" instead of switching accross screens.

I'm almost certain it's because (only-one-frame-p) is returning nil for the conditional added in commit 7e47a4d50ed4643b1cdf076c6e1af341f9a90657, which, looking at the source of only-one-frame-p, I'm certain that's correct. I could fix this myself, but there seems to be multiple options to fix this. Either make only-one-frame-p take a parameter for multiple-head counting or make a new function for counting frames accross heads.

I've been relying on the old behavior of fnext traversing screens for a very long time, so, if the new behavior of fnext staying on a head is what is desired by the dev team, it'd be nice if that could be made an option, though, currently, it's even bugged for that new behavior as it'll traverse from a head with multiple windows to a head with one, but it can't leave once it's there.

**Comment by ak-coram** [comment]
Hi, I already submitted PR #721 regarding this issue, it checks the number of frames passed to `focus-frame-after` directly instead of using `only-one-frame-p`. I'm not sure if this is the right approach, but it works for me as a workaround.

**Comment by ak-coram** [comment]
@triclops200: the aforementioned PR #721 seems to have been merged. I hope it works for you and the issue can be closed.

**Comment by triclops200** [comment]
Works for me! Closing.
