### ISSUE TITLE
New default `exec` UI lags after the first char, discards the following chars

### ISSUE THREAD

**Issue by madand** [stumpwm/stumpwm#741]
## Problem
The new "enhanced" UI for the `exec` command consistently exhibits the following annoying behavior. It discards the second (and third if you type fast enough) typed character, leaving you with only the first typed character and long list of candidates.

## Steps to reproduce
1. Open the `exec` widget with e.g. `Ct !`.
2. In the opened input widget rapidly type some 2- or 3-character prefix for some shell command. For example you can type `em` for Emacs.

## Expected behavior
Have all the character typed present in the input widget.

## Observed behavior
Second character typed is not present, due to a lag caused by filtering the list of candidates. Actually the candidates are cached the first time a prefix is used, but lag is still sufficient enough to cause character "loss" even when the cached candidates list is re-used.

## Proposed solution
Make the new and fancy stuff **optional** and **opt-in**.

**Comment by PuercoPop** [comment]
I just tried to reproduce and the observed behaviour is worse. The second character is not lost, it is sent to the currently selected window. Try to reproduce but before opening the exec widget have your cursor in the text area at the bottom of the issue and you'll see!

You can also reproduce the issue with other text inputs like `C-t ;`. This points to the underlying issue being  a bug in the code that handles that handles the input window.

**Comment by madand** [comment]
I confirm the "lost" chars are indeed sent to the active window.

**Comment by equwal** [comment]
#749 is a workaround for this.

**Comment by m-g-r** [comment]
> I just tried to reproduce and the observed behaviour is worse. The second character is not lost, it is sent to the currently selected window.

Thanks for pointing this out! I noticed that the StumpWM input handling is too slow for me typing on the two machines where I use it but haven't noticed so far that the input goes somewhere else. Maybe that explains some spurious characters in some files I noticed at "commit time".
