### ISSUE TITLE
stumpwm dying when using gimp and other such programs

### ISSUE THREAD

**Issue by fare** [stumpwm/stumpwm#742]
Running `gimp` will kill stumpwm before it's done initializing. Using `display` from ImageMagick can also kill stumpwm when called with pictures of some sizes (I haven't dug too deep which pictures confuse stumpwm yet).

**Comment by fare** [comment]
NB: My workaround is to use `pinta` for simple image editing.

**Comment by madand** [comment]
Cannot reproduce with `GIMP 2.10.16` and `master` StumpWM. `display` is also works OK.

**Comment by PuercoPop** [comment]
I can't reproduce either. Do we have to do something specific with gimp?

**Comment by equwal** [comment]
I wonder if this issue has to do with the way the older gimp versions do dialogues (expecting a stacking floating window manager). Newer gimps do not spam a bunch of windows by default when loaded.

**Comment by fare** [comment]
I can't currently reproduce anymore. It might have been an environmental issue, such as having an out-of-date `$GDK_PIXBUF_MODULE_FILE` or some such. Or it might have been fixed by my loading a newer stumpwm. Or something. Closing for now. I will reopen if I can reproduce. (I was using GIMP 2.10.12)
