### ISSUE TITLE
Right alignment in mode line overlaps with stumptray, resulting in hidden characters

### ISSUE THREAD

**Issue by szos** [stumpwm/stumpwm#744]
When using both stumptray and the right alignment command (`^>`), the text pinned furthest right gets placed under stumptray, and is invisible. If one only ever has one item in the tray it can be worked around by appending spaces to whatever text will be pinned to the right, but this doesn't work if items arrive and leave the tray.

**Comment by jorams** [comment]
Previously reported as stumpwm/stumpwm-contrib#25. In stumpwm/stumpwm-contrib#56 we added [`%T`](https://github.com/stumpwm/stumpwm-contrib/blob/ec9e7c5297a6072eb3c0dfe0745c26fc85c3cdc5/modeline/stumptray/stumptray.lisp#L676) to Stumptray to combat this.

Simply add it to the end of your mode line format and possibly tweak `stumptray:*tray-placeholder-pixels-per-space*`.
