### ISSUE TITLE
fselect command leaves white boxes on screen

### ISSUE THREAD

**Issue by equwal** [stumpwm/stumpwm#745]
The boxes with numbers in them (from `fselect`) leave behind white boxes. Some kind of refresh must be done to fix it. Once it happens, the only way to get rid of them currently is to restart the manager.

Reproduction
- open some applications (eg. xterms)
- `expose` (calls `fselect`, makes for maximum bugging by splitting up the screen).
- abort with `ESC`.
![boxing](https://user-images.githubusercontent.com/13551856/76175771-51cce980-616b-11ea-95d6-0fd3c94ceee1.png)

**Comment by epanji** [comment]
I previously have same case like above, but now I can't reproduce it again after version "18.11-216-gb5300b1 Compiled On Fri Mar 13 2020 22:31:02" with commit head b5300b11ce19da124d4267a530bd276c0a0d763b

Not sure what happen that make it fixed. Let me compile to latest commit first and try it again.

**Comment by epanji** [comment]
Still can't reproduce it again with commit head c01fdae9b04a21db4dda32e63c4c46b688b7213a

**Comment by equwal** [comment]
Oddly enough I can't reproduce it now either. I'll close, make a new issue if it comes back I guess.
