### ISSUE TITLE
Programs should load into the group they are started in, not to the group that is the current display.

### ISSUE THREAD

**Issue by equwal** [stumpwm/stumpwm#754]
When I open a program, I expect it to open in the group I was in _when I ran the program_. Currently it is possible to start a program that boots slowly (eg. Firefox or Emacs), switch groups, and have it load into the new current group. This is problematic for scripting programs into particular groups, because they will not go into the right group! Code like this cannot be expected to work:

```
(gnew "Emacs")
(gselect "Emacs")
(emacs);Cannot expect emacs to be in the Emacs group!
(gselect "Default")
```

This might seem like a trivial bug, but it is problematic in this usecase of setting up windows and groups a certain way.

**Comment by PuercoPop** [comment]
This is not possible as there is not way that I can think of to link a new window to the function call that started it.

What you can do is setup a named hook (that is a function defined by defun not lambdas) that looks matches the window the application would create, moves it and removes itself from `map-window-hook` and have the command that launches the application insert the hook into `*map-window-hook*` before starting emails

**Comment by dmb2** [comment]
Hi @equwal, I'm marking this invalid because it isn't a bug.  I understand the behavior isn't what you would like, and you have a sensible explanation for what you expect.  Unfortunately its not something we can support with the way the code is structured.  

I hope @PuercoPop's suggestions work for you!

**Comment by equwal** [comment]
> Hi @equwal, I'm marking this invalid because it isn't a bug. I understand the behavior isn't what you would like, and you have a sensible explanation for what you expect. Unfortunately its not something we can support with the way the code is structured.
> 
> I hope @PuercoPop's suggestions work for you!

Yes, I greatly appreciate those suggestions. Now I see there is support for this. Thanks.
