### ISSUE TITLE
Wishlist: completing-read-multiple

### ISSUE THREAD

**Issue by equwal** [stumpwm/stumpwm#758]
Why is `Emacs' completing-read-multiple function` on the wishlist?

I think this seems like a straightforward project, although I don't know why we need CSV inputs. Maybe a different system, like repeated prompts after `RET` could be useful.

I have a project that does CSV at https://spensertruex.com/csv which I could repurpose. Otherwise I suggest removing this.

The git blame shows @dmb2 in 2015 here.

More generally I suggest removing the wishlist since it seems outdated and to have been superseded by the Github issue system.

**Comment by dmb2** [comment]
It got migrated from the old wiki, the wish list is not a requirements list.  Its a space for "it would be nice if someone contributed some code, but we'll manage without" list.  If you've got code that would work, feel free to open a PR!

**Comment by equwal** [comment]
> It got migrated from the old wiki, the wish list is not a requirements list. Its a space for "it would be nice if someone contributed some code, but we'll manage without" list. If you've got code that would work, feel free to open a PR!

My question was how this specific item could fit into StumpWM at all.
