### ISSUE TITLE
error when compiled with sbcl 2.0.3

### ISSUE THREAD

**Issue by emacsomancer** [stumpwm/stumpwm#760]
When I try to launch a StumpWM compiled with sbcl 2.0.3, I get an error:

`don't know how to REQUIRE sb-clt12`

**Comment by PuercoPop** [comment]
This seems to be more an error with your SBCL installation not finding contribs that with StumpWM. What happens if you try running `(require "sb-cltl2")` in a bare REPL?

**Comment by emacsomancer** [comment]
```
CL-USER> (require "sb-cltl2")
NIL
```

I tried starting with a empty `init.lisp`, and then evaluating my original `init.lisp`.  It chokes at the line `(set-prefix-key (kbd "s-f"))`, with the output:

```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION STUMPWM::SCREEN-CURRENT-GROUP (1)>
when called with arguments
  (NIL).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
See also:
  Common Lisp Hyperspec, 7.6.6 [:section]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [RETRY] Retry SLIME interactive evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT] abort thread (#<THREAD "worker" RUNNING {100544CBB3}>)

Backtrace:
  0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION STUMPWM::SCREEN-CURRENT-GROUP (1)> NIL) [fast-method]
  1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION STUMPWM::SCREEN-CURRENT-GROUP (1)> (NIL))
  2: (SCREEN-CURRENT-WINDOW NIL)
  3: (SYNC-KEYS)
  4: (SET-PREFIX-KEY #S(KEY :KEYSYM 102 :SHIFT NIL :CONTROL NIL :META NIL :ALT NIL :HYPER NIL ...))
  5: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SET-PREFIX-KEY (KBD "s-f")) #<NULL-LEXENV>)
  6: (EVAL (SET-PREFIX-KEY (KBD "s-f")))
 --more--

```

(Currently I've downgraded back down to 2.0.2.)

**Comment by dmb2** [comment]
Make sure your SBCL_HOME variable is set correctly if SBCL lives in a non-standard place.

**Comment by emacsomancer** [comment]
> Make sure your SBCL_HOME variable is set correctly if SBCL lives in a non-standard place.

it's just the packaged version from my distro, and so lives in `/usr/bin/sbcl`. I updated the quicklisp packages &c. but still have the same issue. Is there something else that could be the issue aside from changes in the new sbcl version?

**Comment by jorams** [comment]
Does the file `/usr/lib/sbcl/contrib/sb-cltl2.asd` exist?

**Comment by emacsomancer** [comment]
> Does the file `/usr/lib/sbcl/contrib/sb-cltl2.asd` exist?

yes

**Comment by alaa-alawi** [comment]
The same happened to me, last week I updated both and compiled both (SBCL,
StumpWM).
Then I narrowed it to (require :swank).
I commented it and went completing other tasks (currently I'm not doing
much REPL).

HiH

**Comment by marcowahl** [comment]
Same issue here.  I use slynk instead of swank BTW.

My naive pragmatic fix: Add dependency #:sb-cltl2 in stumpwm.asd.

**Comment by jorams** [comment]
This is actually due to a change in SBCL. Previously it would remember the prefix SBCL was installed in. Now it forgets the value when saving an executable, and determines the location based on the location of the executable. This allows the SBCL install tree to be moved to an arbitrary location.

Unfortunately, when you dump an executable and then load your `.stumpwmrc` on startup, where you can do arbitrary things, you still want those things to use your normal SBCL installation.

You can fix this by setting the `SBCL_HOME` when starting StumpWM, e.g.

```
SBCL_HOME=/usr/lib/sbcl/ startx
```

**Comment by emacsomancer** [comment]
Thanks, @jorams . Proceeding as you suggest does indeed seem to solve the issue.

(In my case, since I use a display manager, I added `export SBCL_HOME=/usr/lib/sbcl/` to my (otherwise empty) `~/.xprofile`.)

**Comment by alaa-alawi** [comment]
Confirming the same. It works now.

I have linuxmint 19.1 box, with lightdm, and I had exported SBCL_HOME from .xsessionrc

Thanks!

**Comment by stindrago** [comment]
I solved this by adding `export SBCL_HOME=/usr/lib/sbcl/` before `exec [...]` in `~/.xinitrc`.

**Comment by joshcho** [comment]
> I solved this by adding `export SBCL_HOME=/usr/lib/sbcl/` before `exec [...]` in `~/.xinitrc`.

I am having a similar issue with SBCL 2.2.9, and this worked (and not anything else). Thanks.

**Comment by MIvanchev** [comment]
Having similar issue with SBCL 2.3.5 for SB-ROTATE-BYTE, @jorams saved me from insanity.
