### ISSUE TITLE
Completition breaks command gnewbg

### ISSUE THREAD

**Issue by jamesmccabe** [stumpwm/stumpwm#766]
I am using the latest version of stumpwm from git.
When I try to add a new group using the command "gnewbg test" the new input completition feature keeps adding in a dash so I can only type "gnewbg-test". Every time I press Space it adds the dash "-".
The same happens with the command "gnew". 
I have to copy the space from Emacs and use Ctrl+y to insert the space.

Also is there an option to turn off input completition?

**Comment by epanji** [comment]
@jamesmccabe 

There are two solutions for your case:

- Using \<Tab\> for command completion.

- Using M-Space for continue typing without completion.

And for turning off completions, I don't think we have that options for now.

**Comment by jamesmccabe** [comment]
OK thanks! I think I can close this issue so.
