### ISSUE TITLE
Weird issue with window not in frame

### ISSUE THREAD

**Issue by waynee95** [stumpwm/stumpwm#789]
It's the second time that I ran into an issue where a certain application is not inside a frame. I ran into this issue today with OpenBoard. 

http://openboard.ch/index.en.html

I launch that application and it will go in full screen mode. Ignoring any current frame layout.

Executing any frame split on that application will also not work.

Any idea why that's happening?

**Comment by PuercoPop** [comment]
It seems to me you are describing a case when the window opens in fullscreen. If you want the window to be placed in a frame you would have to take the window out of fullscreen.

**Comment by waynee95** [comment]
This still happens when I open the application in a halfscreen frame or smaller.

The application will simply ignore any frames ans will _act_ as it were fullscreen. This messes up every other window. If I now cycle through them, they layover half or do not display correctly.

This contradicts the behavior of other applications. If I open Firefox inside a half screen frame, it will be placed correctly inside that frame.

**Comment by PuercoPop** [comment]
> This still happens when I open the application in a halfscreen frame or smaller.

Fullscreen behaviour is unrelated to frames. By default, Firefox doesn't not open in fullscreen. Clients can go fullscreen w/o the Window Manager explicitly requesting it. Normally only games, like Dota2, open in fullscreen. Sometimes other applications also go into fullscreen w/o the user explicitly requesting it, ej. zoom when someone in the meeting shares a screen. If you press F11 in Firefox does it behave in the same manner as you OpenBoard?

**Comment by waynee95** [comment]
@PuercoPop 
Oh, I see! 

For some reason I thought "fullscreen" = frame is the entire screen. Okay, so yes, it's behaving the same as firefox with F11.

Although I could not find any option inside the OpenBoard options menu  to have it not always in fullscreen.

**Comment by waynee95** [comment]
Using the fullscreen command from Stumpwm, I can solve my issue, which has not really been an actual issue. So I close this.
