### ISSUE TITLE
Why do you use Google?

### ISSUE THREAD

**Issue by resynth1943** [stumpwm/stumpwm#793]
The default configuration file uses Google's privacy-invasive search engine. With respect to yourselves, this is quite a dangerous default for unsuspecting users.

I would suggest replacing Google with [DuckDuckGo](https://duckduckgo.com), a privacy-respecting and more open search engine.

Many thanks,
Synth.

**Comment by jorams** [comment]
StumpWM does not use Google. The `sample-stumpwmrc.lisp` contains a reference to google.fr, but nobody uses that (as seen in #768, which existed for 16 years).

I've replaced the sample with DuckDuckGo in fa77624ac0568228f8935926e1b355904b5f34ce.

**Comment by resynth1943** [comment]
Thank you for removing the Google code :-)
