### ISSUE TITLE
Emacs M-f (right-word) M-b (left-word) functionality in all applications

### ISSUE THREAD

**Issue by rssoc** [stumpwm/stumpwm#794]
I've been wondering for a while now if it was possible to have the fantastic ``M-f`` and ``M-b`` keybindings from Emacs to work in all of my other applications (Firefox, Chrome, etc).

It's one of those features I miss from EXWM and hope it's something that can be implemented into StumpWM.

**Comment by szos** [comment]
There is a way to emulate this iff the target application supports forward/backward-word functionality. (I know firefox supports it). Using [`define-remapped-keys`](http://stumpwm.github.io/git/stumpwm-git_2.html#Remapped-Keys) you can create a translation layer between stumpwm and the application, where stump grabs the key, and sends the translated key instead. An example for firefox: 
```
(define-remapped-keys
    '(("Firefox"
       ("M-f" . "C-Left")
       ("M-b" . "C-Right"))))
```
For other applications you'll need to find the appropriate keybinding to move forward/backward a word.

**Comment by rssoc** [comment]
Wow, I feel dumb.
I had no idea that C-Left and C-Right was something that was already built into browsers (it looks like chrome supports this as well). Also, looking back at how EXWM handles the keybindings for ``M-f`` and ``M-b``reveals that they do a similar thing.

Closing this issue now, but I will submit a pull request to add this onto the stumpwm.github.io manual along with the other key-remapping examples on https://stumpwm.github.io/git/stumpwm-git_2.html#Remapped-Keys
