### ISSUE TITLE
problem installing stumpwm in Ubuntu 18.04 LTS (bionic)

### ISSUE THREAD

**Issue by HumHongeKamyaab** [stumpwm/stumpwm#803]
I have tried different versions of stumpwm and sbcl, but I am getting black screen when I login to stump desktop environment and no key combo is working.
I tried following versions :
For sbcl (apt version, 1.4.5), (compiling from source, 2.0)
For stumpwm (apt version), (compiling from source)

I am using `stumpwm.desktop` file in `/usr/share/xsessions` to start stumpwm.

Can someone update me the versions of sbcl and stumpwm with which it is working on Ubuntu bionic 
Also it would be helpful if documentation contains installation steps for specific distributions. It will be helpful for beginners like me.

**Comment by PuercoPop** [comment]
What are the contents of your StumpWM file? I'm on 18.04 running w/ no issue.

**Comment by HumHongeKamyaab** [comment]
@PuercoPop Can you confirm me the versions of `sbcl` and `stumpwm` you are using in your working stumpwm. It is given in stumpwm wiki that Ubuntu users should not use `sbcl` from `apt`. Have you compiled `sbcl` yourself.
- file `/usr/share/xsessions/stumpwm.desktop`
```
[Desktop Entry]
Encoding=UTF-8
Type=XSession
Exec=stumpwm
Name=StumpWM
Comment=A minimal Window Manager with no mouse support.
```

**Comment by PuercoPop** [comment]
Yeah, I compile SBCL myself. I'm running a the commit that was head when I last updated it, `2.0.0.257-827dc4e83`. For stumpwm I also running on the commit `060898c` through cl-launch

Currently I'm not using a graphical login manager to start StumpWM but have done so in the past (Ubuntu 16.04 LTS). The only thing missing from you .desktop entry is to start stumpwm under a dbus session. Try replacing the Exec entry with. (The full path is not necessary afaiu but it never hurts)

`Exec=dbus-launch --exit-with-session /full/path/to/stumpwm`

**Comment by HumHongeKamyaab** [comment]
@PuercoPop 
Thanks for reply.
I am just beginner.
Can you explain what is meaning of  `though cl-launch`, and why `dbus` is needed as it is not given in stumpwm wiki

**Comment by PuercoPop** [comment]
It means I use [cl-launch] to start StumpWM. That way I don't need to rebuild StumpWM when updating it. But the regular way to build StumpWM should work too.

> Why dbus is needed as it is 

Before we jump to conclusions, did that fix the issue? dbus is needed for some services won't work. I don't recall which ones. Maybe Network Manager? Don't quote me on that, I'm just cargo-culting here :grimacing: 


[cl-launch]: https://github.com/fare/cl-launch

**Comment by HumHongeKamyaab** [comment]
I am not able to compile latest stumpwm (git version) in Ubuntu 18.04.
I am using latest `sbcl 2.0.7`, and getting following error when I used `make` command 
```
debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {10008B8083}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "stumpwm" "head">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "stumpwm" "head">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "stumpwm" "head">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [RETRY                        ] Retry EVAL of current toplevel form.
  7: [CONTINUE                     ] Ignore error and continue loading file "/home/opt/stumpwm/load-stumpwm.lisp".
  8: [ABORT                        ] Abort loading file "/home/opt/stumpwm/load-stumpwm.lisp".
  9:                                 Retry EVAL of current toplevel form.
 10:                                 Ignore error and continue loading file "/home/opt/stumpwm/./make-image.lisp".
 11:                                 Abort loading file "/home/opt/stumpwm/./make-image.lisp".
 12:                                 Ignore runtime option --load "./make-image.lisp".
 13:                                 Skip rest of --eval and --load options.
 14:                                 Skip to toplevel READ/EVAL/PRINT loop.
 15: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "stumpwm" "head">)))
   source: (ERROR 'COMPILE-FILE-ERROR :CONTEXT-FORMAT CONTEXT-FORMAT
                  :CONTEXT-ARGUMENTS CONTEXT-ARGUMENTS)
``` 

I have tried `ACCEPT`, `CONTINUE` steps but it don't produce correct binary and black screen persists while using this executable of stumpwm.

**Comment by PuercoPop** [comment]
What is the output of evaluating `(ql:where-is-system "clx")` in the SBCL REPL?

**Comment by HumHongeKamyaab** [comment]
@PuercoPop 
```
#P"/usr/share/common-lisp/source/clx/"
```

**Comment by PuercoPop** [comment]
Ok that is the version installed by apt. Which is ancient. Don't use that, install clx using Quicklisp

**Comment by HumHongeKamyaab** [comment]
@PuercoPop 
Thanks its working now.

Just to clarify for future Ubuntu users. 
Remove all the sbcl, clx ... etc components installed through `apt` from your machine. 
Strictly follow the installation steps mentioned in the README, i.e compile latest `sbcl` from source, install `clx` ... etc using `quicklisp`, and compile latest `stumpwm` from its source code.
Use this as your executable,
```
Exec=dbus-launch --exit-with-session /full/path/to/stumpwm
```
