### ISSUE TITLE
font issue in GUI applications

### ISSUE THREAD

**Issue by HumHongeKamyaab** [stumpwm/stumpwm#804]
I am getting weird fonts in some of my GUI applications. Check following screenshots

- Inkscape
![image](https://user-images.githubusercontent.com/19993444/90239682-3a83dd80-de28-11ea-920f-b39301453d31.png)

- Emacs
![image](https://user-images.githubusercontent.com/19993444/90239868-8afb3b00-de28-11ea-8e91-ac6671b8ed16.png)

I found following possible solution on `stumpwm` Arch Wiki, but it seems outdated.
The `ttf-fonts` module requires `clx-truetype` which I am unable to install. 
```
(ql:quickload "clx-truetype")
(load-module "ttf-fonts")
(set-font (make-instance 'xft:font :family "DejaVu Sans Mono" :subfamily "Book" :size 11))
```
Can someone update the above section on Arch Wiki and let us know the updated way to resolve this font issue. 
BTW, I am running Ubuntu 18.04 Bionic.

**Comment by tychoish** [comment]
clx-truetype should only really affect the fonts that stump uses to render in its menu and mode line, which I don't think is the issue that you're having, which might just be font configuration in general. I'd take a look at the gnome/gtk theme that you have set. I've used a program called `gtk-chtheme` to configure these settings in the past. Also, the new "Adobe Source Code Pro" font (which is a F/OSS font) looks amazing, and I'd highly recommend that. 

The problem with clx-truetype is that the API changed and stump hasn't updated or decided what direction to go in. I've attached the last known (to me) good version of clx-truetype which you can put in `~/quicklisp/local-projects/` as a workaround.

[clx-truetype.tar.gz](https://github.com/stumpwm/stumpwm/files/5074849/clx-truetype.tar.gz)

**Comment by HumHongeKamyaab** [comment]
@tychoish Thanks for the help.
- inkscape
![image](https://user-images.githubusercontent.com/19993444/90257467-82fec380-de47-11ea-87e8-4469f75f7294.png)

I installed `gtk-chtheme` using `apt` and change my theme and font setting.

**Comment by jorams** [comment]
Just to quickly note here: The API for clx-truetype did not change, but it disappeared from Quicklisp. #659 is the relevant issue.

**Comment by tychoish** [comment]
Oh, sorry! I didn't have the context for that. 

I've also noted that there's still a `truetype-clx` package in QL, and thought that there was some API change, but it makes sense that that's a different project.
