### ISSUE TITLE
Send-raw-key unable to send key combinations like C-n

### ISSUE THREAD

**Issue by glptrst** [stumpwm/stumpwm#807]
I'm using some remapped keys in the browser. For example, C-n is bound to Down, exactly as it is shown in the manual. The manual also says that:

>  if the original key binding needs to be explictly applied the send-raw-key command may be used. It will prompt for a key which will be passed to the application as-is. For example, if the send-raw-key command were bound to C-t C-q as follows:
> 
> (define-key *root-map* (kbd "C-q") "send-raw-key")
> 
> Then, pressing C-t C-q, while the Firefox window has focus, would prompt asking for “Press a key to send”. Pressing C-n at the prompt will send the keystroke as-is to Firefox, causing it to open a new window.

I bound `send-raw-key` to C-t C-q as shown. The problem I'm experiencing is that I get the intended behavior (the browser actually receives C-n and opens a new window) only if I hold down the same Control key for the entire sequence. If I press C-t C-q C-n, holding down right (or left) Control during the whole sequence, the browser correctly receives C-n. Anything else won't work; for example, pressing C-t C-q with right Control and C-n with left Control); `send-raw-key` seems to send Control as soon as Control is pressed, before n is pressed. Same problem when executing `send-raw-key` with C-;.

**Comment by CatherineTower** [comment]
I'm having a look at this one, if that's all right

**Comment by glptrst** [comment]
Thank you, Catherine!

**Comment by CatherineTower** [comment]
I've submitted #823 as a potential solution. It looks like the existing function `read-key-no-modifiers` pretty much solves the problem, so it's a pretty easy fix.

**Comment by PuercoPop** [comment]
Thanks @CatherineTower, the PR looks good. @glptrst can you confirm it fixes the issue for you?

**Comment by glptrst** [comment]
@PuercoPop, it seems to work perfectly now. Thanks @CatherineTower!
