### ISSUE TITLE
How to set prefix "winkey" ?

### ISSUE THREAD

**Issue by spavlovich001** [stumpwm/stumpwm#810]
I set (set-prefix-key (kbd "C-z"), but emacs + simple terminal(st) hook this combination and this do not work. in emacs
```
(global-unset-key [(control z)])
(global-unset-key [(control x)(control z)])
```

When I leave st - all combination work fine.

How to set-prefix-key --> winkey?

**Comment by jorams** [comment]
The super key is a modifier, so to use it as a prefix you need to change some keyboard settings. You can make it not be a modifier anymore, and then bind the keycode to a key you can't normally use. I believe F20 is popular for that.

Put the following in your `.xinitrc` (or run it through `run-shell-command`):

```
xmodmap -e 'clear mod4' -e 'keycode 133 = F20'
```

Then you can make F20 your prefix key:

```
(set-prefix-key (kbd "F20"))
```

This does make it impossible to use it as a modifier. Alternatively you can just bind the commands you want in `*top-map*`, with super as the modifier. For example, you could make `s-t` your prefix key, bind `s-e` to a command like `emacs`, etc.

**Comment by spavlovich001** [comment]
Thanks!

**Comment by spavlovich001** [comment]
Resolved
