### ISSUE TITLE
How to implement dynamic tiling like dwm?

### ISSUE THREAD

**Issue by spavlovich001** [stumpwm/stumpwm#811]
How to implement dynamic tiling in stumpwm like dwm?

**Comment by equwal** [comment]
StumpWM doesn't have that yet, so your options are:
- Hack the CL yourself to add it
- Install dwm

**Comment by dmb2** [comment]
@equwal neither of your options are constructive.  Please consider how someone new to our community might react to your response before you write something.  This response add nothing of material to the question.

@spavlovich001 While we don't have dynamic tiling built in yet, it is something I would like to see either as an module or as an extension to stumpwm proper.

The file `dynamic-window.lisp` was a step in this direction.  Essentially you write a driver function to arrange the windows when a new one is added to the current group.  Then you run your command with the `*new-window-hook*` and it re-arranges all the windows when is created or restored.

If you do go down this route, please share code, even if its just a gist from your .stumpwmrc.  Also, you may need to move/add where the new-window-hook is run or make a new hook specifically for calling a dynamic tiling function.  I tried this a while ago and it got a bit squirrelly and I couldn't figure out why.

**Comment by szos** [comment]
While it isnt dwm, Ive implemented a set of [i3-esq autotiling functions](https://gist.github.com/szos/d05d3d11845196d62e8c66548701ec40) . I dont think its exactly the same as i3, but im really not sure, as i dont use i3.

**Comment by jcguu95** [comment]
I suggest to close this issue as we have #851, which is merged into the repo.

**Comment by jcguu95** [comment]
I suggest to close this issue as we have #851, which is merged into the repo.

I'm also working on a floating version of dynamic tiling - 
![Demo](https://raw.githubusercontent.com/jcguu95/stumpwm--dynamic-floating-group/master/img/demo.gif)
