### ISSUE TITLE
debug.lisp missing

### ISSUE THREAD

**Issue by Khong-Ten** [stumpwm/stumpwm#815]
make: *** No rule to make target 'debug.lisp', needed by 'stumpwm'.  Stop.
Did this commit below not fix it?

commit ffa8a9a06816231417d7e53ced873523793548b7
Author: Javier Olaechea <pirata@gmail.com>
Date:   Thu Sep 24 23:30:05 2020 -0500

    stumpwm.asd: Remove non-existent file from the system definition

**Comment by PuercoPop** [comment]
See https://github.com/stumpwm/stumpwm/pull/813#issuecomment-699882078

@Khong-Ten It only fixes it for ASDF, that is (asdf:make "stumpwm") builds. The Makefile is still broken. In particular building the dependency list by 'parsing' the system definition with sed. In the mean time you can replace the FILES variable in the Makefile with the following to get StumpWM to build

```make
FILES=package.lisp support/debug.lisp primitives.lisp wrappers.lisp pathnames.lisp font-rendering.lisp keysyms.lisp keytrans.lisp kmap.lisp input.lisp core.lisp command.lisp menu-declarations.lisp menu-definitions.lisp screen.lisp head.lisp group.lisp bindings.lisp events.lisp window.lisp floating-group.lisp tile-window.lisp tile-group.lisp window-placement.lisp message-window.lisp selection.lisp module.lisp ioloop.lisp timers.lisp stumpwm.lisp user.lisp interactive-keymap.lisp iresize.lisp help.lisp fdump.lisp time.lisp mode-line.lisp mode-line-formatters.lisp color.lisp wse.lisp dynamic-window.lisp remap-keys.lisp manual.lisp version.lisp main.lisp
```

Closing this issue as it is a dupe. Feel free to comment in #813
