### ISSUE TITLE
can't build using Makefile like the instruction said

### ISSUE THREAD

**Issue by Khong-Ten** [stumpwm/stumpwm#816]
I tried adding the below line like you said, and still doesn't build.  You should do a clean git pull, modify the Makefile, and do a build. You'll see. I appreciate the development time and effort, but please don't leave things broken in the master branch? 

I'm just a newbie wanting to use the software. Now it's no longer usable because I can't build it. 

 FILES=package.lisp support/debug.lisp primitives.lisp wrappers.lisp pathnames.lisp font-rendering.lisp keysyms.lisp keytrans.lisp kmap.lisp input.lisp core.lisp command.lisp menu-declarations.lisp menu-definitions.lisp screen.lisp head.lisp group.lisp bindings.lisp events.lisp window.lisp floating-group.lisp tile-window.lisp tile-group.lisp window-placement.lisp message-window.lisp selection.lisp module.lisp ioloop.lisp timers.lisp stumpwm.lisp user.lisp interactive-keymap.lisp iresize.lisp help.lisp fdump.lisp time.lisp mode-line.lisp mode-line-formatters.lisp color.lisp wse.lisp dynamic-window.lisp remap-keys.lisp manual.lisp version.lisp main.lisp

**Comment by PuercoPop** [comment]
> I tried adding the below line like you said, and still doesn't build. 

Can you add step by step instructions of what you did and paste the error? Before telling you to update that line, I've tried building it and it works on my machine.

> I'm just a newbie wanting to use the software.

In that case you should use a release, not what happened to be the current HEAD when you clone the repository. https://github.com/stumpwm/stumpwm/releases

**Comment by PuercoPop** [comment]
Should be fixed with 14b203e2196016f923565a2b3f53cc76609b5dfd
