### ISSUE TITLE
Cannot type space in `colon` mode

### ISSUE THREAD

**Issue by sjl** [stumpwm/stumpwm#822]
At some point since I last updated, StumpWM started entering a `-` instead of a space when I press the space bar in `colon` mode.  This means I can no longer type something like `gnew foo` to run `gnew` with `foo` as the argument because it comes out as `gnew-foo`.

I've tracked it down to https://github.com/stumpwm/stumpwm/commit/38545872f5efbf60ea653ad657af22d25898ca91 so it seems like this is intentional, but this is completely bananas, right?  There's a `-` key on the keyboard -- why remove the ability to run commands with arguments and make the input behavior way more confusing to save... no keystrokes?

**Comment by dmb2** [comment]
I agree. 

    David

**Comment by jamesmccabe** [comment]
@sjl I had this problem too. I tracker it down in command.lisp where Space is mapped to input-insert-hyphen-or-space
My fix is to remap this to: input-insert-space

```lisp
(defcommand colon (&optional initial-input) (:rest)
  "Read a command from the user. @var{initial-text} is optional. When
supplied, the text will appear in the prompt.
String arguments with spaces may be passed to the command by
delimiting them with double quotes. A backslash can be used to escape
double quotes or backslashes inside the string. This does not apply to
commands taking :REST or :SHELL type arguments."
  (let ((*input-map* (copy-structure *input-map*)))
    (define-key *input-map* (kbd "SPC") 'input-insert-hyphen-or-space)
    (define-key *input-map* (kbd "M-SPC") 'input-insert-space)
    (define-key *input-map* (kbd "RET") 'input-complete-and-submit)
    (let ((cmd (completing-read (current-screen)
				": "
				#'emacs-style-command-complete
				:initial-input (or initial-input ""))))
      (unless cmd
	(throw 'error :abort))
      (when (plusp (length cmd))
	(eval-command cmd t)))))
```

**Comment by jamesmccabe** [comment]
@sjl I had this problem too. I tracked it down in command.lisp where the Space key is mapped to 
```lisp
'input-insert-hyphen-or-space
```
My fix is to remap this to: 
```lisp 
'input-insert-space
```

```lisp
(defcommand colon (&optional initial-input) (:rest)
  "Read a command from the user. @var{initial-text} is optional. When
supplied, the text will appear in the prompt.
String arguments with spaces may be passed to the command by
delimiting them with double quotes. A backslash can be used to escape
double quotes or backslashes inside the string. This does not apply to
commands taking :REST or :SHELL type arguments."
  (let ((*input-map* (copy-structure *input-map*)))
    (define-key *input-map* (kbd "SPC") 'input-insert-hyphen-or-space)
    (define-key *input-map* (kbd "M-SPC") 'input-insert-space)
    (define-key *input-map* (kbd "RET") 'input-complete-and-submit)
    (let ((cmd (completing-read (current-screen)
				": "
				#'emacs-style-command-complete
				:initial-input (or initial-input ""))))
      (unless cmd
	(throw 'error :abort))
      (when (plusp (length cmd))
	(eval-command cmd t)))))
```

**Comment by szos** [comment]
I'm the one behind the specific change in in `colon`. It was intended to make StumpWM more consistent with emacs. The change also introduced the keybinding `meta-space` to insert a space, and not a hyphen. The prompt now has a dumb auto-complete; for example if i run `colon` and type `e space f space` it will autocomplete to the only possible command: `echo-frame-windows`. It will also begin inputting spaces after a valid command has been entered. 

I had figured this would be useful given the high number of emacs users, but im wondering now if this would be better as a module. What do you all think?

**Comment by sjl** [comment]
I think it should definitely be a module, or at least configurable with a special variable.  Being more consistent with Emacs isn't an advantage for those of us who aren't Emacs users, and it's extremely confusing to change the keys.  If you want space you press meta space, if you want `-` you press space, if you want to tab complete you press tab or... space?  It's just completely non-intuitive for someone that's not expecting it.

Switching to spaces after a valid command has been entered doesn't really work, because some commands are prefixes of other commands, e.g.:

    gnew<space>float

Is that `gnew float` (create a new group named float) or `gnew-float` (create a new floating group and prompt me for a name)?  You could default to `gnew float` but then require a `-` for `gnew-float` but now I have to remember that *sometimes* I need the dash key and sometimes I don't and I really just want the key I press to appear on the screen.

I'd really just prefer something simple as a default like space for space, dash for dash, tab for complete, like most other programs (aside from Emacs, apparently).

**Comment by szos** [comment]
I can see how this is quite annoying then! Ill work on and submit a pull request to make space be space and yank out the offending code. Ill try to get to this tomorrow, or if not then, the day after. In the mean time, i guess just throw one of the temporary fixes into your init file. Sorry for introducing such an unexpected/unintuitive change.
