### ISSUE TITLE
installing via quicklisp vs manual building

### ISSUE THREAD

**Issue by Luis-Henriquez-1** [stumpwm/stumpwm#826]
The README of stumpwm seems to suggest to install it by cloning it from github and building it, however the FAQ suggests [this blog post](http://www.kaashif.co.uk/2015/06/28/hacking-stumpwm-with-common-lisp/index.html) which suggest installing it via quicklisp. I'm confused as to which way I should install it.

Also, in the blog it says to add the line `exec sbcl --load /path/to/startstump` in the .xinitrc but I it doesn't tell me how to find the path to `startstump` via quicklisp (If it were installed in my system I'd just do `which stumpwm`).

**Comment by jamesmccabe** [comment]
Personally I would use Quicklisp just to install the dependencies.
Quicklisp could load an old library version of Stump whereas you can download the latest version or latest release from this repo by cloning it and building it. You can also hack it this way and just rebuild it. So I would say its more flexible than loading it from Quicklisp but its a personal choice really. If you choose to build it manually...
For your .xinitrc you just need:
```shell
exec /usr/local/bin/stumpwm
```
When you build stump it creates a binary in /usr/local/bin

**Comment by Luis-Henriquez-1** [comment]
@jamesmccabe Thank you. Taking your advice, I cloned it and built it just now.

Time to start the good hack!
