### ISSUE TITLE
Stumpwm 1.0.1 - hang with '%L' in mode-line

### ISSUE THREAD

**Issue by 28446** [stumpwm/stumpwm#827]
Hi,
stumpwm hang[1] just after opening a first window (whatever windows, es. Firefox, xterm, pcmanfm...) with '%L' in mode-line as:

`(setf stumpwm:*screen-mode-line-format*
      (list

;;       '(:eval (stumpwm:run-shell-command
;;              "echo -n `date '+%a %d %h %H:%M'`" t))

       "%L|%d|%g| %M| %c| %l> %W"))`

Without '%L' it does not hang .

PS. I' have no .Xmodmap, but this is not an issue, at least whit no '%L' in mode-line.

xmodmap:  unable to open file '/home/felipe/.Xmodmap' for reading
xmodmap:  1 error encountered, aborting

[1] no control, need to kill X.

**Comment by szos** [comment]
While I dont have an answer for you, you may consider opening this issue in the contrib repo, as thats where the kbd-layout module is. After looking over the code, xmodmap should only be called via the command `switch-keyboard-layout`, not by the `%L` formatter alone. The shell command run by `%L` is `"setxkbmap -print | awk -F'+' '/xkb_symbols/ {print $2}'"`, perhaps try running that in a terminal to see if something is going wrong there? its a long shot but the only thing i can think of at the moment. 

side note, stumpwm has a date command that you can use in place of shelling out to the *nix date command, eliminating the launching of an extra shell and speeding up the mode line :smiley:

**Comment by 28446** [comment]
> The shell command run by `%L` is `"setxkbmap -print | awk -F'+' '/xkb_symbols/ {print $2}'"`

Hi @szos ,
Thank you for your advice, I've solved whit this workaround: 

`(setf stumpwm:*screen-mode-line-format*
      (list
       '(:eval (stumpwm:run-shell-command
                "echo -n `setxkbmap -query | grep 'layout' | cut -d ' ' -f6`" t))
       "|%d|%g|%M|%C|%l>%W"))`

**Comment by 28446** [comment]
> > The shell command run by `%L` is `"setxkbmap -print | awk -F'+' '/xkb_symbols/ {print $2}'"`
> 
> Hi @szos ,
> Thank you for your advice, I've solved whit this workaround:
> 
> `(setf stumpwm:*screen-mode-line-format* (list '(:eval (stumpwm:run-shell-command "echo -n `setxkbmap -query | grep 'layout' | cut -d ' ' -f6`" t)) "|%d|%g|%M|%C|%l>%W"))`

Never mind, still freeze.
I can't figure out why.  With the same piece of script I can print date and time in the modeline without problem, I can run
`setxkbmap -query | grep 'layout' | cut -d ' ' -f6` in a wile loop in bash and it does not freeze.

**Comment by Junker** [comment]
i have the same behavior.

**Comment by Junker** [comment]
I found out it freeze only when create new window. 
I tried to use different methods, exec "setxkbmap", "xkb-switch", even call dbus method "getCurrentLayout" from kbdd, it always freeze stumpwm on new window creating.
But if i create timer with "run-with-timer" and write layout to the variable, and read that variable in modeline, stumpwm not freeze.

Probably problem happen when trying to get layout on the moment when window is creating.
any ideas how can avoid that?

working method:
e.g.:
```lisp
(defvar *xkb-timer*
    (run-with-timer 0 1
       #'(lambda()
         (setf *current-layout* (run-shell-command "xkb-switch")))))

(setf *screen-mode-line-format* (list '(:eval *current-layout*)))	
```
