### ISSUE TITLE
Cannot build master on Debian bullseye (testing)

### ISSUE THREAD

**Issue by fourier** [stumpwm/stumpwm#842]
Error:
```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "RR-GET-OUTPUT-INFO" not found in the XLIB package.
;   
;       Line: 44, Column: 30, File-Position: 1503
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/fourier/Sources/lisp/stumpwm/head.lisp" {100364E753}>
```
SBCL version: SBCL 2.0.11.debian

**Comment by PuercoPop** [comment]
@fourier That error is likely due to using an outdated version of clx. What does `(ql:where-is-system "clx") return?

**Comment by fourier** [comment]
It returns `#P"/usr/share/common-lisp/source/clx/"`. Apparently QL does not install it as long as it is already present.. It might be because I've installed stumpwm from Debian repository first, and then decided to build from sources.

**Comment by PuercoPop** [comment]
> Apparently QL does not install it as long as it is already present.

Yeah, that is the design of quicklisp. It defers to ADSF. Only if ASDF can't find a system does it download it.

Should I go ahead and close the issue?

**Comment by fourier** [comment]
Probably updating installation instructions with this fact could help, before closing.

**Comment by PuercoPop** [comment]
We already have a note in the build instructions about this

> Please do not install SBCL using your distributions package manager, especially Ubuntu. If you do so it is likely that you'll run into problems when building StumpWM due to using obsolete versions of the dependencies.

**Comment by fourier** [comment]
Thanks, I missed it.

**Comment by PuercoPop** [comment]
Its not just you. I think this is the most common bug report we get. We should probably create an issue template requesting some system information when filing a bug report.
