### ISSUE TITLE
Window does not occupy full frame - previous window visible

### ISSUE THREAD

**Issue by fourier** [stumpwm/stumpwm#843]
Here we see the terminal (urxvt) window do not occupy the full area, the background (far2l) is visible. `*window-border-style*` is set to `:none`.
Built on Debian Linux from git commit 6631e9c052aedc7d7008a44de1a8626680912083

![screen_2021-01-12-20-13-35](https://user-images.githubusercontent.com/900250/104361854-51337b00-5513-11eb-8357-9d587fd80eb5.png)
![screen_2021-01-12-20-12-55](https://user-images.githubusercontent.com/900250/104361869-57295c00-5513-11eb-820f-7652a7c451eb.png)

**Comment by jorams** [comment]
The documentation for `*window-border-style*` `:none` points to `:tight`, which says 

> ...the wasted space within the frame is not obscured, revealing the background.

What you're seeing is the background.

I believe setting `*ignore-wm-inc-hints*` to `t` would cause urxvt to fill the frame.

**Comment by fourier** [comment]
It works perfectly! Thanks, closing.
