### ISSUE TITLE
Terminal opacity not handled

### ISSUE THREAD

**Issue by ThomasBucaioni** [stumpwm/stumpwm#855]
At opening, the terminal says:
```
Failed to enable transparency. This happens when your desktop environment does not support compositing.
```

**Comment by jorams** [comment]
StumpWM does not do compositing, but you can run a separate compositor. I believe [picom](https://github.com/yshui/picom) is fairly popular.

**Comment by tychoish** [comment]
I've always used `xcompmgr` but that might be kind of retro at this point.

**Comment by ThomasBucaioni** [comment]
Let me try both compositors, no issue here. Thank you for your answers
