### ISSUE TITLE
[Prefix] c-h shouldn't be hard-coded

### ISSUE THREAD

**Issue by uti5** [stumpwm/stumpwm#891]
As far as I can tell, [prefix] c-h is a hard-coded binding, but it shouldn't be; for, if one prefers a super binding as prefix (after all, c-t is taken by transpose-char, and similarly for all other control bindings), such as s-x, then s-x c-h is unnecessarily awkward: it would be better to be able to press s-x s-h.  The same goes for every other binding involving ctrl in the root maps; but they are not hard-coded.

**Comment by uti5** [comment]
Quick solution: add "s-h" to the list containing "C-h" and "?" in events.lisp.

**Comment by PuercoPop** [comment]
Closed by #902
