### ISSUE TITLE
Discussion / Request: Generative tests using screenshots

### ISSUE THREAD

**Issue by svenssonaxel** [stumpwm/stumpwm#893]
I've seen a lot of small bugs related to redrawing, resizing frames, resizing the desktop, among others. I think this is partly due to the complexity of managing X11 resources without any automatic change tracking to determine what needs updating. For the same reason, I believe that these types of bugs are prone to regression. Any reasonable mock of X11 in order to test this would probably be unreasonably complex and cause more trouble than it solves. I do however believe that it would be possible to, relatively simply, create an end-to-end, generative test suite to address these types of bugs. I envision it something like this:

* Use `Xvfb` as X11 screen for testing purposes. Use imagemagick `import -window root` for taking screenshots automatically.
* Define one or several categories of states, such as
  * The "normal" category that has e.g. hidden modeline and no more than 4, fairly large frames.
  * The "resizing" category that has resizing active, again with all frames fairly large.
* Define a set of invariants that should hold, depending on the state category, such as
  * In a "normal" state, showing then hiding the modeline should result in the same view as before.
  * In a "resizing" state, increasing then decreasing the width should result in the same view as before.
* Use a random seed to generate the commands to 1) create a state 2) take a screenshot 3) execute an applicable invariant 4) take a screenshot.
* Compare the two screenshots, e.g. using [Farbfeld](https://tools.suckless.org/farbfeld/) and `sha256sum`. If they differ, fail the test and generate a complete bug report, including the screenshots.
* Perhaps use docker for running these tests since they have a few more dependencies.

I'd be willing to do some, but not all, of the work - provided this is something the maintainer and community agrees to. So let's discuss it!

**Comment by tychoish** [comment]
This is an exciting idea and I like the idea of being able to do some more testing at different layers of stumpwm! 

Having said that, I have a few questions about this, from a very high level: 

- Tests like this are great, but they can be flaky or unreliable leading to tests that tend to be less reliable, for reasons that aren't great, and while this is maybe ok, it's also the kind of thing that requires more active maintenance, CI, and policing than perhaps we have. 
- xfrb and imagemagick are not on the top of my list of dependencies that I'd be interested in adding these days. They're not super well maintained, and can be a bit finicky. I think this issue describes a great workflow/stack, but also I worry, in the abstract. 

Are there ways to write tests that exercise this part of the code in CL and can run as regular unit tests. I think there's a lot of room (all over) stump to add abstractions between layers (e.g. between clx/display and stump, for mclim and UI elements, etc.) and these are great places to begin layering various kinds of unit/integration tests to exercise the code and systems we already have. There are also a lot of oppertunities (I suspect) to make functionality more _functional_ in a way that is easier to test. 

There's also an interest that I've heard David (and others) talk about where we break the big stumpwm CL package into more reasonable packages, and this might be a good opportunity to build out some of this testing. 

But I'd definitely be interested in talking more about this, and about testing in general.

**Comment by PuercoPop** [comment]
I like the idea. Although imagemagick is necessary. We can query the size using clx. ej:

- start a connection
- ensure there is only one frame.
- split it two times
- kill one
- assert the sizes of the remaining frames are equal (or we can hard-code the screen size in Xvfb to assert specific values, but I'd like to avoid that tbh).

This is similar to the [i3 test suite](https://github.com/i3/i3/tree/next/testcases/t), which I like. They use perl scripts and their IPC to write use cases.

> xfrb and imagemagick are not on the top of my list of dependencies that I'd be interested in adding these days.

Xvfb would only be needed for the CI. for development purposes Xephyr could be used. imagemagick is not needed at all. I'm not aware of Xvfb being any less well-maintained than the rest of the xorg code base.

> Are there ways to write tests that exercise this part of the code in CL and can run as regular unit tests.

There are parts of the codebase that are amenable for that imho. ej testing keymap functions. But other parts like split-frame require an X11 server.

> I think there's a lot of room (all over) stump to add abstractions between layers (e.g. between clx/display and stump, for mclim and UI elements, etc.)

Can you expand on this idea? What would a layer for the display look like? Are you thinking something about GDK and that we would implement a CL only backend for testing?

**Comment by svenssonaxel** [comment]
> they can be flaky or unreliable leading to tests that tend to be less reliable ... it's also the kind of thing that requires more active maintenance, CI, and policing than perhaps we have.

Sure, perhaps a bit flaky. I imagine there might be need for explicit sleep commands to wait for things to take effect and other ugly hacks like that. However, in some ways they might be more robust than unit tests, since they are end-to-end tests. No matter what refactorings are done to the code, these tests would (should) only fail if something is wrong from the user's perspective. So with regard to refactoring, these types of tests should require _less_ maintenance, although with regard to flakyness maybe a bit more. I also think they would _enable_ better CI and policing, but not _require_ them. Even if they are only run manually once per release, I imagine they would still provide a lot of value.

> xfrb and imagemagick are not on the top of my list of dependencies that I'd be interested in adding these days

Perhaps the tests should be able to run against any X11 server. If we want to automate the tests later, Xvfb might be a candidate for a headless X11 server to do so; it doesn't need to become a dependency now. And we'll never need imagemagick in particular, only some way to take screenshots.

> add abstractions between layers ... these are great places to begin layering various kinds of unit/integration tests

Absolutely. But I don't see any reason we can't benefit from both. My belief is that in terms of payoff/effort ratio for writing tests, it would be hard to beat what I outlined above; a simple way to write an end-to-end integration test, from keypress to displayed result. The key question is probably whether this belief is correct.

> We can query the size using clx. ej: ... assert the sizes of the remaining frames are equal

Sure, such things can be baked in as well. We can also use `vsplit`, `move-focus down`, `remove` as one of the invariants or no-ops, and compare screenshots before and after.

**Comment by svenssonaxel** [comment]
OK, just pushed some improvements. Tests can now be truly end-to-end, from keypress to screen draw. I have included 4 sample tests, of which two are failing.

No dependency on imagemagick. It does depend on Xvfb (which the i3 test suite also does), but I have written the test generation in such a manner that it should be fairly easy to switch to or add support for using another X server in tests.

Many generated tests will fail due the the same few bugs related to group resizing and the frame indicator. (Test cases 002 and 003 are minimized to target these issues.) While these bugs might seem minor, I think that it'd be nice to fix them so that we can move on adding more rules to the test generation. For example, I'd like to add rules for fuzzing IRESIZE.

**Comment by svenssonaxel** [comment]
Actually, I have a suggested fix for one of the issues, but I don't know what I'm doing w.r.t. the X11 integration, so someone needs to check this code for resource leaks etc.

```diff
diff --git a/message-window.lisp b/message-window.lisp
index 06a0495..f42592a 100644
--- a/message-window.lisp
+++ b/message-window.lisp
@@ -183,6 +183,24 @@ function expects to be wrapped in a with-state for win."
         (echo-in-window w font (screen-fg-color (current-screen)) (screen-bg-color (current-screen)) string)
         (reset-frame-indicator-timer)))))

+(defun redraw-frame-indicator (group)
+  (when (and (timer-p *frame-indicator-timer*)
+             (find group (mapcar 'screen-current-group *screen-list*)))
+    (let ((frame (tile-group-current-frame group))
+          (w (screen-frame-window (current-screen)))
+          (string (if (stringp *frame-indicator-text*)
+                      *frame-indicator-text*
+                    (prin1-to-string *frame-indicator-text*)))
+          (font (screen-font (current-screen))))
+      (xlib:with-state (w)
+                       (setf (xlib:drawable-x w) (+ (frame-x frame)
+                                                    (truncate (- (frame-width frame) (text-line-width font string)) 2))
+                             (xlib:drawable-y w) (+ (frame-display-y group frame)
+                                                    (truncate (- (frame-height frame) (font-height font)) 2))
+                             (xlib:window-priority w) :above))
+      (xlib:map-window w)
+      (echo-in-window w font (screen-fg-color (current-screen)) (screen-bg-color (current-screen)) string))))
+
 (defun echo-in-window (win font fg bg string)
   (let* ((height (font-height font))
          (gcontext (xlib:create-gcontext :drawable win
diff --git a/tile-group.lisp b/tile-group.lisp
index b1d24e5..c8b2808 100644
--- a/tile-group.lisp
+++ b/tile-group.lisp
@@ -201,7 +201,8 @@
   (populate-frames group))

 (defmethod group-resize-head ((group tile-group) oh nh)
-  (resize-tree (tile-group-frame-head group oh) (head-width nh) (head-height nh) (head-x nh) (head-y nh)))
+  (resize-tree (tile-group-frame-head group oh) (head-width nh) (head-height nh) (head-x nh) (head-y nh))
+  (redraw-frame-indicator group))

 (defmethod group-sync-all-heads ((group tile-group))
   (sync-all-frame-windows group))
```

**Comment by svenssonaxel** [comment]
@tpine Nice work on automated testing. When this test suite matures a bit, maybe we can look into making them play nice?

**Comment by dmb2** [comment]
Sorry for the late reply, I think @tychoish summarized very nicely the pros and cons of this approach.  

Is there a strong reason why we need to add a graphics stack to determine the invariants? Why can't we do this with in-memory structures?

**Comment by tpine** [comment]
@svenssonaxel I'm keen to add this in properly to the test suite and the CI/CD once its merged. Currently the tests we have are very basic and can only tackle anything not using x11 which isn't all that much in a window manager.

**Comment by svenssonaxel** [comment]
@dmb2, you asked:
> Is there a strong reason why we need to add a graphics stack to determine the invariants? Why can't we do this with in-memory structures?

Some of the time I think you can, but I think @tpine answered that quite nicely:

> Currently the tests we have are very basic and can only tackle anything not using x11 which isn't all that much in a window manager.

In order to test the logic of and assumptions made in the x11 integration code, we need to write tests that exercise this part of the program. For that, we need either an x11 server or a mock x11 server. There are downsides with including an x11 server in the testing pipeline, but since x11 is so complicated, I believe the mock route is even worse.

Essentially, in-memory structures contain neither input nor output of what we want to test. That said, when bugs are found in parts of the code that can be tested using in-memory structures only, I'm all for implementing tests without dependency on a graphics stack.
