### ISSUE TITLE
Title: Building Stumpwm Fails  On Debian

### ISSUE THREAD

**Issue by tvraman** [stumpwm/stumpwm#898]
Description: See log below
This is after refreshing quicklisp etc.
./autogen.sh 
19:58:40 raman-glaptop stumpwm $ ./configure 
checking for sbcl... /usr/bin/sbcl
configure: Using sbcl at /usr/bin/sbcl
checking for makeinfo... yes
configure: creating ./config.status
config.status: creating Makefile
configure: creating ./config.status
config.status: creating Makefile
config.status: creating make-image.lisp
configure: creating ./config.status
config.status: creating Makefile
config.status: creating make-image.lisp
config.status: creating load-stumpwm.lisp
19:58:59 raman-glaptop stumpwm $ make
/usr/bin/sbcl --load ./make-image.lisp
This is SBCL 2.1.1.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
; compiling file "/home/raman/sourceforge/stumpwm/command.lisp" (written 25 JUN 2021 07:31:08 PM):
; processing (IN-PACKAGE #:STUMPWM)
; processing (EXPORT (QUOTE #))
; processing (DEFSTRUCT COMMAND-ALIAS ...)
; processing (DEFSTRUCT COMMAND ...)
; processing (DEFVAR *COMMAND-HASH* ...)
; processing (DEFVAR *MAX-COMMAND-ALIAS-DEPTH* ...)
; processing (DEFINE-CONDITION COMMAND-DOCSTRING-WARNING ...)
; processing (DEFMACRO DEFCOMMAND ...)
; processing (DEFMACRO DEFINE-STUMPWM-COMMAND ...)
; processing (DEFMACRO DEFCOMMAND-ALIAS ...)
; processing (DEFUN DEREFERENCE-COMMAND-SYMBOL ...)
; processing (DEFUN COMMAND-ACTIVE-P ...)
; processing (DEFUN GET-COMMAND-STRUCTURE ...)
; processing (DEFUN ALL-COMMANDS ...)
; processing (DEFSTRUCT ARGUMENT-LINE ...)
; processing (DEFVAR *COMMAND-TYPE-HASH* ...)
; processing (DEFUN ARGUMENT-LINE-END-P ...)
; processing (DEFUN ARGUMENT-POP ...)
; file: /home/raman/sourceforge/stumpwm/command.lisp
; in: DEFUN ARGUMENT-POP
;     (LOOP STUMPWM::FOR STUMPWM::I STUMPWM::FROM STUMPWM::START STUMPWM::BELOW (LENGTH
;                                                                                STUMPWM::INPUT)
;           STUMPWM::FOR CHAR = (CHAR STUMPWM::INPUT STUMPWM::I)
;           DO ...)
; --> BLOCK LET LET TAGBODY 
; ==>
;   NIL
; 
; caught STYLE-WARNING:
;   The binding of I is not a REAL:
;    NIL
;   See also:
;     The SBCL Manual, Node "Handling of Types"

; processing (DEFUN ARGUMENT-POP-OR-READ ...)
; processing (DEFUN ARGUMENT-POP-REST ...)
; processing (DEFUN ARGUMENT-POP-REST-OR-READ ...)
; processing (DEFMACRO DEFINE-STUMPWM-TYPE ...)
; processing (DEFINE-STUMPWM-TYPE :Y-OR-N ...)
; file: /home/raman/sourceforge/stumpwm/command.lisp
; in: DEFINE-STUMPWM-TYPE :Y-OR-N
;     (MEMBER STUMPWM::S STUMPWM::POSITIVE-RESPONSES :TEST #'EQUALP)
; 
; caught ERROR:
;   The LET* binding spec (MEMBER S POSITIVE-RESPONSES :TEST #'EQUALP) is malformed.

;     (STUMPWM::DEFINE-STUMPWM-TYPE :Y-OR-N
;         (STUMPWM::INPUT STUMPWM::PROMPT)
;       (LET* ((STUMPWM::POSITIVE-RESPONSES '("y" T))
;              (STUMPWM::S (OR # #))
;              (MEMBER STUMPWM::S STUMPWM::POSITIVE-RESPONSES :TEST #'EQUALP))))
; --> SETF LET* LET* LAMBDA 
; ==>
;   #'(LAMBDA (STUMPWM::INPUT STUMPWM::PROMPT)
;       (LET* ((STUMPWM::POSITIVE-RESPONSES '("y" T))
;              (STUMPWM::S (OR # #))
;              (MEMBER STUMPWM::S STUMPWM::POSITIVE-RESPONSES :TEST #'EQUALP))))
; 
; caught STYLE-WARNING:
;   The variable INPUT is defined but never used.
; 
; caught STYLE-WARNING:
;   The variable PROMPT is defined but never used.

; processing (DEFUN LOOKUP-SYMBOL ...)
; processing (DEFINE-STUMPWM-TYPE :VARIABLE ...)
; processing (DEFINE-STUMPWM-TYPE :FUNCTION ...)
; processing (DEFINE-STUMPWM-TYPE :COMMAND ...)
; processing (DEFINE-STUMPWM-TYPE :KEY-SEQ ...)
; processing (DEFINE-STUMPWM-TYPE :WINDOW-NUMBER ...)
; processing (DEFINE-STUMPWM-TYPE :NUMBER ...)
; processing (DEFINE-STUMPWM-TYPE :STRING ...)
; processing (DEFINE-STUMPWM-TYPE :PASSWORD ...)
; processing (DEFINE-STUMPWM-TYPE :KEY ...)
; processing (DEFINE-STUMPWM-TYPE :WINDOW-NAME ...)
; processing (DEFINE-STUMPWM-TYPE :DIRECTION ...)
; processing (DEFINE-STUMPWM-TYPE :GRAVITY ...)
; processing (DEFUN SELECT-GROUP ...)
; processing (DEFINE-STUMPWM-TYPE :GROUP ...)
; processing (DEFINE-STUMPWM-TYPE :FRAME ...)
; processing (DEFINE-STUMPWM-TYPE :SHELL ...)
; processing (DEFINE-STUMPWM-TYPE :REST ...)
; processing (DEFUN CALL-INTERACTIVELY ...)
; processing (DEFUN EVAL-COMMAND ...)
; processing (DEFUN RUN-COMMANDS ...)
; processing (DEFCOMMAND COLON ...)

; wrote /home/raman/.cache/common-lisp/sbcl-2.1.1.debian-linux-x64/home/raman/sourceforge/stumpwm/command-tmpGHU3ALSV.fasl
; compilation finished in 0:00:00.120
While evaluating the form starting at line 13, column 0
  of #P"/home/raman/sourceforge/stumpwm/load-stumpwm.lisp":
While evaluating the form starting at line 3, column 0
  of #P"/home/raman/sourceforge/stumpwm/./make-image.lisp":

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1001888173}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "stumpwm" "command">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "stumpwm" "command">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "stumpwm" "command">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [RETRY                        ] Retry EVAL of current toplevel form.
  7: [CONTINUE                     ] Ignore error and continue loading file "/home/raman/sourceforge/stumpwm/load-stumpwm.lisp".
  8: [ABORT                        ] Abort loading file "/home/raman/sourceforge/stumpwm/load-stumpwm.lisp".
  9:                                 Retry EVAL of current toplevel form.
 10:                                 Ignore error and continue loading file "/home/raman/sourceforge/stumpwm/./make-image.lisp".
 11:                                 Abort loading file "/home/raman/sourceforge/stumpwm/./make-image.lisp".
 12:                                 Ignore runtime option --load "./make-image.lisp".
 13:                                 Skip rest of --eval and --load options.
 14:                                 Skip to toplevel READ/EVAL/PRINT loop.
 15: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "stumpwm" "command">)))
   source: (ERROR 'COMPILE-FILE-ERROR :CONTEXT-FORMAT CONTEXT-FORMAT
                  :CONTEXT-ARGUMENTS CONTEXT-ARGUMENTS)

**Comment by vhallac** [comment]
I have created a pull request to fix the compile error.

**Comment by jorams** [comment]
Fixed by #899
