### ISSUE TITLE
A problem configuring TTF fonts

### ISSUE THREAD

**Issue by the-beast-coder** [stumpwm/stumpwm#905]
I have recently started using StumpWM (I am quite a beginner at StumpWM and Lisp so please excuse me for any dumb mistakes that I make), however at the current moment, I just cannot get ttf fonts to work. Here is the problem, in my stumprc I have the following lines of code:
``` lisp
(ql:quickload "stumpwm")
(ql:quickload :clx-truetype)
(load-module "ttf-fonts")

(set-font (make-instance 'xft:font :family "FiraCode" :subfamily "Regular" :size 11))
```
Every time I start StumpWM it gives me the following error:
Font is not found: FiraCode Regular

The command `fc-list | grep FiraCode` gives the following output:
/usr/share/fonts/TTF/FiraCode-SemiBold.ttf: Fira Code,Fira Code SemiBold:style=SemiBold,Regular
/usr/share/fonts/TTF/FiraCode-Retina.ttf: Fira Code,Fira Code Retina:style=Retina,Regular
/usr/share/fonts/TTF/FiraCode-Bold.ttf: Fira Code:style=Bold
/usr/share/fonts/TTF/FiraCode-Light.ttf: Fira Code,Fira Code Light:style=Light,Regular
/usr/share/fonts/TTF/FiraCode-Medium.ttf: Fira Code,Fira Code Medium:style=Medium,Regular
/usr/share/fonts/TTF/FiraCode-Regular.ttf: Fira Code:style=Regular

I tried creating a cache of fonts using the command `(xft:cache-fonts)` on sbcl yet that does not seem to do anything either. Does anyone know what is going wrong here?

Thanks.

**Comment by the-beast-coder** [comment]
Turns out, StumpWM was not detecting most fonts on my system, but when I installed JetBrains Mono, it came up as a listed font and worked perfectly, for anyone that faces the same problem, here is the code to fix the font issue:
``` lisp
(load "~/quicklisp/setup.lisp")
(load-module "ttf-fonts")
(ql:quickload :clx-truetype)
(clx-truetype:cache-fonts)

(set-font (make-instance 'xft:font
                         :family "JetBrains Mono"
                         :subfamily "Regular"
                         :size 9
                         :antialias t))

```

**Comment by jcguu95** [comment]
In this [issue](https://github.com/stumpwm/stumpwm/issues/658) I dived into the source of `clx-truetype`. Some observations that could help:

1. It's not an issue of stumpwm. The error `Font is not found: FiraCode Regular` was produced at the evaluation of `(make-instance [..])`, of which `clx-truetype` is in charge.

2. The reason `clx-truetype` fails to read `"FiraCode` seems to due to a missing space. Try `"Fira Code"` instead,

```
(xft:cache-fonts)
(set-font (make-instance 'xft:font :family "Fira Code" :subfamily "Regular" :size 11))
```
