### ISSUE TITLE
Window not raised after it's selected

### ISSUE THREAD

**Issue by fare** [stumpwm/stumpwm#909]
*Sometimes*, according to rules I don't understand, the window I select via C-t SPC (pull-hidden-next) or C-t C-t (pull-hidden-other) or C-t N (pull N) doesn't show until I do C-t - (fclear). I could reproduce in quite a reliable way by having a terminator window and an emacs window, and when doing a few C-t SPC (pull-hidden-next), going from emacs to terminator, the emacs would stay on top. After a `git bisect` session, I identified the culprit as commit b7c636c425b8f49ee29a2d8563bac5b9257eb364. I don't understand anything about xlib and can't propose any fix more clever than a revert, but there it is.

**Comment by jorams** [comment]
While I think I've seen a similar problem in the past, I can't reproduce it using the steps provided.

**Comment by fare** [comment]
Interesting. Maybe there's something specific with my configuration that triggers it?
https://github.com/fare/fare-stumpwm

**Comment by PuercoPop** [comment]
IIRC from the chat over IRC when this happens the windows are in fullscreen mode right @fare?

**Comment by fare** [comment]
All my windows are always fullscreen (though some don't know how to resize so are just centered).

I don't use screen splitting, that I don't understand. Besides, my vision is bad enough that I don't like anything but fullscreen.

**Comment by fare** [comment]
If you want an interactive debugging session to identify how to reproduce the issue, we can try to negotiate a time to meet online. Or you can suggest debugging information to show as I reproduce the issue at home.

**Comment by jorams** [comment]
Ok, it turns out to be easy to reproduce. I had a fullscreen video open in mpv and moved it to my other monitor, and it moved behind the other windows already in that frame. This happens consistently. Calling `fullscreen` on the emacs and/or terminator window in the reproduction steps also makes it work.

Restating the issue: fullscreen windows don't get raised when selected.

**Comment by jorams** [comment]
@fare Could you check if #911 fixes the issue for you?

**Comment by fare** [comment]
It looks like it does. Thanks!
