### ISSUE TITLE
Cannot enter text with `exec` or `eval`

### ISSUE THREAD

**Issue by Jehops** [stumpwm/stumpwm#915]
Upon typing the first character this error is reported.
   
    Error In Command 'exec': The value -1 is not of type SB-INT:INDEX when binding SB-VM::SRC-START

The same error occurs with `eval` except of course the error references the command `eval`.
   

This started shortly after 20.11-3-g72a4e2c.  I can't pinpoint the exact commit, because the build fails for me for a few commits, then when the build completes, the error occurs.  The problem still occurs in the latest commit at this time, 20.11-90-gccb964d.

**Comment by tobyWorland** [comment]
I have the exact same issue, but only on `sbcl-2.1.7`. Downgrading back to `sbcl-2.1.6` works fine.

**Comment by emacsomancer** [comment]
There are a few issues here related to this, e.g.  https://github.com/stumpwm/stumpwm/pull/910 ,  https://github.com/stumpwm/stumpwm/issues/912 

Downgrading for the moment is probably the easiest thing.

**Comment by Jehops** [comment]
Thanks both (and @CatherineTower) for the update.  I only searched open issues.

**Comment by xificurC** [comment]
Why am I still getting this error?

```
% sbcl --version
SBCL 2.1.9
```

I thought this was fixed in 2.1.8 and upwards.

**Comment by tobyWorland** [comment]
@xificurC 
It is. Did you rebuild Stumpwm?

**Comment by xificurC** [comment]
forgot to answer, indeed, it was just my stupidity :)
