### ISSUE TITLE
Stumpwm command bar issues - my own incompetence?

### ISSUE THREAD

**Issue by JamieWaymark** [stumpwm/stumpwm#918]
Hi, I recently did a recompilation of stumpwm and since that point I've been having errors whenever using the eval, command, or shell bars. "error in command exec (or eval): -1 is not of type sb-int: index when binding sb-vm::src-start.

Now I believe sb-int is related to sbcl and I've been using a downgraded sbcl lately because I'm using stumpwm from the AUR directly rather than a manual build and there seems to be a conflict with the latest version of sbcl, so it checks out to me. However solving this is a bit over my head. I wonder if anyone has experienced similar and can shed light on this issue?

**Comment by jorams** [comment]
This is a [bug in SBCL 2.1.7](https://bugs.launchpad.net/sbcl/+bug/1938598), which should be fixed in the next update. Until then it's probably best to downgrade to 2.1.6 and recompile.
