### ISSUE TITLE
Error In Command 'exec': The value -1 is not of type SB-INT:INDEX when binding SB-VM::SRC-START

### ISSUE THREAD

**Issue by YorkZ** [stumpwm/stumpwm#924]
After upgrading archlinux today (`sbcl` was  upgraded from 2.1.1-1 to 2.1.7-1), I started to have this issue. Steps to reproduces:

1. Type `C-t !`
2. A box shows up showing `/bin/sh -c `
3. Typing any character in the box would result in the following error: 

    > Error In Command 'exec': The value -1 is not of type SB-INT:INDEX when binding SB-VM::SRC-START

Also, the exact same error will occur when typing `C-t :` and then typing any character in the `Eval` box.

Please help. Thanks in advance.

**Comment by jorams** [comment]
This is a [bug in SBCL 2.1.7](https://bugs.launchpad.net/sbcl/+bug/1938598), which should be fixed in the next update. Until then it's probably best to downgrade to 2.1.6 and recompile.

**Comment by YorkZ** [comment]
Thank you @jorams , and yes, sbcl 2.1.6 doesn't have this issue.
