### ISSUE TITLE
Which-key-display is broken when no configuration is set

### ISSUE THREAD

**Issue by Gavinok** [stumpwm/stumpwm#934]
![2021-11-30_19-06-16](https://user-images.githubusercontent.com/34443260/144278859-6e45043b-b58b-4478-9c42-40571a4fe956.png)
with no configuration of which-key-format set this is how `C-t ?` looks

**Comment by Gavinok** [comment]
This should be fixed in #935

**Comment by GnaneshKunal** [comment]
A temporary fix is to set the `*which-key-format*` variable in stump conf file:

```lisp
; .stumprc
(setf *which-key-format* "^5*~5a^n ~a")
```

Note: This makes `*key-seq-color*` unusable.

**Comment by Gavinok** [comment]
https://github.com/stumpwm/stumpwm/pull/935 also resolves this issue.
