### ISSUE TITLE
C-t ? yields incomprehensible keybindings

### ISSUE THREAD

**Issue by joshcho** [stumpwm/stumpwm#940]
I tried multiple installation routes, with current one compiled on my machine (Arch Linux). When I press C-t ?, I get the following:

![screenshot](https://user-images.githubusercontent.com/6498524/147870618-3f135f2d-436e-4407-a373-2d819315b92c.png)

This is different from when I installed the binary through pacman, where I saw what was expected. Is there something I am missing? No idea on how to get this to work.

**Comment by duikboot** [comment]
This is the same issue as https://github.com/stumpwm/stumpwm/issues/934 and it's solved in the latest update AFAIK.
