### ISSUE TITLE
Stumpwm crashes when screen powers on after idle and when trying t add a window to a dynamic group

### ISSUE THREAD

**Issue by elais** [stumpwm/stumpwm#943]
I have a pretty consistent bug where dynamic tiling or trying to turn my screen back on after being idle results in a stumpwm crash. I am using the latest master (and before I was using the latest release) and it has been a consistent problem for me. Now, the one time I was able to do both was when I was originally writing this issue. But on restart the problem persisted. On the surface it seems like God was taking a piss at my expense, but it seems to be some kind of race condition. Here is my error when trying to dynamically tile.

```
        ^B^1*StumpWM Crashed With An Unhandled Error!
        Copy the error to the clipboard with the 'copy-unhandled-error' command.
        ^bThe value
            NIL
          is not of type
            STUMPWM::FRAME^B^n
        Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10022E8173}>
        0: (STUMPWM::FRAME-HEAD #<STUMPWM::DYNAMIC-GROUP {100CC58AE3}> NIL)
        1: (STUMPWM::DYN-SPLIT-FRAME #<STUMPWM::DYNAMIC-GROUP {100CC58AE3}> NIL :COLUMN 2/3)
        2: (STUMPWM::DYN-SPLIT-FRAME-IN-DIR-WITH-FRAME #<STUMPWM::DYNAMIC-GROUP {100CC58AE3}> NIL :COLUMN 2/3)
        3: (STUMPWM::DYNAMIC-GROUP-PLACE-WINDOW #<STUMPWM::DYNAMIC-GROUP {100CC58AE3}> #S(DYNAMIC-WINDOW "emacs@t260g" #x600C23) NIL)
        4: (STUMPWM::DYNAMIC-GROUP-ADD-WINDOW #<STUMPWM::DYNAMIC-GROUP {100CC58AE3}> #S(DYNAMIC-WINDOW "emacs@t260g" #x600C23))
        5: ((:METHOD GROUP-ADD-WINDOW (STUMPWM::DYNAMIC-GROUP T)) #<STUMPWM::DYNAMIC-GROUP {100CC58AE3}> #S(DYNAMIC-WINDOW "emacs@t260g" #x600C23)) [fast-method]
        6: (STUMPWM::PROCESS-MAPPED-WINDOW #S<screen #<XLIB:SCREEN :0.0 3840x2160x24 TRUE-COLOR>> #<XLIB:WINDOW :0 600C23>)
        7: ((LAMBDA (&REST #:G0 &KEY :PARENT :SEND-EVENT-P :WINDOW &ALLOW-OTHER-KEYS) :IN "/gnu/store/nw6qmbmj381y1shccrspyfzvba87r8w9-stumpwm-orange-1c4b087-lib/share/common-lisp/sbcl/stumpwm-orange/events.lisp") :PARENT #<XLIB:WINDOW :0 6B8> :SEND-EVENT-P NIL :WINDOW #<XLIB:WINDOW :0 600C23>)
        8: (STUMPWM::HANDLE-EVENT :DISPLAY #<XLIB:DISPLAY :0 (The X.Org Foundation R12101002)> :EVENT-KEY :MAP-REQUEST :EVENT-CODE 20 :SEND-EVENT-P NIL :SEQUENCE 8956 :PARENT #<XLIB:WINDOW :0 6B8> :EVENT-WINDOW #<XLIB:WINDOW :0 6B8> :WINDOW #<XLIB:WINDOW :0 600C23>)
        9: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB:PROCESS-EVENT))
        10: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
        11: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<FUNCTION (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB:PROCESS-EVENT) {7F1A223E6FFB}> #<SB-THREAD:MUTEX "CLX Event Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {10022E8173}>> T NIL)
        12: ((FLET SB-IMPL::TIMEOUT-BODY :IN XLIB:PROCESS-EVENT))
        13: (XLIB:PROCESS-EVENT #<XLIB:DISPLAY :0 (The X.Org Foundation R12101002)> :HANDLER #<FUNCTION STUMPWM::HANDLE-EVENT> :TIMEOUT 0 :PEEK-P NIL :DISCARD-P NIL :FORCE-OUTPUT-P T)
        14: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
        15: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<FUNCTION (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN STUMPWM::DISPATCH-ALL) {7F1A223E746B}> #<SB-THREAD:MUTEX "CLX Event Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {10022E8173}>> T NIL)
        16: ((FLET STUMPWM::DISPATCH-ALL :IN "/gnu/store/nw6qmbmj381y1shccrspyfzvba87r8w9-stumpwm-orange-1c4b087-lib/share/common-lisp/sbcl/stumpwm-orange/stumpwm.lisp") #<XLIB:DISPLAY :0 (The X.Org Foundation R12101002)>)
        17: ((:METHOD IO-LOOP (STUMPWM::SBCL-IO-LOOP)) #<STUMPWM::SBCL-IO-LOOP {1009836763}> :DESCRIPTION "StumpWM") [fast-method]
        18: (STUMPWM::STUMPWM-INTERNAL-LOOP)
        19: (STUMPWM::STUMPWM-INTERNAL ":0")
        20: (STUMPWM ":0")
        21: (STUMPWM-EXEC:MAIN)
        22: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
        23: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {1000B18C7B}>)
        24: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
        25: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
        26: (SB-IMPL::START-LISP)
```

Having read through previous issues I'm wondering if this is something caused by xrandr.

**Comment by elais** [comment]
I see that @szos is working on changing some of the logic for heads to better support dynamic groups. Have you noticed any changes that might lead to heads not being picked it before frames are added to the group?

**Comment by szos** [comment]
Thank you for the bug report. The initial implementation was written without taking multi-head setups into account, and accounting for them has required a near full rewrite. The initial implementation had (if i recall correctly) no group-[add|remove]-head methods defined, so any sort of adding/removing of heads its likely to cause issues. 

If you're interested, the new implementation is functioning with a single head, and is ready for testing. I dont have access to a second monitor (though things should be coming in the mail soon) so I have only tested this with one head, but since it is oriented around multiple heads fixing bugs related to multiple heads should be possible. If youre interested, test out the new implementation [here](https://github.com/szos/stumpwm/tree/dynamic-group-head-support-rewrite) and report any bugs you encounter. 

Sorry you're having issues with dynamic groups. I hope the new implementation addresses your issue, and if not it should be infinitely easier to address it within the new implementation rather than the implementation currently in master.

**Comment by elais** [comment]
I believe this has been resolved. I have not encountered the issue in the most recent release of stumpwm. l so it’s not worth letting this comment linger. 

If I had to guess I would say it was probably a confluence of problems with my own setup that led to the error. But since it’s no longer a problem I will close this.
