### ISSUE TITLE
How to hack "list key mode"?

### ISSUE THREAD

**Issue by jcguu95** [stumpwm/stumpwm#945]
Pressing the prefix for `*root-map*` and then `?` shows a list of keybindings in `*root-map*`. It would be nice if I can list keybindings in other maps, for example `*top-map*`. How to do that?

I tried to look into the source code, and the closest thing I found is [this](https://github.com/stumpwm/stumpwm/blob/e6bce8a2de78abff54d3cf2073a85f5a642e9943/bindings.lisp#L86). What's weird is that `'?'` itself is not in the list. I'm curious where the listing functionality is actually defined. Any hint is appreciated.

**Comment by szos** [comment]
One option to list the bindings in `*top-map*` is to bind `'*top-map*` and then press that keybinding followed by `?`. Eg `(define-key *top-map* (kbd "C-M-s-t") '*top-map*)` and then press `C-M-s-t ?`. 

You can also do this by way of the function `display-bindings-for-keymaps`, defined in help.lisp. The function call `(display-bindings-for-keymaps nil *top-map*)` should display the keybindings present in `*top-map*`. 

The actual place where the `?` functionality is implemented is a little odd, its in the function `handle-keymap` in the file events.lisp on line 210. Its a hard-coded keybinding, and defined in a very unobvious place.

**Comment by jcguu95** [comment]
Thanks for your clear explanation! I did locate the function `display-bindings-for-keymaps`, but running `(stumpwm::display-bindings-for-keymaps nil stumpwm::*top-map*)` in the eval prompt only gives a message `NIL`. I have changed `*top-map*` to `*root-map*`, `*group-top-map*` and `*float-group-top-map*`. But they all gave me the same thing.
