### ISSUE TITLE
How do you make the windows occupy the full height of the frame?

### ISSUE THREAD

**Issue by joshcho** [stumpwm/stumpwm#953]
![screenshot](https://user-images.githubusercontent.com/6498524/151405230-42e77da6-7d18-40b5-bb41-729a890f6572.png)

My emacsclient shows up into the frame without a full height. How can I make the windows occupy the full height of the frame?

**Comment by jorams** [comment]
This is probably because of the resize hints Emacs specifies. You can tell StumpWM to ignore them by setting `*ignore-wm-inc-hints*` to `t`.

**Comment by joshcho** [comment]
Worked like a charm. Thank you.
