### ISSUE TITLE
`resize` command description seems vague.

### ISSUE THREAD

**Issue by WhyIsEvery4thYearAlwaysBad** [stumpwm/stumpwm#963]
[Posted from reddit.](https://old.reddit.com/r/stumpwm/comments/sn72hc/should_the_resize_commnad_description_be_changed/)

The command description of the `resize` is:

> Resize the current frame by @var{width} and @var{height} pixels.

This description seems confusing to me though; *how* does the command resize the current frame? Does it change the frame size by deltas (delta width and delta height); or does it set the frame size to a specific dimension?

I think the command description should be changed to:

> Incrementally resize the current frame dimensions @var{width} and @var{height} pixels.

**Comment by defaultxr** [comment]
Personally I think the current docstring is better than your proposed one. The word "by" is key; it says we change the size BY the amounts, not TO the amounts.

If it was setting the size of the frame, it would say something like `Resize the current frame to @var{width} and @var{height} pixels.` or maybe just `Set the current frame's dimensions to @var{width} and @var{height}, in pixels.`
