### ISSUE TITLE
Add stumpwm.ros file for installation via roswell

### ISSUE THREAD

**Issue by Gavinok** [stumpwm/stumpwm#964]
Considering stump has this section in the wiki https://github.com/stumpwm/stumpwm/wiki/StartUp#install-via-roswell I am surprised there isn't a stumpwm.ros file for even simpler installation. Here are some docs on how this can be done https://roswell.github.io/How-to-distribute-your-software,-not-library,-on-Quicklisp-ala-python-pip.html

This should be pretty straight forward if not identical to the given script in the wiki.

**Comment by dmb2** [comment]
I don't want to use/depend on roswell for stumpwm proper.  If someone in the community wants to maintain a ros file or put it on the wiki that's fine.
