### ISSUE TITLE
Crash when running Metafont

### ISSUE THREAD

**Issue by uti5** [stumpwm/stumpwm#966]
With texlive installed, run mf.  At the prompt, type

    \relax
    drawdot (0,0); showit; end.

Stump ca8f57 crashes with the message

    The slot STUMPWM:GROUP is unbound in the object #S(WINDOW "Metafont" #x1A00001).
    Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1004D54003}>
    0: (STUMPWM::BACKTRACE-STRING)
    1: ((:METHOD STUMPWM::HANDLE-TOP-LEVEL-CONDITION (SERIOUS-CONDITION)) #<UNBOUND-SLOT GROUP {10060768B3}>) [fast-method]
    2: (SB-KERNEL::%SIGNAL #<UNBOUND-SLOT GROUP {10060768B3}>)
    3: (ERROR #<UNBOUND-SLOT GROUP {10060768B3}>)
    4: (SB-KERNEL:WITH-SIMPLE-CONDITION-RESTARTS ERROR NIL UNBOUND-SLOT :NAME GROUP :INSTANCE #S(WINDOW "Metafont" #x1A00001))
    5: ((:METHOD SLOT-UNBOUND (T T T)) #<unused argument> #S(WINDOW "Metafont" #x1A00001) GROUP) [fast-method]
    6: ((LAMBDA (SB-KERNEL:INSTANCE) :IN SB-PCL::MAKE-OPTIMIZED-STD-READER-METHOD-FUNCTION) #S(WINDOW "Metafont" #x1A00001))
    7: (WINDOW-SCREEN #S(WINDOW "Metafont" #x1A00001))
    8: (STUMPWM::DESTROY-WINDOW #S(WINDOW "Metafont" #x1A00001))
    9: (STUMPWM::HANDLE-EVENT :DISPLAY #<XLIB:DISPLAY :0 (The X.Org Foundation R12101003)> :EVENT-KEY :DESTROY-NOTIFY :EVENT-CODE 17 :SEND-EVENT-P NIL :SEQUENCE 36703 :EVENT-WINDOW #<XLIB:WINDOW :0 DB> :WINDOW #<XLIB:WINDOW :0 1A00001>)
    10: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB:PROCESS-EVENT))
    11: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
    12: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<FUNCTION (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB:PROCESS-EVENT) {7FF9CB65725B}> #<SB-THREAD:MUTEX "CLX Event Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {1004D54003}>> T 0)
    13: (XLIB:PROCESS-EVENT #<XLIB:DISPLAY :0 (The X.Org Foundation R12101003)> :HANDLER #<FUNCTION STUMPWM::HANDLE-EVENT> :TIMEOUT 0 :PEEK-P NIL :DISCARD-P NIL :FORCE-OUTPUT-P T)
    14: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
    15: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<FUNCTION (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN STUMPWM::DISPATCH-ALL) {7FF9CB65751B}> #<SB-THREAD:MUTEX "CLX Event Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {1004D54003}>> T NIL)
    16: ((FLET STUMPWM::DISPATCH-ALL :IN "/home/foo/src/stumpwm/stumpwm.lisp") #<XLIB:DISPLAY :0 (The X.Org Foundation R12101003)>)
    17: ((:METHOD IO-LOOP (STUMPWM::SBCL-IO-LOOP)) #<STUMPWM::SBCL-IO-LOOP {1005D5F793}> :DESCRIPTION "StumpWM") [fast-method]
    18: (STUMPWM::STUMPWM-INTERNAL-LOOP)
    19: (STUMPWM::STUMPWM-INTERNAL ":0")
    20: (STUMPWM ":0")
    21: ((LAMBDA NIL :IN "/home/foo/src/stumpwm/make-image.lisp"))
    22: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
    23: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
    24: (SB-IMPL::START-LISP)

**Comment by tiberious726** [comment]
I can't replicate this with current stumpwm and current `texlive-core 2022.63035-1`

**Comment by dmb2** [comment]
Cannot replicate.
