### ISSUE TITLE
[Feature Request] Fullscreen contained in a frame

### ISSUE THREAD

**Issue by joshcho** [stumpwm/stumpwm#971]
In other window managers (e.g. xmonad), going fullscreen on a video in browser can be configured to be contained in the frame.

![full-screen-2](https://user-images.githubusercontent.com/6498524/165205880-c754fd39-4664-48a4-9964-056adba13f77.png)
This is xmonad, with Brave on the left frame with youtube video as fullscreen.

If I wanted to implement something like this, where should I start looking?

Reference links:
https://www.reddit.com/r/stumpwm/comments/u6tfpr/can_fullscreen_eg_youtube_be_contained_in_the/
https://www.reddit.com/r/stumpwm/comments/awnfwf/is_it_possible_to_contain_full_screen_to_a_frame/

**Comment by szos** [comment]
This feature was merged in #974, can this issue be closed?
