### ISSUE TITLE
clx call `xlib:get-wm-class` causes stumpwm to crash

### ISSUE THREAD

**Issue by mariari** [stumpwm/stumpwm#972]
While trying to run [a game](https://en.wikipedia.org/wiki/Embodiment_of_Scarlet_Devil) Stumpwm crashes upon the game launching. I was able to get a picture of the stack trace.

[Photo of the stack trace](https://pomf2.lain.la/f/7g03szke.jpg)

It seems that stumpwm calls `xlib:get-wm-class` from `clx` which can't handle non latin characters. 

```lisp
(xlib:char->card8 #\latin_small_letter_AE)
The value
  #\LATIN_SMALL_LETTER_AE
is not of type
  BASE-CHAR
when binding CHAR
   [Condition of type TYPE-ERROR]
```

which stumpwm passes it from the game's information.

This issue seems related to https://github.com/sharplispers/clx/issues/182 who also seems to have run into a similar issue for his own stumpwm code.

It might be good to have a check on `stumpwm::xwin-class` or `stumpwm::xwin-to-window` to prevent stumpwm from crashing upon this.

**Comment by dmb2** [comment]
Sorry we ruined your game session! This is a relatively well known issue in clx. Maybe we can work around it, but really its upstream of us.
