### ISSUE TITLE
Document keypad kbd notation

### ISSUE THREAD

**Issue by PhilHudson** [stumpwm/stumpwm#990]
I've been unable to work out what the correct syntax is for binding a command to a key-combination (or plain key) involving the numeric keypad. I've asked on the subreddit, with interest expressed but no answers.

**Comment by jorams** [comment]
I don't have a keyboard with keypad to test with, but generally you can use `<prefix> h k` (`describe-key`) followed by a key combination to show both the name of the key and its binding. Looking at `keysyms.lisp`, it should be `KP_0`, `KP_1`, etc. So you'd use `(kbd "KP_1")` to bind something to the number 1 on the keypad.

**Comment by jorams** [comment]
They're specified here: https://github.com/stumpwm/stumpwm/blob/aaf1569056b80d8d4a095f4b26a556cc784ed037/keysyms.lisp#L120-L156

**Comment by PhilHudson** [comment]
Thanks so much Joram. Should there be an example/link in the manual, do you think?

**Comment by sdilts** [comment]
It's not exactly documentation, but in #1035 I've added some basic diagnostic messages if you get the syntax wrong or use the wrong character to represent a modifier key. It still only tells you there was a parse  error if it can't find a key associated with a specific string representation, but it it should help with things like this.
